### PR TITLE
[service bus] Use ServiceBusException rather than AmqpException

### LINKED ISSUE #17500: [Service Bus] Introduce ServiceBusException with limited set of error condition/code/reason
In the new azure-messaging-servicebus, the exception class we use is the AmqpException. The user is expected to check its `isTransient` and `getErrorCondition()` properties to understand the different error scenarios.

In the older azure-servicebus, there were different exception classes to begin with which mapped to a few of the error condition mentioned above with the rest of the error conditions being classified as a "general error". A similar model is used in .Net library Azure.Messaging.ServiceBus, with the difference being that they use a single ServiceBusException class with different values in the `reason` field denoting the different error scenarios. The JS library `@azure/service-bus` plans to do something similar.

This issue is to request the new azure-messaging-servicebus to follow the same model and have a `ServiceBusException` instead of exposing the `AmqpException`. Historically, the 50 odd error conditions were not required to be exposed to the user. A smaller set with the rest getting swept under "general error" was good enough. Doing this brings all 4 languages to the same page where we use expose the same set of error scenarios with similar details.

Pointers from the .Net implementation:
- [Mapping from error condition to error reason](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/servicebus/Azure.Messaging.ServiceBus/src/Amqp/AmqpExceptionHelper.cs#L94)
- [TranslateException()](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/servicebus/Azure.Messaging.ServiceBus/src/Amqp/AmqpExceptionHelper.cs#L185)

@richardpark-msft : after talking with @conniey the implementation of this will be:
* Add ServiceBusException like .NET (basically, rename ServiceBusReceiverException)
* Update `processError` in ServiceBusMessageProcessor to take an ServiceBusReceiverErrorContext rather than just a throwable.		 
   * ServiceBusReceiverErrorContext will contain a 'reason' field with the appropriate code.

### PR DESCRIPTION
**Pull request by richardpark-msft**
ServiceBusException is basically a friendly envelope around an AmqpException. It's primary purpose is to give the user something simple they can try/catch that has a 'reason' code so they can programatically react to certain kinds of failures.

(as a bonus I'm also tossing in the rename that we want to do for ReceiveMode to ServiceBusReceiveMode).

Fixes #17500 (exception type), #17555 (receive mode)

### CODE REVIEW

File: sdk/servicebus/azure-messaging-servicebus/src/main/java/com/azure/messaging/servicebus/ServiceBusException.java [hunk 1]
```diff
@@ -0,0 +1,101 @@
...
+            reason = ServiceBusFailureReason.GENERAL_ERROR;
+            isTransient = false;
+        }
+    }
+
+    /**
+     * Gets the {@link ServiceBusErrorSource} in case of any errors.
+     * @return the {@link ServiceBusErrorSource}
+     */
+    public ServiceBusErrorSource getErrorSource() {
```
Comment (JoshLove-msft) [inline sdk/servicebus/azure-messaging-servicebus/src/main/java/com/azure/messaging/servicebus/ServiceBusException.java:42]: Interesting that this is on the exception itself. Is it the same in JS?

Comment (richardpark-msft) [reply sdk/servicebus/azure-messaging-servicebus/src/main/java/com/azure/messaging/servicebus/ServiceBusException.java:42]: Ah, its not in JS. I need to move this to the ProcessErrorArgs equivalent in Java.

Comment (richardpark-msft) [reply sdk/servicebus/azure-messaging-servicebus/src/main/java/com/azure/messaging/servicebus/ServiceBusException.java:42]: An interesting thing here is that the ServiceBusProcessor in Java takes a throwable, not a context object at the moment.

Comment (ramya-rao-a) [reply sdk/servicebus/azure-messaging-servicebus/src/main/java/com/azure/messaging/servicebus/ServiceBusException.java:42]: I would expect the Error Source to be available only on the context object passed to the `processError()` in the processor client builder.

File: sdk/servicebus/azure-messaging-servicebus/src/main/java/com/azure/messaging/servicebus/ServiceBusErrorSource.java [hunk 2]
```diff
@@ -36,4 +36,12 @@
...
     public static final ServiceBusErrorSource CLOSE_SESSION = fromString("CLOSE_SESSION",
         ServiceBusErrorSource.class);
+
+    /** Error while sending a message.*/
+    public static final ServiceBusErrorSource SENDING = fromString("SENDING",
+            ServiceBusErrorSource.class);
+
+    /** Error while trying to do an operation on the management link. */
+    public static final ServiceBusErrorSource MANAGEMENT = fromString("MANAGEMENT",
+            ServiceBusErrorSource.class);
```
Comment (ramya-rao-a) [inline sdk/servicebus/azure-messaging-servicebus/src/main/java/com/azure/messaging/servicebus/ServiceBusErrorSource.java:46]: Assuming that the Error Source will be restricted to the processor only as per https://github.com/Azure/azure-sdk-for-java/pull/17601/files#r524813422, we dont need the above additions right?

File: sdk/servicebus/azure-messaging-servicebus/src/main/java/com/azure/messaging/servicebus/ServiceBusProcessErrorContext.java [hunk 3]
```diff
@@ -0,0 +1,60 @@
...
+/**
+ * Context for errors handled by the Service Bus processor.
+ */
+public class ServiceBusProcessErrorContext {
+    private final Throwable exception;
+    private final ServiceBusErrorSource errorSource;
+    private final String fullyQualifiedNamespace;
+    private final String entityPath;
+
+    ServiceBusProcessErrorContext(Throwable throwable, String fullyQualifiedNamespace, String entityPath) {
```
Comment (srnagar) [inline sdk/servicebus/azure-messaging-servicebus/src/main/java/com/azure/messaging/servicebus/ServiceBusProcessErrorContext.java:15]: Why do we need `fullyQualifiedNamespace` and `entityPath`? If this is needed for the error context, we should consider adding it to the `ServiceBusReceivedMessageContext` too? I know Event Hubs had these properties on both event and error context. So, we should consider adding it to both places.

File: sdk/servicebus/azure-messaging-servicebus/src/main/java/com/azure/messaging/servicebus/ServiceBusException.java [hunk 4]
```diff
@@ -0,0 +1,101 @@
...
+public final class ServiceBusException extends AzureException {
+    private final transient ServiceBusErrorSource errorSource;
+    private final transient ServiceBusFailureReason reason;
+    private final boolean isTransient;
+
+    /**
+     * @param throwable for the error happened.
+     * @param errorSource indicating which api caused the error.
+     */
+    public ServiceBusException(Throwable throwable, ServiceBusErrorSource errorSource) {
```
Comment (srnagar) [inline sdk/servicebus/azure-messaging-servicebus/src/main/java/com/azure/messaging/servicebus/ServiceBusException.java:24]: Do we need the constructor to be public?

File: sdk/servicebus/azure-messaging-servicebus/src/main/java/com/azure/messaging/servicebus/ServiceBusException.java (hunk 1 above)
Comment (srnagar) [reply sdk/servicebus/azure-messaging-servicebus/src/main/java/com/azure/messaging/servicebus/ServiceBusException.java:42]: Now that the error context includes the error source, this method can be removed from this class.

File: sdk/servicebus/azure-messaging-servicebus/src/main/java/com/azure/messaging/servicebus/ServiceBusReceiverAsyncClient.java [hunk 5]
```diff
@@ -1200,22 +1201,27 @@ private String getLinkName(String sessionId) {
...
 
     /**
-     * Map the error to {@link ServiceBusReceiverException}
+     * Map the error to {@link ServiceBusException}
      */
     private Throwable mapError(Throwable throwable, ServiceBusErrorSource errorSource) {
         // If it is already `ServiceBusReceiverException`, we can just throw it.
-        if (!(throwable instanceof ServiceBusReceiverException)) {
-            return new ServiceBusReceiverException(throwable, errorSource);
+        if (!(throwable instanceof ServiceBusException)) {
```
Comment (srnagar) [inline sdk/servicebus/azure-messaging-servicebus/src/main/java/com/azure/messaging/servicebus/ServiceBusReceiverAsyncClient.java:1223]: nit: update the comment too.

File: sdk/servicebus/azure-messaging-servicebus/src/main/java/com/azure/messaging/servicebus/ServiceBusReceiverAsyncClient.java [hunk 6]
```diff
@@ -1190,7 +1190,8 @@ private String getLinkName(String sessionId) {
 
         return connectionProcessor
             .flatMap(connection -> connection.getManagementNode(entityPath, entityType))
-            .flatMap(channel -> channel.setSessionState(sessionId, sessionState, linkName));
+            .flatMap(channel -> channel.setSessionState(sessionId, sessionState, linkName))
+                .onErrorMap((err) -> mapError(err, ServiceBusErrorSource.RECEIVE));
```
Comment (srnagar) [inline sdk/servicebus/azure-messaging-servicebus/src/main/java/com/azure/messaging/servicebus/ServiceBusReceiverAsyncClient.java:1194]: nit: fix indentation

File: sdk/servicebus/azure-messaging-servicebus/src/main/java/com/azure/messaging/servicebus/implementation/ManagementChannel.java [hunk 7]
```diff
@@ -499,21 +509,26 @@ public void close() {
...
+                    final Throwable exc = new AmqpException(false, AmqpErrorCondition.UNAUTHORIZED_ACCESS,
+                        message, getErrorContext());
+                    sink.error(new ServiceBusException(exc, ServiceBusErrorSource.MANAGEMENT));
                 } else {
                     sink.complete();
                 }
-            });
+            })
+            .onErrorMap(this::mapError)
+            .then();
```
Comment (srnagar) [inline sdk/servicebus/azure-messaging-servicebus/src/main/java/com/azure/messaging/servicebus/implementation/ManagementChannel.java:531]: I don't think `then()` is needed here.

File: sdk/servicebus/azure-messaging-servicebus/src/main/java/com/azure/messaging/servicebus/ServiceBusProcessErrorContext.java (hunk 3 above)
Comment (richardpark-msft) [reply sdk/servicebus/azure-messaging-servicebus/src/main/java/com/azure/messaging/servicebus/ServiceBusProcessErrorContext.java:15]: This is just mimicking what's already in .net, so this is more a question for @JoshLove-msft .

File: sdk/servicebus/azure-messaging-servicebus/src/main/java/com/azure/messaging/servicebus/ServiceBusErrorSource.java (hunk 2 above)
Comment (richardpark-msft) [reply sdk/servicebus/azure-messaging-servicebus/src/main/java/com/azure/messaging/servicebus/ServiceBusErrorSource.java:46]: I'm adding them in since we do throw this exception type from places other than the processor.

However, I am making the errorSource field package-private now.

File: sdk/servicebus/azure-messaging-servicebus/src/main/java/com/azure/messaging/servicebus/implementation/ManagementChannel.java (hunk 7 above)
Comment (richardpark-msft) [reply sdk/servicebus/azure-messaging-servicebus/src/main/java/com/azure/messaging/servicebus/implementation/ManagementChannel.java]: You were right, it needed to be hoisted further up!

File: sdk/servicebus/azure-messaging-servicebus/src/main/java/com/azure/messaging/servicebus/ServiceBusReceiverAsyncClient.java (hunk 6 above)
Comment (richardpark-msft) [reply sdk/servicebus/azure-messaging-servicebus/src/main/java/com/azure/messaging/servicebus/ServiceBusReceiverAsyncClient.java]: Fixed to be flush with the other calls.

File: sdk/servicebus/azure-messaging-servicebus/src/main/java/com/azure/messaging/servicebus/ServiceBusReceiverAsyncClient.java (hunk 5 above)
Comment (richardpark-msft) [reply sdk/servicebus/azure-messaging-servicebus/src/main/java/com/azure/messaging/servicebus/ServiceBusReceiverAsyncClient.java:1222]: Removed the comment - realized what the function was doing was pretty obvious.

File: sdk/servicebus/azure-messaging-servicebus/src/main/java/com/azure/messaging/servicebus/ServiceBusException.java (hunk 4 above)
Comment (richardpark-msft) [reply sdk/servicebus/azure-messaging-servicebus/src/main/java/com/azure/messaging/servicebus/ServiceBusException.java:24]: Nope, made package private.

File: sdk/servicebus/azure-messaging-servicebus/src/main/java/com/azure/messaging/servicebus/ServiceBusProcessErrorContext.java [hunk 8]
```diff
@@ -0,0 +1,60 @@
+// Copyright (c) Microsoft Corporation. All rights reserved.
+// Licensed under the MIT License.
+
+package com.azure.messaging.servicebus;
+
+/**
+ * Context for errors handled by the Service Bus processor.
+ */
+public class ServiceBusProcessErrorContext {
```
[the remark this answers is not in the document]
Comment (richardpark-msft) [reply sdk/servicebus/azure-messaging-servicebus/src/main/java/com/azure/messaging/servicebus/ServiceBusProcessErrorContext.java]: Both of those sound good, done.

File: sdk/servicebus/azure-messaging-servicebus/src/main/java/com/azure/messaging/servicebus/ServiceBusException.java (hunk 1 above)
Comment (richardpark-msft) [reply sdk/servicebus/azure-messaging-servicebus/src/main/java/com/azure/messaging/servicebus/ServiceBusException.java]: I've made this field internal but we do use it when constructing the ErrorContext. So we won't expose it from the exception but we will use it internally to fill out the context (when appropriate).

**Review by srnagar — APPROVED** [review]

File: sdk/servicebus/azure-messaging-servicebus/src/main/java/com/azure/messaging/servicebus/ServiceBusErrorSource.java [hunk 9]
```diff
@@ -36,4 +36,12 @@
     /** Error while session is closed.*/
     public static final ServiceBusErrorSource CLOSE_SESSION = fromString("CLOSE_SESSION",
         ServiceBusErrorSource.class);
+
+    /** Error while sending a message.*/
+    public static final ServiceBusErrorSource SENDING = fromString("SENDING",
```
Comment (srnagar) [inline sdk/servicebus/azure-messaging-servicebus/src/main/java/com/azure/messaging/servicebus/ServiceBusErrorSource.java:41]: To be consistent with the usage of other terms here, we should just call this `SEND`. Also, we should do the same for `ABANDONED` -> `ABANDON` (sorry, this was not part of your PR).

File: sdk/servicebus/azure-messaging-servicebus/src/main/java/com/azure/messaging/servicebus/ServiceBusException.java [hunk 10]
```diff
@@ -0,0 +1,101 @@
...
+                return ServiceBusFailureReason.SERVICE_BUSY;
+            case TIMEOUT_ERROR:
+                return ServiceBusFailureReason.SERVICE_TIMEOUT;
+            case SESSION_CANNOT_BE_LOCKED:
+                return ServiceBusFailureReason.SESSION_CANNOT_BE_LOCKED;
+            case SESSION_LOCK_LOST:
+                return ServiceBusFailureReason.SESSION_LOCK_LOST;
+            case UNAUTHORIZED_ACCESS:
+                return ServiceBusFailureReason.UNAUTHORIZED;
+            case PROTON_IO:         // does this mapping make sense?
```
Comment (srnagar) [inline sdk/servicebus/azure-messaging-servicebus/src/main/java/com/azure/messaging/servicebus/ServiceBusException.java:96]: PROTO_IO falls under SERVICE_COMMUNICATION_PROBLEM

File: sdk/servicebus/azure-messaging-servicebus/src/main/java/com/azure/messaging/servicebus/ServiceBusFailureReason.java [hunk 11]
```diff
@@ -0,0 +1,73 @@
...
+     * . */
+    public static final ServiceBusFailureReason SERVICE_BUSY = fromString("SERVICE_BUSY",
+        ServiceBusFailureReason.class);
+
+    /** An operation or other request timed out while interacting with the Azure Service Bus service. */
+    public static final ServiceBusFailureReason SERVICE_TIMEOUT = fromString("SERVICE_TIMEOUT",
+        ServiceBusFailureReason.class);
+
+    /** There was a general communications error encountered when interacting with the Azure Service Bus service. */
+    public static final ServiceBusFailureReason SERVICE_COMMUNICATION_PROBLEM = fromString(
```
Comment (srnagar) [inline sdk/servicebus/azure-messaging-servicebus/src/main/java/com/azure/messaging/servicebus/ServiceBusFailureReason.java:59]: Some alternate name proposals: `SERVICE_COMMUNICATION_ERROR`, `SERVICE_CONNECTION_ERROR`. Generally, we don't suffix `PROBLEM`. `ERROR` is the more commonly used term.

File: sdk/servicebus/azure-messaging-servicebus/src/test/java/com/azure/messaging/servicebus/ServiceBusExceptionTestHelper.java [hunk 12]
```diff
@@ -0,0 +1,15 @@
+// Copyright (c) Microsoft Corporation. All rights reserved.
+// Licensed under the MIT License.
+
+package com.azure.messaging.servicebus;
+
+public class ServiceBusExceptionTestHelper {
```
Comment (srnagar) [inline sdk/servicebus/azure-messaging-servicebus/src/test/java/com/azure/messaging/servicebus/ServiceBusExceptionTestHelper.java:6]: :grin:

**Review by srnagar — APPROVED** [review]
LGTM! Thanks @richardpark-msft for making these changes!

File: sdk/servicebus/azure-messaging-servicebus/src/test/java/com/azure/messaging/servicebus/ServiceBusExceptionTestHelper.java (hunk 12 above)
Comment (richardpark-msft) [reply sdk/servicebus/azure-messaging-servicebus/src/test/java/com/azure/messaging/servicebus/ServiceBusExceptionTestHelper.java:6]: It was approved by the deputy architect for Java! ;)

File: sdk/servicebus/azure-messaging-servicebus/src/main/java/com/azure/messaging/servicebus/ServiceBusFailureReason.java (hunk 11 above)
Comment (richardpark-msft) [reply sdk/servicebus/azure-messaging-servicebus/src/main/java/com/azure/messaging/servicebus/ServiceBusFailureReason.java:59]: Went with this just to get better search alignment (this name matches with .net).

I can change it, but that was the reasoning.

File: sdk/servicebus/azure-messaging-servicebus/src/main/java/com/azure/messaging/servicebus/ServiceBusErrorSource.java (hunk 9 above)
Comment (richardpark-msft) [reply sdk/servicebus/azure-messaging-servicebus/src/main/java/com/azure/messaging/servicebus/ServiceBusErrorSource.java]: I live to serve. No apologies needed ;)

File: sdk/servicebus/azure-messaging-servicebus/src/main/java/com/azure/messaging/servicebus/ServiceBusException.java (hunk 10 above)
Comment (richardpark-msft) [reply sdk/servicebus/azure-messaging-servicebus/src/main/java/com/azure/messaging/servicebus/ServiceBusException.java]: Done.

File: sdk/servicebus/azure-messaging-servicebus/src/main/java/com/azure/messaging/servicebus/ServiceBusFailureReason.java (hunk 11 above)
Comment (richardpark-msft) [reply sdk/servicebus/azure-messaging-servicebus/src/main/java/com/azure/messaging/servicebus/ServiceBusFailureReason.java]: (renamed!)

**Comment by richardpark-msft** [comment]
(build failures are just me chasing down some of the spring projects which live in different parts of the tree than I build)

**Review by hemanttanwar — COMMENTED** [review]
Great. @richardpark-msft . I am impressed.
