### PR TITLE
fix issue #16595

### LINKED ISSUE #16595: Default subscription id from configuration is ignored
Following the example in https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-storage, but using an existing Enterprise App that has access to multiple subscriptions the subscriptionid in the my.azureauth seems be be ignored.

The issue seems to be in AzureContextAutoConfiguration when creating the Azure Bean. In the following code the Azure object is not passed the subscriptionId (nor does it read it from the restClient), therefore the attribute "defaultSubsciptionId" is null which means that 
`      return Azure.authenticate(restClient, credentials.domain()).withDefaultSubscription();
`
will just return the first Subscription in the list

As a workaround I've manually created the bean with the following code, however the framework should correctly support multiple subscriptions
```
	@Bean
	public Azure azure(AzureTokenCredentials credentials) {
		com.microsoft.rest.RestClient restClient = new com.microsoft.rest.RestClient.Builder()
				.withBaseUrl(credentials.environment(), AzureEnvironment.Endpoint.RESOURCE_MANAGER)
				.withCredentials(credentials).withSerializerAdapter(new AzureJacksonAdapter())
				.withResponseBuilderFactory(new AzureResponseBuilder.Factory())
				.withInterceptor(new ProviderRegistrationInterceptor(credentials))
				.withInterceptor(new ResourceManagerThrottlingInterceptor()).withUserAgent(SPRING_CLOUD_USER_AGENT)
				.build();

		return Azure.authenticate(restClient, credentials.domain()).withSubscription(credentials.defaultSubscriptionId());
	}`
```

### PR DESCRIPTION
**Pull request by jacko9et**
Fixes #16595

### CODE REVIEW

File: sdk/spring/azure-spring-cloud-context/src/main/java/com/azure/spring/cloud/autoconfigure/context/AzureContextAutoConfiguration.java [hunk 1]
```diff
@@ -57,7 +57,8 @@ public Azure azure(AzureTokenCredentials credentials, AzureProperties azurePrope
             .build();
 
         if (azureProperties.getSubscriptionId() == null) {
-            return Azure.authenticate(restClient, credentials.domain()).withDefaultSubscription();
+            return Azure.authenticate(restClient, credentials.domain())
+                        .withSubscription(credentials.defaultSubscriptionId());
         } else {
             return Azure.authenticate(restClient, credentials.domain())
                 .withSubscription(azureProperties.getSubscriptionId());
```
Comment (chenrujun) [inline sdk/spring/azure-spring-cloud-context/src/main/java/com/azure/spring/cloud/autoconfigure/context/AzureContextAutoConfiguration.java:64]: I prefer the following code:
```
String subscriptionId = Optional.of(azureProperties)
        .map(AzureProperties::getSubscriptionId)
        .orElseGet(credentials::defaultSubscriptionId);
return Azure.authenticate(restClient, credentials.domain())
            .withSubscription(subscriptionId);
```

**Review by chenrujun — CHANGES_REQUESTED** [review]

**Review by chenrujun — APPROVED** [review]
LGTM.
