### PR TITLE
Fixed indexing policy getting reset when not provided

### LINKED ISSUE #20330: Azure Spring Data Cosmos - IndexingPolicy is getting overwritten on application bootup
**Describe the bug**
* In Azure spring data cosmos, container's `IndexingPolicy` is getting overriden on application bootup in both the cases where `CosmosIndexingPolicy` annotation is used and not used on the Entity. 
  
**To Reproduce**
Update the indexing policy on container through Azure portal. Then start a spring data cosmos sample application. As application is booted up, indexing policy reverts back to default value. 

This happens in both cases, even if `CosmosIndexingPolicy` annotation is used on the Entity which defines the container definition. And in the case where no annotation is used, still the indexing policy gets overwritten. 

**Expected behavior**
Spring Data cosmos should only create the container if it does not exists. It should not overwrite the indexing policy already defined in the portal. 

**Setup (please complete the following information):**
 - This issue is happening on azure-spring-data-cosmos 3.3.0 and above.

### PR DESCRIPTION
**Pull request by kushagraThapar**
Closes #20330

### CODE REVIEW

File: sdk/cosmos/azure-spring-data-cosmos/src/main/java/com/azure/spring/data/cosmos/repository/support/SimpleReactiveCosmosRepository.java [hunk 1]
```diff
@@ -47,6 +47,7 @@ public SimpleReactiveCosmosRepository(CosmosEntityInformation<T, K> metadata,
 
         CosmosContainerProperties currentProperties = getContainerProperties();
         if (currentProperties != null
+            && entityInformation.isIndexingPolicySpecified()
```
Comment (mbhaskar) [inline sdk/cosmos/azure-spring-data-cosmos/src/main/java/com/azure/spring/data/cosmos/repository/support/SimpleReactiveCosmosRepository.java:50]: Do we also have to check for empty indexing policy?

**Review by mbhaskar — APPROVED** [review]
You may also consider adding a real integration test by reading container properties and comparing the index. 
LGTM. Thanks for the fix

File: sdk/cosmos/azure-spring-data-cosmos/src/main/java/com/azure/spring/data/cosmos/repository/support/SimpleReactiveCosmosRepository.java (hunk 1 above)
Comment (kushagraThapar) [reply sdk/cosmos/azure-spring-data-cosmos/src/main/java/com/azure/spring/data/cosmos/repository/support/SimpleReactiveCosmosRepository.java:50]: We are not checking for empty indexing policy for now, but future plan is to add an override flag (annotation or to application.properties) - which will ask user to force override indexing policy if they want. If they don't want to override it, then indexing policy will not be updated even if it is used and not same as what they have on their account. 

Regarding IntegrationTest, it is difficult to add one, since for CI, containers are created through spring, and to create a container with indexing policy, the only way to do that is to add the annotation, which if added, will update the indexing policy. 

But we can improve integration tests for this scenario later. For now, the tests in the PR should be sufficient.
