### PR TITLE
Ensure BinaryData responses are durable in polling operations

### LINKED ISSUE #36564: [BUG] LRO Sync PollingStrategy may close the request before impl/user consume the response body
**Describe the bug**
LRO Sync PollingStrategy may close the request before impl/user consume the response body.

***Exception or Stack Trace***
`createSentShareTest()` results to `Error: org.opentest4j.AssertionFailedError: expected: not <null>`.
See https://github.com/Azure/azure-sdk-for-java/pull/35339

**To Reproduce**
Steps to reproduce the behavior: Run `createSentShareTest()` as PLAYBACK, under sync stack https://github.com/Azure/azure-sdk-for-java/pull/36523/commits/d367085ad2c5c3da7b3b311c8fab6e7f20699f96
Ref https://github.com/Azure/azure-sdk-for-java/pull/36523

***Code Snippet***
Add the code snippet that causes the issue.

**Expected behavior**

**Screenshots**

**Setup (please complete the following information):**
 - IDE: [e.g. IntelliJ]
 - Library/Libraries: com.azure:azure-core:1.42.0
 - Java version: 11 
 - App Server/Environment: [e.g. Tomcat, WildFly, Azure Function, Apache Spark, Databricks, IDE plugin or anything special]
 - Frameworks: [e.g. Spring Boot, Micronaut, Quarkus, etc] 

**Additional context**
Possible cause https://github.com/Azure/azure-sdk-for-java/blob/azure-core_1.42.0/sdk/core/azure-core/src/main/java/com/azure/core/util/polling/SyncOperationResourcePollingStrategy.java#L220-L223

When code gets out of the `try with` block, the response body may not be consumed. If the response is a stream (e.g. file download), it actually cannot be consumed here.

Discussion of the problem https://github.com/Azure/azure-sdk-for-java/pull/36523#discussion_r1305411902

In Sync, some one may have to close the `HttpResponse` somewhere, to return the connection back to connection pool (to avoid resource leak).

Not sure if this kind of "close the request" would affect other sync API, e.g. streaming (download file).

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

### PR DESCRIPTION
**Pull request by alzimmermsft**
# Description

Fixes #36564

This fixes a bug where `BinaryData.toReplayableContent` could be called but the underlying content isn't made replayable until the `BinaryData` returned was accessed for data. This only affected `BinaryData`s using `FluxByteBufferContent` as the backing content source, this issue was that the synchronous replayable content API was coded that the underlying `Flux<ByteBuffer>` wasn't copied until the `BinaryData`'s accessor APIs we called to get content from the `BinaryData`. Now, the synchronous API eagerly makes the underlying `Flux<ByteBuffer>` replayable.

# All SDK Contribution checklist:
- [x] **The pull request does not introduce [breaking changes]**
- [x] **CHANGELOG is updated for new features, bug fixes or other significant changes.**
- [x] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md).**

## [General Guidelines and Best Practices](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md#developer-guide)
- [x] Title of the pull request is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md#building-and-unit-testing)
- [x] Pull request includes test coverage for the included changes.

### CODE REVIEW

File: sdk/core/azure-core/src/main/java/com/azure/core/implementation/util/FluxByteBufferContent.java [hunk 1]
```diff
@@ -125,31 +124,47 @@ public BinaryDataContent toReplayableContent() {
...
-        replayableContent = new FluxByteBufferContent(bufferedFlux, length, true);
-        cachedReplayableContent.set(replayableContent);
-        return replayableContent;
+        return bufferContent().map(bufferedData -> {
+            FluxByteBufferContent bufferedContent = new FluxByteBufferContent(Flux.fromIterable(bufferedData)
+                .map(ByteBuffer::duplicate), length, true);
+            cachedReplayableContent.set(bufferedContent);
+
+            return bufferedContent;
+        }).block();
```
Comment (srnagar) [inline sdk/core/azure-core/src/main/java/com/azure/core/implementation/util/FluxByteBufferContent.java:133]: Should we consider using `publishOn` to use `boundedElastic` scheduler?

**Review by srnagar — APPROVED** [review]

File: sdk/core/azure-core/src/main/java/com/azure/core/implementation/util/FluxByteBufferContent.java (hunk 1 above)
Comment (alzimmermsft) [reply sdk/core/azure-core/src/main/java/com/azure/core/implementation/util/FluxByteBufferContent.java:133]: Maybe, we didn't before so this doesn't change that behavior, so we may want to put that off until next release.

The `publishOn` would get the handling of the `Flux` off any non-blocking thread, such as the Netty IO threads, right? And this could help more quickly free up those threads to take on another network request?

Comment (alzimmermsft) [reply sdk/core/azure-core/src/main/java/com/azure/core/implementation/util/FluxByteBufferContent.java:133]: Given this retains previous behavior, this will be held off on for now and reevaluated later.
