### PR TITLE
Use Reflection to Configure Jackson 2.12 Features

### LINKED ISSUE #19897: [BUG] Azure Core 1.14.0 incompatible with Spring Boot 2.3/2.4
**Describe the bug**
Using any library that uses Azure Core 1.14.0 results in NoSuchMethodError when using Spring Boot.

***Exception or Stack Trace***
Caused by: java.lang.NoSuchMethodError: com.fasterxml.jackson.databind.ObjectMapper.coercionConfigDefaults()Lcom/fasterxml/jackson/databind/cfg/MutableCoercionConfig;
	at com.azure.core.util.serializer.JacksonAdapter.<init>(JacksonAdapter.java:106)
	at com.azure.core.util.serializer.JacksonAdapter.createDefaultSerializerAdapter(JacksonAdapter.java:139)
	at com.azure.core.http.rest.RestProxy.createDefaultSerializer(RestProxy.java:585)
	at com.azure.core.http.rest.RestProxy.create(RestProxy.java:637)
	at com.azure.data.appconfiguration.ConfigurationAsyncClient.<init>(ConfigurationAsyncClient.java:73)
	at com.azure.data.appconfiguration.ConfigurationClientBuilder.buildAsyncClient(ConfigurationClientBuilder.java:205)
	at hello.ApplicationRunnerTaskExecutor.run(ApplicationRunnerTaskExecutor.java:48)
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:795)
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:785)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:333)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1309)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1298)
	at hello.Application.main(Application.java:18)
	... 6 more

**To Reproduce**
1. Create Basic Spring Boot Project using Spring Boot Starter
2. Include a Azure Library that uses Azure Core 1.14.0 (I am using azure-data-appconfiguration 1.1.10)
3. Use an then just had the sync and async examples of the library.
4. Run

***Code Snippet***
```
ConfigurationAsyncClient configurationClient = new ConfigurationClientBuilder()
            .connectionString("my-connectionString")
            .buildAsyncClient();

        SettingSelector settingSelector = new SettingSelector().setKeyFilter("*")
            .setLabelFilter("*");

        configurationClient.listRevisions(settingSelector).byPage(1);

        ConfigurationClient configurationClientSync = new ConfigurationClientBuilder()
            .connectionString(
                "my-connection-string")
            .buildClient();

        settingSelector = new SettingSelector().setKeyFilter("*")
            .setLabelFilter("*");

        System.out.println("Pre Request");
        Iterator<PagedResponse<ConfigurationSetting>> iter = configurationClientSync.listRevisions(settingSelector)
            .iterableByPage().iterator();

        System.out.println("Getting Next Page");
        PagedResponse<ConfigurationSetting> response = iter.next();
```

**Expected behavior**
They should be compatible as azure-sdk-for-java has spring boot libraries in it.

**Setup (please complete the following information):**
 - OS: Windows 10
 - IDE : Eclipse
 - azure-data-appconfiguration 1.1.10, spring-boot-starter 2.3.9/2.4.1

**Additional context**
I was able to get it to work by overriding the Jackson libraries in my pom file, but not sure what side affects this may have, and shouldn't be required.

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x ] Bug Description Added
- [x ] Repro Steps Added
- [x ] Setup information Added

### PR DESCRIPTION
**Pull request by alzimmermsft**
Fixes #19897 

This PR updates `azure-core` and `azure-core-serializer-json-jackson` to use `MethodHandle`s when configuring Jackson 2.12 features. The change prevents Core from throwing `MethodNotFoundException`s and `ClassNotFoundException`s if Jackson is resolved to 2.11.

### CODE REVIEW

**Comment by alzimmermsft** [comment]
@saragluna, @mrm9084, this should resolve the issues where method and class not found exceptions are being thrown if Jackson resolves to 2.11.

@srnagar, @anuchandy, could you take a look at this change.

File: sdk/core/azure-core-serializer-json-jackson/src/main/java/com/azure/core/serializer/json/jackson/JacksonJsonSerializer.java [hunk 1]
```diff
@@ -34,6 +37,46 @@
...
+                MethodType.methodType(String.class, AnnotatedMethod.class, String.class));
+            useReflectionForMemberName = true;
+        } catch (Throwable ignored) {
+        }
+
+        GET_ACCESSOR_NAMING = getAccessorNaming;
+        FOR_POJO = forPojo;
+        FIND_NAME_FOR_IS_GETTER = findNameForIsGetter;
+        FIND_NAME_FOR_REGULAR_GETTER = findNameForRegularGetter;
+        USE_REFLECTION_FOR_MEMBER_NAME = useReflectionForMemberName;
```
Comment (srnagar) [inline sdk/core/azure-core-serializer-json-jackson/src/main/java/com/azure/core/serializer/json/jackson/JacksonJsonSerializer.java:77]: If the above `try` block throws, some of these could be null. It would be better to throw instead of ignoring the exception and to get into an inconsistent state here.

File: sdk/core/azure-core-serializer-json-jackson/src/main/java/com/azure/core/serializer/json/jackson/JacksonJsonSerializer.java [hunk 2]
```diff
@@ -195,14 +238,41 @@ private String removePrefix(Method method) {
...
+            name = removePrefixWithBeanUtils(annotatedMethod);
         }
 
         return name;
     }
+
+    private static String removePrefixWithReflection(MapperConfig<?> config, AnnotatedClass annotatedClass,
+        AnnotatedMethod method, String methodName) {
+        try {
+            Object accessorNamingStrategy = FOR_POJO.invoke(GET_ACCESSOR_NAMING.invoke(config), config, annotatedClass);
```
Comment (srnagar) [inline sdk/core/azure-core-serializer-json-jackson/src/main/java/com/azure/core/serializer/json/jackson/JacksonJsonSerializer.java:260]: These could result in NPE if FOR_POJO and other method handles are `null` (see above comment).

File: sdk/core/azure-core-serializer-json-jackson/src/main/java/com/azure/core/serializer/json/jackson/JacksonJsonSerializer.java [hunk 3]
```diff
@@ -195,14 +238,41 @@ private String removePrefix(Method method) {
...
+
+
+            String name = (String) FIND_NAME_FOR_IS_GETTER.invoke(accessorNamingStrategy, method, methodName);
+            if (name == null) {
+                name = (String) FIND_NAME_FOR_REGULAR_GETTER.invoke(accessorNamingStrategy, method, methodName);
+            }
+
+            return name;
+        } catch (Throwable ignored) {
+            return null;
```
Comment (srnagar) [inline sdk/core/azure-core-serializer-json-jackson/src/main/java/com/azure/core/serializer/json/jackson/JacksonJsonSerializer.java:270]: add a log here.

File: sdk/core/azure-core/src/main/java/com/azure/core/util/serializer/JacksonAdapter.java [hunk 4]
```diff
@@ -59,6 +60,49 @@
...
+                .invoke();
+            useReflectionToSetCoercion = true;
+        } catch (Throwable ignored) {
+        }
+
+        COERCION_CONFIG_DEFAULTS = coercionConfigDefaults;
+        SET_COERCION = setCoercion;
+        COERCION_INPUT_SHAPE_EMPTY_STRING = coercionInputShapeEmptyString;
+        COERCION_ACTION_AS_NULL = coercionActionAsNull;
+        USE_REFLECTION_TO_SET_COERCION = useReflectionToSetCoercion;
```
Comment (srnagar) [inline sdk/core/azure-core/src/main/java/com/azure/core/util/serializer/JacksonAdapter.java:103]: Same comment as above - better to throw an exception.

File: sdk/core/azure-core-serializer-json-jackson/src/main/java/com/azure/core/serializer/json/jackson/JacksonJsonSerializer.java (hunk 1 above)
Comment (alzimmermsft) [reply sdk/core/azure-core-serializer-json-jackson/src/main/java/com/azure/core/serializer/json/jackson/JacksonJsonSerializer.java:77]: Given that this is in a static constructor this could result in an application failing to start, and this would happen if Spring resolves to 2.11 as this is trying to fix. Instead, would it better to validate that all constants are non-null? There is a flag that only gets set to true if no exceptions are thrown to use these constants.

Comment (alzimmermsft) [reply sdk/core/azure-core-serializer-json-jackson/src/main/java/com/azure/core/serializer/json/jackson/JacksonJsonSerializer.java:77]: Additionally, I'm not certain if `MethodHandle` lookups can return null, I believe they throw if a handle isn't found (probably for this exact reason, to not get into inconsistent states).

File: sdk/core/azure-core-serializer-json-jackson/src/main/java/com/azure/core/serializer/json/jackson/JacksonJsonSerializer.java (hunk 3 above)
Comment (alzimmermsft) [reply sdk/core/azure-core-serializer-json-jackson/src/main/java/com/azure/core/serializer/json/jackson/JacksonJsonSerializer.java:270]: Added a verbose log

File: sdk/core/azure-core-serializer-json-jackson/src/main/java/com/azure/core/serializer/json/jackson/JacksonJsonSerializer.java (hunk 1 above)
Comment (srnagar) [reply sdk/core/azure-core-serializer-json-jackson/src/main/java/com/azure/core/serializer/json/jackson/JacksonJsonSerializer.java:77]: Yeah, it seems like MethodHandle will never return null. So, just using the boolean at the end makes sense to ensure everything is initialized. Maybe just log the exception in the catch block above.

**Review by srnagar — APPROVED** [review]

**Comment by g2vinay** [comment]
Let's add an unreleased tag in version_client.txt for azure-core, so that spring poms can pick it up and validate the azure-core before we patch release.

**Comment by stliu** [comment]
@alzimmermsft Thanks, I really appreciate this change.

**Review by chenrujun — APPROVED** [review]
LGTM.
