### PR TITLE
Identity mi dac fixes

### LINKED ISSUE #41291: IMDS probe requests should throw CredentialUnavailableException for any response that is not valid json
Currently we handle responses from IMDS under certain conditions by throwing `CredentialUnavailableException`. The purpose of this exception is to indicate to chained credentials, such as `DefaultAzureCredential`, that the credential selection process should not terminate and continue attempting credentials along the chain.

Please validate in our managed identity probe request implementation that any request, either successful or unsuccessful, containing content other than valid json should result in throwing `CredentialUnavailableException`.

### PR DESCRIPTION
**Pull request by billwert**
Fixes #41291

### CODE REVIEW

File: sdk/identity/azure-identity/src/main/java/com/azure/identity/implementation/IdentityClient.java [hunk 1]
```diff
@@ -553,7 +555,12 @@ private Mono<AccessToken> getTokenFromMsalMIClient(String resource) {
                     throw new RuntimeException(e);
                 }
             }))
-            .onErrorMap(t -> new CredentialUnavailableException("Managed Identity authentication is not available.", t))
+            .onErrorMap(t -> {
+                if (options.isChained() && t instanceof MsalJsonParsingException) {
+                    return new CredentialUnavailableException("Managed Identity authentication is not available.", t);
+                }
+                return new ClientAuthenticationException("Managed Identity authentication is not available.", null, t);
```
Comment (g2vinay) [inline sdk/identity/azure-identity/src/main/java/com/azure/identity/implementation/IdentityClient.java:562]: if MI is not available as per message, why not throw Unavilable Exception only ?

File: sdk/identity/azure-identity/src/main/java/com/azure/identity/implementation/IdentityClient.java [hunk 2]
```diff
@@ -913,27 +920,18 @@ int getRetryTimeoutInMs(int retry) {
...
+        try {
+            url = getUrl(endpoint + "?api-version=2018-02-01");
+        } catch (MalformedURLException e) {
+            return Mono.error(e);
+        }
+        HttpRequest request = new HttpRequest(HttpMethod.GET, url);
 
-            return true;
-        });
+        return getPipeline().send(request)
```
Comment (g2vinay) [inline sdk/identity/azure-identity/src/main/java/com/azure/identity/implementation/IdentityClient.java:931]: This is used for probing, I believe.
We need to have a 1 second timeout on this request.

File: sdk/identity/azure-identity/src/main/java/com/azure/identity/implementation/IdentityClient.java (hunk 1 above)
Comment (billwert) [reply sdk/identity/azure-identity/src/main/java/com/azure/identity/implementation/IdentityClient.java:562]: Ah, I was going to change this message to something indicating getting a token failed. Will fix.

**Review by g2vinay — APPROVED** [review]
