### PR TITLE
[Batch] Fix tests

### LINKED ISSUE #10425: Batch changelog.md file doesn't have the correct version formatting
[microsoft-azure-batch/CHANGELOG.md](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/batch/microsoft-azure-batch/CHANGELOG.md#800)  doesn't have the correct release formatting for the version.
## 8.0.0 
should be
## 8.0.0 (2020-04-20)

### PR DESCRIPTION
**Pull request by bgklein**
Edit: Adding fixes #10425

### CODE REVIEW

**Comment by bgklein** [comment]
@g2vinay you have any idea why this is failing? 

Our initial merge passed CI, but failed when looking to do a release. Interestingly this passes locally in RECORD mode so maybe something to do with the playback/build system? Not an expert in Java/the playback system so confused what exactly is failing?

**Comment by g2vinay** [comment]
@bgklein 
Looking at the failure logs.
The subscription id being passed to the test is null.

https://dev.azure.com/azure-sdk/public/_build/results?buildId=367106&view=logs&j=acd39e86-e698-5a60-1b88-c3e97f07b09a&t=9434261b-f861-55ea-b2fe-7ad88c9831af&l=823

File: sdk/batch/microsoft-azure-batch/src/test/java/com/microsoft/azure/batch/BatchIntegrationTestBase.java [hunk 1]
```diff
@@ -344,24 +343,24 @@ private static LogRecord createLogRecord(Level logLevel, String message) {
...
+                .withExistingResourceGroup("sdktest2")
                 .withAddressSpace("192.168.0.0/16")
                 .withSubnet(subnetName, "192.168.1.0/24")
                 .create();
         }
         String vNetResourceId = String.format(
             "/subscriptions/%s/resourceGroups/%s/providers/Microsoft.Network/virtualNetworks/%s/subnets/%s",
-            System.getenv("AZURE_BATCH_SUBSCRIPTION_ID"),
-            System.getenv("AZURE_BATCH_RESOURCE_GROUP"),
+            System.getenv("677f962b-9abf-4423-a27b-0c2f4094dcec"),
```
Comment (g2vinay) [inline sdk/batch/microsoft-azure-batch/src/test/java/com/microsoft/azure/batch/BatchIntegrationTestBase.java:362]: You'll need to remove System.getEnv here.
