### PR TITLE
Use standard scheduler and dispose of Integration test one

### LINKED ISSUE #7142: [BUG] Smoke tests uncovered issue in Event Hubs client beta
**Describe the bug**
Programs that use Event Hubs do not exit when disposing the producer or consumer. 

***Exception or Stack Trace***
Program hangs instead of exiting

**To Reproduce**
See code at -- https://github.com/danieljurek/azure-sdk-for-java/blob/smoke-test-jan2020/eng/smoke-tests/src/main/java/com/azure/EventHubs.java

***Code Snippet***
See code at: https://github.com/danieljurek/azure-sdk-for-java/blob/smoke-test-jan2020/eng/smoke-tests/src/main/java/com/azure/EventHubs.java

**Expected behavior**
The program exits when producers and consumers are disposed and the reactor doesn't keep the program open. 

**Screenshots**

**Setup (please complete the following information):**
 - OS: Windows
 - IDE : vscode
 - Version of the Library used: 5.0.0-beta.6

**Additional context**
This issue was discovered using the Smoke Tests. Smoke Tests simulate real world usage of packages (no source dependency or direct dependency on our engineering systems). 

@conniey started investigating this and it looks like the scheduler is not being closed properly in this version. 

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

### PR DESCRIPTION
**Pull request by conniey**
Fixes issue where a program using Event Hubs will not end because the scheduler is not disposed of.
Using the default elastic scheduler, when a program ends, reactor will take care of disposing of it.

See: https://stackoverflow.com/a/47922868/4220757

Fixes #7142

### CODE REVIEW

File: sdk/eventhubs/azure-messaging-eventhubs/src/samples/java/com/azure/messaging/eventhubs/EventProcessorClientAggregateEventsSample.java [hunk 1]
```diff
@@ -129,10 +129,11 @@ public static void main(String[] args) throws Exception {
                     return client.send(batch);
                 }).block(operationTimeout);
             }
-        }).doFinally(signal -> {
-            logger.info("Disposing of producer.");
-            client.close();
-        }).subscribeOn(scheduler);
+        }).subscribeOn(scheduler)
```
Comment (srnagar) [inline sdk/eventhubs/azure-messaging-eventhubs/src/samples/java/com/azure/messaging/eventhubs/EventProcessorClientAggregateEventsSample.java]: Does the order of `subscribeOn()` matter?

Comment (conniey) [reply sdk/eventhubs/azure-messaging-eventhubs/src/samples/java/com/azure/messaging/eventhubs/EventProcessorClientAggregateEventsSample.java]: According to this, order doesn't matter. 
https://stackoverflow.com/a/37986481/4220757
