### PR TITLE
Fix for bulk operations incorrect routing on split

### LINKED ISSUE #21126: [BUG] Azure Cosmos DB 4.13 - Bulk on Gateway mode
**Describe the bug**
When working with the client on Gateway mode and performing Bulk import operations, when the collection faces splits, the SDK is failing the Bulk operations with a 410 CosmosException

***Exception or Stack Trace***
```
{"ClassName":"CosmosException","userAgent":"azsdk-java-cosmos/4.15.0-beta.3 Windows10/10.0 JRE/11.0.9.1","statusCode":410,"resourceAddress":"https://maquaran-spark-westus2.documents.azure.com:443/dbs/test/colls/test/docs","error":"{\"code\":\"Gone\",\"message\":\"PartitionKeyRange with id '0' in collection '' doesn't exist.\\r\\nActivityId: bf7bd4dd-2136-4c34-82c2-8bbe4d7d2bca, \\r\\nRequestStartTime: 2021-05-04T00:19:02.5814811Z, RequestEndTime: 2021-05-04T00:19:02.5814811Z,  Number of regions attempted:1\\r\\n, Microsoft.Azure.Documents.Common/2.11.0, StatusCode: Gone\",\"additionalErrorInfo\":null}","innerErrorMessage":"PartitionKeyRange with id '0' in collection '' doesn't exist.\r\nActivityId: bf7bd4dd-2136-4c34-82c2-8bbe4d7d2bca, \r\nRequestStartTime: 2021-05-04T00:19:02.5814811Z, RequestEndTime: 2021-05-04T00:19:02.5814811Z,  Number of regions attempted:1\r\n, Microsoft.Azure.Documents.Common/2.11.0, StatusCode: Gone","causeInfo":null,"responseHeaders":"{Transfer-Encoding=chunked, Strict-Transport-Security=max-age=31536000, Server=Microsoft-HTTPAPI/2.0, x-ms-gatewayversion=version=2.11.0, Date=Tue, 04 May 2021 00:19:02 GMT, x-ms-activity-id=bf7bd4dd-2136-4c34-82c2-8bbe4d7d2bca, Content-Type=application/json, x-ms-substatus=1002}","requestHeaders":"[x-ms-cosmos-batch-atomic=false, Accept=application/json, x-ms-session-token=0:-1#2, x-ms-cosmos-is-batch-request=true, x-ms-date=Tue, 04 May 2021 00:19:02 GMT, x-ms-documentdb-partitionkeyrangeid=0, x-ms-cosmos-batch-continue-on-error=true, x-ms-consistency-level=Session, Content-Type=application/json]","cosmosDiagnostics":{"userAgent":"azsdk-java-cosmos/4.15.0-beta.3 Windows10/10.0 JRE/11.0.9.1","requestLatencyInMs":41,"requestStartTimeUTC":"2021-05-04T00:19:02.289941700Z","requestEndTimeUTC":"2021-05-04T00:19:02.331443600Z","connectionMode":"GATEWAY","responseStatisticsList":[],"supplementalResponseStatisticsList":[],"addressResolutionStatistics":{},"regionsContacted":["https://maquaran-spark-westus2.documents.azure.com:443/"],"retryContext":{"statusAndSubStatusCodes":null,"retryLatency":0,"retryCount":0},"metadataDiagnosticsContext":{"metadataDiagnosticList":null},"serializationDiagnosticsContext":{"serializationDiagnosticsList":[{"serializationType":"ITEM_SERIALIZATION","startTimeUTC":"2021-05-04T00:19:02.289941700Z","endTimeUTC":"2021-05-04T00:19:02.289941700Z","durationInMicroSec":0}]},"gatewayStatistics":{"sessionToken":null,"operationType":"Batch","statusCode":410,"subStatusCode":1002,"requestCharge":null,"requestTimeline":[{"eventName":"connectionCreated","startTimeUTC":"2021-05-04T00:19:02.290969600Z","durationInMicroSec":0},{"eventName":"connectionConfigured","startTimeUTC":"2021-05-04T00:19:02.290969600Z","durationInMicroSec":0},{"eventName":"requestSent","startTimeUTC":"2021-05-04T00:19:02.290969600Z","durationInMicroSec":1967},{"eventName":"transitTime","startTimeUTC":"2021-05-04T00:19:02.292937400Z","durationInMicroSec":36467},{"eventName":"received","startTimeUTC":"2021-05-04T00:19:02.329405100Z","durationInMicroSec":989}]},"systemInformation":{"usedMemory":"65651 KB","availableMemory":"4087693 KB","systemCpuLoad":"(2021-05-04T00:19:00.635608300Z 35.5%), (2021-05-04T00:19:00.635608300Z 35.5%), (2021-05-04T00:19:00.635608300Z 35.5%), (2021-05-04T00:19:00.635608300Z 35.5%), (2021-05-04T00:19:00.635608300Z 35.5%), (2021-05-04T00:19:01.061790900Z 35.5%)","availableProcessors":4},"clientCfgs":{"id":-1,"numberOfClients":2,"connCfg":{"rntbd":null,"gw":"(cps:1000, rto:PT5S, icto:PT1M, p:false)","other":"(ed: true, cs: false)"},"consistencyCfg":"(consistency: Session, mm: false, prgns: [])"}}}
```

**To Reproduce**
Running the `CosmosBulkAsyncTest`, `createItem_withBulk` with `@Factory(dataProvider = "simpleClientBuilderGatewaySession")` and triggering splits on the collection generates a Bulk response that contains `null` on the response and an `exception` which is a 410:

image

image

***Code Snippet***
Add the code snippet that causes the issue.

**Expected behavior**
Gateway mode should behave as Direct mode, it should be able to recover from splits.

The reason Direct mode works is because the partition routing maps are refreshed by the Consistency/HA stack, but that doesn't exist on Gateway mode.

**Screenshots**
Already added previously

**Setup (please complete the following information):**
 - OS: Windows
 - IDE : IntelliJ
 - Version of the Library used: 4.13 but also repros on the latest master

**Additional context**
This issue was fixed in the .NET SDK on https://github.com/Azure/azure-cosmos-dotnet-v3/pull/2069

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

### PR DESCRIPTION
**Pull request by mbhaskar**
When a collection split occurs during bulk opertions, the requests were still being retried on the original partition as the partitionkeyrange cache that helps in routing was not being refreshed correctly. The effect is that the user received a failure with a status code 410 and substatus code 1002. 
This PR addresses the above issue by refreshing the partitionkeyrange cache when a collection split occurs

Fixes #21126

### CODE REVIEW

File: sdk/cosmos/azure-cosmos/src/test/java/com/azure/cosmos/CosmosBulkGatewayTest.java [hunk 1]
```diff
@@ -0,0 +1,177 @@
...
+
+            return BulkOperations.getCreateItemOperation(eventDoc, new PartitionKey(partitionKey));
+        });
+
+        BulkProcessingOptions<CosmosBulkAsyncTest> bulkProcessingOptions = new BulkProcessingOptions<>();
+        bulkProcessingOptions.setMaxMicroBatchSize(100);
+        bulkProcessingOptions.setMaxMicroBatchConcurrency(5);
+
+        Flux<CosmosBulkOperationResponse<CosmosBulkAsyncTest>> responseFlux = container
+                                                                                  .processBulkOperations(cosmosItemOperationFlux1, bulkProcessingOptions);
```
Comment (FabianMeiswinkel) [inline sdk/cosmos/azure-cosmos/src/test/java/com/azure/cosmos/CosmosBulkGatewayTest.java:83]: NIT: line has too many chars

**Review by FabianMeiswinkel — APPROVED** [review]
Thanks - LGTM. I will block Spark Connector GA on this PR being merged

File: sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/batch/BulkExecutor.java [hunk 2]
```diff
@@ -264,31 +264,44 @@ public BulkExecutor(CosmosAsyncContainer container,
 
             // First check if it failed due to split, so the operations need to go in a different pk range group. So
             // add it in the mainSink.
-            if (cosmosException.getStatusCode() == HttpResponseStatus.GONE.code() &&
-                itemBulkOperation.getRetryPolicy().shouldRetryForGone(
-                    cosmosException.getStatusCode(),
-                    cosmosException.getSubStatusCode())) {
+            if (cosmosException.getStatusCode() == HttpResponseStatus.GONE.code()) {
```
Comment (ealsur) [inline sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/batch/BulkExecutor.java:267]: should this `if` be removed? since the code already calls `retryOtherExceptions` if the policy didn't handle the current one?

File: sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/batch/BulkOperationRetryPolicy.java [hunk 3]
```diff
@@ -77,25 +79,29 @@ public RetryContext getRetryContext() {
...
+                return Mono.just(false);
+            }
 
-            this.attemptedRetries++;
+            if ((subStatusCode == SubStatusCodes.PARTITION_KEY_RANGE_GONE ||
+                     subStatusCode == SubStatusCodes.COMPLETING_SPLIT ||
+                     subStatusCode == SubStatusCodes.COMPLETING_PARTITION_MIGRATION)) {
+                return collectionCache.resolveByNameAsync(null, collectionLink, null)
+                           .flatMap(collection -> this.partitionKeyRangeCache
+                                                      .forceRefresh(null, collection.getResourceId())
```
Comment (ealsur) [inline sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/batch/BulkOperationRetryPolicy.java:93]: nit: named parameters for null values?

File: sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/caches/RxPartitionKeyRangeCache.java [hunk 4]
```diff
@@ -247,5 +246,20 @@ public RxPartitionKeyRangeCache(RxDocumentClientImpl client, RxCollectionCache c
...
     }
-}
 
+    /**
+     * Force refreshes the partition range cache
+     * @param metadataDiagnosticsContext the metadata diagnostics context
+     * @param collectionRId the collectionRid
+     * @return a void Mono
+     */
+    public Mono<Void> forceRefresh(MetadataDiagnosticsContext metadataDiagnosticsContext, String collectionRId) {
```
Comment (ealsur) [inline sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/caches/RxPartitionKeyRangeCache.java:256]: Is this needed or can't the policy invoke `tryGetOverlappingRangesAsync` with forceRefresh and the full range?

**Review by ealsur — APPROVED** [review]

**Review by moderakh — APPROVED** [review]

**Review by moderakh — COMMENTED** [review]
how do we differentiate between GW vs Direct mode?

isn't only GW mode affected by the bug?

File: sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/batch/BulkExecutor.java (hunk 2 above)
Comment (mbhaskar) [reply sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/batch/BulkExecutor.java]: Have that if for early branching out. But removed it now as it makes code more cleaner

File: sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/batch/BulkOperationRetryPolicy.java (hunk 3 above)
Comment (mbhaskar) [reply sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/batch/BulkOperationRetryPolicy.java]: done

File: sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/caches/RxPartitionKeyRangeCache.java (hunk 4 above)
Comment (mbhaskar) [reply sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/caches/RxPartitionKeyRangeCache.java]: Actually that works. Moved to tryGetOverlappingRangesAsync

**Comment by mbhaskar** [comment]
> how do we differentiate between GW vs Direct mode?
> 
> isn't only GW mode affected by the bug?

Only GW mode is effected by this bug. `GoneAndRetryWithRetryPolicy` should take care of this in direct mode

File: sdk/cosmos/azure-cosmos/src/test/java/com/azure/cosmos/CosmosBulkGatewayTest.java (hunk 1 above)
Comment (mbhaskar) [reply sdk/cosmos/azure-cosmos/src/test/java/com/azure/cosmos/CosmosBulkGatewayTest.java]: formatted
