### PR TITLE
Logging exceptions with context

### LINKED ISSUE #44865: Clientcore: Exception log vs exception message
Here's what happens when we're doing something like

```java
public static void main( String[] args ) {
    ClientLogger logger = new ClientLogger(App.class);
    throw logger.atInfo()
        .addKeyValue("hello", "world")
        .log(new RuntimeException("test exception"));
}
```

1. If user didn't configure any logging, the exception instance is printed to stderr

  ```
  Exception in thread "main" java.lang.RuntimeException: test exception
  	at com.test.App.main(App.java:40)
  ```
  
2. If user set `LOG_LEVEL` or configured logback/etc,  we get a log in stdout and uncaught exception in stderr
  
  ```
  2025-04-02 14:42:16.032 [main] [ERROR] com.test.App - {"exception.type":"java.lang.RuntimeException","exception.message":"test exception","hello":"world"}
  Exception in thread "main" java.lang.RuntimeException: test exception
  	at com.test.App.main(App.java:13)
  ```

Assuming user didn't enable our logging and sees unhandled exception or logs it on their own, they don't get any context provided to the log record. 

With exceptions, we want to make sure we put all the important details into the exception instance (message), not just on the log record.

I.e. we should do something like 

```java
String errorMessage = String.format("Connection with id '%d' terminated, reason - '%s'", connectionId, reason);
throw logger.logThrowableAsError(new SomeException(errorMessage));
```

which in its turn becomes more friendly to users who don't use logging and less friendly to those who do (since we no longer provide structured context)).

To make it friendly to all users, we could do

```java
String errorMessage = String.format("Connection with id '%d' terminated, reason - '%s'", connectionId, reason);
Throwable error = new SomeException(errorMessage);

logger.atError()
  .addKeyValue("connectionId", connectionId)
  .addKeyValue("reason", reason)
  .setThrowable(error)
  .log("Connection terminated")

throw error;
```

But then it's not friendly to anyone who needs to write it - it's also hard to keep exception message and log consistent.

We should consider providing a convenience for lib developers to simplify exception creation along with logging it.

We can consider producing an exception message like `Connection terminated. {"connectionId": "...", "reason" : "..."}` while the log record full be fully structured.

### PR DESCRIPTION
**Pull request by lmolkova**
Fix #44865

Exception messages don't contain all the useful information we put in logs (e.g. connection-id when connection drops).
This PR allows to create and log exception using the same context in log and inside the exception message:

```java
throw logger.throwableAtWarning()
  .addKeyValue("connectionId", "foo")
  .addKeyValue("linkName", 1)
  .log("connection dropped", IOException::new);
```

Results in exception message like :

`java.io.IOException: connection dropped; {"connectionId":"foo","linkName":1}`

and log message:

`{"message":"connection dropped","exception.type":"java.io.IOException","connectionId":"foo","linkName":1}`

### CODE REVIEW

File: sdk/clientcore/core/src/main/java/io/clientcore/core/http/models/ETag.java [hunk 1]
```diff
@@ -66,10 +66,10 @@ public static ETag fromString(String eTag) {
         boolean startsWithQuote = eTag.charAt(0) == '"';
         boolean startsWithWeakETagPrefix = eTag.startsWith(WEAK_ETAG_PREFIX_QUOTE);
         if (!endsWithQuote || (!startsWithQuote && !startsWithWeakETagPrefix)) {
-            String exceptionMessage = String.format(
-                "The ETag '%s' is invalid, it should be null, '*', be wrapped in quotes, or be wrapped in quotes prefixed by W/",
-                eTag);
-            throw LOGGER.logThrowableAsError(new IllegalArgumentException(exceptionMessage));
+            throw LOGGER.throwableAtError(IllegalArgumentException::new)
```
Comment (alzimmermsft) [inline sdk/clientcore/core/src/main/java/io/clientcore/core/http/models/ETag.java:69]: Does this change the stacktrace location in the exception? Ex, does the stacktrace now start where the error was instantiated within the logging system or does it retain a starting point of this spot?

File: sdk/clientcore/core/src/main/java/io/clientcore/core/instrumentation/logging/ClientLogger.java [hunk 2]
```diff
@@ -98,21 +99,6 @@ public ClientLogger(Class<?> clazz, Map<String, Object> context) {
...
-     * Logs the {@link Throwable} at the warning level and returns it to be thrown.
-     * <p>
-     * This API covers the cases where a checked exception type needs to be thrown and logged.
-     *
-     * @param throwable Throwable to be logged and returned.
-     * @param <T> Type of the Throwable being logged.
-     * @return The passed {@link Throwable}.
-     * @throws NullPointerException If {@code throwable} is {@code null}.
-     */
-    public <T extends Throwable> T logThrowableAsWarning(T throwable) {
```
Comment (alzimmermsft) [inline sdk/clientcore/core/src/main/java/io/clientcore/core/instrumentation/logging/ClientLogger.java:111]: Are we keeping `logThrowableAsError(T)` for locations where we're re-throwing caught exceptions? Or was not deleting that too an oversight?

File: sdk/clientcore/core/src/main/java/io/clientcore/core/instrumentation/logging/ExceptionLoggingEvent.java [hunk 3]
```diff
@@ -0,0 +1,117 @@
...
+
+    /**
+     * Logs the exception with the provided short message and cause.
+     * The full exception message is enriched with the context of the log event.
+     *
+     * @param shortMessage The short message to log.
+     * @param cause The cause of the exception.
+     * @return The created exception.
+     */
+    public T log(String shortMessage, Throwable cause) {
```
Comment (alzimmermsft) [inline sdk/clientcore/core/src/main/java/io/clientcore/core/instrumentation/logging/ExceptionLoggingEvent.java:111]: Would we ever add in support for logging exceptions where we're adding suppressed exceptions as well as causal exceptions?

File: sdk/clientcore/core/src/main/java/io/clientcore/core/instrumentation/logging/ExceptionLoggingEvent.java [hunk 4]
```diff
@@ -0,0 +1,117 @@
...
+
+import java.util.function.BiFunction;
+
+/**
+ * This class is used to create a logging event for exception with contextual
+ * information that's consistently populated in exception and log message.
+ *
+ * @param <T> The type of the exception to be logged.
+ */
+public class ExceptionLoggingEvent<T extends Throwable> {
```
Comment (alzimmermsft) [inline sdk/clientcore/core/src/main/java/io/clientcore/core/instrumentation/logging/ExceptionLoggingEvent.java:16]: Does this need to be a different type than `LoggingEvent`?

Did this solve the issue with Spotbugs where all usages of log with throwing causing unchecked cast warnings from Spotbugs?

Comment (alzimmermsft) [reply sdk/clientcore/core/src/main/java/io/clientcore/core/instrumentation/logging/ExceptionLoggingEvent.java:16]: If keeping this add `@Metadata(properties = FLUENT)`

File: sdk/clientcore/core/src/main/java/io/clientcore/core/instrumentation/logging/LoggingEvent.java [hunk 5]
```diff
@@ -305,30 +300,72 @@ private String getMessageWithContext(String message) {
...
+
+    void recordExceptionDetails(Throwable throwable, String message) {
+        addKeyValueInternal(EXCEPTION_TYPE_KEY, throwable.getClass().getCanonicalName());
+        if (message != null) {
+            addKeyValueInternal(EXCEPTION_MESSAGE_KEY, message);
+        }
+
+        if (logger != null && logger.canLogAtLevel(LogLevel.VERBOSE)) {
+            StringBuilder stackTrace = new StringBuilder();
+            DefaultLogger.appendThrowable(stackTrace, throwable);
```
Comment (alzimmermsft) [inline sdk/clientcore/core/src/main/java/io/clientcore/core/instrumentation/logging/LoggingEvent.java:321]: Future enhancement: It's allowable for exceptions to disable stack traces, might want to check if there is a stack trace before adding the key-value pair to the structured log message. And possibly if stack traces were disabled log

`EXCEPTION_STACKTRACE_KEY: <stacktrace disabled by exception>`

to indicate, "sorry, can't help you here"

File: sdk/clientcore/core/src/main/java/io/clientcore/core/instrumentation/logging/LoggingEvent.java [hunk 6]
```diff
@@ -305,30 +300,72 @@ private String getMessageWithContext(String message) {
...
+            addKeyValue(EXCEPTION_STACKTRACE_KEY, stackTrace.toString());
+        }
+    }
+
+    String getExceptionMessageWithContext(String shortMessage, Throwable cause) {
+        if (cause != null) {
```
Comment (alzimmermsft) [inline sdk/clientcore/core/src/main/java/io/clientcore/core/instrumentation/logging/LoggingEvent.java:327]: Would we want to recurse down the cause chain? Ex,

```java
Throwable cause = exception.getCause();
while (cause != null) {
    // Consume cause
    ...
    cause = cause.getCause();
}
```

File: sdk/clientcore/core/src/main/java/io/clientcore/core/instrumentation/logging/LoggingEvent.java [hunk 7]
```diff
@@ -305,30 +300,72 @@ private String getMessageWithContext(String message) {
...
+        }
+
+        if (logger != null && logger.canLogAtLevel(LogLevel.VERBOSE)) {
+            StringBuilder stackTrace = new StringBuilder();
+            DefaultLogger.appendThrowable(stackTrace, throwable);
+            addKeyValue(EXCEPTION_STACKTRACE_KEY, stackTrace.toString());
+        }
+    }
+
+    String getExceptionMessageWithContext(String shortMessage, Throwable cause) {
```
Comment (alzimmermsft) [inline sdk/clientcore/core/src/main/java/io/clientcore/core/instrumentation/logging/LoggingEvent.java:326]: Do we want to add in suppressed exception handling too?

File: sdk/clientcore/core/src/main/java/io/clientcore/core/http/models/ETag.java (hunk 1 above)
Comment (lmolkova) [reply sdk/clientcore/core/src/main/java/io/clientcore/core/http/models/ETag.java:69]: yeah, it does add at least one extra line (`io.clientcore.core/io.clientcore.core.instrumentation.logging.ExceptionLoggingEvent.log`) to the stack trace :(

```
java.io.IOException: connection dropped

	at io.clientcore.core/io.clientcore.core.instrumentation.logging.ExceptionLoggingEvent.log(ExceptionLoggingEvent.java:89)
	at io.clientcore.core/io.clientcore.core.instrumentation.logging.ClientLoggerTests.logExceptionWithoutContext(ClientLoggerTests.java:190)
```

Unfortunately it's not possible to customize how Java fill in the stack trace, but we can, in theory, trim and override it.

While JVM should inline the `ExceptionLoggingEvent.log`, it (hopefully) will not happen frequently enough for optimization to kick in.

I've explored a bunch of variations of these two approaches:

- Make contextual exception that we format message for. Looks great from exception only side. Sucks because:
  - it does not solve the problem for JVM-defined exceptions which we use extensively. 
  - still need to make it work nicely with logging and avoid stylecheck complaints
  - it'd be at least slightly disconnected from logging (you can't make it work nicely with global logging context).
- Convert LoggingEvent to exception message, helper for exception message - still a lot of boilerplate for users and angry logging stylecheck

So I'd rather tolerate extra line on the stacktrace or look into trimming it away.

Comment (lmolkova) [reply sdk/clientcore/core/src/main/java/io/clientcore/core/http/models/ETag.java:69]: yeah, it does add at least one extra line (`io.clientcore.core/io.clientcore.core.instrumentation.logging.ExceptionLoggingEvent.log`) to the stack trace :(

```
java.io.IOException: connection dropped

	at io.clientcore.core/io.clientcore.core.instrumentation.logging.ExceptionLoggingEvent.log(ExceptionLoggingEvent.java:89)
	at io.clientcore.core/io.clientcore.core.instrumentation.logging.ClientLoggerTests.logExceptionWithoutContext(ClientLoggerTests.java:190)
```

Unfortunately it's not possible to customize how Java fill in the stack trace, but we can, in theory, trim and override it.

While JVM should inline the `ExceptionLoggingEvent.log`, it (hopefully) will not happen frequently enough for optimization to kick in.

I've explored a bunch of variations of these two approaches:

- Make contextual exception that we format message for. Looks great from exception only side. Sucks because:
  - it does not solve the problem for JVM-defined exceptions which we use extensively. 
  - still need to make it work nicely with logging and avoid stylecheck complaints
  - it'd be at least slightly disconnected from logging (you can't make it work nicely with global logging context).
- Convert LoggingEvent to exception message, helper for exception message - still a lot of boilerplate for users and angry logging stylecheck

So I'd rather tolerate extra line on the stacktrace or look into trimming it away.

Comment (alzimmermsft) [reply sdk/clientcore/core/src/main/java/io/clientcore/core/http/models/ETag.java:69]: I'm good with one extra line of stack trace, was more concerned if it completely changed the stack trace to somewhere else.

File: sdk/clientcore/core/src/main/java/io/clientcore/core/instrumentation/logging/ExceptionLoggingEvent.java (hunk 3 above)
Comment (lmolkova) [reply sdk/clientcore/core/src/main/java/io/clientcore/core/instrumentation/logging/ExceptionLoggingEvent.java:111]: I *think* we don't need anything special here.

I can do something like 

```java
throw LOGGER.throwableAtError((m, c) -> {
                    var ex = new IllegalArgumentException(m, c);
                    ex.addSuppressed(ex);
                    return ex;
                }))
    .addKeyValue("foo", bar)
    .log("Some message");
```

if I want to log exception with suppressed details.

It's not super-convenient, but there are very few places in the code where we add suppressed exceptions today.

File: sdk/clientcore/core/src/main/java/io/clientcore/core/instrumentation/logging/ExceptionLoggingEvent.java (hunk 4 above)
Comment (lmolkova) [reply sdk/clientcore/core/src/main/java/io/clientcore/core/instrumentation/logging/ExceptionLoggingEvent.java:16]: yes, we need a new type for a few reasons:
1. we need `log` to return exception for ergonomics reasons. An alternative would be to make `LoggingEvent` a template and having a regular one return `Void`
2. Exception logging event is special - it's always functional and always records key-value-pairs since you create it with intent to throw exception unrelated to log levels.  Therefore it does not need a bunch of lazy/supplier features we have on the LoggingEvent.

File: sdk/clientcore/core/src/main/java/io/clientcore/core/instrumentation/logging/LoggingEvent.java (hunk 7 above)
Comment (lmolkova) [reply sdk/clientcore/core/src/main/java/io/clientcore/core/instrumentation/logging/LoggingEvent.java:326]: I don't think suppression should be in the message itself, users can access it and log suppressed exceptions if they want to. We can do a better job logging them to.

Do you have something specific in mind?

File: sdk/clientcore/core/src/main/java/io/clientcore/core/instrumentation/logging/ClientLogger.java (hunk 2 above)
Comment (lmolkova) [reply sdk/clientcore/core/src/main/java/io/clientcore/core/instrumentation/logging/ClientLogger.java:111]: > Are we keeping logThrowableAsError(T) for locations where we're re-throwing caught exceptions

we actually use it to create exception most of the time, e.g. 
`throw LOGGER.logThrowableAsError(new IllegalArgumentException("Parameter 'key' cannot be null or empty"));`  or wrap checked exception `throw LOGGER.logThrowableAsError(CoreException.from(e));` 

I'm keeping `logThrowableAsError` since it's a nice convenience and we use it quite a lot without any context. 
I'm proposing to remove `logThrowableAsWarning` since we barely use it (3 usages in core) and I'd like to minimize the number of overrides we produce. 

Everything that used `logThrowableAsWarning` is now doing a more verbose version of it:

https://github.com/Azure/azure-sdk-for-java/blob/ec187bf9b65aa66814fd7fa7c263889406d6ae0c/sdk/clientcore/http-netty4/src/main/java/io/clientcore/http/netty4/implementation/Netty4HttpProxyHandler.java#L170

File: sdk/clientcore/core/src/main/java/io/clientcore/core/instrumentation/logging/LoggingEvent.java (hunk 5 above)
Comment (lmolkova) [reply sdk/clientcore/core/src/main/java/io/clientcore/core/instrumentation/logging/LoggingEvent.java:321]: it's interesting. According to throwable docs, when you disable stack trace (disable it being writeable), `getStackTrace` returns zero element array.

The `printStackTrace` through still writes the message like `IOException: connection dropped` which results in us populating `exception.stacktrace` with this value. When stack traces are not recorded, we just don't populate the property.

I don't mind doing something like 

```suggestion
           if (throwable.getStackTrace().length > 0) {
               DefaultLogger.appendThrowable(stackTrace, throwable);
           }
```

but I'm not sure I understand the need?

File: sdk/clientcore/annotation-processor/src/main/java/io/clientcore/annotation/processor/utils/ResponseHandler.java [hunk 8]
```diff
@@ -222,8 +222,8 @@ private static void addSerializationFormatResponseBodyStatements(BlockStmt body)
             + "    deserializedResult = CoreUtils.decodeNetworkResponse(networkResponse.getValue(), jsonSerializer, returnType); "
             + "} else if (xmlSerializer.supportsFormat(serializationFormat)) { "
             + "    deserializedResult = CoreUtils.decodeNetworkResponse(networkResponse.getValue(), xmlSerializer, returnType); "
-            + "} else { " + "    throw new RuntimeException(new UnsupportedOperationException("
-            + "        \"None of the provided serializers support the format: \" + serializationFormat + \".\")); "
+            + "} else { " + "    throw new UnsupportedOperationException("
```
Comment (alzimmermsft) [inline sdk/clientcore/annotation-processor/src/main/java/io/clientcore/annotation/processor/utils/ResponseHandler.java:225]: Nice fix!

File: sdk/clientcore/core/src/main/java/io/clientcore/core/http/models/Response.java [hunk 9]
```diff
@@ -83,7 +83,7 @@ public void close() {
             try {
                 ((Closeable) value).close();
             } catch (IOException e) {
-                throw LOGGER.logThrowableAsError(CoreException.from(e, false));
+                throw LOGGER.throwableAtError().log((msg, cause) -> CoreException.from(msg, e, false));
```
Comment (alzimmermsft) [inline sdk/clientcore/core/src/main/java/io/clientcore/core/http/models/Response.java:86]: Where exactly does `cause` come from here again? Should we be consuming it?

File: sdk/clientcore/core/src/main/java/io/clientcore/core/http/paging/PagedIterable.java [hunk 10]
```diff
@@ -211,7 +211,8 @@ private abstract static class PagedIterator<T, E> implements Iterator<E> {
         @Override
         public E next() {
             if (!hasNext()) {
-                throw LOGGER.logThrowableAsError(new NoSuchElementException("Iterator contains no more elements."));
+                throw LOGGER.throwableAtError()
+                    .log("Iterator contains no more elements.", (m, __) -> new NoSuchElementException(m));
```
Comment (alzimmermsft) [inline sdk/clientcore/core/src/main/java/io/clientcore/core/http/paging/PagedIterable.java:215]: I always prefer `ignored` over `_`* when there is only one ignored value

File: sdk/clientcore/core/src/main/java/io/clientcore/core/http/pipeline/OAuthBearerTokenAuthenticationPolicy.java [hunk 11]
```diff
@@ -67,8 +67,8 @@ public void authorizeRequest(HttpRequest httpRequest, OAuthTokenRequestContext c
     @Override
     public Response<BinaryData> process(HttpRequest httpRequest, HttpPipelineNextPolicy next) {
         if (!"https".equals(httpRequest.getUri().getScheme())) {
-            throw LOGGER.logThrowableAsError(
-                new RuntimeException("Token credentials require a URL using the HTTPS protocol scheme"));
+            throw LOGGER.throwableAtError()
+                .log("Token credentials require a URL using the HTTPS protocol scheme.", IllegalArgumentException::new);
```
Comment (alzimmermsft) [inline sdk/clientcore/core/src/main/java/io/clientcore/core/http/pipeline/OAuthBearerTokenAuthenticationPolicy.java:71]: Throwing this somewhere random

Should we have two `log` methods for this?

`log(String, Function<String, T>>` and `log(String, Throwable, BiFunction<String, Throwable, T>)`?

That way we don't need to ignore `Throwable` in exception types that don't support causal exceptions.

**Review by alzimmermsft — COMMENTED** [review]
Per offline discussions, it'd be good to split up `T log(String, Throwable, BiFunction<String, Throwable, T>)` into a few different methods that better align with calls.

`T log(String, BiFunction<String, Throwable, T>)` becomes `T log(String, Function<String, T)` and `T log(Throwable, BiFunction<String, Throwable, T>)` becomes `T log(Throwable, Function<Throwable, T>)`, so we don't need certain `BiFunction` values ignored if the constructor called by the `BiFunction` doesn't support String or Throwable.

This should be fine if we add it as part of release as the compiler should warn ahead of time when a calling pattern is invalid or ambiguous.

File: sdk/clientcore/core/src/main/java/io/clientcore/core/instrumentation/logging/LoggingEvent.java (hunk 5 above)
Comment (alzimmermsft) [reply sdk/clientcore/core/src/main/java/io/clientcore/core/instrumentation/logging/LoggingEvent.java:321]: I think that would help, just in case something odd happens

File: sdk/clientcore/core/src/main/java/io/clientcore/core/instrumentation/logging/LoggingEvent.java (hunk 7 above)
Comment (alzimmermsft) [reply sdk/clientcore/core/src/main/java/io/clientcore/core/instrumentation/logging/LoggingEvent.java:326]: Nope, I'm fine if we're happy with the behavior and call it out

File: sdk/clientcore/core/src/main/java/io/clientcore/core/http/pipeline/OAuthBearerTokenAuthenticationPolicy.java (hunk 11 above)
Comment (lmolkova) [reply sdk/clientcore/core/src/main/java/io/clientcore/core/http/pipeline/OAuthBearerTokenAuthenticationPolicy.java:71]: great idea, done

File: sdk/clientcore/core/src/main/java/io/clientcore/core/http/models/Response.java (hunk 9 above)
Comment (lmolkova) [reply sdk/clientcore/core/src/main/java/io/clientcore/core/http/models/Response.java]: it's a typo, it should be `LOGGER.throwableAtError().log(e, (msg, cause) -> CoreException.from(msg, cause, false)), and `cause` is `e`

File: sdk/clientcore/core/src/main/java/io/clientcore/core/models/CoreException.java [hunk 12]
```diff
@@ -19,6 +19,16 @@
  * Client libraries should implement their own exceptions that extend this class.
  */
 public abstract class CoreException extends RuntimeException {
+    /**
+     * Translates a {@link Throwable} into a {@link CoreException}.
```
Comment (lmolkova) [inline sdk/clientcore/core/src/main/java/io/clientcore/core/models/CoreException.java:23]: oops

File: sdk/clientcore/core/src/main/java/io/clientcore/core/implementation/utils/AuthenticateChallengeParser.java [hunk 13]
```diff
@@ -214,8 +218,9 @@ private AuthenticateChallenge createChallenge(String scheme, String token68, Map
             return new AuthenticateChallenge(scheme, token68);
         }
 
-        String message = String.format("Challenge '%s' had both token68 and auth-params.", challenge);
-        throw LOGGER.logThrowableAsError(new IllegalArgumentException(message));
+        throw LOGGER.throwableAtError()
+            .addKeyValue("challenge", challenge)
+            .log("Challenge ad both token68 and auth-params.", IllegalArgumentException::new);
```
Comment (billwert) [inline sdk/clientcore/core/src/main/java/io/clientcore/core/implementation/utils/AuthenticateChallengeParser.java:223]:
```suggestion
            .log("Challenge had both token68 and auth-params.", IllegalArgumentException::new);
```

**Review by billwert — APPROVED** [review]

**Review by JonathanGiles — APPROVED** [review]
Really nice work! Thanks for doing this.

**Review by alzimmermsft — APPROVED** [review]
