### PR TITLE
Fully Support Null Fields when Using Custom ObjectSerializer

### LINKED ISSUE #28610: [BUG] Search SDK Cannot Sends Null Field Values with Document Merge or MergeOrUpload
**Describe the bug**
We have a cx scenario where they are using java azure-search-documents library from com.azure to index documents. They noticed the library does not properly allow them to send a null value for a field during a merge or mergeOrUpload request. The documentation says this is supported by the API, but it does not work in the library. They need to be able to send a null value when indexing documents in order to remove the existing value from those fields in the index. This problem occurs in all cx environments and search services.

***Exception or Stack Trace***
No errors/exception. There is no changes to the document. 

**To Reproduce**
I'm able to repro the issue with the latest java SDK "11.4.9" and beta SDK"11.5.0-beta.8" where uploading/updating the document was successful with no error message and no changes reflected on the document(for both null values and non-null values). Also, I'm able to perform the upload operation using Rest Api without any issue and see the changes. Attaching the Rest Api collection and Java project that I used for reproducing the issue. 
  
**Note**: I noticed that the below Hotel class is not found in the azure-search-documents dependency so I add the Hotel class in my Java project. 
import com.azure.search.documents.models.Hotel;
***Code Snippet***
Attached
[azuresearch.zip](https://github.com/Azure/azure-sdk-for-java/files/8604885/azuresearch.zip)
[RestAPI_collection.zip](https://github.com/Azure/azure-sdk-for-java/files/8604892/RestAPI_collection.zip)
**Expected behavior**
Document needs to update/change based on merge or mergeOrUpload request using java [sdk.](url)

**Screenshots**

**Setup (please complete the following information):**
 - OS: [Windows]
 - IDE: [IntelliJ]
 - Library/Libraries: [e.g. com.azure:azure-search-documents:11.4.9 (groupId:artifactId:version)]
 RE: sdk/search/azure-search-documents/src/samples/java/com/azure/search/documents/IndexContentManagementExample.java
 - Java version: [e.g. 11] 
 - App Server/Environment: [local windows machine]
 - Frameworks: [Spring] 

If you suspect a dependency version mismatch (e.g. you see `NoClassDefFoundError`, `NoSuchMethodError` or similar), please check out [Troubleshoot dependency version conflict article](https://aka.ms/azsdk/java/dependency/troubleshoot) first. If it doesn't provide solution for the problem, please provide:
- verbose dependency tree (`mvn dependency:tree -Dverbose`)
- exception message, full stack trace, and any available logs

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

### PR DESCRIPTION
**Pull request by alzimmermsft**
# Description

Fixes #28610 

Resolves a gap in functionality where a custom `ObjectSerializer` would be used to convert a customer owned type into a `Map<String, Object>` which would be serialized by `JacksonAdapter` to be sent to the service. This didn't handle null key-value pairs properly as `JacksonAdapter` is configured, and will continue to be configured, to ignore null values, but this defeated the purpose of the custom `ObjectSerializer` to allow for custom handling to be applied to customer owned types.

Now, if an `ObjectSerializer` is included in the `SearchClient` it will be used to convert the document into a JSON string and be injected directly into the serialized JSON, giving full control of document serialization to a customer if they choose, or need, to use it. This should also add small performance improvement as before documents would be converted to JSON to be converted into a `Map<String, Object>` and would then later be converted back to JSON when sending the final request. Customers not using `ObjectSerializer` will continue to see the same runtime behaviors as before where null field values aren't included in the document sent to the service.

# All SDK Contribution checklist:
- [x] **The pull request does not introduce [breaking changes]**
- [x] **CHANGELOG is updated for new features, bug fixes or other significant changes.**
- [x] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md).**

## [General Guidelines and Best Practices](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md#developer-guide)
- [x] Title of the pull request is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md#building-and-unit-testing)
- [x] Pull request includes test coverage for the included changes.

### CODE REVIEW

File: sdk/search/azure-search-documents/src/main/java/com/azure/search/documents/implementation/DocumentsImpl.java [hunk 1]
```diff
@@ -401,21 +399,19 @@ public Mono<Response<SearchDocumentsResult>> searchGetWithResponseAsync(
...
         String orderByConverted =
                 JacksonAdapter.createDefaultSerializerAdapter().serializeList(orderBy, CollectionFormat.CSV);
         List<String> scoringParametersConverted =
-                Optional.ofNullable(scoringParameters)
-                        .map(Collection::stream)
-                        .orElseGet(Stream::empty)
-                        .map((item) -> Objects.toString(item, ""))
-                        .collect(Collectors.toList());
+                (scoringParameters == null)
+                        ? new ArrayList<>()
```
Comment (kasobol-msft) [inline sdk/search/azure-search-documents/src/main/java/com/azure/search/documents/implementation/DocumentsImpl.java:411]: would `Collections.emptyList()` work here (warning, it's immutable). otherwise should this be `ArrayList(0)` if there's low chance of anybody adding anything to this ?

File: sdk/search/azure-search-documents/src/main/java/com/azure/search/documents/implementation/converters/IndexActionConverter.java [hunk 2]
```diff
@@ -52,26 +51,42 @@ public static <T> com.azure.search.documents.implementation.models.IndexAction m
...
+                throw LOGGER.logExceptionAsError(new UncheckedIOException(ex));
+            }
+        } else {
+            // A custom ObjectSerializer is being used, use it.
+            documentJson = new String(serializer.serializeToBytes(document), StandardCharsets.UTF_8);
+        }
+
+        if (documentJson != null) {
+            boolean startsWithCurlyBrace = documentJson.startsWith("{");
+            boolean endsWithCurlyBrace = documentJson.endsWith("}");
```
Comment (kasobol-msft) [inline sdk/search/azure-search-documents/src/main/java/com/azure/search/documents/implementation/converters/IndexActionConverter.java:77]: Is content expected to be trimmed? I.e. is `\t\t{ ...  }\n\n` possible ?

File: sdk/search/azure-search-documents/src/main/java/com/azure/search/documents/implementation/DocumentsImpl.java (hunk 1 above)
Comment (kasobol-msft) [reply sdk/search/azure-search-documents/src/main/java/com/azure/search/documents/implementation/DocumentsImpl.java:411]: good to know.

File: sdk/search/azure-search-documents/src/main/java/com/azure/search/documents/implementation/converters/IndexActionConverter.java (hunk 2 above)
Comment (alzimmermsft) [reply sdk/search/azure-search-documents/src/main/java/com/azure/search/documents/implementation/converters/IndexActionConverter.java:77]: It should be trimmed given that it's serialization of the object without passing through other calls.
