### PR TITLE
Fixed Storage file Datalake test improvement

### LINKED ISSUE #18727: Storage file Datalake test improvement
There are no test cases about `listPaths().byPage()` in the existing test cases in the Java storage file datalake. So, it is recommended to add test cases related to paged retrieval results validation for method [`listPaths()`](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/storage/azure-storage-file-datalake/src/main/java/com/azure/storage/file/datalake/DataLakeFileSystemAsyncClient.java#L415) of `DataLakeFileSystemAsyncClient` class in java test [FileSystemAPITest.groovy](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/storage/azure-storage-file-datalake/src/test/java/com/azure/storage/file/datalake/FileSystemAPITest.groovy). 
By the way, python storage file datalake sdk have the [test cases](https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/storage/azure-storage-file-datalake/tests/test_file_system.py#L241) about  `get_paths().by_page()`.

 

@scottaddie , @joshfree , @kyle-patterson , @tg-msft , @alzimmermsft for notification.

### PR DESCRIPTION
**Pull request by v-hongli1**
Fixed #18727 

@joshfree, @tg-msft, @kyle-patterson and @rickle-msft for notification.

### CODE REVIEW

File: sdk/storage/azure-storage-file-datalake/src/test/java/com/azure/storage/file/datalake/FileSystemAsyncAPITest.groovy [hunk 1]
```diff
@@ -0,0 +1,1261 @@
...
+
+        then:
+        def dirPath = response.next()
+        response.hasNext()
+        def filePath = response.next()
+        !response.hasNext()
+    }
+
+    def "List paths max results by page"() {
+        setup:
```
Comment (rickle-msft) [inline sdk/storage/azure-storage-file-datalake/src/test/java/com/azure/storage/file/datalake/FileSystemAsyncAPITest.groovy:957]: Based on the issue being addressed, I think the list paths by page methods are the only additions here that are really necessary because there can be different behavior in the sync and async clients. We don't otherwise maintain separate tests for sync and async. I'd rather move these few tests into the existing FileSystemApiTest file and delete the rest

Comment (hongli750210) [reply sdk/storage/azure-storage-file-datalake/src/test/java/com/azure/storage/file/datalake/FileSystemAsyncAPITest.groovy]: According to your comment, fixed in the new version.

**Review by rickle-msft — APPROVED** [review]

**Comment by v-xuto** [comment]
@rickle-msft  If there is no problem, please help us merge this PR.
