### PR TITLE
Fixed an issue where whitespace would cause ntfsattributes to fail in…

### LINKED ISSUE #9755: [BUG] NtfsFileAttributes.toAttributes tripped up by whitespace
**Describe the bug**
NtfsFileAttributes unable to parse response when headers include white space

***Exception or Stack Trace***

value
java.lang.IllegalArgumentException: value
	at com.azure.storage.file.share.models.NtfsFileAttributes.toAttributes(NtfsFileAttributes.java:152)
	at com.azure.storage.file.share.FileSmbProperties.<init>(FileSmbProperties.java:199)
	at com.azure.storage.file.share.ShareDirectoryAsyncClient.createWithRestResponse(ShareDirectoryAsyncClient.java:1008)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:107)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1592)
	at reactor.core.publisher.MonoFlatMap$FlatMapInner.onNext(MonoFlatMap.java:241)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1592)
	at reactor.core.publisher.MonoIgnoreThen$ThenAcceptInner.onNext(MonoIgnoreThen.java:296)
	at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:67)
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:114)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1592)
	at reactor.core.publisher.MonoProcessor.onNext(MonoProcessor.java:317)
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:73)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1592)
	at reactor.core.publisher.MonoCallable.subscribe(MonoCallable.java:61)
	at reactor.core.publisher.Mono.subscribe(Mono.java:4087)
	at reactor.core.publisher.MonoProcessor.add(MonoProcessor.java:457)
	at reactor.core.publisher.MonoProcessor.subscribe(MonoProcessor.java:370)
	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:55)
	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.drain(MonoIgnoreThen.java:153)
	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.ignoreDone(MonoIgnoreThen.java:190)
	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreInner.onComplete(MonoIgnoreThen.java:240)
	at reactor.core.publisher.MonoIgnoreElements$IgnoreElementsSubscriber.onComplete(MonoIgnoreElements.java:81)
	at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:136)
	at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onComplete(FluxDoFinally.java:138)
	at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:136)
	at reactor.netty.channel.FluxReceive.terminateReceiver(FluxReceive.java:414)
	at reactor.netty.channel.FluxReceive.drainReceiver(FluxReceive.java:204)
	at reactor.netty.channel.FluxReceive.onInboundComplete(FluxReceive.java:362)
	at reactor.netty.channel.ChannelOperations.onInboundComplete(ChannelOperations.java:363)
	at reactor.netty.channel.ChannelOperations.terminate(ChannelOperations.java:412)
	at reactor.netty.http.client.HttpClientOperations.onInboundNext(HttpClientOperations.java:556)
	at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:93)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:438)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:326)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:300)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1478)
	at io.netty.handler.ssl.SslHandler.decodeNonJdkCompatible(SslHandler.java:1239)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1276)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:503)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:442)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:281)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1422)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:931)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:700)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514)
	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1050)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
	Suppressed: java.lang.Exception: #block terminated with an error
		at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:93)
		at reactor.core.publisher.Mono.block(Mono.java:1663)
		at com.azure.storage.common.implementation.StorageImplUtils.blockWithOptionalTimeout(StorageImplUtils.java:95)
		at com.azure.storage.file.share.ShareDirectoryClient.createWithResponse(ShareDirectoryClient.java:149)
		at bugs.azure.storage.AzureFilesHiddenDirectoryTest.createHiddenDirectory(AzureFilesHiddenDirectoryTest.java:37)
		at bugs.azure.storage.AzureFilesHiddenDirectoryTest.lambda$createHiddenDirectory$1(AzureFilesHiddenDirectoryTest.java:61)
		at bugs.azure.storage.SelfCleaningAzureFilesTest.runTestAndCleanUp(SelfCleaningAzureFilesTest.java:37)
		at bugs.azure.storage.AzureFilesHiddenDirectoryTest.createHiddenDirectory(AzureFilesHiddenDirectoryTest.java:60)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:498)
		at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
		at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
		at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
		at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
		at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
		at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
		at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
		at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
		at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
		at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
		at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
		at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
		at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
		at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
		at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
		at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
		at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
		at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:498)
		at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
		at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
		at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
		at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
		at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
		at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:118)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:498)
		at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
		at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
		at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
		at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
		at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:412)
		at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
		at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
		at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
		... 1 more

**To Reproduce**

1. Clone the linked repository [https://github.com/benfarnold/azure-storage-sdk-copy-files-bug.git](url)
2. Fill in the ENDPOINT and SAS_TOKEN constants in SelfCleaningAzureFilesTest
3. Run the AzureFileHiddenDirectoryTest or use build target _gradle test_
 
***Code Snippet***
<pre>`	private void createHiddenDirectory(String shareName, String directoryName) {
		ShareDirectoryClient destFileClient = getClientBuilder(shareName, directoryName).buildDirectoryClient();
		EnumSet attributes = EnumSet.of(NtfsFileAttributes.HIDDEN, NtfsFileAttributes.DIRECTORY);
		FileSmbProperties smbProperties = new FileSmbProperties();
		smbProperties.setNtfsFileAttributes(attributes);
		destFileClient.createWithResponse(smbProperties, null, null, null, Context.NONE);
	}`
</pre>
**Expected behavior**
Expected a hidden directory to be created.

**Screenshots**
https://drive.google.com/file/d/1JCYUsK6IajKGEvUrMnWOABK5SdiOwopk/view?usp=sharing

**Setup (please complete the following information):**
 - OS: Microsoft Windows 10
 - IDE : IntelliJ
 - Version of the Library used: 
compile group: 'com.azure', name: 'azure-storage-file-share', version: '12.1.0'

**Additional context**
Was actually trying to see if we could create hidden directories via the REST API

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ Y] Bug Description Added
- [Y] Repro Steps Added
- [Y] Setup information Added

### PR DESCRIPTION
**Pull request by gapra-msft**
… parsing

Resolves #9755

### CODE REVIEW

File: sdk/storage/azure-storage-file-share/src/main/java/com/azure/storage/file/share/models/NtfsFileAttributes.java [hunk 1]
```diff
@@ -131,6 +131,7 @@ private static void toStringHelper(StringBuilder sb, EnumSet<NtfsFileAttributes>
         String[] splitAttributes = ntfsAttributes.split("\\|");
 
         for (String sa : splitAttributes) {
+            sa = sa.trim();
```
Comment (alzimmermsft) [inline sdk/storage/azure-storage-file-share/src/main/java/com/azure/storage/file/share/models/NtfsFileAttributes.java:134]: Mind adding a test that directly targets this change.

Comment (gapra-msft) [reply sdk/storage/azure-storage-file-share/src/main/java/com/azure/storage/file/share/models/NtfsFileAttributes.java:133]: Thanks! I realized there werent any tests for those two methods and so I added more robust testing (also found a bug in fromAttributes so that's a win.)

File: sdk/storage/azure-storage-file-share/src/test/resources/session-records/ModelTestsNTFSToAttributes0.json [hunk 2]
```diff
@@ -0,0 +1,4 @@
+{
```
Comment (alzimmermsft) [inline sdk/storage/azure-storage-file-share/src/test/resources/session-records/ModelTestsNTFSToAttributes0.json:1]: I think the capitalization on the file name is causing playback failures in Linux, I think `NTFS` -> `Ntfs` is needed.

File: sdk/storage/azure-storage-file-share/src/test/resources/session-records/ModelTestsNTFSToAttributes1.json [hunk 3]
```diff
@@ -0,0 +1,4 @@
+{
```
Comment (alzimmermsft) [inline sdk/storage/azure-storage-file-share/src/test/resources/session-records/ModelTestsNTFSToAttributes1.json:1]: I think the capitalization on the file name is causing playback failures in Linux, I think `NTFS` -> `Ntfs` is needed.

File: sdk/storage/azure-storage-file-share/src/test/resources/session-records/ModelTestsNTFSToAttributes2.json [hunk 4]
```diff
@@ -0,0 +1,4 @@
+{
```
Comment (alzimmermsft) [inline sdk/storage/azure-storage-file-share/src/test/resources/session-records/ModelTestsNTFSToAttributes2.json:1]: I think the capitalization on the file name is causing playback failures in Linux, I think `NTFS` -> `Ntfs` is needed.

File: sdk/storage/azure-storage-file-share/src/test/resources/session-records/ModelTestsNTFSToAttributes0.json (hunk 2 above)
Comment (gapra-msft) [reply sdk/storage/azure-storage-file-share/src/test/resources/session-records/ModelTestsNTFSToAttributes0.json]: re-recorded and pushed that. I think Windows doesn't replace the file name if the caps are different?
