### PR TITLE
Fix doc for SharedTokenCacheCredential

### LINKED ISSUE #41922: Incorrect SharedTokenCacheCredential docs
This bit is incorrect because `SharedTokenCacheCredential` interoperated with Visual Studio ~~*Code*~~ and `VisualStudioCodeCredential` does not:
https://github.com/Azure/azure-sdk-for-java/blob/e736e3ab58351e31e16392fad15da8cba65eaa8b/sdk/identity/azure-identity/src/main/java/com/azure/identity/SharedTokenCacheCredential.java#L27-L31

### PR DESCRIPTION
**Pull request by billwert**
Fixes #41922

### CODE REVIEW

File: sdk/identity/azure-identity/src/main/java/com/azure/identity/SharedTokenCacheCredential.java [hunk 1]
```diff
@@ -24,8 +24,7 @@
  * Requires a username and client ID. If a username is not provided, then the
  * {@link Configuration#PROPERTY_AZURE_USERNAME AZURE_USERNAME} environment variable will be used.
  *
- * <p>This credential is a legacy mechanism for authenticating clients using credentials provided to Visual Studio Code.
- * This mechanism for Visual Studio authentication has been replaced by the {@link VisualStudioCodeCredential}/>.</p>
+ * <p>This credential is a legacy mechanism for authenticating clients using credentials provided to Visual Studio.</p>
  *
  * @see com.azure.identity
  * @see VisualStudioCodeCredential
```
Comment (chlowell) [inline sdk/identity/azure-identity/src/main/java/com/azure/identity/SharedTokenCacheCredential.java:30]: 👀

**Review by chlowell — APPROVED** [review]

**Review by scottaddie — APPROVED** [review]
