### PR TITLE
[AI] [Inference] use model version 2024-05-01-preview as default #44517

### LINKED ISSUE #44517: Update azure-ai-inference docs/samples to include type of endpoint
azure-ai-inference playground sample does not work

Image

It results in the 404 to `https://*.services.ai.azure.com/models/chat/completions?api-version=2024-08-01-preview`.

```
15:44:41.862 [main] INFO  c.a.a.i.i.C.completeSync - {"az.sdk.message":"HTTP response","statusCode":404,"url":"https://*.services.ai.azure.com/models/chat/completions?api-version=2024-08-01-preview","durationMs":946,"content-length":56,"Date":"Wed, 05 Mar 2025 23:44:41 GMT","redactedHeaders":"Content-Type,x-content-type-options,Strict-Transport-Security,apim-request-id","content-length":56,"body":"{\"error\":{\"code\":\"404\",\"message\": \"Resource not found\"}}"}
Exception in thread "main" com.azure.core.exception.ResourceNotFoundException: Status code 404, "{"error":{"code":"404","message": "Resource not found"}}"
```

**Workarounds**
- Downgrade API version to `2024-05-01-preview` when using inference endpoint
- Use OpenAI endpoint like `https://*.openai.azure.com/openai/deployments/gpt-4o-mini` and not provide model to `chatCompletionOptions`

**Suggestions**

Based on the [inference readme](https://github.com/Azure/azure-sdk-for-java/blob/4ddbed82b4ebe8d2dafbe2985a0e73519f9ff421/sdk/ai/azure-ai-inference/README.md) examples, it's not clear which type of the endpoint to use with/without the model:
- Please provide clarification/hints on which endpoint should be used in readme samples (inference/openai/services), e.g. in a form of `.endpoint("https://{your resource}.openai.azure.com/openai/deployments/{model}")`
- Please add separate examples with and without model name set through `ChatCompletionOptions` - it's not clear when to set/not set it

### PR DESCRIPTION
**Pull request by glharper**
# Description
Fix #44517

Please add an informative description that covers that changes made by the pull request and link all relevant issues.

If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.

# All SDK Contribution checklist:
- [ x] **The pull request does not introduce [breaking changes]**
- [ x] **CHANGELOG is updated for new features, bug fixes or other significant changes.**
- [ ] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md).**

## [General Guidelines and Best Practices](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md#developer-guide)
- [ ] Title of the pull request is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md#building-and-unit-testing)
- [ ] Pull request includes test coverage for the included changes.

### CODE REVIEW

**Review by trangevi — APPROVED** [review]

**Review by dargilco — APPROVED** [review]

File: sdk/ai/azure-ai-inference/src/main/java/com/azure/ai/inference/ModelServiceVersion.java [hunk 1]
```diff
@@ -36,10 +36,10 @@ public String getVersion() {
```
Comment (dargilco) [inline sdk/ai/azure-ai-inference/src/main/java/com/azure/ai/inference/ModelServiceVersion.java:36]: Update CHANGELOG.md
