### PR TITLE
Fixes enqueuing events with partitionId and getBufferedEventCount();

### LINKED ISSUE #43649: [BUG] When producing message with Event Hubs async client - partitionId invalid, no available ones
**Description**
In Event Hubs async client, producing a message to a partition with a valid partition Id "0" fails and the exception message lists an empty list of available partition Id's. 

***Exception***
"partitionId is not valid. Available ones:"

**To Reproduce**
- Create a buffered producer client builder.
- Use the builder to create an async client.
- Create event data.
- Use the client to enqueue the event, specifying a partition Id in the send options. 

***Code Snippet***

	EventHubBufferedProducerClientBuilder builder = new EventHubBufferedProducerClientBuilder()
			.onSendBatchSucceeded(this::onBatchSucceed)
			.onSendBatchFailed(this::onBatchFailed)
			.connectionString(connectionString, hubName);

	EventHubBufferedProducerAsyncClient producerClient = builder.buildAsyncClient();
	EventData eventData = new EventData(("data_0").getBytes()).setMessageId("id_0");
	producerClient.enqueueEvent(eventData, new SendOptions().setPartitionId("0")).subscribe(
			numberOfEvents -> {
				System.out.printf("There are %d events in the buffer.%n", numberOfEvents);
			}, error -> {
				System.err.println("Error occurred enqueueing events: " + error);
			},
			() -> {
				System.out.println("Event successfully enqueued.");
			});

**Setup**
 - OS: Windows Server 2016
 - IDE: IntelliJ IDEA 2024.1.4
 - SDK: 5.19.2
 - Library/Libraries: com.azure:azure-core:1.54.1
 - Java version: 17

### PR DESCRIPTION
**Pull request by conniey**
# Description

* Fixes issue when enqueuing events with partitionId.
* Adds tests for EventHubBufferedProducerAsyncClient.
* Fixes issue when calculating number of events currently buffered.

See #43649, #43765

Fixes #43649

# All SDK Contribution checklist:
- [x] **The pull request does not introduce [breaking changes]**
- [x] **CHANGELOG is updated for new features, bug fixes or other significant changes.**
- [x] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md).**

## [General Guidelines and Best Practices](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md#developer-guide)
- [x] Title of the pull request is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md#building-and-unit-testing)
- [x] Pull request includes test coverage for the included changes.

### CODE REVIEW

File: sdk/eventhubs/azure-messaging-eventhubs/src/main/java/com/azure/messaging/eventhubs/EventDataAggregator.java [hunk 1]
```diff
@@ -36,7 +36,11 @@
 class EventDataAggregator extends FluxOperator<EventData, EventDataBatch> {
     private static final ClientLogger LOGGER = new ClientLogger(EventDataAggregator.class);
 
-    private final AtomicReference<EventDataAggregatorMain> downstreamSubscription = new AtomicReference<>();
+    private volatile Subscription downstreamSubscription;
+    private static final AtomicReferenceFieldUpdater<EventDataAggregator, Subscription> DOWNSTREAM_SUBSCRIPTION
+        = AtomicReferenceFieldUpdater.newUpdater(EventDataAggregator.class, Subscription.class,
+            "downstreamSubscription");
```
Comment (anuchandy) [inline sdk/eventhubs/azure-messaging-eventhubs/src/main/java/com/azure/messaging/eventhubs/EventDataAggregator.java:42]: Just curious; Is there any potential issue if the type of `downstreamSubscription` is declared as `EventDataAggregatorMain`? if `source.subscribe()` auto downcast this type to `Subscription`, then we can avoid type check and casting on every call to `getNumberOfEvents()`

File: sdk/eventhubs/azure-messaging-eventhubs/src/main/java/com/azure/messaging/eventhubs/EventDataAggregator.java [hunk 2]
```diff
@@ -125,6 +143,17 @@ static class EventDataAggregatorMain implements Subscription, CoreSubscriber<Eve
                 });
         }
 
+        /**
+         * The number of events in the current batch.
+         *
+         * @return Number of events in the current batch.
+         */
+        public int getNumberOfEventsInCurrentBatch() {
+            final EventDataBatch b = currentBatch;
```
Comment (anuchandy) [inline sdk/eventhubs/azure-messaging-eventhubs/src/main/java/com/azure/messaging/eventhubs/EventDataAggregator.java:152]: given `getNumberOfEventsInCurrentBatch()` is potentially not protected by drain-loop, should we lock the access so it sync with the access in `updateOrPublishBatch`?

```java
final EventDataBatch b;
synchronized (lock) {
   b = currentBatch;
}
return b != null ? b.getCount() : 0;
```

File: sdk/eventhubs/azure-messaging-eventhubs/src/main/java/com/azure/messaging/eventhubs/EventHubBufferedPartitionProducer.java [hunk 3]
```diff
@@ -166,7 +164,12 @@ String getPartitionId() {
      * @return the number of events in the queue.
      */
     int getBufferedEventCount() {
-        return eventQueue.size();
+        // The number of events waiting to be pushed downstream to the EventDataAggregator.
+        final int value = eventSink.scanOrDefault(Scannable.Attr.BUFFERED, 0);
```
Comment (anuchandy) [inline sdk/eventhubs/azure-messaging-eventhubs/src/main/java/com/azure/messaging/eventhubs/EventHubBufferedPartitionProducer.java:168]: nice!! I didn't know about this

**Review by anuchandy — APPROVED** [review]
ty! Connie, some minor comments

File: sdk/eventhubs/azure-messaging-eventhubs/src/main/java/com/azure/messaging/eventhubs/EventDataAggregator.java (hunk 1 above)
Comment (conniey) [reply sdk/eventhubs/azure-messaging-eventhubs/src/main/java/com/azure/messaging/eventhubs/EventDataAggregator.java:42]: Mm, good idea. I only had it as Subscription because `Operators.setOnce` took `Subscription` as a parameter. I can be more specific.

File: sdk/eventhubs/azure-messaging-eventhubs/src/main/java/com/azure/messaging/eventhubs/EventDataAggregator.java [hunk 4]
```diff
@@ -68,11 +72,25 @@ public void subscribe(CoreSubscriber<? super EventDataBatch> actual) {
...
+            return 0;
+        }
 
-        source.subscribe(subscription);
+        if (!(downstream instanceof EventDataAggregatorMain)) {
+            throw LOGGER.logExceptionAsError(new IllegalStateException(
+                "Subscription is not of type EventDataAggregatorMain. Actual: " + downstream.getClass()));
+        }
+
+        return ((EventDataAggregatorMain) downstream).getNumberOfEventsInCurrentBatch();
```
Comment (anuchandy) [inline sdk/eventhubs/azure-messaging-eventhubs/src/main/java/com/azure/messaging/eventhubs/EventDataAggregator.java:93]: what I meant in the last comment was was - with `downstreamSubscription` is of type `EventDataAggregatorMain`, we can simplify this function -

```java
int getNumberOfEvents() {
  if (downstreamSubscription == null) {
    return 0;
   }
   return downstreamSubscription.getNumberOfEventsInCurrentBatch();
}

Comment (conniey) [reply sdk/eventhubs/azure-messaging-eventhubs/src/main/java/com/azure/messaging/eventhubs/EventDataAggregator.java]: I think this commit addresses that. I had missed it initially. https://github.com/Azure/azure-sdk-for-java/pull/44392/commits/ce3560adabd00c21031e8263a047e012626cc301
