### PR TITLE
Fixes to resolver handling and connection closing

### LINKED ISSUE #46804: [BUG] ByteBuf memory leaks in azure-core-http-netty when using reactor-netty-http 1.1.24+
**Describe the bug**
ByteBuf memory leaks still occur when using `azure-core-http-netty` version
`1.15.11` or higher with `reactor-netty-http` version `1.1.24+`. Even though https://github.com/Azure/azure-sdk-for-java/pull/45143 was supposed to fix this, it only prevents the IllegalStateException but the ByteBuf leaks persist.

***Exception or Stack Trace***
```
21:20:04.337 [reactor-http-nio-93] ERROR io.netty.util.ResourceLeakDetector - LEAK: ByteBuf.release() was not called before it's garbage-collected. See https://netty.io/wiki/reference-counted-objects.html for more information.
Recent access records:
#1:
    Hint: 'reactor.right.reactiveBridge' will handle the message from this point.
    io.netty.handler.codec.http.DefaultHttpContent.touch(DefaultHttpContent.java:86)
    io.netty.handler.codec.http.DefaultLastHttpContent.touch(DefaultLastHttpContent.java:123)
    io.netty.handler.codec.http.DefaultLastHttpContent.touch(DefaultLastHttpContent.java:30)
    io.netty.channel.DefaultChannelPipeline.touch(DefaultChannelPipeline.java:115)
    io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:343)
    com.azure.core.http.netty.implementation.AzureSdkHandler.channelRead(AzureSdkHandler.java:224)
    io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:354)
    ...
```

Full extended logs available [here](https://gist.githubusercontent.com/tymscar/4a33c4ce8700dc39f675cec844f535b3/raw/aa3382c2c9d129df9f60c63a78390d519f0f5602/leak.log)

**To Reproduce**
I've created a minimal reproducible example repository you can find [here](https://github.com/tymscar/azure-openai-bytebuf-leak)

The repository contains a complete Gradle project with a test that demonstrates the issue. To reproduce:

1. Clone the repository
2. Add Azure OpenAI credentials to the .env file
3. Run ./gradlew test

The test will show ByteBuf leak errors with `azure-core-http-netty` `1.15.11` and `reactor-netty-http` `1.1.24+`.

***Code Snippet***
To reproduce the issue, in the example repository, I create 100 requests, 20 concurrently at a time, and when any of them fail for any reason, I catch the exception and I do a system garbage collection.

This happens in prod randomly, but to make it fully reproducible, I call the garbage collector myself (or rather hint
to it, according to the [manual](https://docs.oracle.com/javase/8/docs/api/java/lang/System.html)).

**Expected behavior**
ByteBuf resources should be properly released when connections are returned to the pool or when errors occur, preventing memory leaks.

**Setup:**
 - OS: `Darwin fry 24.6.0 Darwin Kernel Version 24.6.0: Mon Jul 14 11:28:30 PDT 2025; root:xnu-11417. 140.69~1/RELEASE_ARM64_T6030 arm64`
 - IDE: `IntelliJ IDEA 2025.2.1 (Ultimate Edition) Build #IU-252.25557.131`, built on August 27, 2025
 - Library/Libraries:
 • `com.azure:azure-ai-openai:1.0.0-beta.16`
 • `com.azure:azure-core-http-netty:1.15.11`
 • `io.projectreactor.netty:reactor-netty-http:1.1.24+ (tested up to 1.3.0-M7)`
 - Java version: `openjdk 21.0.4 2024-07-16 LTS`
 - App Server/Environment: Standard Java application
 - Frameworks: None

**Additional context**
This was initially reported to `Reactor Netty` [here](https://github.com/reactor/reactor-netty/issues/3926). They identified that starting with `Reactor Netty` version `1.1.24`, connections are properly detached from request/response objects when returned to the pool as per [this PR](https://github.com/reactor/reactor-netty/pull/3459).

The Reactor Netty maintainer pointed to https://github.com/Azure/azure-sdk-for-java/pull/45143 as having fixed this issue. However, that PR only added a check for `channel.isRegistered()` to prevent the `IllegalStateException: channel not registered to an event loop` error. It doesn't actually fix the ByteBuf leak. The leak still occurs but without throwing the exception.

**Information Checklist**
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

### PR DESCRIPTION
**Pull request by alzimmermsft**
# Description

Fixes #46804, #46847 

Changes to how `NettyAsyncHttpClientBuilder` configures the Reactor Netty `HttpClient.resolver` to only set it if there wasn't one configured on the Reactor Netty `HttpClient`.

Changes how `NettyUtility.closeConnection` attempts to close the connection. When the `Connection` is an `instanceof ChannelOperations` it will no longer attempt to execute the closing on the `Connection.Channel.EventLoop`. Investigating into the behavior of `ChannelOperations.discard()` it appears that `FluxReceive` will perform inspections on `EventLoop`, which should be sufficient.

# All SDK Contribution checklist:
- [x] **The pull request does not introduce [breaking changes]**
- [x] **CHANGELOG is updated for new features, bug fixes or other significant changes.**
- [x] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md).**

## [General Guidelines and Best Practices](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md#developer-guide)
- [x] Title of the pull request is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md#building-and-unit-testing)
- [x] Pull request includes test coverage for the included changes.

### CODE REVIEW

**Review by XiaofeiCao — APPROVED** [review]
Thank you @alzimmermsft !

File: sdk/core/azure-core-http-netty/src/main/java/com/azure/core/http/netty/NettyAsyncHttpClientBuilder.java [hunk 1]
```diff
@@ -280,7 +283,7 @@ public com.azure.core.http.HttpClient build() {
             }
 
             AddressResolverGroup<?> resolver = nettyHttpClient.configuration().resolver();
-            if (resolver == null) {
+            if (resolver == null || setDefaultAddressResolverGroup) {
```
Comment (XiaofeiCao) [inline sdk/core/azure-core-http-netty/src/main/java/com/azure/core/http/netty/NettyAsyncHttpClientBuilder.java]: Just for my knowledge, since resolver is already set when it's `null` in line 207, here `resolver == null` should always be `false`? Or could resolver be set to `null` by other methods, e.g. `HttpClient.runOn`?

**Review by tymscar — APPROVED** [review]
I can confirm this fixes https://github.com/Azure/azure-sdk-for-java/issues/46804 for me.

File: sdk/core/azure-core-http-netty/src/main/java/com/azure/core/http/netty/NettyAsyncHttpClientBuilder.java (hunk 1 above)
Comment (alzimmermsft) [reply sdk/core/azure-core-http-netty/src/main/java/com/azure/core/http/netty/NettyAsyncHttpClientBuilder.java]: You're correct, `resolver == null` should always be null here, will remove this check.

**Review by samvaity — APPROVED** [review]

**Comment by sfc-gh-mauhlar** [comment]
Thanks for the fix - will this change be included in the azure-core-http-netty 1.16.2 release? Can you share when this fix will be released?

**Comment by alzimmermsft** [comment]
@sfc-gh-mauhlar the aim is to release this today

**Comment by tymscar** [comment]
Hey @alzimmermsft , was this included in the release?

**Comment by alzimmermsft** [comment]
@tymscar, yep! This was included in the release that happened yesterday, anything additional to report?

**Comment by tymscar** [comment]
I will try to upgrade and report back if something is wrong, but all looks good, thanks.
