### PR TITLE
Fix user agent string format and centralize creation of user agent string

### LINKED ISSUE #12420: Fix Event Hubs User Agent string format
Currently, the UA string for Event Hubs is in the format `<Product Name>/<Product Version> <Java Version>;<Platform Info>` (sample UA string - `azure-messaging-eventhubs/5.2.0-beta.1 14;Windows 10 10.0`) but it should be `[<application_id> ]azsdk-<sdk_language>-<package_name>/<package_version> <platform_info>` as per [design guidelines](https://azure.github.io/azure-sdk/general_azurecore.html#telemetry-policy).

### PR DESCRIPTION
**Pull request by srnagar**
Fixes #12420

### CODE REVIEW

File: sdk/core/azure-core-amqp/src/main/java/com/azure/core/amqp/implementation/ClientConstants.java [hunk 1]
```diff
@@ -8,11 +8,11 @@
     public static final String PLATFORM_INFO = getOSInformation();
     public static final String FRAMEWORK_INFO = getFrameworkInfo();
 
-    /**
+    /*
      * Gets the USER AGENT string as defined in:
      * $/core/azure-core/src/main/java/com/azure/core/http/policy/UserAgentPolicy.java
-     * TODO (conniey): Extract logic from UserAgentPolicy into something we can use here.
      */
+    @Deprecated
```
Comment (alzimmermsft) [inline sdk/core/azure-core-amqp/src/main/java/com/azure/core/amqp/implementation/ClientConstants.java:15]: This is `implementation` code, do we still need to use `@Deprecated` or could we remove it instead?

File: sdk/core/azure-core/src/main/java/com/azure/core/util/UserAgentUtil.java [hunk 2]
```diff
@@ -0,0 +1,118 @@
+package com.azure.core.util;
+
+/**
+ * Utility for building user agent string for Azure client libraries as specified in the
+ * <a href="https://azure.github.io/azure-sdk/general_azurecore.html#telemetry-policy">design guidelines</a>.
+ */
+public final class UserAgentUtil {
```
Comment (alzimmermsft) [inline sdk/core/azure-core/src/main/java/com/azure/core/util/UserAgentUtil.java:7]: Does this utility class resolve this issue? https://github.com/Azure/azure-sdk-for-java/issues/7549

File: sdk/core/azure-core/src/main/java/com/azure/core/util/UserAgentUtil.java [hunk 3]
```diff
@@ -0,0 +1,118 @@
...
+    }
+
+    /**
+     * Return user agent string for the given sdk name and version.
+     *
+     * @param sdkName name of the SDK.
+     * @param sdkVersion Version of the SDK.
+     * @return User agent string as specified in design guidelines.
+     */
+    public static String toUserAgentString(String sdkName, String sdkVersion) {
```
Comment (alzimmermsft) [inline sdk/core/azure-core/src/main/java/com/azure/core/util/UserAgentUtil.java:33]: Thoughts on removing the `Configuration`-less APIs? If we need to extend these in the future to also add a property such as `String features` there would be the need for many additional APIs. Also, right now these additional APIs are only an internal convenience which we could handle with internal code.

File: sdk/core/azure-core/src/main/java/com/azure/core/util/UserAgentUtil.java [hunk 4]
```diff
@@ -0,0 +1,118 @@
...
+     * Return user agent string for the given sdk name and version.
+     *
+     * @param applicationId Name of the application.
+     * @param sdkName Name of the SDK.
+     * @param sdkVersion Version of the SDK.
+     * @param configuration The configuration to use to determine if platform info should be included in the user agent
+     * string.
+     * @return User agent string as specified in design guidelines.
+     */
+    public static String toUserAgentString(String applicationId, String sdkName, String sdkVersion,
```
Comment (alzimmermsft) [inline sdk/core/azure-core/src/main/java/com/azure/core/util/UserAgentUtil.java:73]: Thoughts on only offering this API to begin? Would be trivial to add reduced parameter overloads but can't remove them once they are shipped.

File: sdk/core/azure-core/src/main/java/com/azure/core/util/UserAgentUtil.java [hunk 5]
```diff
@@ -0,0 +1,118 @@
...
+        StringBuilder userAgentBuilder = new StringBuilder();
+
+        // Only add the application ID if it is present as it is optional.
+        if (applicationId != null) {
+            applicationId = applicationId.length() > 24 ? applicationId.substring(0, 24) : applicationId;
+            userAgentBuilder.append(applicationId).append(" ");
+        }
+
+        // Add the required default User-Agent string.
+        userAgentBuilder.append(String.format(DEFAULT_USER_AGENT_FORMAT, sdkName, sdkVersion));
```
Comment (alzimmermsft) [inline sdk/core/azure-core/src/main/java/com/azure/core/util/UserAgentUtil.java:84]: Should we remove the `String.format` and handle appending into the `StringBuilder` to match the format.

File: sdk/core/azure-core-amqp/src/main/java/com/azure/core/amqp/implementation/ClientConstants.java (hunk 1 above)
Comment (conniey) [reply sdk/core/azure-core-amqp/src/main/java/com/azure/core/amqp/implementation/ClientConstants.java:15]: We shouldn't need Deprecated because it's not part of our API surface area.

File: sdk/core/azure-core/src/main/java/com/azure/core/util/UserAgentUtil.java [hunk 6]
```diff
@@ -0,0 +1,118 @@
...
+     * string.
+     * @return User agent string as specified in design guidelines.
+     */
+    public static String toUserAgentString(String applicationId, String sdkName, String sdkVersion,
+        Configuration configuration) {
+        StringBuilder userAgentBuilder = new StringBuilder();
+
+        // Only add the application ID if it is present as it is optional.
+        if (applicationId != null) {
+            applicationId = applicationId.length() > 24 ? applicationId.substring(0, 24) : applicationId;
```
Comment (conniey) [inline sdk/core/azure-core/src/main/java/com/azure/core/util/UserAgentUtil.java:79]: Can 24 be made into a private constant? So if we need to change it, we can without missing a place. Also, how did we come up with 24? :)

File: sdk/core/azure-core/src/main/java/com/azure/core/util/UserAgentUtil.java (hunk 2 above)
Comment (srnagar) [reply sdk/core/azure-core/src/main/java/com/azure/core/util/UserAgentUtil.java:7]: Yes, I had not seen this issue earlier but I think this PR will address this issue too.

File: sdk/core/azure-core/src/test/java/com/azure/core/util/UserAgentUtilTest.java [hunk 7]
```diff
@@ -0,0 +1,49 @@
...
+        assertEquals("myapp azsdk-java-azure-storage-blob/12.0.0",
+            UserAgentUtil.toUserAgentString("myapp", "azure-storage-blob", "12.0.0",
+                Configuration.getGlobalConfiguration().clone().put("AZURE_TELEMETRY_DISABLED", "true")));
+
+        // long app id should be truncated
+        assertEquals("ReallyLongApplicationIde azsdk-java-azure-storage-blob/12.0.0 " + plaform,
+            UserAgentUtil.toUserAgentString("ReallyLongApplicationIdentity", "azure-storage-blob", "12.0.0", null));
+
+        // null sdk name and version
+        assertEquals("myapp azsdk-java-null/null " + plaform,
```
Comment (JonathanGiles) [inline sdk/core/azure-core/src/test/java/com/azure/core/util/UserAgentUtilTest.java:45]: Should this print 'null/null' or just be empty strings?

Comment (srnagar) [reply sdk/core/azure-core/src/test/java/com/azure/core/util/UserAgentUtilTest.java:45]: This is the existing format and it might be useful in doing a regex match to extract fields from the user agent string.
