### PR TITLE
ConnectionString : Default scheme to SB:// in Endpoint if not specified

### LINKED ISSUE #13900: [BUG] Documentation and setting not matched
**Describe the bug**
In the service-bus documentation in the example (https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/servicebus/azure-messaging-servicebus/src/samples/java/com/azure/messaging/servicebus/ReceiveMessageAsyncSample.java)  every where it says  "fully-qualified-namespace" will look similar to "{your-namespace}.servicebus.windows.net"  if we give like this building of client is failing we need to prefix with "sb"  so correct docuementation should be "sb://{your-namespace}.servicebus.windows.net".

Failure is happening in class ServiceBusClientBuilder at 

 [return credential(properties.getEndpoint().getHost(), tokenCredential);]

getHost is failing

***Exception or Stack Trace***
Add the exception log and stack trace if available

**To Reproduce**

***Code Snippet***
Add the code snippet that causes the issue.

**Expected behavior**

**Screenshots**

**Setup (please complete the following information):**
 - IDE : [e.g. IntelliJ]
 - Version of the Library used

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

### PR DESCRIPTION
**Pull request by hemanttanwar**
ConnectionString : Default scheme to SB:// in Endpoint if user did not specified anything

fixes #13900

### CODE REVIEW

File: sdk/core/azure-core-amqp/src/main/java/com/azure/core/amqp/implementation/ConnectionStringProperties.java [hunk 1]
```diff
@@ -21,6 +29,8 @@
     private static final String ERROR_MESSAGE_FORMAT = "Could not parse 'connectionString'. Expected format: "
         + "'Endpoint={endpoint};SharedAccessKeyName={sharedAccessKeyName};"
         + "SharedAccessKey={sharedAccessKey};EntityPath={eventHubName}'. Actual: %s";
```
Comment (YijunXieMS) [inline sdk/core/azure-core-amqp/src/main/java/com/azure/core/amqp/implementation/ConnectionStringProperties.java:31]: Not the code change of this PR. But eventHubName might mislead users. It can be either an eventhub or servicebus it's it's an azure-core class.
And EntityPath is optional in the endpoint.

File: sdk/eventhubs/azure-messaging-eventhubs/CHANGELOG.md [hunk 2]
```diff
@@ -1,6 +1,7 @@
 # Release History
 
 ## 5.2.0-beta.3 (Unreleased)
+- Default scheme to 'sb://' if not scheme is set in 'Endpoint'.
```
Comment (YijunXieMS) [inline sdk/eventhubs/azure-messaging-eventhubs/CHANGELOG.md:4]: "no scheme". This has no impact to any users. So is this considered a "change log"?

File: sdk/core/azure-core-amqp/src/main/java/com/azure/core/amqp/implementation/ConnectionStringProperties.java (hunk 1 above)
Comment (hemanttanwar) [reply sdk/core/azure-core-amqp/src/main/java/com/azure/core/amqp/implementation/ConnectionStringProperties.java:31]: `entityPath` is common across both. I will use that.

File: sdk/eventhubs/azure-messaging-eventhubs/CHANGELOG.md (hunk 2 above)
Comment (hemanttanwar) [reply sdk/eventhubs/azure-messaging-eventhubs/CHANGELOG.md:4]: User do not have to change any API. But surfacing what we change, will give visibility to user when they are looking through changelog related to scheme.
