### PR TITLE
Use HttpResponseException in annotation-processor

### LINKED ISSUE #43728: Improve Error Handling : annotation-processor
For example: Currently the impl throws a generic RuntimeException for IO errors.
```java
try {
            return Response.create(response.getRequest(), response.getStatusCode(), response.getHeaders(), response.getValue().toObject(AudioTranscription.class));
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
```

Could be improved to for eg:
```java
try {
            T value = response.getValue().toObject(targetType);
            return Response.create(response.getRequest(), response.getStatusCode(), response.getHeaders(), value);
        } catch (IOException e) {
            throw LOGGER.logThrowableAsError(new IllegalStateException("Failed to deserialize response", e));
        }
```

### PR DESCRIPTION
**Pull request by samvaity**
# Description

Closes #43728 

Summary of patterns for status code + exception Mapping handling:

| Case                        | Map?         | Default?      | Example Generated Code                                      |
|-----------------------------|--------------|---------------|-------------------------------------------------------------|
| Only default error body type provided                | null         | Yes           | `defaultErrorBodyType = ...; ...handleUnexpectedResponse(..., defaultErrorBodyType, null);` |
| Only status-specific error body type provided     | Yes          | null          | `statusToExceptionTypeMap = ...; ...handleUnexpectedResponse(..., null, statusToExceptionTypeMap);` |
| Both                        | Yes          | Yes           | `statusToExceptionTypeMap = ...; defaultErrorBodyType = ...; ...handleUnexpectedResponse(..., defaultErrorBodyType, statusToExceptionTypeMap);` |
| Neither                     | null         | null          | `...handleUnexpectedResponse(..., null, null);`             |

### CODE REVIEW

File: sdk/clientcore/annotation-processor-test/src/main/java/io/clientcore/annotation/processor/test/SimpleXmlSerializableServiceImpl.java [hunk 1]
```diff
@@ -178,7 +200,25 @@ private static Object decodeNetworkResponse(BinaryData data, ObjectSerializer se
...
+    private static HttpResponseException instantiateUnexpectedException(int responseCode, Response<BinaryData> response, BinaryData data, Object decodedValue) {
+        StringBuilder exceptionMessage = new StringBuilder("Status code ").append(responseCode).append(", ");
+        String contentType = response.getHeaders().getValue(HttpHeaderName.CONTENT_TYPE);
+        if ("application/octet-stream".equalsIgnoreCase(contentType)) {
+            String contentLength = response.getHeaders().getValue(HttpHeaderName.CONTENT_LENGTH);
+            exceptionMessage.append("(").append(contentLength).append("-byte body)");
+        } else if (data == null || data.toBytes().length == 0) {
+            exceptionMessage.append("(empty body)");
+        } else {
+            exceptionMessage.append('"').append(new String(data.toBytes(), StandardCharsets.UTF_8)).append('"');
```
Comment (samvaity) [inline sdk/clientcore/annotation-processor-test/src/main/java/io/clientcore/annotation/processor/test/SimpleXmlSerializableServiceImpl.java:217]: @alzimmermsft I have been considering if we want to port this functionality over from RestProxy, especially where we check the content type and length to determine body length, as well as the exception messages. Should we just let it fall through instead? I think we will still need to check if data is null/empty to avoid decoding it, but for other cases, just let it fall through. Also, do we need custom messaging? It doesn't add much.

Comment (alzimmermsft) [reply sdk/clientcore/annotation-processor-test/src/main/java/io/clientcore/annotation/processor/test/SimpleXmlSerializableServiceImpl.java:186]: The checks around `application/octet-stream` were done as there isn't a good string representation as it's expected to just be a stream of bytes, which could be anything.

File: sdk/clientcore/annotation-processor-test/src/main/java/io/clientcore/annotation/processor/test/ParameterizedHostServiceImpl.java [hunk 2]
```diff
@@ -52,10 +58,32 @@ public byte[] getByteArray(String scheme, String host, int numberOfBytes) {
...
+                ParameterizedType returnType = null;
+                throw instantiateUnexpectedException(responseCode, networkResponse, networkResponse.getValue(), CoreUtils.decodeNetworkResponse(networkResponse.getValue(), jsonSerializer, returnType));
+            }
         }
         BinaryData responseBody = networkResponse.getValue();
         byte[] responseBodyBytes = responseBody != null ? responseBody.toBytes() : null;
         return responseBodyBytes != null ? (responseBodyBytes.length == 0 ? null : responseBodyBytes) : null;
     }
+
+    private static HttpResponseException instantiateUnexpectedException(int responseCode, Response<BinaryData> response, BinaryData data, Object decodedValue) {
```
Comment (samvaity) [inline sdk/clientcore/annotation-processor-test/src/main/java/io/clientcore/annotation/processor/test/ParameterizedHostServiceImpl.java:73]: can move to util.

File: sdk/clientcore/annotation-processor-test/src/main/java/io/clientcore/annotation/processor/test/HostEdgeCase1ServiceImpl.java [hunk 3]
```diff
@@ -53,8 +55,14 @@ public byte[] getByteArray(String url, int numberOfBytes) {
             int responseCode = networkResponse.getStatusCode();
             boolean expectedResponse = responseCode == 200;
             if (!expectedResponse) {
-                String errorMessage = networkResponse.getValue().toString();
-                throw new HttpResponseException(errorMessage, networkResponse, null);
+                BinaryData value = networkResponse.getValue();
+                if (value == null || value.toBytes().length == 0) {
+                    throw CoreUtils.instantiateUnexpectedException(responseCode, networkResponse, null, null);
+                } else {
+                    ParameterizedType returnType = null;
```
Comment (alzimmermsft) [inline sdk/clientcore/annotation-processor-test/src/main/java/io/clientcore/annotation/processor/test/HostEdgeCase1ServiceImpl.java:62]: I'm guessing this is a placeholder until we begin processing the `exceptionBodyClass` in `UnexpectedResponseExceptionDetail`?

File: sdk/clientcore/core/src/main/java/io/clientcore/core/utils/CoreUtils.java [hunk 4]
```diff
@@ -498,6 +500,33 @@ public static <T> T decodeNetworkResponse(BinaryData data, ObjectSerializer seri
...
+        String contentType = response.getHeaders().getValue(HttpHeaderName.CONTENT_TYPE);
+        if ("application/octet-stream".equalsIgnoreCase(contentType)) {
+            String contentLength = response.getHeaders().getValue(HttpHeaderName.CONTENT_LENGTH);
+            exceptionMessage.append("(").append(contentLength).append("-byte body)");
+        } else if (data == null || data.toBytes().length == 0) {
+            exceptionMessage.append("(empty body)");
+        } else {
+            exceptionMessage.append('"').append(new String(data.toBytes(), StandardCharsets.UTF_8)).append('"');
+        }
+        if (decodedValue instanceof IOException || decodedValue instanceof IllegalStateException) {
```
Comment (alzimmermsft) [inline sdk/clientcore/core/src/main/java/io/clientcore/core/utils/CoreUtils.java:524]: I don't think this logic is correct with what has changed between annotation processor and RestProxy. The decoded value should be the declared exception type, ex `ErrorValue`.

File: sdk/clientcore/core/src/main/java/io/clientcore/core/utils/CoreUtils.java [hunk 5]
```diff
@@ -498,6 +500,33 @@ public static <T> T decodeNetworkResponse(BinaryData data, ObjectSerializer seri
...
+        BinaryData data, Object decodedValue) {
+        StringBuilder exceptionMessage = new StringBuilder("Status code ").append(responseCode).append(", ");
+        String contentType = response.getHeaders().getValue(HttpHeaderName.CONTENT_TYPE);
+        if ("application/octet-stream".equalsIgnoreCase(contentType)) {
+            String contentLength = response.getHeaders().getValue(HttpHeaderName.CONTENT_LENGTH);
+            exceptionMessage.append("(").append(contentLength).append("-byte body)");
+        } else if (data == null || data.toBytes().length == 0) {
+            exceptionMessage.append("(empty body)");
+        } else {
+            exceptionMessage.append('"').append(new String(data.toBytes(), StandardCharsets.UTF_8)).append('"');
```
Comment (alzimmermsft) [inline sdk/clientcore/core/src/main/java/io/clientcore/core/utils/CoreUtils.java:522]: By the time this method is call `data` would have been consumed to create `decodedValue`. Attempting to retrieve content again here might cause unexpected exceptions such as a stream closed exception if the response was using streaming.

File: sdk/clientcore/annotation-processor-test/src/main/java/io/clientcore/annotation/processor/test/ParameterizedMultipleHostServiceImpl.java [hunk 6]
```diff
@@ -57,9 +57,16 @@ public HttpBinJSON get(String scheme, String hostPart1, String hostPart2) {
...
+            BinaryData value = networkResponse.getValue();
+            if (value == null || value.toBytes().length == 0) {
+                networkResponse.close();
+                throw CoreUtils.instantiateUnexpectedException(responseCode, networkResponse, null, null);
+            } else {
+                ParameterizedType returnType = CoreUtils.createParameterizedType(io.clientcore.annotation.processor.test.implementation.models.HttpBinJSON.class);
+                Object decoded = CoreUtils.decodeNetworkResponse(value, jsonSerializer, returnType);
+                networkResponse.close();
+                throw CoreUtils.instantiateUnexpectedException(responseCode, networkResponse, value, decoded);
+            }
```
Comment (alzimmermsft) [inline sdk/clientcore/annotation-processor-test/src/main/java/io/clientcore/annotation/processor/test/ParameterizedMultipleHostServiceImpl.java:69]: Would we be better off creating a utility method in Core to handle this logic, rather than repeating in every generated API?

File: sdk/clientcore/annotation-processor-test/src/test/java/io/clientcore/annotation/processor/test/TestInterfaceServiceClientGenerationTests.java [hunk 7]
```diff
@@ -1320,12 +1292,11 @@ public void service20GetResponseBody() {
...
     @Test
-    @Disabled("https://github.com/Azure/azure-sdk-for-java/issues/43728")
-    public void unexpectedHTTPOK() {
-        HttpResponseException e = assertThrows(HttpResponseException.class,
+    public void unexpectedHTTPOKDeserializeError() {
+        CoreException e = assertThrows(CoreException.class,
             () -> createService(TestInterfaceClientImpl.TestInterfaceClientService.class).getBytes(getRequestUri()));
 
-        assertEquals("Status code 200, (1024-byte body)", e.getMessage());
+        assertTrue(e.getMessage().startsWith("Unexpected character"));
```
Comment (alzimmermsft) [inline sdk/clientcore/annotation-processor-test/src/test/java/io/clientcore/annotation/processor/test/TestInterfaceServiceClientGenerationTests.java:1299]: This test logic to me feels off. The message here seems to be a deserialization error when handling the exception type.

File: sdk/clientcore/annotation-processor-test/src/main/java/io/clientcore/annotation/processor/test/implementation/TestInterfaceClientImpl.java [hunk 8]
```diff
@@ -297,26 +297,6 @@ HttpBinJSON putBodyAndContentLength(@HostParam("uri") String uri,
...
-
-        @HttpRequestInformation(method = HttpMethod.PUT, path = "put", expectedStatusCodes = { 201 })
-        @UnexpectedResponseExceptionDetail(statusCode = { 200 }, exceptionBodyClass = HttpBinJSON.class)
-        HttpBinJSON putWithUnexpectedResponseAndDeterminedExceptionType(@HostParam("uri") String uri,
-            @BodyParam(ContentType.APPLICATION_OCTET_STREAM) String putBody);
-
-        @HttpRequestInformation(method = HttpMethod.PUT, path = "put", expectedStatusCodes = { 201 })
-        @UnexpectedResponseExceptionDetail(statusCode = { 400 })
-        @UnexpectedResponseExceptionDetail(exceptionBodyClass = HttpBinJSON.class)
-        HttpBinJSON putWithUnexpectedResponseAndFallthroughExceptionType(@HostParam("uri") String uri,
```
Comment (alzimmermsft) [inline sdk/clientcore/annotation-processor-test/src/main/java/io/clientcore/annotation/processor/test/implementation/TestInterfaceClientImpl.java:317]: Were these APIs removed or moved? They seem to test valid cases where different response codes correlate to different exception types.

File: sdk/clientcore/annotation-processor/src/main/java/io/clientcore/annotation/processor/utils/ResponseHandler.java [hunk 9]
```diff
@@ -88,29 +86,62 @@ private static void validateResponseStatus(BlockStmt body, HttpRequestContext me
         boolean usingTryWithResources) {
         body.addStatement(StaticJavaParser.parseStatement("int responseCode = networkResponse.getStatusCode();"));
         String expectedResponseCheck;
-        if (method.getExpectedStatusCodes().size() == 1) {
-            expectedResponseCheck = "responseCode == " + method.getExpectedStatusCodes().get(0) + ";";
+        if (method.getExpectedStatusCodes() == null || method.getExpectedStatusCodes().isEmpty()) {
+            // If expectedStatusCodes is empty, treat <400 as expected
+            expectedResponseCheck = "responseCode < 400";
```
Comment (alzimmermsft) [inline sdk/clientcore/annotation-processor/src/main/java/io/clientcore/annotation/processor/utils/ResponseHandler.java:91]: Hmm, historically only 2xx was treated as expected.

File: sdk/clientcore/annotation-processor-test/src/main/java/io/clientcore/annotation/processor/test/HostEdgeCase1ServiceImpl.java (hunk 3 above)
Comment (samvaity) [reply sdk/clientcore/annotation-processor-test/src/main/java/io/clientcore/annotation/processor/test/HostEdgeCase1ServiceImpl.java:62]: Actually, let me just include it in this PR. Will do a follow up commit.

File: sdk/clientcore/annotation-processor-test/src/main/java/io/clientcore/annotation/processor/test/implementation/TestInterfaceClientImpl.java (hunk 8 above)
Comment (alzimmermsft) [reply sdk/clientcore/annotation-processor-test/src/main/java/io/clientcore/annotation/processor/test/implementation/TestInterfaceClientImpl.java:317]: I explained it poorly as type is too vague.

Correct, we don't support different exception types, such as `NotModifiedException extends HttpResponseException`.

I was more talking on how we still allow different exception body types to be configured, which isn't handled.

File: sdk/clientcore/annotation-processor-test/src/main/java/io/clientcore/annotation/processor/test/HostEdgeCase1ServiceImpl.java (hunk 3 above)
Comment (alzimmermsft) [reply sdk/clientcore/annotation-processor-test/src/main/java/io/clientcore/annotation/processor/test/HostEdgeCase1ServiceImpl.java:67]: An example explaining this further using an interface method definition that would be consumed by either the annotation-processor or SwaggerMethodParser based on ClientCore vs azure-core.
 
**ClientCore**

```java
@UnexpectedResponseExceptionDetail(statusCode = { 400 }, exceptionBodyClass = ErrorValue.class)
@UnexpectedResponseExceptionDetail(statusCode = { 403 }, exceptionBodyClass = StorageError.class)
public void someApi();
```
(Need not care about how the class references are defined)
 
In both cases, with the restriction of throwable types used within core code, `HttpResponseException` will be thrown. But, if a 400 is received the `getValue()` will be an instance of `ErrorValue` (unless the body was empty), and 403 is `StorageError`, and there should be logic for a generic deserialization fallback. In azure-core, we attempt generic JSON deserialization, if that failed we just use the network response body as a string.
 
**azure-core**
 
```java
@UnexpectedResponseExceptionDetail(statusCode = { 400 }, value = ErrorValueException.class)
@UnexpectedResponseExceptionDetail(statusCode = { 403 }, value = StorageErrorException.class)
public void someApi();
```
(In azure-core we do care about how the exception class is defined)

```java
public class ErrorValueException extends HttpResponseException {
    public ErrorValue getValue();
}
public class StorageErrorException extends HttpResponseException {
    public StorageError getValue();
}
```
(`getValue()`'s return type determines how azure-core deserializes the network response)
 
azure-core's design is more complex and harder to follow as the status codes declare the type of exception being thrown. We then use reflection magic to look for a magic method return type to determine how to deserialize the network response. If that can't be found or we have a reflection issue it falls back to Object (which is problematic if the problem was a reflection issue and the body type did exist). There's also a fallback to using `HttpResponseException` itself for undeclared status codes, and same deserialization logic here with generic JSON deserialization followed by stringifying the network response.
 
 
With ClientCore the decision was to restrict the exception type to always be `HttpResponseException` as changing the exception type isn't very useful, changing how the network response deserializes is the important part. Where azure-core messed conflated the two by using really complicated reflection magic.

File: sdk/clientcore/annotation-processor-test/src/main/java/io/clientcore/annotation/processor/test/implementation/TestInterfaceClientServiceImpl.java [hunk 10]
```diff
@@ -177,12 +182,13 @@ public Response<Foo> getFoo(String key, String label, String syncToken) {
         int responseCode = networkResponse.getStatusCode();
         boolean expectedResponse = responseCode == 200;
         if (!expectedResponse) {
-            String errorMessage = networkResponse.getValue().toString();
+            Map<Integer, java.lang.reflect.ParameterizedType> statusToExceptionTypeMap = Collections.emptyMap();
```
[the remark this answers is not in the document]
Comment (alzimmermsft) [reply sdk/clientcore/annotation-processor-test/src/main/java/io/clientcore/annotation/processor/test/implementation/TestInterfaceClientServiceImpl.java:185]: And talking on this, I feel a better design would be:

```java
Object exceptionBody;
if (statusCode == x) {
    exceptionBody = CoreUtils.decodeNetworkResponse(networkResponseValue, jsonSerializer, xErrorCodeBodyType);
} else if (statusCode == y) {
    exceptionBody = CoreUtils.decodeNetworkResponse(networkResponseValue, jsonSerializer, yErrorCodeBodyType);
} else {
    exceptionBody = CoreUtils.decodeNetworkResponse(networkResponseValue, jsonSerializer, defaultErrorBodyType);
}

// Exception creation logic.
```

And a future TODO will be handling XmlSerializer being passed to decode the error response body.

[the remark this answers is not in the document]
Comment (samvaity) [reply sdk/clientcore/annotation-processor-test/src/main/java/io/clientcore/annotation/processor/test/implementation/TestInterfaceClientServiceImpl.java:185]: hmm I think the ServiceError didnt make it to the error body type since it was not tied to a specific error code. But makes sense to have it as default in all cases other than the expected status code. Let me add that and XMl serializer too

[the remark this answers is not in the document]
Comment (samvaity) [reply sdk/clientcore/annotation-processor-test/src/main/java/io/clientcore/annotation/processor/test/implementation/TestInterfaceClientServiceImpl.java]: updated https://github.com/Azure/azure-sdk-for-java/pull/45053/commits

**Review by alzimmermsft — APPROVED** [review]
