### PR TITLE
Better logging and tracing  for stream errors

### LINKED ISSUE #37978: [BUG] Logging: errors during stream reading should have context
When logging stream reading error, we need to add some context to the error 
```log
4:16:15.743 PM	Trace	Severity level: Information, Message: {"az.sdk.message":"Using retry attempt 2 of 5.","exception":"Connection prematurely closed DURING response","tryCount":1}
```

It's not clear what response it refers to:

image

Also, the response itself has no indication of failure even through content was not received fully:
```
{"az.sdk.message":"HTTP response","contentLength":"1049960","statusCode":206,"url":"REDACTED","durationMs":11,"Content-Length":"1049960","Content-Type":"application/octet-stream","Date":"Thu, 07 Dec 2023 00:16:15 GMT","Server":"Windows-Azure-Blob/1.0,Microsoft-HTTPAPI/2.0","Accept-Ranges":"bytes","Content-Range":"bytes 3144344-4194303/8405002","Last-Modified":"Wed, 06 Dec 2023 23:59:37 GMT","x-ms-request-id":"fea68192-501e-0076-38a2-2850b9000000","x-ms-client-request-id":"7deafa55-eced-410c-8002-904bbe9f3d6b",...}
```

### PR DESCRIPTION
**Pull request by lmolkova**
Fixes #37978 and #37975

Issues came up in storage stress tests where lack of context makes it difficult or impossible to reconstruct what the Storage SDK was doing when stream reading error happens (e.g. how many bytes were actually downloaded in which try)

# Description
1. Adds context (`x-ms-client-request-id` and `traceparent`) to stream reading helpers error logs that previously had no context
2. Ends HTTP client span when underlying stream is closed

After: 

image

image

image

### CODE REVIEW

File: sdk/core/azure-core/src/main/java/com/azure/core/implementation/http/policy/InstrumentationPolicy.java [hunk 1]
```diff
@@ -78,8 +85,8 @@ public HttpResponse processSync(HttpPipelineCallContext context, HttpPipelineNex
         Context span = startSpan(context);
         try (AutoCloseable scope = tracer.makeSpanCurrent(span)) {
             HttpResponse response = next.processSync();
-            endSpan(response, span);
-            return response;
+            updateSpan(response, span);
+            return new TraceableResponse(response, span);
```
Comment (lmolkova) [inline sdk/core/azure-core/src/main/java/com/azure/core/implementation/http/policy/InstrumentationPolicy.java:89]: @alzimmermsft what would you think about 
1. `boolean HttpResponse.isBuffered()` method? It'd allow to optimize stuff here and in HttpResponseLogger
2. something like `HttpResponse.addCloseHook(BiSupplier<HttpResponse, Throwable> hook)` - this would help us avoid wrapping streams

Not strictly related, but I think `BinaryData` should also have `isBuffered` or `isBufferable` and `close` to optimize/allow more control to close streams under (e.g. when I don't want to  read full content)

Comment (alzimmermsft) [reply sdk/core/azure-core/src/main/java/com/azure/core/implementation/http/policy/InstrumentationPolicy.java:89]: I have no issue with these additions. Though I think it'd be good to have a larger discussion around the entire HTTP request-response lifecycle, hooks into it, and metadata associated with it. There are a lot of areas we could improve through these enhancements and it'd be good to get them all in one place so we can be consistent with what we're doing.

Comment (lmolkova) [reply sdk/core/azure-core/src/main/java/com/azure/core/implementation/http/policy/InstrumentationPolicy.java:89]: created https://github.com/Azure/azure-sdk-for-java/issues/38228 to track it

File: sdk/core/azure-core/src/main/java/com/azure/core/http/policy/HttpLoggingPolicy.java [hunk 2]
```diff
@@ -151,19 +154,42 @@ public HttpResponse processSync(HttpPipelineCallContext context, HttpPipelineNex
         final long startNs = System.nanoTime();
 
         requestLogger.logRequestSync(logger, getRequestLoggingOptions(context));
+        HttpResponse response = null;
         try {
-            HttpResponse response = next.processSync();
+            response = next.processSync();
```
Comment (alzimmermsft) [inline sdk/core/azure-core/src/main/java/com/azure/core/http/policy/HttpLoggingPolicy.java:159]: Any reason the instantiation was split into separate lines?

**Review by alzimmermsft — APPROVED** [review]

File: sdk/core/azure-core/src/main/java/com/azure/core/util/io/IOUtils.java [hunk 3]
```diff
@@ -210,16 +214,19 @@ private static Mono<Void> transferStreamResponseToAsynchronousByteChannelHelper(
...
-                LOGGER.atInfo().addKeyValue(LoggingKeys.TRY_COUNT_KEY, retryCount)
-                    .log(() -> String.format("Using retry attempt %d of %d.", updatedRetryCount, maxRetries),
-                        exception);
-                return onErrorResume.apply(exception, targetChannel.getBytesWritten())
+                long bytesWritten = targetChannel.getBytesWritten();
+                createBasicLoggingContext(LogLevel.INFORMATIONAL, response)
+                    .addKeyValue(LoggingKeys.TRY_COUNT_KEY, retryCount)
+                    .addKeyValue("maxRetries", maxRetries)
+                    .addKeyValue("bytesWritten", bytesWritten)
+                    .log("Attempt failed. Scheduling new try.", exception);
```
Comment (trask) [inline sdk/core/azure-core/src/main/java/com/azure/core/util/io/IOUtils.java:228]:
```suggestion
                    .log("Attempt failed. Scheduling retry.", exception);
```

**Review by trask — COMMENTED** [review]
is this related to https://github.com/open-telemetry/semantic-conventions/blob/main/docs/http/http-spans.md#http-client-span-duration?

> If there is any possibility for application code to not fully read the HTTP response (and for the HTTP client library to then have to clean up the HTTP response asynchronously), the HTTP client span SHOULD NOT be ended in this cleanup phase, and instead SHOULD end at some point after the HTTP response headers are fully read (or fail to be read).

**Comment by lmolkova** [comment]
> is this related to https://github.com/open-telemetry/semantic-conventions/blob/main/docs/http/http-spans.md#http-client-span-duration?

yes, but the reason for this change is to fix something we hit in the stress tests - telemetry shows that everything is fine when connection resets in the middle of the response stream
