### PR TITLE
[core-amqp] Removing connection string from leaking connection information being logged

### LINKED ISSUE #19249: [BUG] ESB Connection Builder Exception leaks credentials
**Describe the bug**
In case the connection string is of invalid format, e.g. 
`Endpoint=sb://company.servicebus.windows.net/;SharedAccessKey=SharedAccessKeyName=MySharedAccessKey;SharedAccessKey=1234` then the error message is
```
Could not parse 'connectionString'. Expected format: Endpoint={endpoint};
SharedAccessKeyName={sharedAccessKeyName};
SharedAccessKey={sharedAccessKey};EntityPath={entityPath} or Endpoint={endpoint};
SharedAccessSignature=SharedAccessSignature {sharedAccessSignature};
EntityPath={entityPath}.
Actual: Endpoint=sb://company.servicebus.windows.net/;
SharedAccessKey=SharedAccessKeyName=MySharedAccessKey;
SharedAccessKey=1234
```

Hence the SharedAccessKey ends up in user error messages, in log files etc. Not good.

**Expected behavior**
The error message itself is very helpful, the SharedAccessKey should be masked out though.

### PR DESCRIPTION
**Pull request by hemanttanwar**
`ConnectionStringProperties` has logic to validate `connectionString`. When certain mandatory information is not present, it will leak the whole connection string as part of error logging which has connection information.  

Thus removing `connectionString` from error logging. 

The error message is good enough to help user what could be the problem as it specifies what format the connectionString should be in. 

Fixes #19249

### CODE REVIEW

File: sdk/core/azure-core-amqp/src/main/java/com/azure/core/amqp/implementation/ConnectionStringProperties.java [hunk 1]
```diff
@@ -106,7 +104,7 @@ public ConnectionStringProperties(String connectionString) {
         if (endpoint == null
             || (includesSharedKey && includesSharedAccessSignature) // includes both SAS and key or value
             || (!hasSharedKeyAndValue && !includesSharedAccessSignature)) { // invalid key, value and SAS
-            throw new IllegalArgumentException(String.format(Locale.US, ERROR_MESSAGE_FORMAT, connectionString));
+            throw new IllegalArgumentException(ERROR_MESSAGE_FORMAT);
```
Comment (srnagar) [inline sdk/core/azure-core-amqp/src/main/java/com/azure/core/amqp/implementation/ConnectionStringProperties.java:107]: use `logger.logExceptionAsError()`

File: sdk/core/azure-core-amqp/src/main/java/com/azure/core/amqp/implementation/ConnectionStringProperties.java [hunk 2]
```diff
@@ -161,14 +159,15 @@ public String getSharedAccessSignature() {
...
-            throw logger.logExceptionAsError(new IllegalArgumentException(String.format(Locale.US,
-                ERROR_MESSAGE_ENDPOINT_FORMAT, connectionString)));
-
+            throw logger.logExceptionAsError(new IllegalArgumentException(
+                "'Endpoint' must be provided in 'connectionString'."));
         }
+
+        String updatedEndpoint = endpoint.trim();
+
         final String endpointLowerCase = endpoint.toLowerCase(Locale.getDefault());
```
Comment (srnagar) [inline sdk/core/azure-core-amqp/src/main/java/com/azure/core/amqp/implementation/ConnectionStringProperties.java:171]: This should use `updatedEndpoint` instead.

**Review by srnagar — APPROVED** [review]

**Review by alzimmermsft — APPROVED** [review]

File: sdk/core/azure-core-amqp/src/main/java/com/azure/core/amqp/implementation/ConnectionStringProperties.java [hunk 3]
```diff
@@ -33,9 +33,7 @@
     private static final String CONNECTION_STRING_WITH_SAS = "Endpoint={endpoint};SharedAccessSignature="
         + "SharedAccessSignature {sharedAccessSignature};EntityPath={entityPath}";
     private static final String ERROR_MESSAGE_FORMAT = "Could not parse 'connectionString'. Expected format: "
-        + CONNECTION_STRING_WITH_ACCESS_KEY + " or " + CONNECTION_STRING_WITH_SAS + ". Actual: %s";
-    private static final String ERROR_MESSAGE_ENDPOINT_FORMAT = "'Endpoint' must be provided in 'connectionString'."
-        + " Actual: %s";
+        + CONNECTION_STRING_WITH_ACCESS_KEY + " or " + CONNECTION_STRING_WITH_SAS + ".";
```
Comment (conniey) [inline sdk/core/azure-core-amqp/src/main/java/com/azure/core/amqp/implementation/ConnectionStringProperties.java:36]: It's easier to read using string.format.

File: sdk/core/azure-core-amqp/src/main/java/com/azure/core/amqp/implementation/ConnectionStringProperties.java [hunk 4]
```diff
@@ -161,15 +159,16 @@ public String getSharedAccessSignature() {
...
         if (CoreUtils.isNullOrEmpty(endpoint)) {
-            throw logger.logExceptionAsError(new IllegalArgumentException(String.format(Locale.US,
-                ERROR_MESSAGE_ENDPOINT_FORMAT, connectionString)));
-
+            throw logger.logExceptionAsError(new IllegalArgumentException(
+                "'Endpoint' must be provided in 'connectionString'."));
         }
-        final String endpointLowerCase = endpoint.toLowerCase(Locale.getDefault());
+
+        String updatedEndpoint = endpoint.trim();
```
Comment (conniey) [inline sdk/core/azure-core-amqp/src/main/java/com/azure/core/amqp/implementation/ConnectionStringProperties.java:169]: Is there a reason not to chain this?

Also, not to use `Locale.getDefault()`. These endpoints are of invariant culture. It's possible that the user's machine has another locale.
