### PR TITLE
Fix an issue preventing population of the "tags" and "managed" properties in KeyVaultKey and KeyProperties

### LINKED ISSUE #14513: [BUG] KeyVault KeyProperties.getTags returns null
**Describe the bug**

Calling `getTags()` on a `KeyProperties` object sometimes returns `null` when it should return the tags.

**To Reproduce**

1. Create a KeyVault key
2. Add tags to it (e.g. via the web interface)
3. Get a `CryptographyClient` for the key
4. Call `cryptographyClient.getKey().getProperties().getTags()` to get the tags. Result is null.
5. Get a `KeyClient` for the vault and call `listPropertiesOfKeys()`
6. Loop through to get the properties for the desired key and call `getTags()`. The tags are there.

***Code Snippet***

Assuming `VAULT_URL`, `KEY_NAME`, `KEY_VERSION` and `CREDENTIAL` are set and valid:

```
    System.out.println("First via CryptographyClient.getKey():");
    String keyId = VAULT_URL + "/keys/" + KEY_NAME + "/" + KEY_VERSION;
    CryptographyClient cryptographyClient = new CryptographyClientBuilder()
        .credential(CREDENTIAL)
        .keyIdentifier(keyId)
        .buildClient();
    Map<String, String> tags = cryptographyClient.getKey().getProperties().getTags();
    if (tags != null) {
      for (Map.Entry<String, String> entry : tags.entrySet()) {
        String key = entry.getKey();
        String value = entry.getValue();
        System.out.printf("%s -> %s\n", key, value);
      }
    } else {
      System.out.println("tags is null");
    }

    System.out.println("And now via KeyClient.listPropertiesOfKeys()");
    KeyClient keyClient = new KeyClientBuilder()
        .vaultUrl(VAULT_URL)
        .credential(CREDENTIAL)
        .buildClient();
    for (KeyProperties keyProperties : keyClient.listPropertiesOfKeys()) {
      if (keyProperties.getName().equals(KEY_NAME)) {
        tags = keyProperties.getTags();
        if (tags != null) {
          for (Map.Entry<String, String> entry : tags.entrySet()) {
            String key = entry.getKey();
            String value = entry.getValue();
            System.out.printf("%s -> %s\n", key, value);
          }
        } else {
          System.out.println("tags is null");
        }
      }
    }
```

**Expected behavior**

Both parts of the code snippet above should print

```
some-tag-name -> some-tag-value
another-tag-name -> another-tag-value
```

but the first one instead prints `tags is null`.

**Screenshots**

Screenshot from 2020-08-27 16-31-32

**Setup:**
 - OS: Debian GNU/Linux bullseye/sid
 - Kernel: Linux 5.7.0-2-amd64
 - Architecture: x86-64
 - IDE : VSCode but running from command line via Gradle
 - Version of the library used: `com.azure:azure-security-keyvault-keys:4.2.0`

**Additional context**

- Possibly related to #10899?
- Possibly a bug in (or incorrect use of) `lazyValueSelection()`. See https://github.com/Azure/azure-sdk-for-java/blob/4becfc24f9a0b94af038c2ab9ec8f201a88a0ea6/sdk/keyvault/azure-security-keyvault-keys/src/main/java/com/azure/security/keyvault/keys/models/KeyProperties.java#L283

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

### PR DESCRIPTION
**Pull request by vcolin7**
- Fixed an issue that prevented the `tags` and `managed` members of `KeyProperties` from getting populated when retrieving a single key using `KeyClient`, `KeyAsyncClient`, `CryptographyClient` and `CryptographyAsyncClient`.
- Removed unnecessary setter calls in `KeyProperties.unpackAttributes()` for values that are not a part of the `attributes` property in `KeyVaultKey` and `KeyProperties`. 
- Removed `KeyVaultKey.unpackKid()` since `kid` is not a top level property of the JSON returned by the Key Vault service and thus, is only populated in `KeyProperties` when calling `KeyVaultKey.unpackAttributes()`.

References:
- Service Version 7.0
    - [KeyBundle](https://github.com/Azure/azure-rest-api-specs/blob/1b04f5fce19cd330dcc0eec11a98e499c0cda50d/specification/keyvault/data-plane/Microsoft.KeyVault/stable/7.0/keyvault.json#L3927)
    - [KetAttributes](https://github.com/Azure/azure-rest-api-specs/blob/1b04f5fce19cd330dcc0eec11a98e499c0cda50d/specification/keyvault/data-plane/Microsoft.KeyVault/stable/7.0/keyvault.json#L3868)
    - [Attributes](https://github.com/Azure/azure-rest-api-specs/blob/1b04f5fce19cd330dcc0eec11a98e499c0cda50d/specification/keyvault/data-plane/Microsoft.KeyVault/stable/7.0/keyvault.json#L3686)
- Service Version 7.1
    - [KeyBundle](https://github.com/Azure/azure-rest-api-specs/blob/1b04f5fce19cd330dcc0eec11a98e499c0cda50d/specification/keyvault/data-plane/Microsoft.KeyVault/stable/7.1/keys.json#L1192)
    - [KetAttributes](https://github.com/Azure/azure-rest-api-specs/blob/1b04f5fce19cd330dcc0eec11a98e499c0cda50d/specification/keyvault/data-plane/Microsoft.KeyVault/stable/7.1/keys.json#L1127)
    - [Attributes](https://github.com/Azure/azure-rest-api-specs/blob/1b04f5fce19cd330dcc0eec11a98e499c0cda50d/specification/keyvault/data-plane/Microsoft.KeyVault/stable/7.1/common.json#L10)    

Fixes #14513.

### CODE REVIEW

File: sdk/keyvault/azure-security-keyvault-keys/src/main/java/com/azure/security/keyvault/keys/models/KeyProperties.java [hunk 1]
```diff
@@ -266,10 +267,7 @@ void unpackAttributes(Map<String, Object> attributes) {
         this.createdOn = epochToOffsetDateTime(attributes.get("created"));
         this.updatedOn = epochToOffsetDateTime(attributes.get("updated"));
         this.recoveryLevel = (String) attributes.get("recoveryLevel");
-        this.tags = (Map<String, String>) lazyValueSelection(attributes.get("tags"), this.tags);
```
Comment (g2vinay) [inline sdk/keyvault/azure-security-keyvault-keys/src/main/java/com/azure/security/keyvault/keys/models/KeyProperties.java:269]: Validate that these are not needed in V7.0 SDK.

File: sdk/keyvault/azure-security-keyvault-keys/src/main/java/com/azure/security/keyvault/keys/models/KeyVaultKey.java [hunk 2]
```diff
@@ -106,14 +106,19 @@ private void unpackKeyMaterial(Map<String, Object> key) {
         this.key = properties.createKeyMaterialFromJson(key);
     }
 
-    @JsonProperty(value = "kid")
-    private void unpackKid(String kid) {
-        properties.unpackId(kid);
```
Comment (g2vinay) [inline sdk/keyvault/azure-security-keyvault-keys/src/main/java/com/azure/security/keyvault/keys/models/KeyVaultKey.java:111]: Validate that kid is not sent in a different location in V7.0 SDK .

**Review by g2vinay — COMMENTED** [review]
Check if these changes are applicable to Secrets and Certificates SDKs too.

File: sdk/keyvault/azure-security-keyvault-keys/src/main/java/com/azure/security/keyvault/keys/models/KeyProperties.java (hunk 1 above)
Comment (vcolin7) [reply sdk/keyvault/azure-security-keyvault-keys/src/main/java/com/azure/security/keyvault/keys/models/KeyProperties.java:269]: `tags` are only a part of the `KeyBundle` object definition (mapped to the `KeyVaultKey` model) in the Swagger for service version 7.0, they are not included in `KeyAttributes` (mapped to the `KeyProperties` model).

File: sdk/keyvault/azure-security-keyvault-keys/src/main/java/com/azure/security/keyvault/keys/models/KeyVaultKey.java (hunk 2 above)
Comment (vcolin7) [reply sdk/keyvault/azure-security-keyvault-keys/src/main/java/com/azure/security/keyvault/keys/models/KeyVaultKey.java:111]: `kid` is only a part of the `JsonWebKey` object definition in the Swagger for service version 7.0, which is part of `KeyBundle` (mapped to the `KeyVaultKey` model) but not a direct member of it. It's deserialized in by `unpackKid()` in `unpackKeyMaterial()`.

**Comment by vcolin7** [comment]
The Build Analyze step succeeded on [attempt 2](https://dev.azure.com/azure-sdk/public/_build/results?buildId=544366&view=logs&jobId=b70e5e73-bbb6-5567-0939-8415943fadb9&j=36df4387-3551-57fa-098c-b43a23930261) but it seems it was not picked up by GitHub. Overriding Check Enforcer.

**Comment by g2vinay** [comment]
Check if these changes are applicable to Secrets and Certificates libraries too.

**Comment by vcolin7** [comment]
> Check if these changes are applicable to Secrets and Certificates libraries too.

@g2vinay Do you mean to check if the models are compliant with the Swaggers specifications for both service versions `7.0` and `7.1`?

**Comment by g2vinay** [comment]
> > Check if these changes are applicable to Secrets and Certificates libraries too.
> 
> @g2vinay Do you mean to check if the models are compliant with the Swaggers specifications for both service versions `7.0` and `7.1`?

yes, if we need to add these updates on the models for Secret and Certificiate SDKs too or not.

**Review by g2vinay — APPROVED** [review]
