### PR TITLE
[Tables] Adjust catch level to exception

### LINKED ISSUE #44005: [BUG] TableUtils ClassCastException when Throwable isn't an Exception type
**Describe the bug**

Exception mapping in `TableUtils` makes the assumption that the caught `Throwable` is some form of `Exception`. If that doesn't hold true and the underlying issue is an `Error` type it'll result in a crash when attempting to cast the `Throwable` to `RuntimeException`.

**To Reproduce**

Add tests where the `Throwable` caught is an `Error` type or the `Throwable` caught isn't a `RuntimeException` type defined by `azure-data-tables` and the cause is an `Error`.

***Code Snippet***

`TableUtils.callWithOptionalTimeout(() -> throw new NoClassDefFoundError(), Duration.ZERO, clientLogger)`
`TableUtils.callWithOptionalTimeout(() -> throw new IllgealStateException(new NoClassDefFoundError()), Duration.ZERO, clientLogger)`

**Expected behavior**

In both those cases the `Error` type shouldn't be cast or wrapped by a `RuntimeException` and should be thrown directly.

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

### PR DESCRIPTION
**Pull request by jairmyree**
Closes #44005 

This PR fixes the aformentioned issue by not attempt to catch `Throwable`, opting for `Exception` instead.

### CODE REVIEW

**Review by alzimmermsft — APPROVED** [review]

File: sdk/tables/azure-data-tables/src/test/java/com/azure/data/tables/TableClientTest.java [hunk 1]
```diff
@@ -1338,4 +1334,13 @@ public void allowDeleteEntityWithEmptyPrimaryKey() {
         tableClient.createEntity(entity);
         tableClient.deleteEntity(entity);
     }
+
+    @Test
+    void NonRuntimeExceptionsDontGetCasted() {
```
Comment (alzimmermsft) [inline sdk/tables/azure-data-tables/src/test/java/com/azure/data/tables/TableClientTest.java:1339]: Might want to add this into a test class that doesn't extend `TestProxyTestBase`
