### PR TITLE
Close response body in bearer policy

### LINKED ISSUE #39981: [BUG] Revisit bearer policy response body consumption and retries
**Describe the bug**
It seems  `BearerTokenAuthenticationPolicy` does not ~~always~~ ever consume 401 response bodies potentially leading to suboptimal usage of connections in the pool.

The assumption on how it should behave

- bearer policy starts
  - retry policy starts
    - http client starts
    - http client returns 401
  - retry policy ignores it
- bearer policy sees 401
   - buffers body no matter what (this returns connection to the connection pool right away)
   - authenticates the request, updates header
   - things go on
     - retries (not 401) are handled by retry
     - 401s are handled by bearer. There should be another guard for number of 401s?
- finally we see something except 401 and bearer propagates it back

The corner case if service returns 401 no matter what. Regardless of retry and bearer policy order, there is a need to make sure we limit number of 401s?
 
If 401 needs to be propagated back, we still have the buffered body which we can return

### PR DESCRIPTION
**Pull request by lmolkova**
Fix #39981

- Close response body in `BearerTokenAuthenticationPolicy.processSync`  for 401 response. 
- Test that response is closed in in common policies when the response is not propagated back.

### CODE REVIEW

File: sdk/core/azure-core/src/main/java/com/azure/core/http/policy/BearerTokenAuthenticationPolicy.java [hunk 1]
```diff
@@ -123,16 +123,11 @@ public Mono<HttpResponse> process(HttpPipelineCallContext context, HttpPipelineN
...
-                return authorizeRequestOnChallenge(context, httpResponse).flatMap(retry -> {
-                    if (retry) {
-                        // Both Netty and OkHttp expect the requestBody to be closed after the response has been read.
-                        // Failure to do so results in memory leak.
-                        // In case of StreamResponse (or other scenarios where we do not eagerly read the response)
-                        // the response body may not be consumed.
-                        // This can cause potential leaks in the scenarios like above, where the policy
-                        // may intercept the response and it may never be read.
-                        // Forcing the read here - so that the memory can be released.
-                        return httpResponse.getBody().ignoreElements().then(nextPolicy.process());
```
Comment (lmolkova) [inline sdk/core/azure-core/src/main/java/com/azure/core/http/policy/BearerTokenAuthenticationPolicy.java:135]: closing is better than reading to the end in edge cases:
- we don't need to waste time on reading (unlikely) big response
- if there is a transient issue during stream reading, we don't need to handle/retry it.

**Review by alzimmermsft — APPROVED** [review]
