### PR TITLE
BlobOutputStream#close handling Close Exception

### LINKED ISSUE #24782: BlobOutputStream#close should be idempotent
References:

https://github.com/Azure/azure-sdk-for-java/blob/3ace711dcfc67d45deb8a36f30ded342d9d68045/sdk/storage/azure-storage-blob/src/main/java/com/azure/storage/blob/specialized/BlobOutputStream.java#L108-L119

https://github.com/Azure/azure-sdk-for-java/blob/26e7c0c89d7efb17499272bfc41e458225b7cf17/sdk/storage/azure-storage-common/src/main/java/com/azure/storage/common/StorageInputStream.java#L139-L147

The `java.lang.Closeable#close` [contract](https://docs.oracle.com/javase/8/docs/api/java/lang/AutoCloseable.html) does not **mandate** idempotency of the method.

However, in the Java ecosystem it is normal that a `Stream` object may be closed multiple times. Instead, `BlobOutputStream`, unlike `BlobInputStream`, can be closed only once. It is also recommended by Javadoc

> Note that unlike the close method of Closeable, this close method is not required to be idempotent. In other words, calling this close method more than once may have some visible side effect, unlike Closeable.close which is required to have no effect if called more than once. However, implementers of this interface are strongly encouraged to make their close methods idempotent.

I would like to raise the inconsistency between the two symmetric classes.

Also, the feature renders unusable the following code block that stacks output streams one above another for `FilterOutputStream` processing

```java
        try (BlobOutputStream blob = blobClient.getBlockBlobClient().getBlobOutputStream();
             BufferedOutputStream buffer = new BufferedOutputStream(blob);
             DigestOutputStream digest = new DigestOutputStream(buffer, getChecksumDigest());
             InputStream is = payload.getInputStream();
        ) {
            byteSize = IOUtils.copyLarge(is, digest);
            checksum = encodeHexString(digest.getMessageDigest().digest());
        }
```

The above code works if `blob` is type `FileOutputStream`, as the order is

- Open blob
- Open buffer
- Open digest
- Open is
- Close is
- Close digest
  - Cascade close buffer
    - Cascade close blob
- Close buffer
  - Cascade close blob

It is very helpful to try-with-multiple resources as it renders code more readable.

To ensure that every stream gets closed (otherwise evil could happen), the code fragment would be rendered to

```java
        try {
            BufferedOutputStream buffer = new BufferedOutputStream(blob);
            try {
                try (DigestOutputStream digest = new DigestOutputStream(buffer, getChecksumDigest());
                     InputStream is = payload.getInputStream();
                ) {
                    byteSize = IOUtils.copyLarge(is, digest);
                    checksum = encodeHexString(digest.getMessageDigest().digest());
                }
            } finally {
                IOUtils.closeQuietly(buffer);
            }
        } finally {
            IOUtils.closeQuietly(blob);
        }
```

(Author's edit) I have discovered that Apache Commons's IOUtils does not work because the exception thrown here is a `RuntimeException` than an `IOException`, so I had to refactor this code in a more complicated way with try-catch-es.

Suggesting to make `BlobOutputStream#close` method idempotent to adhere to the `FilterOutputStream` contract and stack streams.

Thank you for your time.

### PR DESCRIPTION
**Pull request by ibrahimrabab**
resolves #24782

### CODE REVIEW

File: sdk/storage/azure-storage-blob/src/main/java/com/azure/storage/blob/specialized/BlobOutputStream.java [hunk 1]
```diff
@@ -114,6 +114,9 @@ static BlobOutputStream pageBlobOutputStream(final PageBlobAsyncClient client, f
     @Override
     public synchronized void close() throws IOException {
         try {
+            if (this.lastError != null && this.lastError.getMessage().equals(Constants.STREAM_CLOSED)) {
+                return;
+            }
```
Comment (alzimmermsft) [inline sdk/storage/azure-storage-blob/src/main/java/com/azure/storage/blob/specialized/BlobOutputStream.java:119]: Would this be better handled as an AtomicBoolean check?

```java
// Check if the stream has already been closed and mark it as closed if it hasn't.
if (!alreadyClosed.compareAndSet(false, true)) {
  // Already been closed, return early.
  return;
}
```

There may need additional checking if the last error should be rethrown instead of just a return.

File: sdk/storage/azure-storage-blob/src/test/java/com/azure/storage/blob/BlobOutputStreamTest.groovy [hunk 2]
```diff
@@ -33,6 +34,27 @@ class BlobOutputStreamTest extends APISpec {
...
+        def data = getRandomByteArray(10 * Constants.MB)
+        def blockBlobClient = cc.getBlobClient(generateBlobName()).getBlockBlobClient()
+
+        when:
+        // set option for allowing multiple close() calls
+        def outputStream = blockBlobClient.getBlobOutputStream(new BlockBlobOutputStreamOptions(true))
+
+        outputStream.write(data)
+        outputStream.close()
+        // call again, no exceptions should be thrown
```
Comment (rickle-msft) [inline sdk/storage/azure-storage-blob/src/test/java/com/azure/storage/blob/BlobOutputStreamTest.groovy:49]: I think it would be good to check the etag of the blob we're writing to and assert it doesn't change. This way we know that we're not re-committing the blob or anything. Redundant closes are just a no op in that case.

**Review by rickle-msft — APPROVED** [review]

File: sdk/storage/azure-storage-blob/src/main/java/com/azure/storage/blob/specialized/BlobOutputStream.java [hunk 3]
```diff
@@ -35,8 +36,24 @@
  */
 public abstract class BlobOutputStream extends StorageOutputStream {
 
+    private AtomicBoolean isAlreadyClosed;
+    private final boolean isMultipleClosedAllowed;
```
Comment (kasobol-msft) [inline sdk/storage/azure-storage-blob/src/main/java/com/azure/storage/blob/specialized/BlobOutputStream.java:40]: I'm not sure we have to do this .
The Closeable contract says `Closes this stream and releases any system resources associated with it. If the stream is already closed then invoking this method has no effect.`

See https://docs.oracle.com/javase/8/docs/api/java/io/Closeable.html

File: sdk/storage/azure-storage-blob/src/main/java/com/azure/storage/blob/specialized/BlobOutputStream.java [hunk 4]
```diff
@@ -135,6 +157,7 @@ public synchronized void close() throws IOException {
         } finally {
             // if close() is called again, an exception will be thrown
             this.lastError = new IOException(Constants.STREAM_CLOSED);
+            isAlreadyClosed.set(true);
```
Comment (srnagar) [inline sdk/storage/azure-storage-blob/src/main/java/com/azure/storage/blob/specialized/BlobOutputStream.java:160]: This isn't required anymore as you are using `compareAndSet` that'll set this boolean to `true`. Also, since the method itself is synchronized and the `isAlreadyClose` is read/updated only inside this method, `AtomicBoolean` is not required. A regular `volatile boolean` is sufficient.

File: sdk/storage/azure-storage-blob/src/main/java/com/azure/storage/blob/specialized/BlobOutputStream.java (hunk 3 above)
Comment (srnagar) [reply sdk/storage/azure-storage-blob/src/main/java/com/azure/storage/blob/specialized/BlobOutputStream.java:40]: Agree. We don't need to have this fallback behavior. We can remove `isMultipleCloseAllowed` option.

File: sdk/storage/azure-storage-blob/src/main/java/com/azure/storage/blob/specialized/BlobOutputStream.java [hunk 5]
```diff
@@ -114,6 +132,10 @@ static BlobOutputStream pageBlobOutputStream(final PageBlobAsyncClient client, f
     @Override
     public synchronized void close() throws IOException {
         try {
+            // check if multiple closes are expected to be made and stream is already closed
+            if (isMultipleClosedAllowed && !isAlreadyClosed.compareAndSet(false, true)) {
+                return;
+            }
```
Comment (srnagar) [inline sdk/storage/azure-storage-blob/src/main/java/com/azure/storage/blob/specialized/BlobOutputStream.java:138]: If the first `close()` attempt tried to `commit` and failed with a retriable exception (like timeout), the previous behavior allowed the user to call `close()` again to attempt to commit. Since that is no longer possible, we should ensure the exception message is updated on line no. 150 to specify that the user will have to `flush` and `commit` manually to create the blob. 

The other option is to allow closing again only if the first `close()`  did not succeed but this will require maintaining additional state and knowing which exception is retriable. If the service throws an exception because the blob was already created and cannot be overwritten, then we know the first attempt succeeded on the service side and we just ignore the "resource already exists exception" and consider `close()` as successful. All subsequent `close()` calls will return immediately.

Comment (kasobol-msft) [reply sdk/storage/azure-storage-blob/src/main/java/com/azure/storage/blob/specialized/BlobOutputStream.java:138]: The retry policy should be already taking care of retriable exceptions.
The "resource already exists" is kind of grey area, it might happen if concurrent transaction finished first.

Perhaps we should just.
```
if (alreadySuccessfullyClosed) {
  // do nothing
} else {
  // existing logic.
}
```

Comment (srnagar) [reply sdk/storage/azure-storage-blob/src/main/java/com/azure/storage/blob/specialized/BlobOutputStream.java:127]: > The "resource already exists" is kind of grey area, it might also happen if concurrent transaction finished first.

Either way, the `commit` didn't complete successfully and we get the exception to indicate that the blob already exists. So, we don't attempt to commit again and consider it to be "alreadySuccessfullyClosed" when close is called again. Basically, do what you are suggesting above with the additional consideration that "blob already exists" (whether it's from this commit or from another concurrent transaction) will be treated as a success.

File: sdk/storage/azure-storage-blob/src/main/java/com/azure/storage/blob/specialized/BlobOutputStream.java [hunk 6]
```diff
@@ -133,8 +143,8 @@ public synchronized void close() throws IOException {
                 throw lastError;
             }
         } finally {
-            // if close() is called again, an exception will be thrown
             this.lastError = new IOException(Constants.STREAM_CLOSED);
+            isClosed = true;
```
Comment (srnagar) [inline sdk/storage/azure-storage-blob/src/main/java/com/azure/storage/blob/specialized/BlobOutputStream.java:147]: Based on the above discussion, we should set this to true only when `lastError` is `null` or falls under the category of "won't retry".

File: sdk/storage/azure-storage-blob/CHANGELOG.md [hunk 7]
```diff
@@ -3,12 +3,8 @@
 ## 12.18.0-beta.2 (Unreleased)
 
 ### Features Added
-
-### Breaking Changes
-
-### Bugs Fixed
-
-### Other Changes
+- Introducing a new field isMultipleClosedAllowed for BlobOutputStream and BlockBlobOutputStream, which allows users to
```
Comment (srnagar) [inline sdk/storage/azure-storage-blob/CHANGELOG.md:6]: We don't have this `isMultipleClosedAllowed` boolean anymore. So, the changelog should be updated before release.

Comment (ibrahimrabab) [reply sdk/storage/azure-storage-blob/CHANGELOG.md:6]: Thank you for pointing this out! Let me make the change in a separate PR.
