### PR TITLE
Fixes OOM when receiving from Event Hubs

### LINKED ISSUE #9659: Fix Disabled tests in Event Hubs
Fix disabled tests in Event Hubs. They are disabled because they often fail in CI but pass locally.
* SetPrefetchCountTest
* EventHubAsyncClientIntegrationTest

### LINKED ISSUE #20790: [BUG] EventHubs OutOfMemoryError after long running with large amounts of Event in backlog. It recovers though.
**Describe the bug**
`EventProcessorClient` may throw OutOfMemoryError after long running. Then it will close the partition that happens to be hit by this exception, and re-claim this partition to proceed consuming.

The following is the heap dump of the long running test some minutes after OOM happened. The retained size of each `AmqpReceiveLinkProcessor` becomes over 100M because the kept too many events in the cache. One `AmqpReceiveLinkProcessor` has small retained size because it was new. After OOM or other exceptions happened on a partition, the partition is lost so the link is closed and recreated. This might be why this single `AmqpReceiveLinkProcessor` has small retained size while others have large size.

For the EH metrics, the throughput deteriorates slowly over time and when OOM happens on a partition, the throughput of that partition becomes normal from the previous slowdown. This might be because the OOM-ed partition recreated the `AmqpReceiveLinkProcessor`.

Possible root cause is because the SDK keeps requesting too many credits from the EH service and dumped too many events in the client cache for each partition.

image

***Exception or Stack Trace***
```
com.azure.messaging.eventhubs.implementation.PartitionProcessorException: Error in event processing callback
	at com.azure.messaging.eventhubs.PartitionPumpManager.processEvents(PartitionPumpManager.java:318) ~[azure-messaging-eventhubs-5.7.0-beta.1.jar:?]
	at com.azure.messaging.eventhubs.PartitionPumpManager.lambda$startPartitionPump$2(PartitionPumpManager.java:231) ~[azure-messaging-eventhubs-5.7.0-beta.1.jar:?]
	at reactor.core.publisher.LambdaSubscriber.onNext(LambdaSubscriber.java:160) ~[reactor-core-3.4.3.jar:3.4.3]
	at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.runAsync(FluxPublishOn.java:440) ~[reactor-core-3.4.3.jar:3.4.3]
	at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.run(FluxPublishOn.java:527) ~[reactor-core-3.4.3.jar:3.4.3]
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84) [reactor-core-3.4.3.jar:3.4.3]
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37) [reactor-core-3.4.3.jar:3.4.3]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: com.azure.messaging.eventhubs.implementation.PartitionProcessorException: Error in event processing callback
	at com.azure.messaging.eventhubs.PartitionPumpManager.processEvent(PartitionPumpManager.java:280) ~[azure-messaging-eventhubs-5.7.0-beta.1.jar:?]
	at com.azure.messaging.eventhubs.PartitionPumpManager.processEvents(PartitionPumpManager.java:314) ~[azure-messaging-eventhubs-5.7.0-beta.1.jar:?]
	... 11 more
Caused by: java.lang.OutOfMemoryError: Java heap space
	at com.azure.messaging.eventhubs.EventDataBatch.<init>(EventDataBatch.java:74) ~[azure-messaging-eventhubs-5.7.0-beta.1.jar:?]
	at com.azure.messaging.eventhubs.EventHubProducerAsyncClient.lambda$createBatch$4(EventHubProducerAsyncClient.java:252) ~[azure-messaging-eventhubs-5.7.0-beta.1.jar:?]
	at com.azure.messaging.eventhubs.EventHubProducerAsyncClient$$Lambda$845/0x00000008408d3840.apply(Unknown Source) ~[?:?]
	at reactor.core.publisher.FluxFlatMap.trySubscribeScalarMap(FluxFlatMap.java:151) ~[reactor-core-3.4.3.jar:3.4.3]
	at reactor.core.publisher.MonoFlatMap.subscribeOrReturn(MonoFlatMap.java:53) ~[reactor-core-3.4.3.jar:3.4.3]
	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:57) ~[reactor-core-3.4.3.jar:3.4.3]
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:157) ~[reactor-core-3.4.3.jar:3.4.3]
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1815) ~[reactor-core-3.4.3.jar:3.4.3]
	at reactor.core.publisher.MonoFlatMap$FlatMapInner.onNext(MonoFlatMap.java:249) ~[reactor-core-3.4.3.jar:3.4.3]
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1815) ~[reactor-core-3.4.3.jar:3.4.3]
	at reactor.core.publisher.MonoFlatMap$FlatMapInner.onNext(MonoFlatMap.java:249) ~[reactor-core-3.4.3.jar:3.4.3]
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:120) ~[reactor-core-3.4.3.jar:3.4.3]
	at reactor.core.publisher.FluxFirstWithSignal$FirstEmittingSubscriber.onNext(FluxFirstWithSignal.java:329) ~[reactor-core-3.4.3.jar:3.4.3]
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:127) ~[reactor-core-3.4.3.jar:3.4.3]
	at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2397) ~[reactor-core-3.4.3.jar:3.4.3]
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.request(FluxMapFuseable.java:169) ~[reactor-core-3.4.3.jar:3.4.3]
	at reactor.core.publisher.Operators$DeferredSubscription.set(Operators.java:1716) ~[reactor-core-3.4.3.jar:3.4.3]
	at reactor.core.publisher.FluxFirstWithSignal$FirstEmittingSubscriber.onSubscribe(FluxFirstWithSignal.java:314) ~[reactor-core-3.4.3.jar:3.4.3]
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onSubscribe(FluxMapFuseable.java:96) ~[reactor-core-3.4.3.jar:3.4.3]
	at reactor.core.publisher.MonoJust.subscribe(MonoJust.java:54) ~[reactor-core-3.4.3.jar:3.4.3]
	at reactor.core.publisher.Mono.subscribe(Mono.java:4046) ~[reactor-core-3.4.3.jar:3.4.3]
	at reactor.core.publisher.FluxFirstWithSignal$RaceCoordinator.subscribe(FluxFirstWithSignal.java:225) ~[reactor-core-3.4.3.jar:3.4.3]
	at reactor.core.publisher.MonoFirstWithSignal.subscribe(MonoFirstWithSignal.java:146) ~[reactor-core-3.4.3.jar:3.4.3]
	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64) ~[reactor-core-3.4.3.jar:3.4.3]
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:157) ~[reactor-core-3.4.3.jar:3.4.3]
	at reactor.core.publisher.FluxFirstWithSignal$FirstEmittingSubscriber.onNext(FluxFirstWithSignal.java:329) ~[reactor-core-3.4.3.jar:3.4.3]
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1815) ~[reactor-core-3.4.3.jar:3.4.3]
	at reactor.core.publisher.MonoFlatMap$FlatMapInner.onNext(MonoFlatMap.java:249) ~[reactor-core-3.4.3.jar:3.4.3]
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1815) ~[reactor-core-3.4.3.jar:3.4.3]
	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.drain(MonoIgnoreThen.java:148) ~[reactor-core-3.4.3.jar:3.4.3]
	at reactor.core.publisher.MonoIgnoreThen.subscribe(MonoIgnoreThen.java:56) ~[reactor-core-3.4.3.jar:3.4.3]
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:157) ~[reactor-core-3.4.3.jar:3.4.3]
```

**To Reproduce**
1. Send large amounts of events to an EventHub. This is to make the events backlog.
2. Run `EventProcessorClient` for long time. Eventually this exception will happen after 10 to 20 hours.

***Code Snippet***
Nil.

**Expected behavior**
`AmqpReceiveLinkProcessor` should keep the client cache size <= prefetch 

**Screenshots**

**Setup (please complete the following information):**
 - OS: [e.g. iOS] Both windows and Linux
 - IDE : [e.g. IntelliJ]
 - Version of the Library used azure-messaging-eventhubs 5.7.0

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

### PR DESCRIPTION
**Pull request by conniey**
* Checks to see if there are messages in the queue and if the emptyCreditListener has been invoked (ie. meaning there are no credits left on the link) before adding credits.
* Enables disabled tests related to prefetch.

Fixes #9659
Fixes #20790

### CODE REVIEW

File: sdk/eventhubs/azure-messaging-eventhubs/src/main/java/com/azure/messaging/eventhubs/implementation/AmqpReceiveLinkProcessor.java [hunk 1]
```diff
@@ -41,6 +41,7 @@
     private final AtomicBoolean isTerminated = new AtomicBoolean();
     private final AtomicInteger retryAttempts = new AtomicInteger();
     private final Deque<Message> messageQueue = new ConcurrentLinkedDeque<>();
+    private final AtomicBoolean linkHasNoCredits = new AtomicBoolean();
```
Comment (anuchandy) [inline sdk/eventhubs/azure-messaging-eventhubs/src/main/java/com/azure/messaging/eventhubs/implementation/AmqpReceiveLinkProcessor.java:44]: jfyi, Ideally a scalar boolean should do if access to `linkHasNoCredits` is always guarded by `creditsAdded`; the aquire-release (a-r) semantic provided by `creditsAdded` should ensure modification of all shared data sandwiched between the a-r is visible to threads in all cpus.

Comment (YijunXieMS) [reply sdk/eventhubs/azure-messaging-eventhubs/src/main/java/com/azure/messaging/eventhubs/implementation/AmqpReceiveLinkProcessor.java:44]: We might be able to go further to remove this attribute

File: sdk/eventhubs/azure-messaging-eventhubs/src/main/java/com/azure/messaging/eventhubs/implementation/AmqpReceiveLinkProcessor.java [hunk 2]
```diff
@@ -356,23 +369,29 @@ public void request(long request) {
...
+
         synchronized (creditsAdded) {
-            final AmqpReceiveLink link = currentLink;
-            final int credits = getCreditsToAdd();
+            credits = getCreditsToAdd();
 
-            logger.verbose("linkName[{}] entityPath[{}] request[{}] credits[{}] Backpressure request from downstream.",
-                currentLinkName, entityPath, request, credits);
+            if (link != null && credits > 0) {
+                final boolean hadNoCredits = linkHasNoCredits.compareAndSet(true, false);
```
Comment (YijunXieMS) [inline sdk/eventhubs/azure-messaging-eventhubs/src/main/java/com/azure/messaging/eventhubs/implementation/AmqpReceiveLinkProcessor.java:379]: This part is hard to understand. If linkHasNoCredits is successfully set to false, then hasNoCredits is true.

File: sdk/eventhubs/azure-messaging-eventhubs/src/main/java/com/azure/messaging/eventhubs/implementation/AmqpReceiveLinkProcessor.java (hunk 1 above)
Comment (conniey) [reply sdk/eventhubs/azure-messaging-eventhubs/src/main/java/com/azure/messaging/eventhubs/implementation/AmqpReceiveLinkProcessor.java:44]: There are times we asynchronously update it outside of a `creditsAdded` lock. For example, our usage in `next.setEmptyCreditListener` and some of the subscriber callbacks when an exception occurs asynchronously.

File: sdk/eventhubs/azure-messaging-eventhubs/src/main/java/com/azure/messaging/eventhubs/implementation/AmqpReceiveLinkProcessor.java (hunk 2 above)
Comment (conniey) [reply sdk/eventhubs/azure-messaging-eventhubs/src/main/java/com/azure/messaging/eventhubs/implementation/AmqpReceiveLinkProcessor.java:379]: I created a variable so it would make it easier to log, but I really don't need the `hadNoCredits` variable.

**Review by YijunXieMS — APPROVED** [review]
I did a 20-minute test. No memory leak was seen.
Let's merge to master and do a long running test to verify after other changes are also merged to master.
