### PR TITLE
Use `IterableStream<T>(Iterable)` ctor in EventHubProperties

### LINKED ISSUE #6515: Cannot use IterableStream with Schedulers.parallel() or Schedulers.single()
**Repo**:
1. Copy the snippet below
1. Execute test.

**Expected**: It passes
**Actual**:
```
java.lang.AssertionError: expectation "assertNext" failed
(expected: onNext(); actual: onError(java.lang.IllegalStateException: 
Iterating over a toIterable() / toStream() is blocking, which is not supported in thread parallel-1))
```

**Snippet**
```java
import com.azure.core.util.IterableStream;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import reactor.core.publisher.Flux;
import reactor.core.publisher.Mono;
import reactor.core.scheduler.Scheduler;
import reactor.core.scheduler.Schedulers;
import reactor.test.StepVerifier;

import java.util.Arrays;

class IterableStreamTest {
    @Test
    public void repro() {
        Foo foo = new Foo();

        // Also fails with Schedulers.single().
        Scheduler scheduler = Schedulers.parallel();

        System.out.println("Using array.");
        StepVerifier.create(foo.getPartitionIdsFromArray().subscribeOn(scheduler))
            .assertNext(id -> Assertions.assertEquals("0", id))
            .assertNext(id -> Assertions.assertEquals("1", id))
            .assertNext(id -> Assertions.assertEquals("2", id))
            .expectComplete()
            .verify(Duration.ofSeconds(5));

        System.out.println("Using IterableStream.");
        StepVerifier.create(foo.getPartitionIds().subscribeOn(scheduler))
            .assertNext(id -> Assertions.assertEquals("0", id))
            .assertNext(id -> Assertions.assertEquals("1", id))
            .assertNext(id -> Assertions.assertEquals("2", id))
            .expectComplete()
            .verify(Duration.ofSeconds(5));
    }

    static class Foo {
        Mono<Bar> getProperties() {
            return Mono.fromCallable(() -> new Bar(new String[]{"0", "1", "2"}));
        }

        Flux<String> getPartitionIds() {
            return getProperties().flatMapMany(x -> Flux.fromIterable(x.getPartitionIds()));
        }

        Flux<String> getPartitionIdsFromArray() {
            return getProperties().flatMapMany(x -> Flux.fromArray(x.getPartitionIdsArray()));
        }
    }

    static class Bar {
        private final IterableStream<String> partitionIds;
        private final String[] partitionArrays;

        Bar(String[] partitionIds) {
            this.partitionIds = partitionIds != null
                ? new IterableStream<>(Flux.fromArray(partitionIds))
                : new IterableStream<>(Flux.empty());
            this.partitionArrays = partitionIds;
        }

        IterableStream<String> getPartitionIds() {
            return partitionIds;
        }

        String[] getPartitionIdsArray() {
            return Arrays.copyOf(partitionArrays, partitionArrays.length);
        }
    }
}
```

### PR DESCRIPTION
**Pull request by conniey**
* Updates EventHubProperties to use `IterableStream<T>(Iterable<T>)` overload. This fixes the IllegalStateException because we are no longer moving from the Flux universe, into synchronous then back into the Flux world.
* Adds back a package-private scheduler override on EventHubClientBuilder and forces our integration tests to use Schedulers.parallel, so we can double check that we don't have blocking calls in our code.

Fixes #6515

### CODE REVIEW

File: sdk/eventhubs/azure-messaging-eventhubs/src/main/java/com/azure/messaging/eventhubs/EventHubProperties.java [hunk 1]
```diff
@@ -31,9 +31,10 @@
         final String[] partitionIds) {
         this.name = name;
         this.createdAt = createdAt;
+
         this.partitionIds = partitionIds != null
```
Comment (srnagar) [inline sdk/eventhubs/azure-messaging-eventhubs/src/main/java/com/azure/messaging/eventhubs/EventHubProperties.java]: partitionIds cannot be null and if it is, then should we bubble up an error?

Comment (conniey) [reply sdk/eventhubs/azure-messaging-eventhubs/src/main/java/com/azure/messaging/eventhubs/EventHubProperties.java]: kk. will do
