### PR TITLE
Change Netty version logging

### LINKED ISSUE #40732: [BUG] azure-core-http-netty 1.15.1 contains wrong netty.version property
# **Issue description**
Netty utility class is expecting an older version of Netty dependencies in `azure-core-http-netty 1.15.1`.

Check this POM file in the public Maven repo:

[azure-core-http-netty-1.15.1.pom](https://repo1.maven.org/maven2/com/azure/azure-core-http-netty/1.15.1/azure-core-http-netty-1.15.1.pom)

We can see that there are different version numbers of Netty:

- `4.1.108.Final` (the `netty.version` project property)
- `4.1.110.Final` (all individual Netty dependency versions)
Now, compare with the previous version:

[azure-core-http-netty-1.15.0.pom](https://repo1.maven.org/maven2/com/azure/azure-core-http-netty/1.15.0/azure-core-http-netty-1.15.0.pom)

We can see that it only contains a single version number, i.e. 4.1.108.Final.
___
# **Impact**
It is causing the `azure-core-http-netty.properties` file to contain wrong Netty version.

- Expected: `4.1.110.Final`
- Actual: `4.1.108.Final`
This value, if I guess right, is populated with the netty.version Maven property.

See: [azure-core-http-netty.properties (1.15.1)](https://github.com/Azure/azure-sdk-for-java/blob/azure-core-http-netty_1.15.1/sdk/core/azure-core-http-netty/src/main/resources/azure-core-http-netty.properties)
  
___
# **Exception or error**
There is one `INFO` level log:

> NettyUtility - The following is Netty version information that was found on the classpath: 'io.netty:netty-common' version: 4.1.110.Final, 'io.netty:netty-handler' version: 4.1.110.Final, 'io.netty:netty-handler-proxy' version: 4.1.110.Final, 'io.netty:netty-buffer' version: 4.1.110.Final, 'io.netty:netty-codec' version: 4.1.110.Final, 'io.netty:netty-codec-http' version: 4.1.110.Final, 'io.netty:netty-codec-http2' version: 4.1.110.Final, 'io.netty:netty-transport-native-unix-common' version: 4.1.110.Final, 'io.netty:netty-transport-native-epoll' version: 4.1.110.Final, 'io.netty:netty-transport-native-kqueue' version: 4.1.110.Final. The version of azure-core-http-netty being used was built with Netty version 4.1.108.Final and Netty Tcnative version 2.0.65.Final. If your application runs without issue this message can be ignored, otherwise please align the Netty versions used in your application. For more information, see https://aka.ms/azsdk/java/dependency/troubleshoot.
___
Same issue as https://github.com/Azure/azure-sdk-for-java/issues/39583, different netty versions

### PR DESCRIPTION
**Pull request by alzimmermsft**
# Description

Fixes #40732 

Changes how Netty version logging is performed to retain more metadata while inspecting Netty versions found in the class path and comparing them against what `azure-core-http-netty` specifies in its POM.

The only time Netty versions will be logged is when `INFORMATIONAL` logging, or more verbose, logging is enabled and there is a difference between the Netty versions specified in `azure-core-http-netty` and what was found on the class path. As before, this log is purely informational to help troubleshooting dependency conflicts, and the message will continue stating that. And, the message state to just align Netty versions, not to align them to what `azure-core-http-netty` is using, in case an older version of `azure-core-http-netty` is being used and CVEs are found in the versions of Netty it was released with.

Tests have been updated to fail if the versions listed in `azure-core-http-netty`'s POM are forgotten to be updated when the dependency versions of Netty used change, this should prevent errant logs in the future when versions are upgraded and result in the message always being logged incorrectly.

# All SDK Contribution checklist:
- [x] **The pull request does not introduce [breaking changes]**
- [x] **CHANGELOG is updated for new features, bug fixes or other significant changes.**
- [x] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md).**

## [General Guidelines and Best Practices](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md#developer-guide)
- [x] Title of the pull request is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md#building-and-unit-testing)
- [x] Pull request includes test coverage for the included changes.

### CODE REVIEW

File: sdk/core/azure-core-http-netty/src/main/java/com/azure/core/http/netty/implementation/NettyUtility.java [hunk 1]
```diff
@@ -93,31 +92,35 @@ public static void closeConnection(Connection reactorNettyConnection) {
      * warning will contain the versions found in runtime and the expected versions to be used by the SDK.
      */
     public static void validateNettyVersions() {
```
Comment (lmolkova) [inline sdk/core/azure-core-http-netty/src/main/java/com/azure/core/http/netty/implementation/NettyUtility.java:94]: do we have any means to know that it's called once/rare? And that it won't change over time?

Otherwise, I'd at least move initialization of `versionLogInformation` to a static block and made it a static field. Or, as an alternative, have a flag indicating that it's already been logged and not create/log it again.

**Review by lmolkova — APPROVED** [review]

File: sdk/core/azure-core-http-netty/src/main/java/com/azure/core/http/netty/implementation/NettyUtility.java (hunk 1 above)
Comment (alzimmermsft) [reply sdk/core/azure-core-http-netty/src/main/java/com/azure/core/http/netty/implementation/NettyUtility.java:94]: Should only be called once per class loading.
