### PR TITLE
Sas time encoding roundtrip

### LINKED ISSUE #22042: [BUG] SAS token SAS_EXPIRY_TIME encoding results in an invalid signature
**Describe the bug**
After introducing https://github.com/Azure/azure-sdk-for-java/pull/20520 SAS query params are sanitized but it seems like the `SAS_EXPIRY_TIME` gets modified and it invalidates the provided signature.

***Exception or Stack Trace***
```
<?xml version="1.0" encoding="utf-8"?><Error><Code>AuthenticationFailed</Code><Message>Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
RequestId:76972c6c-201e-0090-1453-582f4d000000
Time:2021-06-03T08:38:25.4063780Z</Message><AuthenticationErrorDetail>Signature did not match. String to sign used was rwdl

2021-07-20T13:21:00Z
/blob/<account>/<container>



2018-11-09
c

```
**To Reproduce**
Provide a SAS token with `SAS_EXPIRY_TIME` without seconds, i.e. `se=2021-07-20T13%3A21Z&sp=rwdl&sv=2018-11-09&sr=c&sig=<redacted>` that converts the http request query params into `se=2021-07-20T13%3A21%3A00Z&sp=rwdl&sv=2018-11-09&sr=c&sig=<redacted>` making the signature invalid. This can be reproduced with curl easily. 

**Expected behavior**
Generate a valid http request

**Setup (please complete the following information):**
 - Version of the Library used: `12.11.1`

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Bug Description Added
- [X] Repro Steps Added
- [X] Setup information Added

### PR DESCRIPTION
**Pull request by rickle-msft**
Resolves #22042

### CODE REVIEW

File: sdk/storage/azure-storage-common/src/main/java/com/azure/storage/common/Utility.java [hunk 1]
```diff
@@ -187,7 +186,7 @@ public static String encodeUrlPath(String url) {
      * @return the corresponding <code>Date</code> object
      * @throws IllegalArgumentException If {@code dateString} doesn't match an ISO8601 pattern
      */
-    public static OffsetDateTime parseDate(String dateString) {
+    public static TimeAndFormat parseDate(String dateString) {
```
Comment (alzimmermsft) [inline sdk/storage/azure-storage-common/src/main/java/com/azure/storage/common/Utility.java:189]: nit: mark `parseDate` as deprecated instead of changing the API

File: sdk/storage/azure-storage-common/src/main/java/com/azure/storage/common/Utility.java [hunk 2]
```diff
@@ -216,7 +215,49 @@ public static OffsetDateTime parseDate(String dateString) {
...
+
+    /**
+     * Given a String representing a date in a form of the ISO8601 pattern, generates a Date representing it with up to
+     * millisecond precision.
+     *
+     * @param dateString the {@code String} to be interpreted as a <code>Date</code>
+     * @return the corresponding <code>Date</code> object
+     * @throws IllegalArgumentException If {@code dateString} doesn't match an ISO8601 pattern
+     */
+    public static TimeAndFormat parseDateAndFormat(String dateString) {
```
Comment (alzimmermsft) [inline sdk/storage/azure-storage-common/src/main/java/com/azure/storage/common/Utility.java:230]: Given that azure-storage-common exposes it's implementation packages to the other azure-storage libraries we should think about moving this into implementation in case we need to do API changes to it in the future.

File: sdk/storage/azure-storage-common/src/main/java/com/azure/storage/common/TimeAndFormat.java [hunk 3]
```diff
@@ -0,0 +1,49 @@
...
+import java.time.format.DateTimeFormatter;
+
+/**
+ * A class to hold an {@code OffsetDateTime} object and the formatter from which it was parsed for effective
+ * roundtripping.
+ * Without this, we always format date-times the same way, but if we parsed a value from a sas token in on an endpoint
+ * or in a connection string, we have to preserve the formatting, especially the precision, so the signature still
+ * matches.
+ */
+public class TimeAndFormat {
```
Comment (alzimmermsft) [inline sdk/storage/azure-storage-common/src/main/java/com/azure/storage/common/TimeAndFormat.java:16]: Same comment about the new utility method, unless we're expecting to return this in public APIs somewhere. Also, let's make it `final`

File: sdk/storage/azure-storage-common/src/main/java/com/azure/storage/common/TimeAndFormat.java [hunk 4]
```diff
@@ -0,0 +1,49 @@
...
+import java.time.format.DateTimeFormatter;
+
+/**
+ * A class to hold an {@code OffsetDateTime} object and the formatter from which it was parsed for effective
+ * roundtripping.
+ * Without this, we always format date-times the same way, but if we parsed a value from a sas token in on an endpoint
+ * or in a connection string, we have to preserve the formatting, especially the precision, so the signature still
+ * matches.
+ */
+public final class TimeAndFormat {
```
Comment (alzimmermsft) [inline sdk/storage/azure-storage-common/src/main/java/com/azure/storage/common/TimeAndFormat.java:16]: Given this class isn't exposed in any public APIs does it itself need to be exposed as a public API?

**Review by alzimmermsft — APPROVED** [review]
