### PR TITLE
Stop processor client when load balance occurs errors.

### LINKED ISSUE #27282: [BUG]Account Storage "premium" tier not work with eventhubs
**Describe the bug**
Account Storage "premium" tier not work with eventhubs.

When using storage account(template pasted in the context section) of the premium tier,  the event hubs sdk not work normally as the standard tier do.
 

***Exception or Stack Trace***

**To Reproduce**
Run the following code in the IDE will reproduce the issue.

***Code Snippet***

dependencies:
```
    <dependency>
      <groupId>com.azure</groupId>
      <artifactId>azure-storage-blob</artifactId>
      <version>12.14.3</version> <!-- {x-version-update;com.azure:azure-storage-blob;dependency} -->
    </dependency>

    <dependency>
      <groupId>com.azure</groupId>
      <artifactId>azure-messaging-eventhubs</artifactId>
      <version>5.10.4</version> <!-- {x-version-update;com.azure:azure-messaging-eventhubs;current} -->
    </dependency>

```

```
    public static void main(String[] args) throws InterruptedException {

        String accountName = "xxx";
        String accessKey = "xxxxx";
        String endpoint = "https://xxxx.blob.core.windows.net/";
        StorageSharedKeyCredential cre = new StorageSharedKeyCredential(accountName, accessKey);
        BlobServiceClientBuilder builder =   new BlobServiceClientBuilder().credential(cre).endpoint(endpoint);

        BlobContainerAsyncClient blobContainerAsyncClient =  builder
            .buildAsyncClient()
            .getBlobContainerAsyncClient("xxxx");

        EventProcessorClient eventProcessorClient = new EventProcessorClientBuilder()
            .consumerGroup("$Default")
            .connectionString("Endpoint=xxxxxx")
            .checkpointStore(new BlobCheckpointStore(blobContainerAsyncClient))
            .processEvent(eventContext -> {
                System.out.println("Partition id = " + eventContext.getPartitionContext().getPartitionId() + " and "
                    + "sequence number of event = " + eventContext.getEventData().getSequenceNumber());
            })
            .processError(errorContext -> {
                System.out
                    .println("Error occurred while processing events " + errorContext.getThrowable().getMessage());
            })
            .buildEventProcessorClient();

        // This will start the processor. It will start processing events from all partitions.
        eventProcessorClient.start();

        // (for demo purposes only - adding sleep to wait for receiving events)
        TimeUnit.SECONDS.sleep(200);

        // This will stop processing events.
        eventProcessorClient.stop();
    }
}

```
**Expected behavior**
 Number of ownership records should not be `0`.

**Screenshots**

 Number of ownership records 0 appear in the following log.

 >  If applicable, add screenshots to help explain your problem.
  13:49:50.913 [reactor-http-nio-1] DEBUG reactor.netty.channel.FluxReceive - [5dec2153-1, L:/10.10.2.72:51583 - R:garyliuac3.blob.core.windows.net/52.239.155.4:443] FluxReceive{pending=0, cancelled=false, inboundDone=false, inboundError=null}: subscribing inbound receiver
  13:49:50.913 [reactor-http-nio-1] DEBUG reactor.netty.http.client.HttpClientOperations - [5dec2153-1, L:/10.10.2.72:51583 - R:garyliuac3.blob.core.windows.net/52.239.155.4:443] Received last HTTP packet
  13:49:51.033 [reactor-http-nio-1] INFO com.azure.messaging.eventhubs.PartitionBasedLoadBalancer - Starting next iteration of load balancer
  13:49:51.033 [reactor-http-nio-1] INFO com.azure.messaging.eventhubs.PartitionBasedLoadBalancer - Number of ownership records 0, number of partitions 1
  13:49:51.033 [reactor-http-nio-1] INFO com.azure.messaging.eventhubs.PartitionBasedLoadBalancer - Number of active ownership records 0
 
**Additional context**
Template is following:
```
{
    "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {
        "storageAccounts_garyliuac3_name": {
            "defaultValue": "garyliuac3",
            "type": "String"
        }
    },
    "variables": {},
    "resources": [
        {
            "type": "Microsoft.Storage/storageAccounts",
            "apiVersion": "2021-08-01",
            "name": "[parameters('storageAccounts_garyliuac3_name')]",
            "location": "eastus",
            "sku": {
                "name": "Premium_LRS",
                "tier": "Premium"
            },
            "kind": "StorageV2",
            "properties": {
                "defaultToOAuthAuthentication": false,
                "allowCrossTenantReplication": false,
                "minimumTlsVersion": "TLS1_2",
                "allowBlobPublicAccess": true,
                "allowSharedKeyAccess": true,
                "networkAcls": {
                    "bypass": "AzureServices",
                    "virtualNetworkRules": [],
                    "ipRules": [],
                    "defaultAction": "Allow"
                },
                "supportsHttpsTrafficOnly": true,
                "encryption": {
                    "requireInfrastructureEncryption": false,
                    "services": {
                        "file": {
                            "keyType": "Account",
                            "enabled": true
                        },
                        "blob": {
                            "keyType": "Account",
                            "enabled": true
                        }
                    },
                    "keySource": "Microsoft.Storage"
                },
                "accessTier": "Hot"
            }
        },
        {
            "type": "Microsoft.Storage/storageAccounts/blobServices",
            "apiVersion": "2021-08-01",
            "name": "[concat(parameters('storageAccounts_garyliuac3_name'), '/default')]",
            "dependsOn": [
                "[resourceId('Microsoft.Storage/storageAccounts', parameters('storageAccounts_garyliuac3_name'))]"
            ],
            "sku": {
                "name": "Premium_LRS",
                "tier": "Premium"
            },
            "properties": {
                "cors": {
                    "corsRules": []
                },
                "deleteRetentionPolicy": {
                    "enabled": true,
                    "days": 7
                },
                "containerDeleteRetentionPolicy": {
                    "enabled": true,
                    "days": 7
                }
            }
        },
        {
            "type": "Microsoft.Storage/storageAccounts/blobServices/containers",
            "apiVersion": "2021-08-01",
            "name": "[concat(parameters('storageAccounts_garyliuac3_name'), '/default/garyliucontainer3')]",
            "dependsOn": [
                "[resourceId('Microsoft.Storage/storageAccounts/blobServices', parameters('storageAccounts_garyliuac3_name'), 'default')]",
                "[resourceId('Microsoft.Storage/storageAccounts', parameters('storageAccounts_garyliuac3_name'))]"
            ],
            "properties": {
                "immutableStorageWithVersioning": {
                    "enabled": false
                },
                "defaultEncryptionScope": "$account-encryption-key",
                "denyEncryptionScopeOverride": false,
                "publicAccess": "None"
            }
        }
    ]
}

```

### PR DESCRIPTION
**Pull request by ZejiaJiang**
# Description
- Return error if checkpoint store claim ownership occurs an error.
- Stop processor client when load balance occurs errors.
Fixes #27282

# All SDK Contribution checklist:
- [x] **The pull request does not introduce [breaking changes]**
- [x] **CHANGELOG is updated for new features, bug fixes or other significant changes.**
- [x] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md).**

## [General Guidelines and Best Practices](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md#developer-guide)
- [x] Title of the pull request is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md#building-and-unit-testing)
- [x] Pull request includes test coverage for the included changes.

### CODE REVIEW

File: sdk/eventhubs/azure-messaging-eventhubs/src/main/java/com/azure/messaging/eventhubs/EventProcessorClient.java [hunk 1]
```diff
@@ -144,6 +144,14 @@ public synchronized void start() {
             return;
         }
         logger.info("Starting a new event processor instance.");
+        try {
+            partitionBasedLoadBalancer.checkBlobStatus().block();
+        } catch (RuntimeException ex) {
+            logger.error("Start event processor error", ex);
+            partitionBasedLoadBalancer.removePartitionCache();
```
Comment (weidongxu-microsoft) [inline sdk/eventhubs/azure-messaging-eventhubs/src/main/java/com/azure/messaging/eventhubs/EventProcessorClient.java:151]: Will partitionBasedLoadBalancer have cache? From code, it is scheduled after this check.

Or put is another way, why not do this in `checkBlobStatus`?

File: sdk/eventhubs/azure-messaging-eventhubs/src/main/java/com/azure/messaging/eventhubs/PartitionBasedLoadBalancer.java [hunk 2]
```diff
@@ -286,10 +286,101 @@ private Mono<Void> loadBalance(final Tuple2<Map<String, PartitionOwnership>, Lis
...
+                if (!CoreUtils.isNullOrEmpty(activePartitionOwnershipMap)) {
+                    return Mono.empty();
+                }
+
+                /*
+                 * If there is no active partition ownership, claim a random partition and the other partitions will be
+                 * claimed in load balance.
+                 */
+                PartitionOwnership ownershipRequest = createPartitionOwnershipRequest(partitionOwnershipMap,
+                    partitionIds.get(RANDOM.nextInt(partitionIds.size())));
```
Comment (weidongxu-microsoft) [inline sdk/eventhubs/azure-messaging-eventhubs/src/main/java/com/azure/messaging/eventhubs/PartitionBasedLoadBalancer.java:358]: Does RANDON better than just take first partition?

File: sdk/eventhubs/azure-messaging-eventhubs/src/main/java/com/azure/messaging/eventhubs/PartitionBasedLoadBalancer.java [hunk 3]
```diff
@@ -286,10 +286,101 @@ private Mono<Void> loadBalance(final Tuple2<Map<String, PartitionOwnership>, Lis
...
+                return this.checkpointStore.claimOwnership(partitionToClaim)
+                    .collectList()
+                    .zipWhen(ownershipList -> checkpointStore.listCheckpoints(fullyQualifiedNamespace, eventHubName,
+                            consumerGroupName)
+                        .collectMap(checkpoint -> checkpoint.getPartitionId(), Function.identity()))
+                    .flatMap(ownedPartitionCheckpointsTuple -> {
+                        ownedPartitionCheckpointsTuple.getT1()
+                            .stream()
+                            .forEach(po -> partitionPumpManager.startPartitionPump(po,
+                                ownedPartitionCheckpointsTuple.getT2().get(po.getPartitionId())));
```
Comment (weidongxu-microsoft) [inline sdk/eventhubs/azure-messaging-eventhubs/src/main/java/com/azure/messaging/eventhubs/PartitionBasedLoadBalancer.java:369]: Why do we startPartitionPump here?

File: sdk/eventhubs/azure-messaging-eventhubs/src/main/java/com/azure/messaging/eventhubs/PartitionBasedLoadBalancer.java (hunk 2 above)
Comment (ZejiaJiang) [reply sdk/eventhubs/azure-messaging-eventhubs/src/main/java/com/azure/messaging/eventhubs/PartitionBasedLoadBalancer.java:358]: I'm not sure. But in loadbalance, if there are no partition start pump, it take a random partition to start as well. I keep the same logic.

File: sdk/eventhubs/azure-messaging-eventhubs/src/main/java/com/azure/messaging/eventhubs/EventProcessorClient.java (hunk 1 above)
Comment (ZejiaJiang) [reply sdk/eventhubs/azure-messaging-eventhubs/src/main/java/com/azure/messaging/eventhubs/EventProcessorClient.java:151]: partitionBasedLoadBalancer has the partition cache. In check blob status, I'll cache the partition for loadbalancer to use.

I use the partition cache to check did the client start successfully. If client started successfully, then client stop and start again, the client doesn't need to check blob status. If client start failed, I remove the cache.

File: sdk/eventhubs/azure-messaging-eventhubs/src/main/java/com/azure/messaging/eventhubs/PartitionBasedLoadBalancer.java (hunk 3 above)
Comment (ZejiaJiang) [reply sdk/eventhubs/azure-messaging-eventhubs/src/main/java/com/azure/messaging/eventhubs/PartitionBasedLoadBalancer.java:369]: If we don't startPartitionPump here, the partition won't start pump until elapse expirationInterval (default value is 2 minutes). So here are three solutions:

1. Just claim partition, don't start pump. This partition wil start pump after expirationInterval.
2. Claim partition and set an early lastModifiedTime, then loadbalance can start this partition quickly, I try to avoid modifying the `claimOwnerShip` method.
3. Claim partion and start pump.

I choose the third solution, actually I'm not sure which one is the best.

File: sdk/eventhubs/azure-messaging-eventhubs/src/test/java/com/azure/messaging/eventhubs/EventProcessorClientErrorHandlingTest.java [hunk 4]
```diff
@@ -78,13 +78,7 @@ public void testCheckpointStoreErrors(CheckpointStore checkpointStore) throws In
             Assertions.assertTrue(errorContext.getThrowable() instanceof IllegalStateException);
         }, new HashMap<>(), 1, null, false, Duration.ofSeconds(10), Duration.ofMinutes(1), LoadBalancingStrategy.BALANCED);
         client.start();
-        boolean completed = countDownLatch.await(3, TimeUnit.SECONDS);
-        try {
-            client.stop();
-        } catch (IllegalStateException ex) {
-            // do nothing, expected as the checkpointstores are expected to throw errors
-        }
-        Assertions.assertTrue(completed);
```
[the remark this answers is not in the document]
Comment (ZejiaJiang) [reply sdk/eventhubs/azure-messaging-eventhubs/src/test/java/com/azure/messaging/eventhubs/EventProcessorClientErrorHandlingTest.java:87]: This test is check checkpoint store error, so the client is not running and completed will not be done. I just delete the code.

File: sdk/eventhubs/azure-messaging-eventhubs/src/main/java/com/azure/messaging/eventhubs/PartitionBasedLoadBalancer.java (hunk 3 above)
Comment (ZejiaJiang) [reply sdk/eventhubs/azure-messaging-eventhubs/src/main/java/com/azure/messaging/eventhubs/PartitionBasedLoadBalancer.java:369]: Firstly, claim ownerShip and start pump are at same time. Before this PR, loadbalance will find unclaimed partition or inactive partition(claimed but didn't get modify for expirationInterval) to claim and start pump.

Comment (weidongxu-microsoft) [reply sdk/eventhubs/azure-messaging-eventhubs/src/main/java/com/azure/messaging/eventhubs/PartitionBasedLoadBalancer.java:369]: OK, make sense.

So before this PR, all partitions is claimed and started by load balancer.
After this PR, 1 partition is claimed and started here. And the rest will be claimed and started by load balancer?

Comment (ZejiaJiang) [reply sdk/eventhubs/azure-messaging-eventhubs/src/main/java/com/azure/messaging/eventhubs/PartitionBasedLoadBalancer.java:369]: yeah

File: sdk/eventhubs/azure-messaging-eventhubs/src/main/java/com/azure/messaging/eventhubs/PartitionBasedLoadBalancer.java [hunk 5]
```diff
@@ -286,10 +286,101 @@ private Mono<Void> loadBalance(final Tuple2<Map<String, PartitionOwnership>, Lis
...
+                List<String> partitionIds = tuple.getT2();
+
+                if (CoreUtils.isNullOrEmpty(partitionIds)) {
+                    // This may be due to an error when getting Event Hub metadata.
+                    throw logger.logExceptionAsError(Exceptions.propagate(
+                        new IllegalStateException("There are no partitions in Event Hub " + eventHubName)));
+                }
+                partitionsCache.set(partitionIds);
+
+                if (!isValid(partitionOwnershipMap)) {
```
Comment (liukun-msft) [inline sdk/eventhubs/azure-messaging-eventhubs/src/main/java/com/azure/messaging/eventhubs/PartitionBasedLoadBalancer.java:331]: Do we need to put partitionOwnershipMap before setting partitionsCache?

File: sdk/eventhubs/azure-messaging-eventhubs/src/main/java/com/azure/messaging/eventhubs/PartitionBasedLoadBalancer.java [hunk 6]
```diff
@@ -286,10 +286,101 @@ private Mono<Void> loadBalance(final Tuple2<Map<String, PartitionOwnership>, Lis
...
 
-            claimOwnership(partitionOwnershipMap, ownerPartitionMap, partitionToClaim);
+            claimOwnership(partitionOwnershipMap, partitionToClaim);
         });
     }
 
+    /**
+     * This method make sure that checkpoint store works well and start processing messages of one partition.
+     */
+    Mono<Void> checkBlobStatus() {
```
Comment (liukun-msft) [inline sdk/eventhubs/azure-messaging-eventhubs/src/main/java/com/azure/messaging/eventhubs/PartitionBasedLoadBalancer.java:296]: add test for this function?

Comment (ZejiaJiang) [reply sdk/eventhubs/azure-messaging-eventhubs/src/main/java/com/azure/messaging/eventhubs/PartitionBasedLoadBalancer.java:296]: Not quite need to add the test, because there has been a client start hanlding checkpoint store error already.

File: sdk/eventhubs/azure-messaging-eventhubs/src/main/java/com/azure/messaging/eventhubs/EventProcessorClient.java [hunk 7]
```diff
@@ -144,6 +144,14 @@ public synchronized void start() {
             return;
         }
         logger.info("Starting a new event processor instance.");
+        try {
+            partitionBasedLoadBalancer.checkBlobStatus().block();
```
Comment (conniey) [inline sdk/eventhubs/azure-messaging-eventhubs/src/main/java/com/azure/messaging/eventhubs/EventProcessorClient.java:148]: This block should have a timeout interval... `.block()` by default will be indefinite. `.block(retryOptions.getOperationTimeout)`?

File: sdk/eventhubs/azure-messaging-eventhubs/src/main/java/com/azure/messaging/eventhubs/PartitionBasedLoadBalancer.java (hunk 6 above)
Comment (conniey) [reply sdk/eventhubs/azure-messaging-eventhubs/src/main/java/com/azure/messaging/eventhubs/PartitionBasedLoadBalancer.java:296]: The partition based load balancer should only have methods related to load balancing... Is this better for CheckpointStore interface?  Additionally, these interfaces should contain methods that are agnostic of their implementation.  For example, if customers write an in-memory or Redis checkpoint store, they don't have a concept of "blob status".

Comment (ZejiaJiang) [reply sdk/eventhubs/azure-messaging-eventhubs/src/main/java/com/azure/messaging/eventhubs/PartitionBasedLoadBalancer.java:296]: `checkBlobStatus` do load balance operation for one time to check everything works. If customers use their own checkpoint store, I think we also need to check their checkpoint store. Did I misunderstand?

File: sdk/eventhubs/azure-messaging-eventhubs-checkpointstore-blob/src/main/java/com/azure/messaging/eventhubs/checkpointstore/blob/BlobCheckpointStore.java [hunk 8]
```diff
@@ -193,7 +193,7 @@ public Flux<PartitionOwnership> claimOwnership(List<PartitionOwnership> requeste
                             LOGGER.atVerbose()
                                 .addKeyValue(PARTITION_ID_LOG_KEY, partitionId)
                                 .log(Messages.CLAIM_ERROR, error);
-                            return Mono.empty();
+                            return Mono.error(error);
```
Comment (anuchandy) [inline sdk/eventhubs/azure-messaging-eventhubs-checkpointstore-blob/src/main/java/com/azure/messaging/eventhubs/checkpointstore/blob/BlobCheckpointStore.java:196]: Hi @conniey,  wondering if we should be inspecting the error to decide whether to stop LB entirely or notify the error but continue. For example, looking at the error handling in .NET check point blob store https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/eventhub/Azure.Messaging.EventHubs.Shared/src/BlobCheckpointStore/BlobCheckpointStoreInternal.cs#L247-L265

Comment (conniey) [reply sdk/eventhubs/azure-messaging-eventhubs-checkpointstore-blob/src/main/java/com/azure/messaging/eventhubs/checkpointstore/blob/BlobCheckpointStore.java:196]: By notify of the error, you mean calling the user's callback rather than just logging it?

Comment (conniey) [reply sdk/eventhubs/azure-messaging-eventhubs-checkpointstore-blob/src/main/java/com/azure/messaging/eventhubs/checkpointstore/blob/BlobCheckpointStore.java:196]: We would use the existing processError() method for the callback

Comment (srnagar) [reply sdk/eventhubs/azure-messaging-eventhubs-checkpointstore-blob/src/main/java/com/azure/messaging/eventhubs/checkpointstore/blob/BlobCheckpointStore.java:196]: All processor errors, whether it is from partition processing or from load balancing, should be sent to the `processError` callback that the user configures when creating the EventProcessorClient. The `errorContext` may not have partition details if the error is related to load balancing. 

The user then has a chance to inspect the error and decide whether to continue or stop the processor.

**Review by conniey — APPROVED** [review]
LGTM. Thanks so much!
