### PR TITLE
Storage Page Flux

### LINKED ISSUE #12496: [BUG] Listing Blobs by page with desired page size doesn't work
image

Repro:
```
    public static void main(String[] args) {

        String connectionString = "YOUR OWN";
        BlobServiceClient blobServiceClient = new BlobServiceClientBuilder()
            .connectionString(connectionString)
            .buildClient();
        BlobContainerClient blobContainerClient = blobServiceClient.getBlobContainerClient("test-list-paging");
        if (!blobContainerClient.exists()){
            blobContainerClient.create();
        }

        for(int i = 0 ; i<10 ; i++){
            blobContainerClient.getBlobClient(UUID.randomUUID().toString()).upload(new ByteArrayInputStream(new byte[0]), 0);
        }

        System.out.println("Start");
        blobContainerClient.listBlobs().streamByPage(10)
            .forEach(page -> {
                System.out.println("Processing page");
                page.getValue().forEach(item -> {
                    System.out.println(item.getName());
                });
            });
        System.out.println("End");
    }
```

Output:
```
Start
End
```

Expected Output:
```
Start
<list of blobs here>
End
```

When listing is replaced with `blobContainerClient.listBlobs().forEach(item -> System.out.println(item.getName()));` the output contains blobs.

### LINKED ISSUE #19982: Azure Blob - listBlobsByHierarchy().iterableByPage(10) - not providing results based on defined page size
I have a folder in blob container which have 112 blobs. I defined to get 10 blobs per page, but I am getting all 112 blobs in one page response. Please find below sample code to reproduce this issue.

```
PagedIterable<BlobItem> pagedIterable = getBlobContainerClient().listBlobsByHierarchy("batch/");
        
        Iterable<PagedResponse<BlobItem>> iterableByPage = pagedIterable.iterableByPage(10);
        
        for (PagedResponse<BlobItem> pagedResponse : iterableByPage) {
            Iterator<BlobItem> iterableStream = pagedResponse.getElements().iterator();
            int counter = 1;
            System.err.println("counter - " + counter);
            
            while (iterableStream.hasNext()) {
                BlobItem blobItem = iterableStream.next();
                LOGGER.info(counter++ +" ** listBlob name -'{}' properties-'{}', tags -'{}', version -'{}', snapshot -'{}' ***", 
                                        blobItem.getName(), blobItem.getProperties(), blobItem.getTags(), blobItem.getVersionId(),
                                        blobItem.getSnapshot());
                
            }
        }
```
**ScreenShot**
image

**To Reproduce**
1. Create Folder with 112 items
2. Run above sample code and you will get all items in a single page response

**Expected behavior**
Only 10 blobs should be available in one page response.

Setup (please complete the following information if applicable):
OS: window
IDE : eclipse
Version of the Library used:` azure-storage-blob-12.10.0`

### PR DESCRIPTION
**Pull request by rickle-msft**
Resolves #19982 
Resolves #12496

### CODE REVIEW

File: sdk/storage/azure-storage-blob/src/main/java/com/azure/storage/blob/BlobContainerAsyncClient.java [hunk 1]
```diff
@@ -980,8 +982,17 @@ public String getEncryptionScope() {
      */
     PagedFlux<BlobItem> listBlobsHierarchyWithOptionalTimeout(String delimiter, ListBlobsOptions options,
         Duration timeout) {
-        Function<String, Mono<PagedResponse<BlobItem>>> func =
-            marker -> listBlobsHierarchySegment(marker, delimiter, options, timeout)
+        BiFunction<String, Integer, Mono<PagedResponse<BlobItem>>> func =
+            (marker, pageSize) -> {
+                ListBlobsOptions finalOptions = null;
+                if (pageSize != null) {
```
Comment (gapra-msft) [inline sdk/storage/azure-storage-blob/src/main/java/com/azure/storage/blob/BlobContainerAsyncClient.java:988]: What happens if a user sets the ListBlobsOptions maxResultsPerPage and the iterableByPage(size)? Should we deprecate our way of doing it?

File: sdk/storage/azure-storage-blob/src/main/java/com/azure/storage/blob/BlobServiceAsyncClient.java [hunk 2]
```diff
@@ -329,10 +331,20 @@ public String getAccountUrl() {
...
-        Function<String, Mono<PagedResponse<BlobContainerItem>>> func =
-            marker -> listBlobContainersSegment(marker, options, timeout);
+        BiFunction<String, Integer, Mono<PagedResponse<BlobContainerItem>>> func =
+            (marker, pageSize) -> {
+                ListBlobContainersOptions finalOptions = null;
+                if (pageSize != null) {
+                    if (options == null) {
+                        finalOptions = new ListBlobContainersOptions().setMaxResultsPerPage(pageSize);
+                    } else {
+                        finalOptions = options.setMaxResultsPerPage(pageSize);
```
Comment (kasobol-msft) [inline sdk/storage/azure-storage-blob/src/main/java/com/azure/storage/blob/BlobServiceAsyncClient.java:341]: does this mutate object passed by user to the api or is there a copy somewhere in between?

there's few other places with similar mutation in this PR, same question apply.

File: sdk/storage/azure-storage-blob/src/test/java/com/azure/storage/blob/ContainerAPITest.groovy [hunk 3]
```diff
@@ -1291,6 +1312,26 @@ class ContainerAPITest extends APISpec {
             .verifyComplete()
     }
 
+    def "List blobs hier options maxResults by page"() {
```
Comment (kasobol-msft) [inline sdk/storage/azure-storage-blob/src/test/java/com/azure/storage/blob/ContainerAPITest.groovy:1315]: typo. hier

File: sdk/storage/azure-storage-blob/src/test/java/com/azure/storage/blob/ContainerAPITest.groovy [hunk 4]
```diff
@@ -911,6 +914,25 @@ class ContainerAPITest extends APISpec {
...
+        def copyName = "c" + generateBlobName()
+        def metadataName = "m" + generateBlobName()
+        def tagsName = "t" + generateBlobName()
+        def uncommittedName = "u" + generateBlobName()
+        setupListBlobsTest(normalName, copyName, metadataName, tagsName, uncommittedName)
+
+        expect: "Get first page of blob listings (sync and async)"
+        cc.listBlobs(options, null).iterableByPage(PAGE_SIZE).iterator().next().getValue().size() == PAGE_SIZE
+        StepVerifier.create(ccAsync.listBlobs(options).byPage(PAGE_SIZE).limitRequest(1))
+            .assertNext({ assert it.getValue().size() == PAGE_SIZE })
```
Comment (kasobol-msft) [inline sdk/storage/azure-storage-blob/src/test/java/com/azure/storage/blob/ContainerAPITest.groovy:932]: should we validate that subsequent pages also have PAGE_SIZE size?

File: sdk/storage/azure-storage-common/src/main/java/com/azure/storage/common/implementation/StoragePagedFlux.java [hunk 5]
```diff
@@ -0,0 +1,38 @@
...
+        super(firstPageRetriever);
+    }
+
+    public static <T> PagedFlux<T> create(Function<Integer, Mono<PagedResponse<T>>> firstPageRetriever,
+        BiFunction<String, Integer, Mono<PagedResponse<T>>> nextPageRetriever) {
+        return PagedFlux.create(() -> (continuationToken, pageSize) ->
+            continuationToken == null
+                ? firstPageRetriever.apply(pageSize).flux()
+                : nextPageRetriever.apply(continuationToken, pageSize).flux());
+    }
```
Comment (kasobol-msft) [inline sdk/storage/azure-storage-common/src/main/java/com/azure/storage/common/implementation/StoragePagedFlux.java:37]: shouldn't this go to core ? @alzimmermsft

File: sdk/storage/azure-storage-file-datalake/src/main/java/com/azure/storage/file/datalake/DataLakeServiceAsyncClient.java [hunk 6]
```diff
@@ -284,12 +285,18 @@ public String getAccountUrl() {
...
-        /* Note: pageSize is not passed in as a parameter since the underlying implementation of listBlobContainers
-           does not use the pageSize parameter. Passing it in will have no effect. */
-        return PagedFlux.create(() -> (continuationToken, pageSize) -> {
-            Flux<PagedResponse<BlobContainerItem>> flux = (continuationToken == null)
-                ? inputPagedFlux.byPage()
-                : inputPagedFlux.byPage(continuationToken);
+        return StoragePagedFlux.create(() -> (continuationToken, pageSize) -> {
+            Flux<PagedResponse<BlobContainerItem>> flux;
+            if (continuationToken != null && pageSize != null) {
+                flux = inputPagedFlux.byPage(continuationToken, pageSize);
```
Comment (kasobol-msft) [inline sdk/storage/azure-storage-file-datalake/src/main/java/com/azure/storage/file/datalake/DataLakeServiceAsyncClient.java:291]: isn't `byPage` smart enough to deal with optional parameters ?

File: sdk/storage/azure-storage-common/src/main/java/com/azure/storage/common/implementation/StoragePagedFlux.java [hunk 7]
```diff
@@ -0,0 +1,38 @@
...
+ *
+ * @param <T> The type of items in a {@link PagedResponse}
+ */
+public class StoragePagedFlux<T> extends PagedFlux<T> {
+
+    public StoragePagedFlux(Supplier<Mono<PagedResponse<T>>> firstPageRetriever) {
+        super(firstPageRetriever);
+    }
+
+    public static <T> PagedFlux<T> create(Function<Integer, Mono<PagedResponse<T>>> firstPageRetriever,
```
Comment (alzimmermsft) [inline sdk/storage/azure-storage-common/src/main/java/com/azure/storage/common/implementation/StoragePagedFlux.java:31]: This throws if pageSize is less than or equal to 0 right?

File: sdk/storage/azure-storage-blob/src/main/java/com/azure/storage/blob/BlobServiceAsyncClient.java [hunk 8]
```diff
@@ -384,16 +396,24 @@ public String getAccountUrl() {
 
     PagedFlux<TaggedBlobItem> findBlobsByTags(FindBlobsOptions options, Duration timeout) {
         throwOnAnonymousAccess();
-        return new PagedFlux<>(
-            () -> withContext(context -> this.findBlobsByTags(options, null, timeout, context)),
-            marker -> withContext(context -> this.findBlobsByTags(options, marker, timeout, context)));
+        StorageImplUtils.assertNotNull("options", options);
```
Comment (alzimmermsft) [inline sdk/storage/azure-storage-blob/src/main/java/com/azure/storage/blob/BlobServiceAsyncClient.java:399]: Is there a reason why `FindBlobsOptions` can no longer be null? Or did this throw an NPE if null previously and is being triggered sooner?

File: sdk/storage/azure-storage-common/src/main/java/com/azure/storage/common/implementation/StoragePagedFlux.java (hunk 5 above)
Comment (alzimmermsft) [reply sdk/storage/azure-storage-common/src/main/java/com/azure/storage/common/implementation/StoragePagedFlux.java:37]: This would be a good constructor to add into PagedFlux, right now it has the following:

```java
public PagedFlux(Supplier<Mono<PagedResponse<T>>> firstPageRetriever,
        Function<String, Mono<PagedResponse<T>>> nextPageRetriever) {
        this(() -> (continuationToken, pageSize) -> continuationToken == null
            ? firstPageRetriever.get().flux()
            : nextPageRetriever.apply(continuationToken).flux(), true);
    }
```

File: sdk/storage/azure-storage-blob/src/main/java/com/azure/storage/blob/BlobContainerAsyncClient.java (hunk 1 above)
Comment (rickle-msft) [reply sdk/storage/azure-storage-blob/src/main/java/com/azure/storage/blob/BlobContainerAsyncClient.java:1002]: Discussed offline, but I think keeping both is fine because this is specific to the sync case. If the customer sets a value using iterableByPage, it'll overwrite the one from the options, but if they call iterableByPage() with no arg, it'll fall back to the options

File: sdk/storage/azure-storage-file-datalake/src/main/java/com/azure/storage/file/datalake/DataLakeServiceAsyncClient.java (hunk 6 above)
Comment (rickle-msft) [reply sdk/storage/azure-storage-file-datalake/src/main/java/com/azure/storage/file/datalake/DataLakeServiceAsyncClient.java:291]: No. If you pass a null continuationToken, it short circuits and returns an empty flux. We need to specifically use the overload which matches the values we have

File: sdk/storage/azure-storage-blob/src/test/java/com/azure/storage/blob/ContainerAPITest.groovy (hunk 3 above)
Comment (rickle-msft) [reply sdk/storage/azure-storage-blob/src/test/java/com/azure/storage/blob/ContainerAPITest.groovy:1315]: I don' think this is a typo? This is how all the other hierarchical listing tests are prefixed.

File: sdk/storage/azure-storage-common/src/main/java/com/azure/storage/common/implementation/StoragePagedFlux.java (hunk 7 above)
Comment (rickle-msft) [reply sdk/storage/azure-storage-common/src/main/java/com/azure/storage/common/implementation/StoragePagedFlux.java:31]: It doesn't currently, but I can update it so it does

File: sdk/storage/azure-storage-blob/src/main/java/com/azure/storage/blob/BlobServiceAsyncClient.java (hunk 8 above)
Comment (rickle-msft) [reply sdk/storage/azure-storage-blob/src/main/java/com/azure/storage/blob/BlobServiceAsyncClient.java:399]: Correct. It'll validate when we call the inner overload of findBlobsByTags anyway, but since we will set the maxResults on the options here, I wanted to assert that it wasn't null just a step earlier.

File: sdk/storage/azure-storage-blob/src/main/java/com/azure/storage/blob/BlobServiceAsyncClient.java (hunk 2 above)
Comment (rickle-msft) [reply sdk/storage/azure-storage-blob/src/main/java/com/azure/storage/blob/BlobServiceAsyncClient.java]: Fixed

File: sdk/storage/azure-storage-common/src/main/java/com/azure/storage/common/implementation/StoragePagedFlux.java (hunk 5 above)
Comment (rickle-msft) [reply sdk/storage/azure-storage-common/src/main/java/com/azure/storage/common/implementation/StoragePagedFlux.java]: @alzimmermsft If you'd like me to add it to core directly, let me know. And point more towards any samples or tests I'd need to update

Comment (alzimmermsft) [reply sdk/storage/azure-storage-common/src/main/java/com/azure/storage/common/implementation/StoragePagedFlux.java]: Given that this is in implementation which is only share between Storage libraries, to unblock the issue I think this can stay and then once Core adds the new APIs it can be transitioned over.

File: sdk/storage/azure-storage-blob/src/test/java/com/azure/storage/blob/ContainerAPITest.groovy (hunk 3 above)
Comment (kasobol-msft) [reply sdk/storage/azure-storage-blob/src/test/java/com/azure/storage/blob/ContainerAPITest.groovy:1315]: i thought it's "tier" , maybe expanding hier would help.

File: sdk/storage/azure-storage-common/src/main/java/com/azure/storage/common/implementation/StoragePagedFlux.java (hunk 5 above)
Comment (kasobol-msft) [reply sdk/storage/azure-storage-common/src/main/java/com/azure/storage/common/implementation/StoragePagedFlux.java]: I'd rather add this to core directly and depend on unreleased core until next release cycle. IMO it doesn't make sense to create this type and remove it iteration later (think classnotfoundexceptions if someone doesn't get dependnecy versions right...). Unless this issue need some hotfix release (but I think we're not there).

File: sdk/storage/azure-storage-blob/src/test/java/com/azure/storage/blob/ContainerAPITest.groovy (hunk 3 above)
Comment (rickle-msft) [reply sdk/storage/azure-storage-blob/src/test/java/com/azure/storage/blob/ContainerAPITest.groovy:1315]: For some of them, expanding hierarchy makes the test name too long so that the resulting container names are invalid

File: sdk/storage/azure-storage-blob/src/test/java/com/azure/storage/blob/ContainerAPITest.groovy (hunk 4 above)
Comment (rickle-msft) [reply sdk/storage/azure-storage-blob/src/test/java/com/azure/storage/blob/ContainerAPITest.groovy:934]: Updated

File: sdk/storage/azure-storage-blob/src/main/java/com/azure/storage/blob/BlobContainerAsyncClient.java (hunk 1 above)
Comment (gapra-msft) [reply sdk/storage/azure-storage-blob/src/main/java/com/azure/storage/blob/BlobContainerAsyncClient.java:1005]: Should we put this in docs?

File: sdk/storage/azure-storage-blob/src/main/java/com/azure/storage/blob/BlobServiceAsyncClient.java [hunk 9]
```diff
@@ -384,16 +399,30 @@ public String getAccountUrl() {
...
+        BiFunction<String, Integer, Mono<PagedResponse<TaggedBlobItem>>> func =
+            (marker, pageSize) -> {
+                options.setMaxResultsPerPage(pageSize);
```
Comment (gapra-msft) [inline sdk/storage/azure-storage-blob/src/main/java/com/azure/storage/blob/BlobServiceAsyncClient.java:405]: Should we create a new options here?

Comment (rickle-msft) [reply sdk/storage/azure-storage-blob/src/main/java/com/azure/storage/blob/BlobServiceAsyncClient.java:405]: Good catch. Updated.

**Review by gapra-msft — APPROVED** [review]

File: sdk/storage/azure-storage-common/src/main/java/com/azure/storage/common/implementation/StoragePagedFlux.java (hunk 5 above)
Comment (alzimmermsft) [reply sdk/storage/azure-storage-common/src/main/java/com/azure/storage/common/implementation/StoragePagedFlux.java]: This should cover the requirements here: https://github.com/Azure/azure-sdk-for-java/pull/20164

File: sdk/storage/azure-storage-blob/src/main/java/com/azure/storage/blob/BlobContainerAsyncClient.java [hunk 10]
```diff
@@ -837,25 +838,40 @@ public String getEncryptionScope() {
...
+            (marker, pageSize) -> {
+                ListBlobsOptions finalOptions;
+                if (pageSize != null) {
+                    if (options == null) {
+                        finalOptions = new ListBlobsOptions().setMaxResultsPerPage(pageSize);
+                    } else {
+                        finalOptions = new ListBlobsOptions()
+                            .setMaxResultsPerPage(pageSize)
+                            .setPrefix(options.getPrefix())
+                            .setDetails(options.getDetails());
```
Comment (kasobol-msft) [inline sdk/storage/azure-storage-blob/src/main/java/com/azure/storage/blob/BlobContainerAsyncClient.java:850]: I wonder if we should make a copy earlier in the call stack. might simplify some of this and we won't be worried about updating many places if more parameters or branches are added.

**Review by kasobol-msft — APPROVED** [review]

File: sdk/storage/azure-storage-blob/pom.xml [hunk 11]
```diff
@@ -55,12 +55,12 @@
     <dependency>
       <groupId>com.azure</groupId>
       <artifactId>azure-core</artifactId>
-      <version>1.14.1</version> <!-- {x-version-update;com.azure:azure-core;dependency} -->
+      <version>1.15.0-beta.1</version> <!-- {x-version-update;com.azure:azure-core;current} -->
```
Comment (alzimmermsft) [inline sdk/storage/azure-storage-blob/pom.xml:58]: We should use the [unreleased_](https://github.com/Azure/azure-sdk-for-java/blob/master/eng/versioning/version_client.txt#L222) instead as they have additional guards preventing libraries from being shipped with them. Basically, it catches scenarios where `current` dependencies would allow shipping but that dependency version hasn't been released.

**Review by alzimmermsft — APPROVED** [review]
