### PR TITLE
Fixes rules update.

### LINKED ISSUE #15723: Fix Service Bus subscription rule update
Repro Steps
* Update a subscription rule

Expected:
* It works

Actual
* It fails to deserialize rule.

### PR DESCRIPTION
**Pull request by conniey**
* Fixes serialization bug for creating and deserializing rules.
* Adds tests for serialization.

Fixes #15723

### CODE REVIEW

File: sdk/servicebus/azure-messaging-servicebus/src/main/java/com/azure/messaging/servicebus/implementation/ServiceBusManagementSerializer.java [hunk 1]
```diff
@@ -35,21 +39,39 @@
...
+
+        if (!CreateRuleBody.class.equals(clazz)) {
+            return replaced;
         }
 
-        return contents;
+        // This hack is here because RuleFilter and RuleAction type="Foo" should have a namespace like n0:type="Foo".
+        final Matcher filterType = FILTER_ACTION_PATTERN.matcher(replaced);
+        if (filterType.find()) {
+            return filterType.replaceAll("<$1 xmlns:ns0=\"http://www.w3.org/2001/XMLSchema-instance\" ns0:type=");
```
Comment (YijunXieMS) [inline sdk/servicebus/azure-messaging-servicebus/src/main/java/com/azure/messaging/servicebus/implementation/ServiceBusManagementSerializer.java:70]: Rules might also have ns1 in some cases.

Comment (conniey) [reply sdk/servicebus/azure-messaging-servicebus/src/main/java/com/azure/messaging/servicebus/implementation/ServiceBusManagementSerializer.java:70]: Do you know when? I couldn't find an example.

Comment (YijunXieMS) [reply sdk/servicebus/azure-messaging-servicebus/src/main/java/com/azure/messaging/servicebus/implementation/ServiceBusManagementSerializer.java:70]: This is a Python generated XML that has both ns0 and ns1. Disregard this comment if Java generates differently without ns1.
In the following file, "ns0" doesn't hurt. "ns1" hurts.

```xml
<ns0:entry xmlns:ns0="http://www.w3.org/2005/Atom" xmlns:ns1="http://schemas.microsoft.com/netservices/2010/10/servicebus/connect" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<ns0:content type="application/xml">
		<ns1:RuleDescription>
			<ns1:Filter xsi:type="SqlFilter">
				<ns1:CompatibilityLevel>20</ns1:CompatibilityLevel>
				<ns1:RequiresPreprocessing>true</ns1:RequiresPreprocessing>
			</ns1:Filter>
			<ns1:Action xsi:type="EmptyRuleAction"/>
			<ns1:Name>rule1</ns1:Name>
		</ns1:RuleDescription>
	</ns0:content>
</ns0:entry>

```

Comment (hemanttanwar) [reply sdk/servicebus/azure-messaging-servicebus/src/main/java/com/azure/messaging/servicebus/implementation/ServiceBusManagementSerializer.java:70]: Normally validity of XML can be verified at generation time, I am not sure if generator are doing  that.

File: sdk/servicebus/azure-messaging-servicebus/src/main/java/com/azure/messaging/servicebus/implementation/ServiceBusManagementSerializer.java [hunk 2]
```diff
@@ -35,21 +39,39 @@
...
-            if (matcher.find()) {
-                final String namespace = matcher.group("namespace");
-                return contents
-                    .replaceAll(namespace + ":", "")
-                    .replace("xmlns:" + namespace + "=", "xmlns=");
-            }
+        final Matcher namespaceMatcher = NAMESPACE_PATTERN.matcher(contents);
+        if (!namespaceMatcher.find()) {
+            logger.info("Could not find {} in {}", NAMESPACE_PATTERN.pattern(), contents);
+            return contents;
```
Comment (hemanttanwar) [inline sdk/servicebus/azure-messaging-servicebus/src/main/java/com/azure/messaging/servicebus/implementation/ServiceBusManagementSerializer.java:55]: If we could not find namespace pattern , wouldn't this be a error or warning ?

**Review by hemanttanwar — APPROVED** [review]
LGTM . I just had one comment

**Comment by YijunXieMS** [comment]
A separate discussion. SqlRuleFilter and SqlRuleAction have parameters in other languages. But I don't see them in Java.

File: sdk/servicebus/azure-messaging-servicebus/src/main/java/com/azure/messaging/servicebus/implementation/ServiceBusManagementSerializer.java (hunk 1 above)
Comment (conniey) [reply sdk/servicebus/azure-messaging-servicebus/src/main/java/com/azure/messaging/servicebus/implementation/ServiceBusManagementSerializer.java:70]: The XML generated by Jackson is valid. It's the service side that is fickle about what XML it likes to consume, that's why we're doing all these hacks.

I verified that we aren't generating multiple namespaces. The reason for this is because we use a global xml namespace, so we don't need n0.

**Comment by conniey** [comment]
>A separate discussion. SqlRuleFilter and SqlRuleAction have parameters in other languages. But I don't see them in Java.

We do have parameters exposed. https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/servicebus/azure-messaging-servicebus/src/main/java/com/azure/messaging/servicebus/administration/models/SqlRuleAction.java#L81

**Comment by YijunXieMS** [comment]
> > A separate discussion. SqlRuleFilter and SqlRuleAction have parameters in other languages. But I don't see them in Java.
> 
> We do have parameters exposed. https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/servicebus/azure-messaging-servicebus/src/main/java/com/azure/messaging/servicebus/administration/models/SqlRuleAction.java#L81



> > A separate discussion. SqlRuleFilter and SqlRuleAction have parameters in other languages. But I don't see them in Java.
> 
> We do have parameters exposed. https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/servicebus/azure-messaging-servicebus/src/main/java/com/azure/messaging/servicebus/administration/models/SqlRuleAction.java#L81

It's called "parameters" in other languages. Do we need to change the method name to getParameters()?

**Review by YijunXieMS — APPROVED** [review]
