### PR TITLE
[AppConfig] Fixed bugs where FeatureFlag prefix should always has prefix when call setKey()

### LINKED ISSUE #33332: [BUG] App Config SDK setKey result in invalid Key name for feature flags
**Describe the bug**
When creating a feature flag with the SDK, using the set key method results in the removal of the prefix `.appconfig.featureflag/` that is required for all feature flags.

***Exception or Stack Trace***
N/A

**To Reproduce**
N/A

***Code Snippet***
```java
FeatureFlagConfigurationSetting newSetting = new FeatureFlagConfigurationSetting("FeatureId2", false);
newSetting.setKey("UpdatedKey"); 
client.addConfigurationSetting(newSetting);
```

This make the key `UpdatedKey` not `.appconfig.featureflag/UpdatedKey`, which results in the feature flag not showing up in the Feature Flag blade in the App Configuration Portal.

**Expected behavior**
The key name should always have the `.appconfig.featureflag/` for feature flags.

**Screenshots**
N/A

**Setup (please complete the following information):**
 - OS: Windows 11
 - IDE: Eclipse
 - Library/Libraries: azure-data-appconfiguraiton
 - Java version: 17 
 - App Server/Environment: Tomcat
 - Frameworks: Spring

### PR DESCRIPTION
**Pull request by mssfang**
Fixed `FeatureFlagConfigurationSetting`'s `setKey()` which should always add the feature flag prefix `.appconfig.featureflag/` before the input key

fixes: https://github.com/Azure/azure-sdk-for-java/issues/33332

### CODE REVIEW

File: sdk/appconfiguration/azure-data-appconfiguration/src/main/java/com/azure/data/appconfiguration/models/FeatureFlagConfigurationSetting.java [hunk 1]
```diff
@@ -136,7 +136,7 @@ public String getValue() {
      */
     @Override
     public FeatureFlagConfigurationSetting setKey(String key) {
-        super.setKey(key);
+        super.setKey(KEY_PREFIX + key);
```
Comment (alzimmermsft) [inline sdk/appconfiguration/azure-data-appconfiguration/src/main/java/com/azure/data/appconfiguration/models/FeatureFlagConfigurationSetting.java:139]: This should be doing the same check that is happening in the deserialization helper. Customers who were already passing the `key` prefixed with `.appconfig.featureflag/` will now have `.appconfig.featureflag/.appconfig.featureflag/something` with this change.

Additionally, handling the prefix check here will mean that there is not change needed in the deserialization helper.

**Review by alzimmermsft — CHANGES_REQUESTED** [review]

File: sdk/appconfiguration/azure-data-appconfiguration/src/main/java/com/azure/data/appconfiguration/models/FeatureFlagConfigurationSetting.java [hunk 2]
```diff
@@ -136,7 +136,11 @@ public String getValue() {
      */
     @Override
     public FeatureFlagConfigurationSetting setKey(String key) {
-        super.setKey(key);
+        if (key != null && key.startsWith(FeatureFlagConfigurationSetting.KEY_PREFIX)) {
```
Comment (alzimmermsft) [inline sdk/appconfiguration/azure-data-appconfiguration/src/main/java/com/azure/data/appconfiguration/models/FeatureFlagConfigurationSetting.java:139]: Few more thoughts:

- Should a null `key` throw an error?
- Instead of substring when the `key` starts with `KEY_PREFIX` we should instead add the `KEY_PREFIX` if it doesn't start with the `KEY_PREFIX`.

```java
if (key != null && !key.startsWith(KEY_PREFIX)) {
    super.setKey(KEY_PREFIX + key);
} else {
    super.setKey(key);
}

return this;
```

Comment (mssfang) [reply sdk/appconfiguration/azure-data-appconfiguration/src/main/java/com/azure/data/appconfiguration/models/FeatureFlagConfigurationSetting.java:139]: `key` is required and cannot be null. But we don't do client-side validation

**Review by alzimmermsft — APPROVED** [review]
