### PR TITLE
Identity adfs support aug 2020

### LINKED ISSUE #14183: [FEATURE REQ] Add ADFS Identity Provider Support to Interactive Browser Credential
Azure Stack backed with ADFS fails to authenticate with Interactive Browser Credential.
The support to authenticate against ADFS authorities needs to be added to Interactive Browser Credential.

### PR DESCRIPTION
**Pull request by g2vinay**
Fixes #14183 #14188  #14653 , #13460 

This PR adds ADFS Authorities support to Identity SDK.
Also upgrades the MSAL version in the repo to 1.6.2 everywhere.

### CODE REVIEW

File: sdk/identity/azure-identity/src/main/java/com/azure/identity/implementation/IdentityClient.java [hunk 1]
```diff
@@ -640,38 +639,20 @@ private HttpPipeline setupPipeline(HttpClient httpClient) {
...
-                            clientId,
-                            redirectUri.toString(),
-                            UUID.randomUUID(),
-                            String.join(" ", request.getScopes()));
-                } catch (URISyntaxException e) {
-                    return server.dispose().then(Mono.error(e));
-                }
+        URI redirectUri;
+        try {
+            redirectUri = new URI(String.format("http://localhost:%s", port));
```
Comment (srnagar) [inline sdk/identity/azure-identity/src/main/java/com/azure/identity/implementation/IdentityClient.java:644]: Use string constants.

File: sdk/identity/azure-identity/src/main/java/com/azure/identity/implementation/IdentityClient.java [hunk 2]
```diff
@@ -640,38 +639,20 @@ private HttpPipeline setupPipeline(HttpClient httpClient) {
...
+        } catch (URISyntaxException e) {
+            return Mono.error(logger.logExceptionAsError(new RuntimeException(e)));
+        }
+        InteractiveRequestParameters parameters = InteractiveRequestParameters.builder(redirectUri)
+                                                     .scopes(new HashSet<>(request.getScopes()))
+                                                     .build();
+        Mono<IAuthenticationResult> acquireToken = publicClientApplicationAccessor.getValue()
+                               .flatMap(pc -> Mono.fromFuture(() -> pc.acquireToken(parameters)));
```
Comment (srnagar) [inline sdk/identity/azure-identity/src/main/java/com/azure/identity/implementation/IdentityClient.java:652]: Do you need to use `fromFuture`? Can it just be:
```java
.flatMap(pc -> pc.acquireToken(parameters));
```

Comment (g2vinay) [reply sdk/identity/azure-identity/src/main/java/com/azure/identity/implementation/IdentityClient.java:653]: its needed, because we get back a CompletableFuture.
