### PR TITLE
Tracing: update semconv to v1.23.1

### LINKED ISSUE #37440: Tracing: Adopt OpenTelemetry HTTP semconv 1.23.1
Update HTTP attributes to comply with HTTP semconv 1.23.1  (declares HTTP as stable):
1.  Rename attributes according to [docs](https://github.com/lmolkova/semantic-conventions/blob/2532c4146481a27199bf14d9dd5edf139a841097/docs/cloud-providers/azure-sdk.md#http-client):
    - `http.method` -> `http.request.method`
    - `http.status_code` -> `http.response.status_code`
    - `net.peer.name` -> `server.address`
    - `net.peer.port` -> `server.port`
    - `http.url` -> `url.full`
    - `http.user_agent` -> remove
2. Add new attributes:
    - `error.type` - some error-code or a full exception name if exception happens. Also includes status code (as string) for responses we consider to be an error. Maybe we can steal something from .NET - https://github.com/dotnet/runtime/blob/main/src/libraries/System.Net.Http/src/System/Net/Http/Metrics/MetricsHandler.cs#L157
    - `http.request.resend_count` - try count
3. Update HTTP span names according to the new conventions 
4. Check if there is anything else in [otel semconv](https://github.com/open-telemetry/semantic-conventions/blob/main/docs/http/http-spans.md) that needs attention

### PR DESCRIPTION
**Pull request by lmolkova**
Fixes #37440 and #37441

### CODE REVIEW

File: sdk/core/azure-core-tracing-opentelemetry/src/main/java/com/azure/core/tracing/opentelemetry/OpenTelemetryUtils.java [hunk 1]
```diff
@@ -140,16 +140,23 @@ static void addAttribute(Span span, String key, Object value, OpenTelemetrySchem
...
         }
 
-        // "success" is needed for back compat with older Event Hubs and Service Bus, don't use it.
-        if (statusMessage == null || "success".equals(statusMessage)) {
+        if (statusMessage == null && throwable == null) {
             return span;
         }
 
+        span.setAttribute(ERROR_TYPE_ATTRIBUTE,
+            statusMessage != null ? statusMessage : throwable.getClass().getName());
```
Comment (trask) [inline sdk/core/azure-core-tracing-opentelemetry/src/main/java/com/azure/core/tracing/opentelemetry/OpenTelemetryUtils.java:153]: just checking that `statusMessage` is low-cardinality?

also, if you want to copy the instrumentation-api logic, we do a bit of unwrapping of the throwable to get a slightly nicer / more stable name: https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/instrumentation-api/src/main/java/io/opentelemetry/instrumentation/api/instrumenter/DefaultErrorCauseExtractor.java

File: sdk/core/azure-core/src/main/java/com/azure/core/implementation/http/policy/InstrumentationPolicy.java [hunk 2]
```diff
@@ -122,16 +137,16 @@ private void addPostSamplingAttributes(Context span, HttpRequest request) {
...
             int statusCode = response.getStatusCode();
-            tracer.setAttribute(HTTP_STATUS_CODE, statusCode, span);
+            tracer.setAttribute(HTTP_RESPONSE_STATUS_CODE, statusCode, span);
             String requestId = response.getHeaderValue(SERVICE_REQUEST_ID_HEADER);
             if (requestId != null) {
                 tracer.setAttribute(SERVICE_REQUEST_ID_ATTRIBUTE, requestId, span);
             }
 
-            tracer.end((statusCode >= 400) ? "error" : null, null, span);
+            tracer.end((statusCode >= 400) ? String.valueOf(statusCode) : null, null, span);
```
Comment (trask) [inline sdk/core/azure-core/src/main/java/com/azure/core/implementation/http/policy/InstrumentationPolicy.java:146]: I didn't follow if it's intentional to fall through and call tracer.end() again below?
```suggestion
            tracer.end((statusCode >= 400) ? String.valueOf(statusCode) : null, null, span);
            return;
```

File: sdk/core/azure-core-tracing-opentelemetry/src/main/java/com/azure/core/tracing/opentelemetry/OpenTelemetrySchemaVersion.java [hunk 3]
```diff
@@ -17,13 +17,13 @@ public class OpenTelemetrySchemaVersion extends ExpandableStringEnum<OpenTelemet
     /**
      * 1.12.0 version.
```
Comment (alzimmermsft) [inline sdk/core/azure-core-tracing-opentelemetry/src/main/java/com/azure/core/tracing/opentelemetry/OpenTelemetrySchemaVersion.java:18]: nit: wrong version

File: sdk/core/azure-core-metrics-opentelemetry/src/main/java/com/azure/core/metrics/opentelemetry/OpenTelemetryAttributes.java [hunk 4]
```diff
@@ -22,10 +22,10 @@ private static Map<String, String> getMappings() {
         Map<String, String> mappings = new HashMap<>();
         // messaging mapping, attributes are defined in com.azure.core.amqp.implementation.ClientConstants and in EventHubs, ServiceBus
         // metric helpers
-        mappings.put("status", "otel.status_code");
+        mappings.put("status", "error.type");
```
Comment (alzimmermsft) [inline sdk/core/azure-core-metrics-opentelemetry/src/main/java/com/azure/core/metrics/opentelemetry/OpenTelemetryAttributes.java:25]: Would we ever enable the ability for users to specify which convention so use? This would allow the SDKs to match their environment rather than following whatever the latest specification the SDKs are using.

File: sdk/core/azure-core/src/main/java/com/azure/core/implementation/http/policy/InstrumentationPolicy.java [hunk 5]
```diff
@@ -107,10 +114,18 @@ private Context startSpan(HttpPipelineCallContext azContext) {
...
+            port = url.getDefaultPort();
+        }
+        return port;
+    }
+
     private void addPostSamplingAttributes(Context span, HttpRequest request) {
-        String userAgent = request.getHeaders().getValue(HttpHeaderName.USER_AGENT);
-        if (!CoreUtils.isNullOrEmpty(userAgent)) {
-            tracer.setAttribute(HTTP_USER_AGENT, userAgent, span);
+        Object rawRetryCount = span.getData(RETRY_COUNT_CONTEXT).orElse(null);
```
Comment (alzimmermsft) [inline sdk/core/azure-core/src/main/java/com/azure/core/implementation/http/policy/InstrumentationPolicy.java:126]: Comment for myself: Investigate adding metadata to `HttpRequest` where well-known values, such as retry count, can be propagated without the "magic" of Context.

Comment (lmolkova) [reply sdk/core/azure-core/src/main/java/com/azure/core/implementation/http/policy/InstrumentationPolicy.java:126]: common to both of us: try count and maybe other things like user-agent or x-ms-client-request-id variations are only necessary as logging scope - perhaps we don't need to know what's in it but can work with it as it was a bag of key-value-pairs

File: sdk/core/azure-core-metrics-opentelemetry/src/main/java/com/azure/core/metrics/opentelemetry/OpenTelemetryAttributes.java (hunk 4 above)
Comment (lmolkova) [reply sdk/core/azure-core-metrics-opentelemetry/src/main/java/com/azure/core/metrics/opentelemetry/OpenTelemetryAttributes.java:25]: That was the plan, but I don't think we will now.
The semconv version is for us to specify which version we're using. (e.g. `error.type` is defined in version 1.23.0).

If a new attribute `error.foo` is introduced in 1.42.0 we won't start reporting it until our code is updated. And then we'd just report version 1.42.

It's totally fine for stable attributes, and is only problematic if otel has any breaking changes.
We'll keep unstable attributes behind the feature flag (not done yet, but the whole package is still in beta) and will keep breaking them until they stabilize.

File: sdk/core/azure-core/src/main/java/com/azure/core/implementation/http/policy/InstrumentationPolicy.java (hunk 2 above)
Comment (lmolkova) [reply sdk/core/azure-core/src/main/java/com/azure/core/implementation/http/policy/InstrumentationPolicy.java:146]: great catch, thanks!

File: sdk/core/azure-core-tracing-opentelemetry/src/main/java/com/azure/core/tracing/opentelemetry/OpenTelemetryUtils.java (hunk 1 above)
Comment (lmolkova) [reply sdk/core/azure-core-tracing-opentelemetry/src/main/java/com/azure/core/tracing/opentelemetry/OpenTelemetryUtils.java:145]: yes, `statusMessage`  has low-cardinality - I added a comment to javadoc.
There is nothing that enforces it for traces though.

It's almost impossible to misuse it for metrics since we promote creating attributes and caching them in advance (vs creating on measurement).

**Comment by lmolkova** [comment]
@alzimmermsft @trask could you please take another look?

**Review by alzimmermsft — APPROVED** [review]
Approved from a non-telemetry perspective

File: sdk/core/azure-core/src/main/java/com/azure/core/implementation/http/policy/InstrumentationPolicy.java [hunk 6]
```diff
@@ -18,16 +18,21 @@
...
-    private static final String HTTP_USER_AGENT = "http.user_agent";
-    private static final String HTTP_METHOD = "http.method";
-    private static final String HTTP_URL = "http.url";
-    private static final String HTTP_STATUS_CODE = "http.status_code";
+    private static final String HTTP_REQUEST_METHOD = "http.request.method";
+    private static final String HTTP_RESEND_COUNT = "http.request.resend_count";
+    private static final String URL_FULL = "url.full";
+    private static final String SERVER_ADDRESS = "server.address";
+    private static final String SERVER_PORT = "server.port";
+    private static final String HTTP_RESPONSE_STATUS_CODE = "http.response.status_code";
```
Comment (trask) [inline sdk/core/azure-core/src/main/java/com/azure/core/implementation/http/policy/InstrumentationPolicy.java:32]: I hadn't noticed this before that OpenTelemetry semconv is natively baked into `azure-core`

**Review by trask — COMMENTED** [review]
we won't have support for stable semconv in Application Insights Java agent until mid-Jan

this isn't a problem for semconv changes in `azure-core-tracing-opentelemetry` since we inject specific compatible version at runtime, but it may be a problem for semconv changes in `azure-core`

File: sdk/core/azure-core/src/main/java/com/azure/core/implementation/http/policy/InstrumentationPolicy.java (hunk 6 above)
Comment (lmolkova) [reply sdk/core/azure-core/src/main/java/com/azure/core/implementation/http/policy/InstrumentationPolicy.java:32]: they are! (we still can remap them to something else in the plugin though)

**Comment by lmolkova** [comment]
> we won't have support for stable semconv in Application Insights Java agent until mid-Jan
> 
> this isn't a problem for semconv changes in `azure-core-tracing-opentelemetry` since we inject specific compatible version at runtime, but it may be a problem for semconv changes in `azure-core`

great point!

So let me change this approach to:
- keep (for now) old attribute names in azure-core
- add mappings to the plugin instead
- merge this PR
- update plugin version in otel agent
- let it settle for a month or two then update core and remove mappings as a final cleanup before we declare HTTP tracing stable

**Review by trask — APPROVED** [review]
