### PR TITLE
Make Cosmos logical spans CLIENT and current

### LINKED ISSUE #23032: [BUG] CosmosDb spans are INTERNAL and not parents of underlying HTTP spans
**Describe the bug**
1. CosmosDB creates public API spans, auto-instrumentation (with otel agent or app insights agent) tracks underlying HTTP calls.
Underlying HTTP calls (there is no way to suppress them currently) are siblings (not children) of Cosmos spans and are confusing and misleading. It's also not clear if they are coming from CosmosDb or user app. To, at least, reduce the confusion, we'd like to make them children of Cosmos calls. 

2. Spans are INTERNAL, which breaks OTel expectations and means Azure Monitor can't show cosmos on the application map 

**To Reproduce**
1) use cosmosdb sample app
2) [add and configure](https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-standalone-config#auto-collected-azure-sdk-telemetry-preview) appinsights agent 

***Code Snippet***
Add the code snippet that causes the issue.

**Expected behavior**
http spans are children of cosmos spans (in future, we may want them to be suppressed, but OpenTelemtry does not support it at the moment).

Spans are CLIENT.

**Screenshots**
image

[transaction link](https://ms.portal.azure.com/#blade/AppInsightsExtension/DetailsV2Blade/DataModel/%7B%22eventId%22:%2231cede6c-e577-11eb-b561-501ac5103a4d%22,%22timestamp%22:%222021-07-15T14:15:47.747Z%22%7D/ComponentId/%7B%22Name%22:%22spring-boot-1623527233948%22,%22ResourceGroup%22:%22limolkova%22,%22SubscriptionId%22:%22faa080af-c1d8-40ad-9cce-e1a450ca5b57%22%7D)

**Setup (please complete the following information):**
 - OS: windows
 - IDE: IntelliJ
 - Library/Libraries: com.azure:azure-core:1.17.0, com.azure:azure-cosmos:4.17.0

**Additional context**
CosmosDB can't fix it without support in azure-core to create spans **and make them current, and allow to specify CLIENT kind**. So this needs to be addressed first.

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

### PR DESCRIPTION
**Pull request by lmolkova**
# Description

Fixes #23032

- Runs hot path of Mono or Flux within current span scope and moves
  - If Reactor instrumentation is enabled in OpenTelemtery, the cold path will run in the same scope as well 
- Makes Cosmos spans CLIENT - it will allow Azure Monitor to build Application Map correctly in direct mode

Note this change does not suppress control HTTP calls yet, just makes them nested under Cosmos spans

Outcome:

first call (with underlying control HTTP call)

image

consequent calls (no nested control call)
image

### CODE REVIEW

File: sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/TracerProvider.java [hunk 1]
```diff
@@ -499,4 +570,52 @@ private void addDiagnosticsOnTracerEvent(CosmosDiagnostics cosmosDiagnostics, Co
         this.addEvent("ClientCfgs", attributes,
             OffsetDateTime.ofInstant(clientSideRequestStatistics.getRequestStartTimeUTC(), ZoneOffset.UTC), context);
     }
+
+    private static void subscribe(Tracer tracer, CoreSubscriber<? super Object> actual) {
+        Context context = actual.currentContext().getOrDefault(REACTOR_TRACING_CONTEXT_KEY, null);
+        if (context != null) {
+            AutoCloseable scope = tracer.makeSpanCurrent(context);
+            try {
+                actual.onSubscribe(Operators.scalarSubscription(actual, DUMMY_VALUE));
```
Comment (simplynaveen20) [inline sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/TracerProvider.java:579]: What is the logic behind this dummy value in subscribe. ?

**Review by simplynaveen20 — COMMENTED** [review]
Any time we have direct calls which is calling http requests for metadata, all those http will show under single e2e span ?, this is only in the case if user explicitly opted to track http calls in tracer ?

**Comment by lmolkova** [comment]
> Any time we have direct call which is calling http requests for metadata, all those http will show under single e2e span ?, this is only in the case if user explicitly opted to track http calls in open telemetry ?

yes, you're right. All HTTP calls will be scoped under the e2e call. With javaagent instrumentation (it's default Azure Monitor story and super-common among all major tracing vendors), http tracing is opt-out, we assume it's on for almost every customer .

File: sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/TracerProvider.java (hunk 1 above)
Comment (lmolkova) [reply sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/TracerProvider.java:579]: it will be ignored- it's this `ignored` value in 
```java
return propagatingFlux
            .flatMap(ignored -> publisher);
```

all magic is done by `AutoCloseable scope = tracer.makeSpanCurrent(context)`

**Review by simplynaveen20 — APPROVED** [review]
LGTM, thank you. Please merge once all ci green

**Review by trask — APPROVED** [review]
nice 👍
