### PR TITLE
No Longer Decoding URL-Encoded Blob Name for EncryptedBlobClient and only Storing Original Name

### LINKED ISSUE #41178: [BUG] Blob Storage Cryptography encode special characters in blob names
**Describe the bug**
We use Azure Blob Storage Cryptography which encodes blob names in `EncryptedBlobClientBuilder.blobName(String blobName)`
https://github.com/Azure/azure-sdk-for-java/blob/d56e1e3f33a9634bbfec24dfe7b0c00dce16b10a/sdk/storage/azure-storage-blob-cryptography/src/main/java/com/azure/storage/blob/specialized/cryptography/EncryptedBlobClientBuilder.java#L597-L598

As you can see there is `Utility.urlEncode()` this is not in the normal `BlobClientBuilder.blobName(String blobName)` (and other clients also)
https://github.com/Azure/azure-sdk-for-java/blob/d56e1e3f33a9634bbfec24dfe7b0c00dce16b10a/sdk/storage/azure-storage-blob/src/main/java/com/azure/storage/blob/BlobClientBuilder.java#L397-L398

So if we create a blob with a name containing `/` e.g. `foo/bar.txt` then this blob is stored as `foo%2Fbar.txt` if we use `EncryptedBlobClientBuilder`. It is stored normally with the `BlobClientBuilder`.

It worked in the previous versions (e.g. 12.25.1) because there was `Utility.urlDecode`  and it was removed in this PR https://github.com/Azure/azure-sdk-for-java/pull/37711

***Exception or Stack Trace***
Add the exception log and stack trace if available

**To Reproduce**
1. Upload encrypted blob with name containing `/` e.g. `foo/bar.txt`
2. The blob name is stored as `foo%bar.txt` instead of `foo/bar.txt`

***Code Snippet***
Add the code snippet that causes the issue.

**Expected behavior**

**Screenshots**
Blob name is stored as is with special characters (mainly with `/`).

**Setup (please complete the following information):**
 - Library/Libraries: com.azure:azure-storage-blob-cryptography:12.25.0
 - Java version: 21

**Additional context**
The fix it replace implementation of `blobName` in `EncryptedBlobClientBuilder` and remove `Utility.urlEncode(Utility.urlDecode())` there.

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

### PR DESCRIPTION
**Pull request by ibrahimrabab**
# Description

resolves #41178

Following similar logic done in PR: https://github.com/Azure/azure-sdk-for-java/pull/37711

### CODE REVIEW

File: sdk/storage/azure-storage-blob-cryptography/src/main/java/com/azure/storage/blob/specialized/cryptography/EncryptedBlobClientBuilder.java [hunk 1]
```diff
@@ -595,8 +595,7 @@ public EncryptedBlobClientBuilder containerName(String containerName) {
      * @throws NullPointerException If {@code blobName} is {@code null}
      */
     public EncryptedBlobClientBuilder blobName(String blobName) {
-        this.blobName = Utility.urlEncode(Utility.urlDecode(Objects.requireNonNull(blobName,
-            "'blobName' cannot be null.")));
+        this.blobName = Objects.requireNonNull(blobName, "'blobName' cannot be null.");
```
Comment (Saljack) [inline sdk/storage/azure-storage-blob-cryptography/src/main/java/com/azure/storage/blob/specialized/cryptography/EncryptedBlobClientBuilder.java:598]: Remove it also from `EncryptedBlobClientBuilder endpoint(String endpoint)`

https://github.com/Azure/azure-sdk-for-java/blob/5f96f6ab2124bb45095670866fb89ff850074cad/sdk/storage/azure-storage-blob-cryptography/src/main/java/com/azure/storage/blob/specialized/cryptography/EncryptedBlobClientBuilder.java#L562

**Comment by Saljack** [comment]
Url encode is mentioned also in javadoc. It should be also removed.
https://github.com/Azure/azure-sdk-for-java/blob/494b294c18596016a8c3beb399c1bf97d70be0f4/sdk/storage/azure-storage-blob-cryptography/src/main/java/com/azure/storage/blob/specialized/cryptography/EncryptedBlobClientBuilder.java#L540
and
https://github.com/Azure/azure-sdk-for-java/blob/494b294c18596016a8c3beb399c1bf97d70be0f4/sdk/storage/azure-storage-blob-cryptography/src/main/java/com/azure/storage/blob/specialized/cryptography/EncryptedBlobClientBuilder.java#L592

`com.azure.storage.common.Utility` is now unused import
https://github.com/Azure/azure-sdk-for-java/blob/494b294c18596016a8c3beb399c1bf97d70be0f4/sdk/storage/azure-storage-blob-cryptography/src/main/java/com/azure/storage/blob/specialized/cryptography/EncryptedBlobClientBuilder.java#L53

**Review by alzimmermsft — APPROVED** [review]
