### PR TITLE
Use Default DNS Resolver when Creating a New HttpClient

### LINKED ISSUE #22618: [BUG] Azure Core slow response with newer versions.
**Describe the bug**
When making requests with azure-core 1.16, to Azure App Configuration requests take 22seconds, compared to the ~1s of older versions.

The can be seen by using azure-data-appconfiguration 1.1.12 and making to requests. The first will take ~22000ms and the ~50ms.

***Exception or Stack Trace***
N/A

**To Reproduce**/***Code Snippet***
```java
public static void main(String[] args) {
        ConfigurationClientBuilder builder = new ConfigurationClientBuilder();
        builder.connectionString(CONNECTION_STRING);
        ConfigurationClient client = builder.buildClient();
        SettingSelector select = new SettingSelector().setKeyFilter("/noResults/*");

        long start = 0;
        
        System.out.println("Starting Client");
        start = System.currentTimeMillis();
        client.listConfigurationSettings(select).stream().forEach(config -> System.out.println(config));
        System.out.println("It took: " + (System.currentTimeMillis() - start));
        
        System.out.println("Starting Client 2");
        start = System.currentTimeMillis();
        client.listConfigurationSettings(select).stream().forEach(config -> System.out.println(config));
        System.out.println("It took: " + (System.currentTimeMillis() - start));
    }
```
using  azure-data-appconfiguration 1.1.12

**Expected behavior**
using  azure-data-appconfiguration 1.1.9 works as expected.

**Setup (please complete the following information):**
 - OS: Windows 10
 - IDE: Eclipse
 - Library/Libraries: com.azure:azure-core:1.16.0 

**Additional context**
I have been able to "Fix" the issue by doing the following.

```xml
<dependency>
            <groupId>com.azure</groupId>
            <artifactId>azure-data-appconfiguration</artifactId>
            <version>1.1.12</version>
            <exclusions>
                <exclusion>
                    <groupId>com.azure</groupId>
                    <artifactId>azure-core</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>com.azure</groupId>
                    <artifactId>azure-core-http-netty</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>com.azure</groupId>
            <artifactId>azure-core</artifactId>
            <version>1.13.0</version>
            <exclusions>
                <exclusion>
                    <groupId>io.projectreactor</groupId>
                    <artifactId>reactor-core</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>com.azure</groupId>
            <artifactId>azure-core-http-netty</artifactId>
            <version>1.8.0</version>
            <exclusions>
                <exclusion>
                    <groupId>io.projectreactor</groupId>
                    <artifactId>reactor-netty</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>io.projectreactor</groupId>
            <artifactId>reactor-core</artifactId>
            <version>3.4.6</version>
        </dependency>
        <dependency>
            <groupId>io.projectreactor.netty</groupId>
            <artifactId>reactor-netty</artifactId>
            <version>0.9.15.RELEASE</version>
        </dependency>
```

### PR DESCRIPTION
**Pull request by alzimmermsft**
Fixes #22618

Updates `NettyAsyncHttpClientBuilder` to use the default DNS resolver when an `HttpClient` instance is being created without an initial underlying Netty HTTP client. This resolves an issue where the first request made in an application has a much higher completion time (>10s) compared to subsequent requests (generally in ms).

### CODE REVIEW

File: sdk/core/azure-core-http-netty/src/main/java/com/azure/core/http/netty/NettyAsyncHttpClientBuilder.java [hunk 1]
```diff
@@ -92,9 +93,9 @@ public NettyAsyncHttpClientBuilder(HttpClient nettyHttpClient) {
         if (this.baseHttpClient != null) {
             nettyHttpClient = baseHttpClient;
         } else if (this.connectionProvider != null) {
-            nettyHttpClient = HttpClient.create(this.connectionProvider);
+            nettyHttpClient = HttpClient.create(this.connectionProvider).resolver(DefaultAddressResolverGroup.INSTANCE);
         } else {
-            nettyHttpClient = HttpClient.create();
+            nettyHttpClient = HttpClient.create().resolver(DefaultAddressResolverGroup.INSTANCE);
```
Comment (anuchandy) [inline sdk/core/azure-core-http-netty/src/main/java/com/azure/core/http/netty/NettyAsyncHttpClientBuilder.java:98]: Do we know whether this default resolver is a blocking-resolver (that uses blocking InetSocketAddress resolution) or default is netty's non-blocking resolver?

Comment (anuchandy) [reply sdk/core/azure-core-http-netty/src/main/java/com/azure/core/http/netty/NettyAsyncHttpClientBuilder.java:98]: I remember browsing through this deadlock issue https://github.com/reactor/reactor-netty/issues/710 so thought of checking.

Comment (anuchandy) [reply sdk/core/azure-core-http-netty/src/main/java/com/azure/core/http/netty/NettyAsyncHttpClientBuilder.java:98]: So as per this - https://github.com/reactor/reactor-netty/issues/1563#issuecomment-871591339 there is no conclusion that blocking resolver can cause a dead-lock.

Btw if we explicitly set it for user, I guess user can still override it if needed right? (By providing an HttpClient instance)

Comment (alzimmermsft) [reply sdk/core/azure-core-http-netty/src/main/java/com/azure/core/http/netty/NettyAsyncHttpClientBuilder.java:98]: Yes, this would be overridable by using a configured `HttpClient`

File: sdk/core/azure-core-http-netty/src/main/java/com/azure/core/http/netty/NettyAsyncHttpClientBuilder.java [hunk 2]
```diff
@@ -92,9 +93,9 @@ public NettyAsyncHttpClientBuilder(HttpClient nettyHttpClient) {
         if (this.baseHttpClient != null) {
             nettyHttpClient = baseHttpClient;
         } else if (this.connectionProvider != null) {
-            nettyHttpClient = HttpClient.create(this.connectionProvider);
+            nettyHttpClient = HttpClient.create(this.connectionProvider).resolver(DefaultAddressResolverGroup.INSTANCE);
```
Comment (srnagar) [inline sdk/core/azure-core-http-netty/src/main/java/com/azure/core/http/netty/NettyAsyncHttpClientBuilder.java:96]: Is this not supported in OkHttp?

Comment (alzimmermsft) [reply sdk/core/azure-core-http-netty/src/main/java/com/azure/core/http/netty/NettyAsyncHttpClientBuilder.java:96]: It is possible to configure the DNS resolver in OkHttp as well but it doesn't run into the same issue being seen with Reactor Netty.

Comment (srnagar) [reply sdk/core/azure-core-http-netty/src/main/java/com/azure/core/http/netty/NettyAsyncHttpClientBuilder.java:96]: Since this is applicable to all HTTP clients, is this something we should put on `HttpClientOptions` so that the user doesn't have to go build their own HTTP client when they have to configure this?

Comment (alzimmermsft) [reply sdk/core/azure-core-http-netty/src/main/java/com/azure/core/http/netty/NettyAsyncHttpClientBuilder.java:96]: Issue is that the types being used aren't in the base Java library so there will need to be a wrapper interface

**Review by srnagar — APPROVED** [review]

**Comment by jbkervyn** [comment]
@alzimmermsft Hello Alan, this is causing my application to be unable to connect to the azure keyvault (who's behind a corporate proxy). Before your fix, the http client resolver was null, and later in the same class initialized with an NoopAddressResolver. Because of this fix, this is not happening anymore. 

In other words, this code that was executed before the fix is not anymore :) 

```
if (resolver == null) {
                    nettyHttpClient.resolver(NoopAddressResolverGroup.INSTANCE);
                }
```

Is this a regression, or is there something else I should be doing? Thanks !
