### PR TITLE
Fixed Inappropriate Logging and String.format Usage

### LINKED ISSUE #22443: [BUG] Wrong logging format used in JacksonAdapter
https://github.com/Azure/azure-sdk-for-java/blob/532d427683d51fbd1e40bf9478cb69b3c7b57abd/sdk/core/azure-core/src/main/java/com/azure/core/util/serializer/JacksonAdapter.java#L503

http://www.slf4j.org/api/org/slf4j/helpers/MessageFormatter.html

It uses %s instead of {}:

    2021-06-22 11:38:19,949 DEBUG [com.azure.core.util.serializer.JacksonAdapter] User setter %s on class %s to set header collection.

### PR DESCRIPTION
**Pull request by alzimmermsft**
Fixes #22443 

This PR fixes a few cases where `ClientLogger` and `String.format` are being used inappropriately. Inappropriate usage is string manipulation before passing into the logger or missing/using incorrect placeholders.

### CODE REVIEW

File: eng/code-quality-reports/src/main/java/com/azure/tools/checkstyle/checks/FluentMethodNameCheck.java [hunk 1]
```diff
@@ -74,7 +74,8 @@ public void visitToken(DetailAST token) {
                 // logs error if the @Fluent method has 'throws' at the method declaration.
                 if (token.findFirstToken(TokenTypes.LITERAL_THROWS) != null) {
                     log(token, String.format(
-                        "Fluent Method ''%s'' must not be declared to throw any checked exceptions"));
+                        "Fluent Method ''%s'' must not be declared to throw any checked exceptions.",
```
Comment (samvaity) [inline eng/code-quality-reports/src/main/java/com/azure/tools/checkstyle/checks/FluentMethodNameCheck.java:77]: Nice catch! o_0

**Review by samvaity — APPROVED** [review]

**Review by drwill-ms — APPROVED** [review]

File: sdk/eventhubs/azure-messaging-eventhubs/src/test/java/com/azure/messaging/eventhubs/EventProcessorClientBuilderTest.java [hunk 2]
```diff
@@ -51,7 +51,7 @@ public void testEventProcessorBuilderMissingProperties() {
                         + "sequence number of event = " + eventContext.getEventData().getSequenceNumber());
                 })
                 .processError(errorContext -> {
-                    System.out.printf("Error occurred in partition processor for partition {}, {}",
+                    System.out.printf("Error occurred in partition processor for partition %s, %s",
```
Comment (vcolin7) [inline sdk/eventhubs/azure-messaging-eventhubs/src/test/java/com/azure/messaging/eventhubs/EventProcessorClientBuilderTest.java:54]: Should we make it so that whenever we call `printf` we add a new line at the end?

**Review by vcolin7 — APPROVED** [review]
LGTM, just had a small question.

File: sdk/eventhubs/azure-messaging-eventhubs/src/test/java/com/azure/messaging/eventhubs/EventProcessorClientBuilderTest.java (hunk 2 above)
Comment (alzimmermsft) [reply sdk/eventhubs/azure-messaging-eventhubs/src/test/java/com/azure/messaging/eventhubs/EventProcessorClientBuilderTest.java:54]: Yes, this should have a `%n` at the end

**Review by kushagraThapar — APPROVED** [review]
Thanks @alzimmermsft  for fixing these for cosmos

**Review by srnagar — APPROVED** [review]
