### PR TITLE
Fixing formatting for Instant type in diagnostics

### LINKED ISSUE #13580: StoreResponseStatistics instant type is in wrong format in diagnostics
**Describe the bug**
1. StoreResponseStatistics contains requestResponseTime which is not in "dd MMM yyyy HH:mm:ss" format .
	example :	 "requestResponseTime": 1595891486.712483000 -> "requestResponseTime": "28 Jul 2020 19:20:41.735",
2. StoreResponseStatistics requestResourceType and requestOperationType are  not populating.

**Setup (please complete the following information):**
 - V4 (4.2.0)

### PR DESCRIPTION
**Pull request by simplynaveen20**
Closes #13580 
Response will change from 

	"responseStatisticsList": [{
		"storeResult": {
			...
                        ...
		"requestResponseTime": 1595891486.712483000
	}]
to 

		"responseStatisticsList": [{
		"storeResult": {
			...
                        ...
		"requestResponseTime": 28 Jul 2020 19:20:41.735
		"requestResourceType": "Document",
		"requestOperationType": "Create"
	}]

### CODE REVIEW

File: sdk/cosmos/azure-cosmos/src/test/java/com/azure/cosmos/CosmosDiagnosticsTest.java [hunk 1]
```diff
@@ -224,6 +224,14 @@ public void supplementalResponseStatisticsList() throws Exception {
         supplementalResponseStatisticsListNode = (ArrayNode) jsonNode.get("supplementalResponseStatisticsList");
         assertThat(storeResponseStatistics.size()).isEqualTo(7);
         assertThat(supplementalResponseStatisticsListNode.size()).isEqualTo(7);
+
+        //verifying all components from StoreResponseStatistics
+        for(JsonNode node : supplementalResponseStatisticsListNode) {
+            assertThat(node.get("storeResult")).isNotNull();
+            assertThat(node.get("requestResponseTimeUTC")).isNotNull();
```
Comment (j82w) [inline sdk/cosmos/azure-cosmos/src/test/java/com/azure/cosmos/CosmosDiagnosticsTest.java:231]: Should there be validation to check if it is in the correct format?

**Comment by simplynaveen20** [comment]
> LGTM.
> 
> Thanks @simplynaveen20 - can you please paste a sample diagnostics sample here before and after the PR so that it is clear exactly what is changing?

Added in description

File: sdk/cosmos/azure-cosmos/src/test/java/com/azure/cosmos/CosmosDiagnosticsTest.java (hunk 1 above)
Comment (simplynaveen20) [reply sdk/cosmos/azure-cosmos/src/test/java/com/azure/cosmos/CosmosDiagnosticsTest.java:248]: Added
