### PR TITLE
Nio Walk File Tree

### LINKED ISSUE #25883: [BUG] azure-storage-blob-nio: Files/walkFileTree does not work due to readAttributes failing on directories
**Describe the bug**
The java.nio.file.Files/walkFileTree method takes a FileVisitor object.  The `preVisitDirectory` method of this object expects (typically a `Path`) argument and a `BasicFileAttributes` object.  But for entries in the storage container that are like directories, the `AzureBasicFileAttributeView` class' `readAttributes` method throws an `IOException` wrapping a `BlobNotFound` error.  This appears to prematurely terminate the traversal of the directory tree.

***Exception or Stack Trace***
```clojure
(java.nio.file.Files/walkFileTree some-azurepath-object (nio-file-visitor #(println %)))
2021-12-07T22:52:23.436Z  ERROR [com.azure.storage.blob.nio.AzureBasicFileAttributes:265] - com.azure.storage.blob.models.BlobStorageException: Status code 404, (BlobNotFound)
#object[com.azure.storage.blob.nio.AzurePath 0x1bebe26b "acceptance-test-data:/acceptance-test-data"]
```
There is no exception because walkFileTree appears to swallow the exception and terminate the tree traversal.

**To Reproduce**
Call `java.nio.file.Files/walkFileTree` on an `AzurePath` to a folder on an Azure storage blob.

***Code Snippet***
```clojure
(defn nio-file-visitor
  [file-fn]
  (reify FileVisitor
    (^FileVisitResult preVisitDirectory [_ dir ^BasicFileAttributes attrs]
     FileVisitResult/CONTINUE)
    (^FileVisitResult postVisitDirectory [_ dir ^IOException exc]
     (when exc
       (warnf "postVisitDirectory failure on directory %s: %s" dir (.getMessage exc)))
     FileVisitResult/CONTINUE)
    (^FileVisitResult visitFile [_ file ^BasicFileAttributes attrs]
     (debugf "visitFile: %s" file)
     (let [uri (try (str (.toUri ^Path file))
                    (catch Throwable e
                      (errorf "Error get URI: %s" (.getMessage e))
                      nil))]
       (when (and uri (not (get (get-user-metadata ^Path file attrs) "i2kfs_hidden")))
         (file-fn uri)))
     FileVisitResult/CONTINUE)
    (^FileVisitResult visitFileFailed [_ file ^IOException exc]
     (if-let [cause (.getCause exc)]
       (if (and (instance? com.azure.storage.blob.models.BlobStorageException cause)
                (= 404 (.getStatusCode cause)))
         FileVisitResult/CONTINUE
         (do 
           (warnf "visitFileFailed for file %s: %s" file (.getMessage exc))
           (debug exc)
           FileVisitResult/TERMINATE))
       (do 
         (warnf "visitFileFailed for file %s: %s" file (.getMessage exc))
         (debug exc)
         FileVisitResult/TERMINATE)))))

(defn nonhidden-file-seq-nio
  [^Path path]
  (let [files (java.util.ArrayList.)]
    (Files/walkFileTree 
     path 
     (nio-file-visitor
      (fn [uri]
         (.add files (java.net.URLDecoder/decode uri)))))
    files))
```

**Expected behavior**
Should call `FileVisitor.visitFile` for every file in the storage container beneath the given starting path.

**Setup (please complete the following information):**
 - OS: Debian 10 buster
 - IDE: Emacs
 - Library/Libraries: [com.azure/azure-storage-blob-nio "12.0.0-beta.10"]
 - Java version: OpenJDK 1.8.0_302-b08-1-~deb9u1-b08
 - App Server/Environment: [Clojure 1.8.0]

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

### LINKED ISSUE #27302: Storage - Blobs NIO ReadMe and Samples issues
1. Section [link](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/storage/azure-storage-blob-nio/src/samples/java/com/azure/storage/blob/nio/ReadmeSamples.java#L31)
image

Reason:
java.lang.IllegalArgumentException: There was an error parsing the configurations map. Please ensure all fields are set to a legal value of the correct type.

Suggestion:
Change to `
    private FileSystem myFs = FileSystems.newFileSystem(new URI("azb://?account=<your_account_name>"),
            new HashMap<String, Object>(){{
                put(AzureFileSystem.AZURE_STORAGE_ACCOUNT_KEY, "account_key");
                put(AzureFileSystem.AZURE_STORAGE_FILE_STORES, "file_stores");
            }});`

2. Section [link](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/storage/azure-storage-blob-nio/src/samples/java/com/azure/storage/blob/nio/ReadmeSamples.java#L43)
image

Reason:
    1. `AZURE_STORAGE_SHARED_KEY_CREDENTIAL` cannot be resolved or is not a field.
    2. java.lang.IllegalArgumentException: URI does not contain an "account=" parameter. FileSystems require a URI of the format "azb://?account=<account_name>"
 
Suggestion:
    1. Change to `config.put(AzureFileSystem.AZURE_STORAGE_ACCOUNT_KEY, "account_key");`
    2. Change to `new URI("azb://?account=<your_account_name>")`

3. Section [link](https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/storage/azure-storage-blob-nio#uri-format)
image

Suggestion:
Change to `"azb://?account=<your_account_name>"`

4. Section [link](https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/storage/azure-storage-blob-nio#create-a-filesystem)
image

Suggestion:
Change to `config.put(AzureFileSystem.AZURE_STORAGE_ACCOUNT_KEY, "account_key");`

joshfree, tg-msft, kyle-patterson and rickle-msft for notification.

### PR DESCRIPTION
**Pull request by rickle-msft**
Resolves #25883 
Resolves #27302

### CODE REVIEW

File: sdk/storage/azure-storage-blob-nio/src/main/java/com/azure/storage/blob/nio/AzureBasicFileAttributes.java [hunk 1]
```diff
@@ -136,17 +144,17 @@ public boolean isSymbolicLink() {
...
+     * Returns the size of the file (in bytes) or null if this is a virtual directory.
      *
-     * @return the size of the file
+     * @return the size of the file or null if this is a virtual directory
      */
     @Override
     public long size() {
-        return properties.getBlobSize();
+        return this.internalAttributes.size();
     }
```
Comment (JonathanGiles) [inline sdk/storage/azure-storage-blob-nio/src/main/java/com/azure/storage/blob/nio/AzureBasicFileAttributes.java:158]: You are returning little `l` `long` here - but your comment says it returns null if a virtual directory?

Comment (rickle-msft) [reply sdk/storage/azure-storage-blob-nio/src/main/java/com/azure/storage/blob/nio/AzureBasicFileAttributes.java:158]: Good catch! Thank you. I think in the case of regular directories we return 0, and there's probably no need to distinguish here, so I'll change this to return 0 and update the comment.

File: sdk/storage/azure-storage-blob-nio/src/main/java/com/azure/storage/blob/nio/AzureBlobFileAttributes.java [hunk 2]
```diff
@@ -74,198 +86,277 @@
...
         return map;
     }
 
     /**
-     * Returns the creation time. The creation time is the time that the file was created.
+     * Returns the creation time. The creation time is the time that the file was created. Returns null if this is a
+     * virtual directory.
      *
-     * @return The creation time.
+     * @return The creation time or
```
Comment (JonathanGiles) [inline sdk/storage/azure-storage-blob-nio/src/main/java/com/azure/storage/blob/nio/AzureBlobFileAttributes.java:100]:
```suggestion
     * @return The creation time or null if this is a virtual directory.
```

File: sdk/storage/azure-storage-blob-nio/src/main/java/com/azure/storage/blob/nio/AzureBlobFileAttributes.java [hunk 3]
```diff
@@ -74,198 +86,277 @@
...
 
     /**
-     * Returns the time of last modification.
+     * Returns the time of last modification or null if this is a virtual directory.
      * <p>
      * Last access time is not supported by the blob service. In this case, it is typical for implementations to return
      * the {@link #lastModifiedTime()}.
      *
-     * @return the time of last modification.
+     * @return the time of last modification null if this is a virtual directory
```
Comment (JonathanGiles) [inline sdk/storage/azure-storage-blob-nio/src/main/java/com/azure/storage/blob/nio/AzureBlobFileAttributes.java:351]:
```suggestion
     * @return the time of last modification or null if this is a virtual directory.
```

File: sdk/storage/azure-storage-blob-nio/src/main/java/com/azure/storage/blob/nio/AzureBlobFileAttributes.java [hunk 4]
```diff
@@ -319,7 +426,11 @@ public boolean isOther() {
      */
     @Override
     public long size() {
-        return properties.getBlobSize();
+        if (!this.isVirtualDirectory) {
+            return properties.getBlobSize();
+        } else {
+            return 0;
+        }
```
Comment (JonathanGiles) [inline sdk/storage/azure-storage-blob-nio/src/main/java/com/azure/storage/blob/nio/AzureBlobFileAttributes.java:433]: As a minor stylistic comment (and as such, I'm not expecting anything from saying this), one pattern I've favoured over the years is to reverse this code approach, to reduce indentation and 'fall out' of the method early, rather than late. In this case, I would have considered doing it as such:

```java
public long size() {
    if (this.isVirtualDirectory) {
        return 0;
    }
    return properties.getBlobSize();
}
```

In some projects, we even had a code style expectation that such simple return statements didn't need to have braces, so we would have made it simpler and on one line, as below:

```java
public long size() {
    if (this.isVirtualDirectory) return 0;
    return properties.getBlobSize();
}
```

Of course, at this point we might as well go the whole way and just do a single-line ternary expression:

```java
public long size() {
    return this.isVirtualDirectory ? 0 : properties.getBlobSize();
}
```

Comment (rickle-msft) [reply sdk/storage/azure-storage-blob-nio/src/main/java/com/azure/storage/blob/nio/AzureBlobFileAttributes.java:433]: Good idea. I can turn these into ternary expressions. Much cleaner

File: sdk/storage/azure-storage-blob-nio/src/test/java/com/azure/storage/blob/nio/CompositeTest.groovy [hunk 5]
```diff
@@ -106,4 +112,130 @@ class CompositeTest extends APISpec {
...
+        def visitor = new TestFileVisitor()
+        System.out.println(Files.readAttributes(fs.getPath(baseDir), AzureBasicFileAttributes).isDirectory())
+        Files.walkFileTree(fs.getPath(baseDir), visitor)
+
+        // might need to make this work on root directories as well, which would probably mean inspecting the path and adding an isRoot method
+
+        then:
+        visitor.fileCount == 5
+        visitor.directoryCount == 8 // includes baseDir
+        visitor.failureCount == 0
```
Comment (kasobol-msft) [inline sdk/storage/azure-storage-blob-nio/src/test/java/com/azure/storage/blob/nio/CompositeTest.groovy:208]: should we validate that visitor is observing expected paths ?

File: sdk/storage/azure-storage-blob-nio/src/main/java/com/azure/storage/blob/nio/AzureBlobFileAttributes.java [hunk 6]
```diff
@@ -43,14 +45,24 @@
...
     AzureBlobFileAttributes(Path path) throws IOException {
+        this.resource = new AzureResource(path);
+        BlobProperties props = null;
         try {
-            this.resource =  new AzureResource(path);
-            this.properties = resource.getBlobClient().getProperties();
+            props = resource.getBlobClient().getProperties();
         } catch (BlobStorageException e) {
-            throw LoggingUtility.logError(logger, new IOException("Path: " + path.toString(), e));
+            if (e.getStatusCode() == 404 && this.resource.checkDirectoryExists()) {
```
Comment (kasobol-msft) [inline sdk/storage/azure-storage-blob-nio/src/main/java/com/azure/storage/blob/nio/AzureBlobFileAttributes.java:56]: It seems that `this.resource.checkDirectoryExists()` internally calls `this.getBlobClient().getProperties()` in the `checkDirStatus()`. Which means have one more extra get properties call. We should work a bit on this to make sure this only calls blob listing as a fallback.

File: sdk/storage/azure-storage-blob-nio/src/main/java/com/azure/storage/blob/nio/AzureBasicFileAttributes.java [hunk 7]
```diff
@@ -35,64 +35,60 @@
...
-    There are some work-arounds we could do to try to accommodate virtual directories such as making a checkDirStatus
-    call before or after getProperties to throw an appropriate error or adding an isVirtualDirectory method. However,
-    the former wastes network time only to throw a slightly more specific error when we will throw on 404 anyway. The
-    latter introduces virtual directories into the actual code path/api surface. While we are clear in our docs about
-    the possible pitfalls of virtual directories, and customers should be aware of it, they shouldn't have to code
-    against it. Therefore, we fall back to documenting that reading attributes on a virtual directory will throw.
+    In order to support Files.exist() and other methods like Files.walkFileTree() which depend on it, we have had to add
+    support for virtual directories. This is not ideal as customers will have to now perform null checks when inspecting
+    attributes (or at least check if it is a virtual directory before inspecting properties). It also incurs extra
+    network requests as we have to call a checkDirectoryExists() after receiving the initial 404. This is two
```
Comment (kasobol-msft) [inline sdk/storage/azure-storage-blob-nio/src/main/java/com/azure/storage/blob/nio/AzureBasicFileAttributes.java:52]: We should call out extra cost in the changelog.

File: sdk/storage/azure-storage-blob-nio/src/test/java/com/azure/storage/blob/nio/CompositeTest.groovy (hunk 5 above)
Comment (rickle-msft) [reply sdk/storage/azure-storage-blob-nio/src/test/java/com/azure/storage/blob/nio/CompositeTest.groovy:208]: This felt like overkill to me because it seemed like it'd be more validating that the jvm's implementation of walkFileTree is correct than that we have the correct behavior to enable proper use of that method. If you don't agree with that, though, I can add in validation that we hit all the expected paths.

File: sdk/storage/azure-storage-blob-nio/src/main/java/com/azure/storage/blob/nio/AzureBlobFileAttributes.java (hunk 6 above)
Comment (rickle-msft) [reply sdk/storage/azure-storage-blob-nio/src/main/java/com/azure/storage/blob/nio/AzureBlobFileAttributes.java:56]: Yea it's not perfectly optimal, I agree. I think in general checkDirectoryStatus() (and consequently checkDirectoryExists()) may be trying to do too much at once and should potentially be refactored. That said, given that we've had more requests for functionality than performance, I've been trying to avoid premature optimization. Especially in this case, I don't know how common it is that people will be trying to get file attributes on a nonexistent file/virtual directory. Thoughts?

Comment (kasobol-msft) [reply sdk/storage/azure-storage-blob-nio/src/main/java/com/azure/storage/blob/nio/AzureBlobFileAttributes.java:56]: If the penalty was only runtime performance I would agree. However, in this case the penalty is extra $ spent by customer unnecessarily.

Comment (rickle-msft) [reply sdk/storage/azure-storage-blob-nio/src/main/java/com/azure/storage/blob/nio/AzureBlobFileAttributes.java:56]: Fair enough. I think I can refactor the listing part of that method into its own method and just use that here

**Review by JonathanGiles — APPROVED** [review]
