### PR TITLE
azure-search-documents Documentation and Linting Cleanup

### LINKED ISSUE #29119: Cognitive Search samples issue
1.
**Section** [link](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/search/azure-search-documents/src/samples/java/com/azure/search/documents/HttpResponseExceptionExample.java#L83)
image

**Reason:**
'search(java.lang.String, com.azure.search.documents.models.SearchOptions, com.azure.core.util.Context)' is not public in 'com.azure.search.documents.SearchAsyncClient'. Cannot be accessed from outside package
**Suggestion:**
Update to `client.search("hotel", searchOptions)`

2.
**Section** [link](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/search/azure-search-documents/src/samples/java/com/azure/search/documents/indexes/ListIndexersExample.java#L37)
image

**Reason:**
''listIndexers(com.azure.core.util.Context)' is not public in 'com.azure.search.documents.indexes.SearchIndexerAsyncClient'. Cannot be accessed from outside package
**Suggestion:**
Update to `indexerAsyncClient.listIndexers())`

joshfree, AlexGhiondea, meeraharidasa and samvaity for notification.

### PR DESCRIPTION
**Pull request by alzimmermsft**
Fixes #29119 

Enables Spotbugs linting on samples and tests and resolves a sample bug.

### CODE REVIEW

File: sdk/search/azure-search-documents/src/test/java/com/azure/search/documents/test/environment/models/Hotel.java [hunk 1]
```diff
@@ -112,11 +112,11 @@ public Hotel category(String category) {
     }
 
     public List<String> tags() {
-        return this.tags;
+        return (this.tags == null) ? null : new ArrayList<>(this.tags);
```
Comment (mssfang) [inline sdk/search/azure-search-documents/src/test/java/com/azure/search/documents/test/environment/models/Hotel.java:115]: nit: `this` is not neccessary

File: sdk/search/azure-search-documents/src/test/java/com/azure/search/documents/test/environment/models/LoudHotel.java [hunk 2]
```diff
@@ -103,11 +103,11 @@ public LoudHotel CATEGORY(String category) {
     }
 
     public List<String> TAGS() {
-        return this.TAGS;
+        return (this.TAGS) == null ? null : new ArrayList<>(this.TAGS);
```
Comment (mssfang) [inline sdk/search/azure-search-documents/src/test/java/com/azure/search/documents/test/environment/models/LoudHotel.java:106]: nit: `this` is  not neccessary

**Review by mssfang — APPROVED** [review]
