### PR TITLE
Spark: Support ArrayData conversion

### LINKED ISSUE #20930: [BUG] Spark 3.x cosmos DB connector doesn't handle JSON arrays properly
**Describe the bug**
Spark 3.x Cosmos DB connector can't deal with Json containing arrays. 
***Exception or Stack Trace***

> java.lang.ClassCastException: org.apache.spark.sql.catalyst.expressions.UnsafeArrayData cannot be cast to scala.collection.Seq
> 	at com.azure.cosmos.spark.CosmosRowConverter$.convertSparkDataTypeToJsonNode(CosmosRowConverter.scala:133)
> 	at com.azure.cosmos.spark.CosmosRowConverter$.$anonfun$fromInternalRowToObjectNode$1(CosmosRowConverter.scala:96)
> 	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
> 	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
> 	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:198)
> 	at com.azure.cosmos.spark.CosmosRowConverter$.fromInternalRowToObjectNode(CosmosRowConverter.scala:91)
> 	at com.azure.cosmos.spark.ItemsDataWriteFactory$CosmosWriter.write(ItemsDataWriteFactory.scala:83)
> 	at com.azure.cosmos.spark.ItemsDataWriteFactory$CosmosWriter.write(ItemsDataWriteFactory.scala:64)
> 	at org.apache.spark.sql.execution.datasources.v2.DataWritingSparkTask$.$anonfun$run$1(WriteToDataSourceV2Exec.scala:425)
> 	at org.apache.spark.util.Utils$.tryWithSafeFinallyAndFailureCallbacks(Utils.scala:1677)
> 	at org.apache.spark.sql.execution.datasources.v2.DataWritingSparkTask$.run(WriteToDataSourceV2Exec.scala:461)
> 	at org.apache.spark.sql.execution.datasources.v2.V2TableWriteExec.$anonfun$writeWithV2$2(WriteToDataSourceV2Exec.scala:369)
> 	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
> 	at org.apache.spark.scheduler.Task.doRunTask(Task.scala:150)
> 	at org.apache.spark.scheduler.Task.run(Task.scala:119)
> 	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$10(Executor.scala:732)
> 	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1643)
> 	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:735)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 	at java.lang.Thread.run(Thread.java:748)

**To Reproduce**
1. Create json payload with at least one array. 
2. Try to save the Dataframe in Cosmo DB. 

***Code Snippet***
```
val readConfig = Map(
  "spark.cosmos.accountEndpoint" -> cosmosEndpoint,
  "spark.cosmos.accountKey" -> cosmosMasterKey,
  "spark.cosmos.database" -> cosmosDatabaseName,
  "spark.cosmos.container" -> cosmosContainerName)

val jsonStr = """{ "id":"abc", "array": ["abc","def"]}"""
val testStream = spark.read.json(Seq(jsonStr).toDS)
testStream
  .write
  .format("cosmos.items")
  .options(readConfig)
   .mode("Append")
  .save()
```

**Expected behavior**
Simple record with id "abc" and array in the body stored in CosmosDB. *Actual behaviour* is class cast exception.

**Screenshots**
Not applicable. 

**Setup (please complete the following information):**
 - OS: N/A (running on Azure Databricks 8.1 (includes Apache Spark 3.1.1, Scala 2.12) with node Standard_DS3_v2
 - IDE : Notebook in Azure Databricks
 - azure_cosmos_spark_3_1_2_12_4_0_0_beta_2.jar

**Additional context**
N/A - not sure if anything more is relevant, I am trying other options to see if workaround is possible. The schemas/jsons without Array save just fine. 

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Bug Description Added
- [X] Repro Steps Added
- [X] Setup information Added

### PR DESCRIPTION
**Pull request by ealsur**
Depending on the source of the data, arrays can be also of type ArrayData, so we add support for the conversion.

Closes #20930

### CODE REVIEW

File: sdk/cosmos/azure-cosmos-spark_3-1_2-12/src/main/scala/com/azure/cosmos/spark/CosmosRowConverter.scala [hunk 1]
```diff
@@ -187,23 +189,41 @@ private object CosmosRowConverter
...
+      val arrayNode = objectMapper.createArrayNode()
+
+      data.foreach(elementType, (_, value)
+        => writeSparkArrayDataToArrayNode(arrayNode, elementType, containsNull, value))
+
+      arrayNode
+    }
+
+    private def writeSparkArrayDataToArrayNode(arrayNode: ArrayNode,
+                                             elementType: DataType,
```
Comment (moderakh) [inline sdk/cosmos/azure-cosmos-spark_3-1_2-12/src/main/scala/com/azure/cosmos/spark/CosmosRowConverter.scala:209]: nit: indentation mis alignment.

**Review by moderakh — APPROVED** [review]
LGTM. Thanks Matias for the prompt fix.

**Review by FabianMeiswinkel — APPROVED** [review]
Thanks Matias
