### PR TITLE
Internal: Fixed exception handling around GoneException and RequestTimeoutException

### LINKED ISSUE #15304: [BUG] when unsure if a write request has reached the service or not SDK should not retry on failure.
on write failure due to some connection issue in RNTBD stack, RNTBD sends 410 to consistency stack for cases when it is not certain if the request has or hasn't reached the service, the consistency stack retries on such writes, causing a conflict.

expected behaviour is to not retry on such write as cosmos db write is not idempotent.

see the following
```json
{
	"userAgent": "azsdk-java-cosmos/4.5.0 Linux/5.4.0-47-generic JRE/11.0.8",
	"requestLatencyInMs": 1775,
	"requestStartTimeUTC": "17 Sep 2020 04:42:19.946",
	"requestEndTimeUTC": "17 Sep 2020 04:42:21.722",
	"connectionMode": "DIRECT",
	"responseStatisticsList": [{
		"storeResult": {
			"storePhysicalAddress": "rntbd://cdb-ms-prod-southcentralus1-fd14.documents.azure.com:14310/apps/2e2cb427-5005-42a7-845f-a21ce98ef009/services/f5a47728-01d1-4ecc-978b-2ee4cdea7f29/partitions/56a5b2e7-0918-40f9-ae14-0627c2313f3a/replicas/132447567042908231p/",
			"lsn": 0,
			"globalCommittedLsn": -1,
			"partitionKeyRangeId": null,
			"isValid": true,
			"statusCode": 410,
			"subStatusCode": 0,
			"isGone": true,
			"isNotFound": false,
			"isInvalidPartition": false,
			"requestCharge": 0.0,
			"itemLSN": -1,
			"sessionToken": null,
			"exception": "ChannelHandlerContext(RntbdRequestManager#0, [id: 0x1481d0c4, L:/10.211.55.9:49520 - R:cdb-ms-prod-southcentralus1-fd14.documents.azure.com/104.214.18.16:14310]) closed exceptionally with 2 pending requests",
			"transportRequestTimeline": null
		},
		"requestResponseTimeUTC": "17 Sep 2020 04:42:20.015",
		"requestResourceType": "Document",
		"requestOperationType": "Create"
	}, {
		"storeResult": {
			"storePhysicalAddress": "rntbd://cdb-ms-prod-southcentralus1-fd14.documents.azure.com:14310/apps/2e2cb427-5005-42a7-845f-a21ce98ef009/services/f5a47728-01d1-4ecc-978b-2ee4cdea7f29/partitions/56a5b2e7-0918-40f9-ae14-0627c2313f3a/replicas/132447567042908231p/",
			"lsn": 0,
			"globalCommittedLsn": -1,
			"partitionKeyRangeId": null,
			"isValid": true,
			"statusCode": 410,
			"subStatusCode": 0,
			"isGone": true,
			"isNotFound": false,
			"isInvalidPartition": false,
			"requestCharge": 0.0,
			"itemLSN": -1,
			"sessionToken": null,
			"exception": "failed to establish connection to cdb-ms-prod-southcentralus1-fd14.documents.azure.com:14310 due to java.io.IOException: Connection reset by peer",
			"transportRequestTimeline": null
		},
		"requestResponseTimeUTC": "17 Sep 2020 04:42:20.560",
		"requestResourceType": "Document",
		"requestOperationType": "Create"
	}, {
		"storeResult": {
			"storePhysicalAddress": "rntbd://cdb-ms-prod-southcentralus1-fd14.documents.azure.com:14310/apps/2e2cb427-5005-42a7-845f-a21ce98ef009/services/f5a47728-01d1-4ecc-978b-2ee4cdea7f29/partitions/56a5b2e7-0918-40f9-ae14-0627c2313f3a/replicas/132447567042908231p/",
			"lsn": 4388,
			"globalCommittedLsn": 4388,
			"partitionKeyRangeId": "0",
			"isValid": true,
			"statusCode": 409,
			"subStatusCode": 0,
			"isGone": false,
			"isNotFound": false,
			"isInvalidPartition": false,
			"requestCharge": 1.24,
			"itemLSN": -1,
			"sessionToken": "-1#4388",
			"exception": "[\"Resource with specified id or name already exists.\"]",
			"transportRequestTimeline": null
		},
		"requestResponseTimeUTC": "17 Sep 2020 04:42:21.722",
		"requestResourceType": "Document",
		"requestOperationType": "Create"
	}],
	"supplementalResponseStatisticsList": [],
	"addressResolutionStatistics": {
		"2ca3cf81-f8a0-11ea-9e46-4b4d61d16aad": {
			"startTimeUTC": "17 Sep 2020 04:42:21.561",
			"endTimeUTC": "17 Sep 2020 04:42:21.646",
			"targetEndpoint": "https://m-p-j-southcentralus.documents.azure.com:443/addresses/?$resolveFor=dbs%2F2bh7AA%3D%3D%2Fcolls%2F2bh7AIhoZzw%3D%2Fdocs&$filter=protocol%20eq%20rntbd&$partitionKeyRangeIds=0",
			"errorMessage": null,
			"inflightRequest": false
		}
	},
	"regionsContacted": ["https://m-p-j-southcentralus.documents.azure.com:443/"],
	"retryContext": {
		"retryCount": 2,
		"statusAndSubStatusCodes": [
			[410, 0],
			[410, 0],
			[409, 0]
		],
		"retryLatency": 1707
	},
	"metadataDiagnosticsContext": {
		"metadataDiagnosticList": [{
			"metaDataName": "SERVER_ADDRESS_LOOKUP",
			"startTimeUTC": "17 Sep 2020 04:42:21.561",
			"endTimeUTC": "17 Sep 2020 04:42:21.646",
			"durationinMS": 85
		}]
	},
	"serializationDiagnosticsContext": {
		"serializationDiagnosticsList": [{
			"serializationType": "ITEM_SERIALIZATION",
			"startTimeUTC": "17 Sep 2020 04:42:19.946",
			"endTimeUTC": "17 Sep 2020 04:42:19.947",
			"durationInMicroSec": 22
		}]
	},
	"gatewayStatistics": null,
	"systemInformation": {
		"usedMemory": "50026 KB",
		"availableMemory": "4048022 KB",
		"systemCpuLoad": "(2020-09-17T04:41:52.694638Z 5.1%), (2020-09-17T04:41:57.694587Z 3.4%), (2020-09-17T04:42:02.694855Z 3.7%), (2020-09-17T04:42:07.694565Z 6.2%), (2020-09-17T04:42:12.695353Z 5.7%), (2020-09-17T04:42:17.694565Z 4.4%)"
	}
}
```

### LINKED ISSUE #15305: [BUG] For read operations RNTBD RequestTimeoutException from one replica, we should retry on other replicas
For read operations RNTBD RequestTimeoutException from one replica, we should retry on other replicas.
Instead we fail RequestTimeoutException back to the user with no retries on the other replicas.

```json
{
 	"userAgent": "azsdk-java-cosmos/4.5.0 Linux/5.4.0-47-generic JRE/11.0.8",
 	"requestLatencyInMs": 5439,
 	"requestStartTimeUTC": "17 Sep 2020 04:20:45.619",
 	"requestEndTimeUTC": "17 Sep 2020 04:20:51.059",
 	"connectionMode": "DIRECT",
 	"responseStatisticsList": [{
 		"storeResult": {
 			"storePhysicalAddress": null,
 			"lsn": -1,
 			"globalCommittedLsn": -1,
 			"partitionKeyRangeId": null,
 			"isValid": true,
 			"statusCode": 408,
 			"subStatusCode": 0,
 			"isGone": false,
 			"isNotFound": false,
 			"isInvalidPartition": false,
 			"requestCharge": 0.0,
 			"itemLSN": -1,
 			"sessionToken": null,
 			"exception": "AsyncRntbdRequestRecord({\"args\":{\"transportRequestId\":160,\"activityId\":\"2832c0db-f89d-11ea-892c-f5ff8efd5a72\",\"origin\":\"rntbd://cdb-ms-prod-southcentralus1-fd14.documents.azure.com:14332\",\"replicaPath\":\"/apps/2e2cb427-5005-42a7-845f-a21ce98ef009/services/f5a47728-01d1-4ecc-978b-2ee4cdea7f29/partitions/56a5b2e7-0918-40f9-ae14-0627c2313f3a/replicas/132447567127603872s\",\"timeCreated\":\"2020-09-17T04:20:45.620797Z\",\"lifetime\":\"PT5.435442737S\"},\"requestLength\":492,\"responseLength\":-1,\"status\":{\"done\":false,\"cancelled\":false,\"completedExceptionally\":false},\"timeline\":[{\"eventName\":\"created\",\"durationInMicroSec\":\"20\",\"startTime\":\"2020-09-17T04:20:45.620797Z\"},{\"eventName\":\"queued\",\"durationInMicroSec\":\"325971\",\"startTime\":\"2020-09-17T04:20:45.620817Z\"},{\"eventName\":\"pipelined\",\"durationInMicroSec\":\"19127\",\"startTime\":\"2020-09-17T04:20:45.946788Z\"},{\"eventName\":\"transitTime\",\"durationInMicroSec\":\"5090411\",\"startTime\":\"2020-09-17T04:20:45.965915Z\"},{\"eventName\":\"received\",\"durationInMicroSec\":\"0\",\"startTime\":null},{\"eventName\":\"completed\",\"durationInMicroSec\":\"0\",\"startTime\":null}]})",
 			"transportRequestTimeline": null
 		},
 		"requestResponseTimeUTC": "17 Sep 2020 04:20:51.059",
 		"requestResourceType": "Document",
 		"requestOperationType": "Read"
 	}],
 	"supplementalResponseStatisticsList": [],
 	"addressResolutionStatistics": {},
 	"regionsContacted": ["https://moderakh-perf-java-southcentralus.documents.azure.com:443/"],
 	"retryContext": {
 		"retryCount": 0,
 		"statusAndSubStatusCodes": null,
 		"retryLatency": 0
 	},
 	"metadataDiagnosticsContext": {
 		"metadataDiagnosticList": null
 	},
 	"serializationDiagnosticsContext": {
 		"serializationDiagnosticsList": null
 	},
 	"gatewayStatistics": null,
 	"systemInformation": {
 		"usedMemory": "40021 KB",
 		"availableMemory": "4058027 KB",
 		"systemCpuLoad": "(2020-09-17T04:20:24.504305Z 9.8%), (2020-09-17T04:20:29.502914Z 4.1%), (2020-09-17T04:20:34.503036Z 2.9%), (2020-09-17T04:20:39.503185Z 4.9%), (2020-09-17T04:20:44.503167Z 2.8%), (2020-09-17T04:20:49.503221Z 1.5%)"
 	}
 }
```

### LINKED ISSUE #15363: [BUG] RNTB admission control should throw GoneException instead of RequestTimeoutException for reads
**Describe the bug**
Currently RNTBD admission control always throws RequestTimeoutExceptions, which are never retried. The intent was to avoid retries for the same ServiceEndpoint (because that one is overloaded anyway) - but for read operations retries could very well happen on another replica/another RntbdServiceEndpoint - so they should actually happen. 

***Exception or Stack Trace***
n/a

**To Reproduce**
n/a

***Code Snippet***
n/a

**Expected behavior**
We should throw a GoneException instead in Admission control for read operations to trigger the usual retry policies (different rpelica - even different region for multi-region accounts)

**Screenshots**
n/a

**Setup (please complete the following information):**
 n/a

**Additional context**
n/a

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

### PR DESCRIPTION
**Pull request by FabianMeiswinkel**
Fixing a couple of issues with the exception handling in the availability stack:

- Write-requests which have been sent to the service should not be retried when they fail with GoneException
- Read-requests resulting in Request timeouts (when the time between sending the request and waiting for response extends the request timeout duration or service returns 408) should be retried
- Admission control incorrectly was throwing a RequestTimeoutException -should have been a GoneException instead

Closes #15363 
Closes #15305 
Closes #15304

### CODE REVIEW

**Comment by FabianMeiswinkel** [comment]
Looking into options to add some additional test coverage (for admission control and the request timeout exception to gone exception mapping)

File: sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/directconnectivity/RntbdTransportClient.java [hunk 1]
```diff
@@ -203,7 +203,7 @@ public long id() {
             BridgeInternal.setRequestTimeline(cosmosException, record.takeTimelineSnapshot());
             BridgeInternal.setRntbdPendingRequestQueueSize(cosmosException, record.pendingRequestQueueSize());
             BridgeInternal.setChannelTaskQueueSize(cosmosException, record.channelTaskQueueLength());
-
+            BridgeInternal.setSendingRequestStarted(cosmosException, record.hasSendingRequestStarted());
```
Comment (moderakh) [inline sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/directconnectivity/RntbdTransportClient.java:206]: nice! thanks.

File: sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/directconnectivity/rntbd/RntbdRequestManager.java [hunk 2]
```diff
@@ -799,7 +800,11 @@ private void messageReceived(final ChannelHandlerContext context, final RntbdRes
                     break;
 
                 case StatusCodes.REQUEST_TIMEOUT:
-                    cause = new RequestTimeoutException(error, lsn, partitionKeyRangeId, responseHeaders);
+                    Exception inner = new RequestTimeoutException(error, lsn, partitionKeyRangeId, responseHeaders);
+                    String resourceAddress = requestRecord.args().physicalAddress() != null ?
+                        requestRecord.args().physicalAddress().toString() : null;
+
+                    cause = new GoneException(resourceAddress, error, lsn, partitionKeyRangeId, responseHeaders, inner);
```
Comment (moderakh) [inline sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/directconnectivity/rntbd/RntbdRequestManager.java:807]: we should ensure we are not refreshing the cache on this scenario.

File: sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/directconnectivity/rntbd/RntbdRequestRecord.java [hunk 3]
```diff
@@ -213,13 +214,26 @@ public long transportRequestId() {
...
+    /**
+     * Provides information whether the request could have been sent to the service
+     * @return fals if it is possible to guarantee that the request never arrived at the service - true otherwise
+     */
+    public boolean hasSendingRequestStarted() {
+        return this.sendingRequestHasStarted;
+    }
+
+    void setSendingRequestHasStarted() {
+        this.sendingRequestHasStarted = true;
```
Comment (moderakh) [inline sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/directconnectivity/rntbd/RntbdRequestRecord.java:234]: I wonder if we should incorporate that into the RntbdRequestRecord stages as SEND_STARTED stage, and this as an event to the request timeline.

e.g.:
QUEUED, PIPELINED, SEND_STARTED, SENT, RECEIVED, COMPLETED

File: sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/directconnectivity/GoneAndRetryWithRetryPolicy.java [hunk 4]
```diff
@@ -60,12 +60,25 @@ public GoneAndRetryWithRetryPolicy(RxDocumentServiceRequest request, Integer wai
...
+            !request.isReadOnly() &&
+            BridgeInternal.hasSendingRequestStarted((CosmosException)exception)) {
+
+            logger.debug(
+                "Operation will NOT be retried. Write operations can not be retried safely when sending the request " +
+                    "to the service because they aren't idempotent. Current attempt {}, Exception: ",
+                this.attemptCount,
+                exception);
             stopStopWatch(this.durationTimer);
+            this.request.requestContext.forceRefreshAddressCache = true;
```
Comment (moderakh) [inline sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/directconnectivity/GoneAndRetryWithRetryPolicy.java:81]: address refresh is done as part of the retry.

If no one retries then what is the impact of setting `request.requestContext.forceRefreshAddressCache` to true?
who is going to refresh the cache?

**Review by moderakh — CHANGES_REQUESTED** [review]

**Review by moderakh — COMMENTED** [review]
address refresh is done as part of the retry.

If no one retries then what is the impact of setting request.requestContext.forceRefreshAddressCache to true?
who is going to refresh the cache?

File: sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/directconnectivity/GoneAndRetryWithRetryPolicy.java (hunk 4 above)
Comment (FabianMeiswinkel) [reply sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/directconnectivity/GoneAndRetryWithRetryPolicy.java]: Fixed

File: sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/directconnectivity/rntbd/RntbdRequestRecord.java (hunk 3 above)
Comment (FabianMeiswinkel) [reply sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/directconnectivity/rntbd/RntbdRequestRecord.java:234]: I thought about it - decided against it because I haven't found a place where I could interrupt really when starting to send on the wire. Right now I set the flag at the last point where I can guarantee that sending hasn't started yet - which is good enough for the exception handling. But when pushing it into a first-class STAGE i think we should do it really when starting to send data to the wire. So my preference would to leave this as is - are you ok with it or still disagree?

File: sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/RxDocumentServiceRequest.java [hunk 5]
```diff
@@ -83,6 +83,10 @@ public boolean isReadOnlyScript() {
         }
     }
 
+    public boolean isReadOnly() {
+        return this.isReadOnlyRequest() || this.isReadOnlyScript();
```
Comment (kirankumarkolli) [inline sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/RxDocumentServiceRequest.java:87]: Nice thanks.

File: sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/directconnectivity/GoneAndRetryWithRetryPolicy.java [hunk 6]
```diff
@@ -60,13 +60,27 @@ public GoneAndRetryWithRetryPolicy(RxDocumentServiceRequest request, Integer wai
...
             logger.debug("Operation will NOT be retried. Current attempt {}, Exception: ", this.attemptCount,
-                    exception);
+                exception);
             stopStopWatch(this.durationTimer);
             return Mono.just(ShouldRetryResult.noRetry());
+        } else if (exception instanceof GoneException &&
+            !request.isReadOnly() &&
+            BridgeInternal.hasSendingRequestStarted((CosmosException)exception)) {
+
+            logger.debug(
```
Comment (kirankumarkolli) [inline sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/directconnectivity/GoneAndRetryWithRetryPolicy.java:75]: Other similar tracers are at warn below.
Warn seems makes sense.

File: sdk/cosmos/azure-cosmos-dotnet-benchmark/src/main/java/com/azure/cosmos/dotnet/benchmark/Utility.java [hunk 7]
```diff
@@ -10,7 +10,6 @@
     private final static Logger LOGGER = LoggerFactory.getLogger(Main.class);
 
     public static void traceInformation(String payload) {
-        System.out.println(payload);
```
Comment (kirankumarkolli) [inline sdk/cosmos/azure-cosmos-dotnet-benchmark/src/main/java/com/azure/cosmos/dotnet/benchmark/Utility.java:13]: wow we shipped it?

**Review by kirankumarkolli — APPROVED** [review]

File: sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/directconnectivity/rntbd/RntbdRequestManager.java [hunk 8]
```diff
@@ -492,6 +492,7 @@ public void write(final ChannelHandlerContext context, final Object message, fin
 
             final RntbdRequestRecord record = (RntbdRequestRecord) message;
             this.timestamps.channelWriteAttempted();
+            record.setSendingRequestHasStarted();
```
Comment (xinlian12) [inline sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/directconnectivity/rntbd/RntbdRequestManager.java:496]: If the STAGE status is before SENT, is that enough to decide whether we should retry? 

Or maybe can use @flush() to decide whether the request is on wire? I think when calling flush(), sslHandler will start to prepare handshake etc

File: sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/directconnectivity/rntbd/RntbdRequestManager.java [hunk 9]
```diff
@@ -799,7 +800,11 @@ private void messageReceived(final ChannelHandlerContext context, final RntbdRes
                     break;
 
                 case StatusCodes.REQUEST_TIMEOUT:
-                    cause = new RequestTimeoutException(error, lsn, partitionKeyRangeId, responseHeaders);
+                    Exception inner = new RequestTimeoutException(error, lsn, partitionKeyRangeId, responseHeaders);
```
Comment (xinlian12) [inline sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/directconnectivity/rntbd/RntbdRequestManager.java:803]: Why need to create RequestTimeoutException as inner? would not 'error' itself enough?

File: sdk/cosmos/azure-cosmos-dotnet-benchmark/src/main/resources/log4j2.properties [hunk 10]
```diff
@@ -0,0 +1,25 @@
...
+
+# STDOUT is a ConsoleAppender and uses PatternLayout.
+appender.console.name = STDOUT
+appender.console.type = Console
+appender.console.layout.type = PatternLayout
+appender.console.layout.pattern = %d %5X{pid} [%t] %-5p %c - %m%n
+
+#appender.logfile.name = FILE
+#appender.logfile.type = File
+#appender.logfile.filename = ${logDirectory}/azure-cosmos-benchmark.log
```
Comment (xinlian12) [inline sdk/cosmos/azure-cosmos-dotnet-benchmark/src/main/resources/log4j2.properties:23]: not important, just wonder should we use different file name here for .net?

File: sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/directconnectivity/GoneAndRetryWithRetryPolicy.java [hunk 11]
```diff
@@ -60,13 +60,27 @@ public GoneAndRetryWithRetryPolicy(RxDocumentServiceRequest request, Integer wai
             !(exception instanceof RetryWithException) &&
             !(exception instanceof PartitionIsMigratingException) &&
             !(exception instanceof InvalidPartitionException &&
-            (this.request.getPartitionKeyRangeIdentity() == null ||
-            this.request.getPartitionKeyRangeIdentity().getCollectionRid() == null)) &&
+                (this.request.getPartitionKeyRangeIdentity() == null ||
```
Comment (xinlian12) [inline sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/directconnectivity/GoneAndRetryWithRetryPolicy.java:63]: NIT: the the indent same as above line?

File: sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/RetryUtils.java [hunk 12]
```diff
@@ -82,11 +84,20 @@
...
-                        return Mono.error(shouldRetryResult.exception);
+
+                    final Throwable errorToReturn = shouldRetryResult.exception != null ? shouldRetryResult.exception : e;
+                    final Mono<T> failure = Mono.error(errorToReturn);
+
+                    if (shouldRetryResult.policyArg != null &&
+                        shouldRetryResult.policyArg.getValue0() != null &&
+                        shouldRetryResult.policyArg.getValue0()) {
+
+                        return addressSelector.resolveAddressesAsync(
```
Comment (xinlian12) [inline sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/RetryUtils.java:95]: Why we need to refresh address here? If we reach here, it means we will not going to retry the request, is that we are trying to proactively refresh the address?

File: sdk/cosmos/azure-cosmos-dotnet-benchmark/src/main/resources/log4j2.properties (hunk 10 above)
Comment (FabianMeiswinkel) [reply sdk/cosmos/azure-cosmos-dotnet-benchmark/src/main/resources/log4j2.properties:23]: Fixed in next iteration

File: sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/directconnectivity/GoneAndRetryWithRetryPolicy.java (hunk 11 above)
Comment (FabianMeiswinkel) [reply sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/directconnectivity/GoneAndRetryWithRetryPolicy.java:63]: No - intentional - because it is the second condition for the logical AND.

File: sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/RetryUtils.java (hunk 12 above)
Comment (FabianMeiswinkel) [reply sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/RetryUtils.java:95]: It is the Gone for write requests - before we were refreshing addresses and retry. Retrying is a problem because writes aren't idempotent. But the address refresh as reaction of all 410s should still happen

File: sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/directconnectivity/rntbd/RntbdRequestManager.java (hunk 9 above)
Comment (FabianMeiswinkel) [reply sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/directconnectivity/rntbd/RntbdRequestManager.java:803]: To not loose context in cases where we iterate through exceptions recursively through all inner exceptions etc.

File: sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/directconnectivity/rntbd/RntbdRequestManager.java (hunk 8 above)
Comment (FabianMeiswinkel) [reply sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/directconnectivity/rntbd/RntbdRequestManager.java:496]: No - Especially the SSL handhsake has relatively high potential for error/timeout - and at that point we would still be "safe to retry" - the right time is really just before we start sending the actual request on the wire. Does that make sense?

File: sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/directconnectivity/GoneAndRetryWithRetryPolicy.java (hunk 11 above)
Comment (xinlian12) [reply sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/directconnectivity/GoneAndRetryWithRetryPolicy.java:63]: oh, yea, sorry, miss read )

File: sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/RetryUtils.java (hunk 12 above)
Comment (xinlian12) [reply sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/RetryUtils.java:95]: I see, got it, make sense, thanks for the explanation.

File: sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/directconnectivity/rntbd/RntbdRequestManager.java (hunk 8 above)
Comment (xinlian12) [reply sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/directconnectivity/rntbd/RntbdRequestManager.java:496]: Hmm, but I thought instead of creating a new flag, we probably should be safe enough to use Stage.Sent to guard the retry?

But this change makes sense to me~

Comment (FabianMeiswinkel) [reply sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/directconnectivity/rntbd/RntbdRequestManager.java:496]: Stage.SENT is only set after finishing sending the request on the wire - which means we could receive an error we map to 410 while sending the request - which isn't 100% safe from the idempotency perspective. Once we start sending the request we can't exclude the risk of side effects on the service (because retrieving ACK from the service and setting Stage.SENT isn't happening atomically - although I admit the risk is low. I personally don't think the additional flag is increasing overall complexity much - but as the author I am obviously biased. If there is broader concern about the complexity introduced by this additional flag I am ok with trading-in some correctness and using Stage < SENT as indication of allowing retries. @moderakh / @kirankumarkolli  / @kushagraThapar / @simplynaveen20 - Thoughts?

Comment (xinlian12) [reply sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/directconnectivity/rntbd/RntbdRequestManager.java:496]: So currently, we are using write() not writeAndFlush(), that is why I think maybe it is safe (since the write method is only queue the message, but not really writing the message to the underlying socket).

File: sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/RetryUtils.java (hunk 12 above)
Comment (moderakh) [inline sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/RetryUtils.java:95]: this is for refreshing address cache on a Gone Exception for write request.

With this approach the write response will get blocked till the unrelated address resolution completes.

you could instead trigger a address cache refresh in background and return the write response immediately.

See this as example:
https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/directconnectivity/ConsistencyWriter.java#L365-L373

File: sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/directconnectivity/rntbd/RntbdRequestRecord.java (hunk 3 above)
Comment (moderakh) [reply sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/directconnectivity/rntbd/RntbdRequestRecord.java:234]: I agree with you. Thanks.

**Review by moderakh — COMMENTED** [review]
you don't need to wait on address refresh cache when write request result in gone.

you could instead trigger an address cache refresh in background and return the write response immediately.

See this as example:
https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/directconnectivity/ConsistencyWriter.java#L365-L373

**Review by moderakh — APPROVED** [review]
for failed write, please do the address cache refresh in background. 

other than that LGTM.
https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/directconnectivity/ConsistencyWriter.java#L365-L373

File: sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/RetryUtils.java (hunk 12 above)
Comment (FabianMeiswinkel) [reply sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/RetryUtils.java]: Fixed - good catch. Thanks!

File: sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/RetryUtils.java [hunk 13]
```diff
@@ -82,11 +85,18 @@
...
                     retryPolicy.updateEndTime();
-                    if(shouldRetryResult.exception == null) {
-                        return Mono.error(e);
-                    } else {
-                        return Mono.error(shouldRetryResult.exception);
+
+                    final Throwable errorToReturn = shouldRetryResult.exception != null ? shouldRetryResult.exception : e;
+                    final Mono<T> failure = Mono.error(errorToReturn);
+
+                    if (shouldRetryResult.policyArg != null &&
```
Comment (kushagraThapar) [inline sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/RetryUtils.java:92]: Can you please add a comment here what `policyArg.getValue0()` is ?

File: sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/directconnectivity/rntbd/RntbdRequestManager.java (hunk 8 above)
Comment (kushagraThapar) [reply sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/directconnectivity/rntbd/RntbdRequestManager.java:496]: @FabianMeiswinkel  - I am fine with adding the flag, I don't think it introduces additional complexity.

File: sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/directconnectivity/rntbd/RntbdRequestRecord.java [hunk 14]
```diff
@@ -213,13 +214,26 @@ public long transportRequestId() {
...
         BridgeInternal.setRequestHeaders(error, this.args.serviceRequest().getHeaders());
+
         return this.completeExceptionally(error);
     }
 
     public abstract Timeout newTimeout(final TimerTask task);
 
+    /**
+     * Provides information whether the request could have been sent to the service
+     * @return fals if it is possible to guarantee that the request never arrived at the service - true otherwise
```
Comment (kushagraThapar) [inline sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/directconnectivity/rntbd/RntbdRequestRecord.java:227]: typo on return value :) 
`fals` -> `false`

Comment (kushagraThapar) [reply sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/directconnectivity/rntbd/RntbdRequestRecord.java:227]: If I understand this correctly, we are saying that this API returns `true` if the request has been sent to the service and received it, `false` otherwise - meaning either the request is sent but not received by the service, or request is not sent at all ?

File: sdk/cosmos/azure-cosmos/src/test/java/com/azure/cosmos/implementation/directconnectivity/ReplicatedResourceClientGoneForWriteTest.java [hunk 15]
```diff
@@ -0,0 +1,127 @@
+package com.azure.cosmos.implementation.directconnectivity;
```
Comment (kushagraThapar) [inline sdk/cosmos/azure-cosmos/src/test/java/com/azure/cosmos/implementation/directconnectivity/ReplicatedResourceClientGoneForWriteTest.java:1]: Not sure why the CI didn't catch this, but this is missing Microsoft copyright header information.

**Review by kushagraThapar — CHANGES_REQUESTED** [review]
Overall looks good to me, some minor suggestions and one blocking comment to add Microsoft copyright header to the new file.

File: sdk/cosmos/azure-cosmos/src/test/java/com/azure/cosmos/implementation/directconnectivity/ReplicatedResourceClientGoneForWriteTest.java (hunk 15 above)
Comment (FabianMeiswinkel) [reply sdk/cosmos/azure-cosmos/src/test/java/com/azure/cosmos/implementation/directconnectivity/ReplicatedResourceClientGoneForWriteTest.java:1]: Fixed in next iteration

File: sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/directconnectivity/rntbd/RntbdRequestRecord.java (hunk 14 above)
Comment (FabianMeiswinkel) [reply sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/directconnectivity/rntbd/RntbdRequestRecord.java:227]: No - will return true if there exists a chance that the request could have arrived at the service
False if we are 100% sure the request wasn't sent on the wire

File: sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/RetryUtils.java (hunk 13 above)
Comment (FabianMeiswinkel) [reply sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/RetryUtils.java:92]: Fixed in next iteration

**Review by kushagraThapar — APPROVED** [review]
Thanks @FabianMeiswinkel  looks good to me.
