### PR TITLE
Fix organizations tenant bug in sync client

### LINKED ISSUE #34387: [BUG] Azure CLI auth fails when tenant is organizations
**Describe the bug**
This issue is observed when we upgrade the azure-sdk-bom from 1.2.3 to 1.2.5.

We have a suite of tests that work perfectly fine locally, and as well when triggered via azure devops pipelines (via service connection). This is used against azure-sdk-bom 1.2.3. As part of tests, the code authenticates against azure storage account, event grid etc.

When tried against any version post that (say 1.2.5 or 1.2.11), all the tests start to fail.

> [INFO] Running xx.xxx.xxxxx.xxxx
> [ERROR] Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 15.872 s <<< FAILURE! - in xx.xxx.xxxxx.xxxx
> [ERROR] startListeningToMessages2  Time elapsed: 9.308 s  <<< ERROR!
> com.azure.messaging.servicebus.ServiceBusException: 
> EnvironmentCredential authentication unavailable. Environment variables are not fully configured.To mitigate this issue, please refer to the troubleshooting guidelines here at https://aka.ms/azsdk/java/identity/environmentcredential/troubleshoot
> Managed Identity authentication is not available.
> SharedTokenCacheCredential authentication unavailable. No accounts were found in the cache.
> IntelliJ Authentication not available. Please log in with Azure Tools for IntelliJ plugin in the IDE.
> AzureCliCredential authentication unavailable. Please run 'az login' to set up account. To further mitigate this issue, please refer to the troubleshooting guidelines here at https://aka.ms/azsdk/java/identity/azclicredential/troubleshoot
> Error reading data from readerTo mitigate this issue, please refer to the troubleshooting guidelines here at https://aka.ms/azure-identity-java-default-azure-credential-troubleshoot
> Caused by: com.azure.identity.CredentialUnavailableException: 
> EnvironmentCredential authentication unavailable. Environment variables are not fully configured.To mitigate this issue, please refer to the troubleshooting guidelines here at https://aka.ms/azsdk/java/identity/environmentcredential/troubleshoot
> Managed Identity authentication is not available.
> SharedTokenCacheCredential authentication unavailable. No accounts were found in the cache.
> IntelliJ Authentication not available. Please log in with Azure Tools for IntelliJ plugin in the IDE.
> AzureCliCredential authentication unavailable. Please run 'az login' to set up account. To further mitigate this issue, please refer to the troubleshooting guidelines here at https://aka.ms/azsdk/java/identity/azclicredential/troubleshoot
> Error reading data from readerTo mitigate this issue, please refer to the troubleshooting guidelines here at https://aka.ms/azure-identity-java-default-azure-credential-troubleshoot

These tests work locally but not when run by azure devops pipeline. This issue can only be found in the newer versions.

I see an update-log here: https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/identity/azure-identity/CHANGELOG.md#154-2022-08-08 
Not sure if this is creating trouble

image

***Code Snippet***

        this.sender = new ServiceBusClientBuilder()
                .credential(namespace, new DefaultAzureCredentialBuilder().build())
                .sender()
                .queueName(queue)
                .buildClient();

And we specify the service connection here:

```
    - task: AzureCLI@2
      displayName: 'Running unit tests'
      inputs:
        azureSubscription: '${{ parameters.environments.serviceConnectionId }}'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
         # The below gives expected output. So I am sure azure cli is working as expected.
          az account show 
          java -version
          source /etc/profile.d/java.sh
          source /etc/profile.d/maven.sh
          cd java-services
          mvn clean verify -ntp -Dmaven.artifact.threads=30
```

**Expected behavior**
Expected it to work with newer versions, as it did with older versions.

Can confirm az cli installed on the underlying host

**Setup (please complete the following information):**
 - OS: Linux
 - IDE: 
 - Library/Libraries: azure-sd-bom 1.2.11
 - Java version: 17
 - App Server/Environment: 
 - Frameworks:

### PR DESCRIPTION
**Pull request by billwert**
#35764 missed fixing the Sync client.

Fixes #34387

### CODE REVIEW

**Comment by billwert** [comment]
@Azure/azure-sdk-write-identity can someone PTAL? Thanks!

File: sdk/identity/azure-identity/src/main/java/com/azure/identity/implementation/IdentitySyncClient.java [hunk 1]
```diff
@@ -361,9 +361,8 @@ public AccessToken authenticateWithAzureCli(TokenRequestContext request) {
         String tenant = IdentityUtil.resolveTenantId(tenantId, request, options);
         ValidationUtil.validateTenantIdCharacterRange(tenant, LOGGER);
 
-        if (!CoreUtils.isNullOrEmpty(tenant)) {
+        if (!CoreUtils.isNullOrEmpty(tenant) && !tenant.equals(IdentityUtil.DEFAULT_TENANT)) {
```
Comment (christothes) [inline sdk/identity/azure-identity/src/main/java/com/azure/identity/implementation/IdentitySyncClient.java:364]: In .NET, I believe we unconditionally use the tenantID. I'm just curious why this logic is needed.

Comment (billwert) [reply sdk/identity/azure-identity/src/main/java/com/azure/identity/implementation/IdentitySyncClient.java:364]: `organizations` is not a valid tenant for getting a token from a service principal. A service principal should always be bound to a given tenant. The customer was not passing this through - we made a change a while go that introduced this bug and caused the issue. After researching and talking to @jiasli it was determined that we should never pass this to azcli so we put the check in.

**Review by christothes — APPROVED** [review]
