### PR TITLE
Apply RequestOptions Callback Before Validation in RestProxy

### LINKED ISSUE #25168: [BUG] Request with payload of BinaryData from InputStream fails due to invalid content length
**Describe the bug**

Request fails due to invalid content length.

code
```java
        ByteArrayInputStream messageStream = new ByteArrayInputStream(message.toBytes());
        client.sendToUserWithResponse("test_user",
            BinaryData.fromStream(messageStream),
            WebPubSubContentType.APPLICATION_OCTET_STREAM, message.getLength(),
            null, Context.NONE);
```

internally it already included the "Content-Length"
```java
        requestOptions.addRequestCallback(httpRequest -> {
            if (httpRequest.getHeaders().stream()
                .noneMatch(header -> header.getName().equalsIgnoreCase("Content-Length"))) {
                httpRequest.setHeader("Content-Length", String.valueOf(contentLength));
            }
        });
```

Possible cause:

`InputStreamContent` return `null` in `getLength`, which is kind of reasonable.
https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/core/azure-core/src/main/java/com/azure/core/implementation/util/InputStreamContent.java#L40-L46

Code provided `Content-Length` header in `RequestOptions`. However due to the order of `validateLength` and `options.getRequestCallback().accept(request)`, the set of `Content-Length` header in `RequestOptions` is after `validateLength`.
https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/core/azure-core/src/main/java/com/azure/core/http/rest/RestProxy.java#L134-L140

***Exception or Stack Trace***
Add the exception log and stack trace if available

stack
```
java.lang.NumberFormatException: null

	at java.base/java.lang.Long.parseLong(Long.java:670)
	at java.base/java.lang.Long.parseLong(Long.java:832)
	at com.azure.core@1.22.0-beta.1/com.azure.core.http.rest.RestProxy.validateLength(RestProxy.java:164)
	at com.azure.core@1.22.0-beta.1/com.azure.core.http.rest.RestProxy.invoke(RestProxy.java:130)
```

**To Reproduce**

***Code Snippet***
Add the code snippet that causes the issue.

**Expected behavior**

**Screenshots**

**Setup (please complete the following information):**
 - IDE: [e.g. IntelliJ]
 - Library/Libraries: [e.g. com.azure:azure-core:1.16.0 (groupId:artifactId:version)] 1.22.0-beta.1 (should be same as the unreleased 1.22.0)
 - Java version: [e.g. 8] 15
 - App Server/Environment: [e.g. Tomcat, WildFly, Azure Function, Apache Spark, Databricks, IDE plugin or anything special]
 - Frameworks: [e.g. Spring Boot, Micronaut, Quarkus, etc] 

If you suspect a dependency version mismatch (e.g. you see `NoClassDefFoundError`, `NoSuchMethodError` or similar), please provide
- verbose dependency tree (`mvn dependency:tree -Dverbose`)
  
**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

### PR DESCRIPTION
**Pull request by alzimmermsft**
Fixes #25168

This PR resolves an issue where `RequestOptions` callbacks that consume an `HttpRequest` didn't occur before validation done in `RestProxy`. The change is being done as the `RequestOptions` callbacks mutate the `HttpRequest`, so if validation was configured before they are applied it won't be configuring the final `HttpRequest` that will be sent through `RestProxy`. 

Additionally, this PR closes another functionality gap where `RequestOptions` only exposed adding headers. Now, it also exposes a set headers API which resolves a pain point where adding a header value could result in having a header with multiple values that results in a comma-separated header value when sent over the wire where it was expected to override the value.

### CODE REVIEW

**Review by lmolkova — COMMENTED** [review]
Can you please add tests for setHeader and updating body in addRequestCallback in core (if it ever breaks, it'd be discovered immediately in the inner loop)

File: sdk/core/azure-core/src/main/java/com/azure/core/http/rest/RestProxy.java [hunk 1]
```diff
@@ -131,14 +131,16 @@ public Object invoke(Object proxy, final Method method, Object[] args) {
                 .addData("azure-eagerly-read-response", shouldEagerlyReadResponse(methodParser.getReturnType()));
             context = startTracingSpan(method, context);
 
-            if (request.getBody() != null) {
-                request.setBody(validateLength(request));
-            }
-
+            // If there is 'RequestOptions' apply its request callback operations before validating the body.
+            // This is because the callbacks may mutate the request body.
```
Comment (JonathanGiles) [inline sdk/core/azure-core/src/main/java/com/azure/core/http/rest/RestProxy.java:135]: Nice internal commentary!

File: sdk/webpubsub/azure-messaging-webpubsub/src/main/java/com/azure/messaging/webpubsub/WebPubSubServiceAsyncClient.java [hunk 2]
```diff
@@ -223,13 +218,8 @@
...
         }
-        requestOptions.addHeader("Content-Type", contentType.toString());
-        requestOptions.addRequestCallback(httpRequest -> {
-            if (httpRequest.getHeaders().stream()
-                .noneMatch(header -> header.getName().equalsIgnoreCase("Content-Length"))) {
-                httpRequest.setHeader("Content-Length", String.valueOf(contentLength));
-            }
-        });
+        requestOptions.setHeader("Content-Type", contentType.toString());
+        requestOptions.setHeader("Content-Length", String.valueOf(contentLength));
```
Comment (JonathanGiles) [inline sdk/webpubsub/azure-messaging-webpubsub/src/main/java/com/azure/messaging/webpubsub/WebPubSubServiceAsyncClient.java:222]: Make sure the WPS team are aware of these changes

**Review by JonathanGiles — APPROVED** [review]

File: sdk/webpubsub/azure-messaging-webpubsub/src/main/java/com/azure/messaging/webpubsub/WebPubSubServiceAsyncClient.java (hunk 2 above)
Comment (alzimmermsft) [reply sdk/webpubsub/azure-messaging-webpubsub/src/main/java/com/azure/messaging/webpubsub/WebPubSubServiceAsyncClient.java:222]: This is actually a change that needs to be know to LLC code generation.

cc: @weidongxu-microsoft

Comment (weidongxu-microsoft) [reply sdk/webpubsub/azure-messaging-webpubsub/src/main/java/com/azure/messaging/webpubsub/WebPubSubServiceAsyncClient.java:222]: @alzimmermsft
This method is actually manual code (the method is likely added by Srikanta as a easier-to-use convenient method for the LLC generated method, or another possibility is that this is generated by a very old codegen, and Srikanta keeps it for backward-compatibility when updating the Client), so there is no business with codegen here.

I see you already recorded the test, so this should be good.
