### PR TITLE
Blob post UX study fixes

### LINKED ISSUE #3965: Convert all methods that return AutoRest generated headers to return manually crafted types

### PR DESCRIPTION
**Pull request by jianghaolu**
Fixes #3965 #3966 #3967 #3961 #3960 #3969 

- Unified client constructors to take the generated builder on async clients and take the async client on sync clients
- Add `getUrl()`
- Add `getContainerClient()` on blob client and `getStorageClient()` on container client
- Add `.exists()` on blob client and container client
- Return `Response<T>`
- Return `AppendBlobItem`, `PageBlobItem`, `BlockBlobItem` on their clients' most methods (according to https://gist.github.com/jaschrep-msft/59f5d4312d0ef555f5ed454c9a504a13)
- Add `listBlobsHierarchy()`
- Parallel upload/download
- Adapt credentials to azure-core, which gets AAD for free through azure-identity

### CODE REVIEW

File: storage/client/src/main/java/com/azure/storage/blob/BlobClientBuilder.java [hunk 1]
```diff
@@ -60,20 +71,30 @@ public BlobClientBuilder() {
...
+    private AzureBlobStorageBuilder buildImpl() {
         Objects.requireNonNull(endpoint);
+        Objects.requireNonNull(containerName);
+        Objects.requireNonNull(blobName);
 
         // Closest to API goes first, closest to wire goes last.
         final List<HttpPipelinePolicy> policies = new ArrayList<>();
 
+        if (configuration == null) {
+            configuration = Configuration.NONE;
```
Comment (JonathanGiles) [inline storage/client/src/main/java/com/azure/storage/blob/BlobClientBuilder.java]: Same question here

File: storage/client/src/main/java/com/azure/storage/blob/BlobClientBuilder.java [hunk 2]
```diff
@@ -136,8 +204,8 @@ public BlobClientBuilder credentials(SharedKeyCredentials credentials) {
      * @param credentials authorization credentials
      * @return the updated BlobClientBuilder object
      */
-    public BlobClientBuilder credentials(TokenCredentials credentials) {
-        this.credentials = credentials;
+    public BlobClientBuilder credentials(SASTokenCredential credentials) {
```
Comment (JonathanGiles) [inline storage/client/src/main/java/com/azure/storage/blob/BlobClientBuilder.java]: credentials -> credential

File: storage/client/src/main/java/com/azure/storage/blob/BlockBlobClient.java [hunk 3]
```diff
@@ -126,21 +131,29 @@ public void upload(InputStream data, long length) throws IOException {
...
+        Mono<Response<BlockBlobItem>> upload = blockBlobAsyncClient
+            .upload(fbb, length, headers, metadata, accessConditions, context);
 
         try {
             if (timeout == null) {
-                upload.block();
+                return upload.block();
             } else {
-                upload.block(timeout);
+                return upload.block(timeout);
```
Comment (JonathanGiles) [inline storage/client/src/main/java/com/azure/storage/blob/BlockBlobClient.java]: I keep seeing this pattern - we should extract it out into a util method

File: storage/client/src/main/java/com/azure/storage/blob/ContainerClient.java [hunk 4]
```diff
@@ -634,7 +671,7 @@ public void releaseLease(String leaseID,
      * @return
      *      The remaining time in the broken lease in seconds.
      */
-    public int breakLease() {
+    public Response<Integer> breakLease() {
```
Comment (JonathanGiles) [inline storage/client/src/main/java/com/azure/storage/blob/ContainerClient.java]: Should this be represented as a Duration?

File: storage/client/src/main/java/com/azure/storage/blob/BlobAsyncClient.java [hunk 5]
```diff
@@ -102,9 +121,65 @@ public AppendBlobAsyncClient asAppendBlobAsyncClient() {
...
+     * @param context
+     *         {@code Context} offers a means of passing arbitrary data (key/value pairs) to an
+     *         {@link com.azure.core.http.HttpPipeline}'s policy objects. Most applications do not need to pass
+     *         arbitrary data to the pipeline and can pass {@code Context.NONE} or {@code null}. Each context object is
+     *         immutable. The {@code withContext} with data method creates a new {@code Context} object that refers to its
+     *         parent, forming a linked list.
+     * @return
+     *         true if the blob exists, false if it doesn't
+     */
+    public Mono<Response<Boolean>> exists(Context context) {
```
[the remark this answers is not in the document]
Comment (jianghaolu) [reply storage/client/src/main/java/com/azure/storage/blob/BlobAsyncClient.java]: Thanks for the review - agreeing with everything but a little confused about this. Storage team may have reasons why they need the `Context` parameter on every method.

[the remark this answers is not in the document]
Comment (JonathanGiles) [reply storage/client/src/main/java/com/azure/storage/blob/BlobAsyncClient.java]: This was one of the things I emailed about a few weeks back. For our first preview the desire is to not expose the Context argument. We will resolve how to expose it in a follow up preview release.

File: storage/client/src/main/java/com/azure/storage/blob/models/AppendBlobItem.java [hunk 6]
```diff
@@ -0,0 +1,67 @@
...
+    public Boolean isServerEncrypted() {
+        return isServerEncrypted;
+    }
+
+    public String encryptionKeySha256() {
+        return encryptionKeySha256;
+    }
+
+    public byte[] contentMD5() {
+        return contentMD5;
```
Comment (alzimmermsft) [inline storage/client/src/main/java/com/azure/storage/blob/models/AppendBlobItem.java]: Should clone this on return

File: storage/client/src/main/java/com/azure/storage/common/credentials/SharedKeyCredential.java [hunk 7]
```diff
@@ -80,30 +89,63 @@ public String generateAuthorizationHeader(URL requestURL, String httpMethod, Map
...
 
+    /**
+     * Computes a signature for the specified string using the HMAC-SHA256 algorithm.
+     * Package-private because it is used to generate SAS signatures.
+     *
+     * @param stringToSign The UTF-8-encoded string to sign.
+     * @return A {@code String} that contains the HMAC-SHA256-encoded signature.
+     * @throws InvalidKeyException If the accountKey is not a valid Base64-encoded string.
+     */
+    public String computeHmac256(final String stringToSign) throws InvalidKeyException {
```
Comment (alzimmermsft) [inline storage/client/src/main/java/com/azure/storage/common/credentials/SharedKeyCredential.java]: Should reconcile that this class has a private computeHMACSHA256 and this public computHmac256

File: storage/client/src/main/java/com/azure/storage/blob/AppendBlobClientBuilder.java [hunk 8]
```diff
@@ -60,20 +71,30 @@ public AppendBlobClientBuilder() {
...
         Objects.requireNonNull(endpoint);
+        Objects.requireNonNull(containerName);
+        Objects.requireNonNull(blobName);
 
         // Closest to API goes first, closest to wire goes last.
         final List<HttpPipelinePolicy> policies = new ArrayList<>();
 
+        if (configuration == null) {
+            configuration = Configuration.NONE;
+        }
```
[the remark this answers is not in the document]
Comment (alzimmermsft) [reply storage/client/src/main/java/com/azure/storage/blob/AppendBlobClientBuilder.java]: In the other SDKs the default is to use the global configuration, it is a fair question to ask if the configuration store should be opt-in (default to Configuration.NONE) or opt-out (default to the global configuration store). Both approaches have their pros and cons.

For now we should switch this to align with the other SDKs but have a quick chat about opt-in vs opt-out on configurations.

File: storage/client/src/main/java/com/azure/storage/blob/AccountSASSignatureValues.java [hunk 9]
```diff
@@ -186,8 +188,8 @@ public AccountSASSignatureValues withResourceTypes(String resourceTypes) {
      *
      * @return {@link SASQueryParameters}
      */
-    public SASQueryParameters generateSASQueryParameters(SharedKeyCredentials sharedKeyCredentials) {
-        Utility.assertNotNull("SharedKeyCredentials", sharedKeyCredentials);
+    public SASQueryParameters generateSASQueryParameters(SharedKeyCredential sharedKeyCredentials) {
+        Utility.assertNotNull("SharedKeyCredential", sharedKeyCredentials);
```
Comment (alzimmermsft) [inline storage/client/src/main/java/com/azure/storage/blob/AccountSASSignatureValues.java]: Post preview we should look to changing these Utility.assertNotNull to Objects.requireNonNull

Comment (rickle-msft) [reply storage/client/src/main/java/com/azure/storage/blob/AccountSASSignatureValues.java]: Should we open an issue for this?

File: storage/client/src/main/java/com/azure/storage/blob/AppendBlobClientBuilder.java [hunk 10]
```diff
@@ -106,28 +126,76 @@ public AppendBlobAsyncClient buildAsyncClient() {
...
         try {
-            this.endpoint = new URL(endpoint);
+            url = new URL(endpoint);
+            this.endpoint = new URL(url.getProtocol() + "://" + url.getAuthority());
+            String path = url.getPath();
+            if (path != null && !path.isEmpty() && !path.equals("/")) {
+                path = path.replaceAll("^/", "").replaceAll("/$", "");
+                String[] segments = path.split("/", 2);
+                if (segments.length != 2) {
+                    throw new IllegalArgumentException("Endpoint should contain 0 or at least 2 path segments");
```
Comment (rickle-msft) [inline storage/client/src/main/java/com/azure/storage/blob/AppendBlobClientBuilder.java]: This is not always true. If the customer has set up a root container, it's possible to have a blobUrl of the format:
myaccount.blob.core.windows.net/blobName

File: storage/client/src/main/java/com/azure/storage/blob/BlobAsyncRawClient.java [hunk 11]
```diff
@@ -256,8 +256,9 @@
      */
     public Mono<DownloadAsyncResponse> download(BlobRange range, BlobAccessConditions accessConditions,
                                              boolean rangeGetContentMD5, Context context) {
-        Boolean getMD5 = rangeGetContentMD5 ? rangeGetContentMD5 : null;
         range = range == null ? new BlobRange(0) : range;
```
[the remark this answers is not in the document]
Comment (rickle-msft) [reply storage/client/src/main/java/com/azure/storage/blob/BlobAsyncRawClient.java]: If you don't specify a range, it'll default to downloading the whole blob. I think the reason we wanted to get an equivalent result without a null object here is because it makes the logic below easier since we check range values.

File: storage/client/src/main/java/com/azure/storage/blob/BlobAsyncClient.java [hunk 12]
```diff
@@ -243,7 +318,7 @@ public PageBlobAsyncClient asPageBlobAsyncClient() {
      * @return
      *      A reactive response containing the blob data.
      */
-    public Flux<ByteBuffer> download() {
+    public Mono<Response<Flux<ByteBuffer>>> download() {
```
[the remark this answers is not in the document]
Comment (jianghaolu) [reply storage/client/src/main/java/com/azure/storage/blob/BlobAsyncClient.java]: I wrapped this one in `Response<T>` primarily because it returns `Flux<ByteBuffer>`, not `Flux<T>` - it's not a paginated operation.

File: storage/client/src/main/java/com/azure/storage/blob/ContainerAsyncClient.java [hunk 13]
```diff
@@ -140,13 +144,66 @@ public AppendBlobAsyncClient getAppendBlobAsyncClient(String blobName) {
...
+     * @param context
+     *         {@code Context} offers a means of passing arbitrary data (key/value pairs) to an
+     *         {@link com.azure.core.http.HttpPipeline}'s policy objects. Most applications do not need to pass
+     *         arbitrary data to the pipeline and can pass {@code Context.NONE} or {@code null}. Each context object is
+     *         immutable. The {@code withContext} with data method creates a new {@code Context} object that refers to its
+     *         parent, forming a linked list.
+     * @return
+     *         true if the container exists, false if it doesn't
+     */
+    public Mono<Response<Boolean>> exists(Context context) {
```
[the remark this answers is not in the document]
Comment (jianghaolu) [reply storage/client/src/main/java/com/azure/storage/blob/ContainerAsyncClient.java]: Are you referring to this method or the `Context` parameter?

File: storage/client/src/main/java/com/azure/storage/blob/AppendBlobClientBuilder.java (hunk 10 above)
Comment (jianghaolu) [reply storage/client/src/main/java/com/azure/storage/blob/AppendBlobClientBuilder.java]: I'm using BlobUrlParts now with UrlParser.

File: storage/client/src/main/java/com/azure/storage/blob/BlobClientBuilder.java [hunk 14]
```diff
@@ -112,22 +132,70 @@ public BlobAsyncClient buildAsyncClient() {
      */
     public BlobClientBuilder endpoint(String endpoint) {
         Objects.requireNonNull(endpoint);
+        URL url;
         try {
-            this.endpoint = new URL(endpoint);
+            url = new URL(endpoint);
```
[the remark this answers is not in the document]
Comment (jianghaolu) [reply storage/client/src/main/java/com/azure/storage/blob/BlobClientBuilder.java]: There turns out to be a utility already - BlobUrlParts can be created from UrlParser.

File: storage/client/src/main/java/com/azure/storage/blob/ContainerAsyncClient.java (hunk 13 above)
[the remark this answers is not in the document]
Comment (alzimmermsft) [reply storage/client/src/main/java/com/azure/storage/blob/ContainerAsyncClient.java]: `Context` parameter as a whole, it was a guideline change a few weeks ago to hide it from the public API as we work through the tracing and overload stories for our clients.

@rickle-msft @jaschrep-msft Are you good with removing this wholesale for this preview?

File: storage/client/src/main/java/com/azure/storage/blob/AccountSASSignatureValues.java (hunk 9 above)
Comment (alzimmermsft) [reply storage/client/src/main/java/com/azure/storage/blob/AccountSASSignatureValues.java]: I think this should be opened as an issue and cleaned up in another preview as this won't change any public interface or functionality.

See #4077

File: storage/client/src/main/java/com/azure/storage/blob/AppendBlobAsyncClient.java [hunk 15]
```diff
@@ -92,21 +94,15 @@ public static AppendBlobClientBuilder appendBlobClientBuilder() {
...
-     *         arbitrary data to the pipeline and can pass {@code Context.NONE} or {@code null}. Each context object is
-     *         immutable. The {@code withContext} with data method creates a new {@code Context} object that refers to
-     *         its parent, forming a linked list.
      *
      * @return
      *      A reactive response containing the information of the created appended blob.
      */
-    public Mono<AppendBlobCreateHeaders> create(BlobHTTPHeaders headers, Metadata metadata,
-                BlobAccessConditions accessConditions, Context context) {
+    public Mono<Response<AppendBlobItem>> create(BlobHTTPHeaders headers, Metadata metadata,
```
Comment (rickle-msft) [inline storage/client/src/main/java/com/azure/storage/blob/AppendBlobAsyncClient.java]: create returns way more information that appedBlock and yet they both return the same type?

File: storage/client/src/main/java/com/azure/storage/blob/AppendBlobAsyncRawClient.java [hunk 16]
```diff
@@ -66,26 +69,20 @@
...
-     *                         {@link com.azure.core.http.HttpPipeline}'s policy objects. Most applications do not need to pass
-     *                         arbitrary data to the pipeline and can pass {@code Context.NONE} or {@code null}. Each context object is
-     *                         immutable. The {@code withContext} with data method creates a new {@code Context} object that refers to
-     *                         its parent, forming a linked list.
      * @return Emits the successful response.
      * @apiNote ## Sample Code \n
      * [!code-java[Sample_Code](../azure-storage-java/src/test/java/com/microsoft/azure/storage/Samples.java?name=append_blob "Sample code for AppendBlobAsyncRawClient.create")] \n
      * For more samples, please see the [Samples file](%https://github.com/Azure/azure-storage-java/blob/master/src/test/java/com/microsoft/azure/storage/Samples.java)
      */
     public Mono<AppendBlobsCreateResponse> create(BlobHTTPHeaders headers, Metadata metadata,
```
Comment (rickle-msft) [inline storage/client/src/main/java/com/azure/storage/blob/AppendBlobAsyncRawClient.java]: What's the difference between Mono<Response<AppendBlobItem>and Mono<AppendBlobsCreateResponse? This seems more confusing than just picking one.

File: storage/client/src/main/java/com/azure/storage/blob/AppendBlobClient.java [hunk 17]
```diff
@@ -121,8 +143,8 @@ public AppendBlobCreateHeaders create(BlobHTTPHeaders headers, Metadata metadata
      * @return
      *      The information of the append blob operation.
      */
-    public AppendBlobAppendBlockHeaders appendBlock(Flux<ByteBuf> data, long length) {
-        return this.appendBlock(data, length, null, null, null);
+    public Response<AppendBlobItem> appendBlock(Flux<ByteBuf> data, long length) {
```
Comment (rickle-msft) [inline storage/client/src/main/java/com/azure/storage/blob/AppendBlobClient.java]: This needs to take an InputStream, not a Flux

File: storage/client/src/main/java/com/azure/storage/blob/AppendBlobClientBuilder.java [hunk 18]
```diff
@@ -60,20 +73,30 @@ public AppendBlobClientBuilder() {
...
+            configuration = ConfigurationManager.getConfiguration();
+        }
         policies.add(new UserAgentPolicy(BlobConfiguration.NAME, BlobConfiguration.VERSION, configuration));
         policies.add(new RequestIdPolicy());
         policies.add(new AddDatePolicy());
-        policies.add(credentials); // This needs to be a different credential type.
+
+        if (sharedKeyCredential != null) {
+            policies.add(new SharedKeyCredentialPolicy(sharedKeyCredential));
+        } else if (tokenCredential != null) {
```
Comment (rickle-msft) [inline storage/client/src/main/java/com/azure/storage/blob/AppendBlobClientBuilder.java]: This is essentially saying if multiple credentials are present, we just pick one. Perhaps we should throw?

File: storage/client/src/main/java/com/azure/storage/blob/AppendBlobClientBuilder.java [hunk 19]
```diff
@@ -106,47 +128,88 @@ public AppendBlobAsyncClient buildAsyncClient() {
...
+    }
+
+    /**
+     * Sets the credential used to authorize requests sent to the service
+     * @param credential authorization credential
      * @return the updated AppendBlobClientBuilder object
      */
-    public AppendBlobClientBuilder credentials(SharedKeyCredentials credentials) {
-        this.credentials = credentials;
+    public AppendBlobClientBuilder credential(SharedKeyCredential credential) {
```
Comment (rickle-msft) [inline storage/client/src/main/java/com/azure/storage/blob/AppendBlobClientBuilder.java]: Is there no base type or interface for credentials? We need all these overloads?

File: storage/client/src/main/java/com/azure/storage/blob/BlobAsyncClient.java [hunk 20]
```diff
@@ -102,9 +121,49 @@ public AppendBlobAsyncClient asAppendBlobAsyncClient() {
      *      A {@link PageBlobAsyncClient} to this resource.
      */
     public PageBlobAsyncClient asPageBlobAsyncClient() {
-        return new PageBlobAsyncClient(this.blobAsyncRawClient.azureBlobStorage);
+        return new PageBlobAsyncClient(new AzureBlobStorageBuilder().url(getBlobUrl().toString()).pipeline(blobAsyncRawClient.azureBlobStorage.httpPipeline()), snapshot);
+    }
+
+    /**
+     * Initializes a {@link ContainerAsyncClient} object pointing to the containing this blob is in. This method does
```
Comment (rickle-msft) [inline storage/client/src/main/java/com/azure/storage/blob/BlobAsyncClient.java]: Typo: "containing" instead of "container"

File: storage/client/src/main/java/com/azure/storage/blob/AppendBlobClientBuilder.java [hunk 21]
```diff
@@ -60,20 +73,30 @@ public AppendBlobClientBuilder() {
         policies = new ArrayList<>();
     }
 
-    /**
-     * Constructs an instance of AppendBlobAsyncClient based on the configurations stored in the appendBlobClientBuilder.
-     * @return a new client instance
-     */
-    private AzureBlobStorageImpl buildImpl() {
+    private AzureBlobStorageBuilder buildImpl() {
```
Comment (rickle-msft) [inline storage/client/src/main/java/com/azure/storage/blob/AppendBlobClientBuilder.java]: This builder also needs to accept a secondary endpoint, and we either need a customer Storage policy to retry against secondaries, or the Core retry policy needs to support it.

File: storage/client/src/main/java/com/azure/storage/blob/BlobAsyncClient.java [hunk 22]
```diff
@@ -296,35 +331,50 @@ public PageBlobAsyncClient asPageBlobAsyncClient() {
...
-                    fstream.close();
+                    channel.close();
                 } catch (IOException e) {
                     throw new UncheckedIOException(e);
                 }
+            });
+    }
+
+    private Mono<BlobRange> getFullBlobRange(BlobAccessConditions accessConditions) {
+        return getProperties(accessConditions).map(rb -> new BlobRange(0, rb.value().blobSize()));
```
Comment (rickle-msft) [inline storage/client/src/main/java/com/azure/storage/blob/BlobAsyncClient.java]: We can't make an extra getProperties call just to get the size. This potentially doubles the number of IO operations. Is there a reason why we didn't just pull the implementation from v11?

Comment (rickle-msft) [reply storage/client/src/main/java/com/azure/storage/blob/BlobAsyncClient.java]: This also does not support etag locking or progress reporting.

File: storage/client/src/main/java/com/azure/storage/blob/BlobAsyncClient.java [hunk 23]
```diff
@@ -296,35 +331,50 @@ public PageBlobAsyncClient asPageBlobAsyncClient() {
...
+                .download(chunk, accessConditions, rangeGetContentMD5)
+                .subscribeOn(Schedulers.elastic())
+                .flatMap(dar -> FluxUtil.bytebufStreamToFile(dar.body(options), channel, chunk.offset() - (range == null ? 0 : range.offset())))
+                .timeout(Duration.ofSeconds(300))
+                .retry(3, throwable -> throwable instanceof IOException || throwable instanceof TimeoutException))
+            .then()
+            .doOnTerminate(() -> {
                 try {
-                    fstream.close();
+                    channel.close();
```
Comment (rickle-msft) [inline storage/client/src/main/java/com/azure/storage/blob/BlobAsyncClient.java]: Why not use Mono.using?

File: storage/client/src/main/java/com/azure/storage/blob/BlobAsyncClient.java [hunk 24]
```diff
@@ -296,35 +331,50 @@ public PageBlobAsyncClient asPageBlobAsyncClient() {
...
-                .doOnNext(byteBuffer -> {
-                    try {
-                        fstream.write(byteBuffer.array());
-                    } catch (IOException e) {
-                        throw new UncheckedIOException(e);
-                    }
-                })
-                .then(),
-            fstream -> {
+                                     boolean rangeGetContentMD5, ReliableDownloadOptions options) {
```
Comment (rickle-msft) [inline storage/client/src/main/java/com/azure/storage/blob/BlobAsyncClient.java]: This should also accept a block size

File: storage/client/src/main/java/com/azure/storage/blob/BlobAsyncRawClient.java [hunk 25]
```diff
@@ -255,32 +225,31 @@
      * For more samples, please see the [Samples file](%https://github.com/Azure/azure-storage-java/blob/master/src/test/java/com/microsoft/azure/storage/Samples.java)
      */
     public Mono<DownloadAsyncResponse> download(BlobRange range, BlobAccessConditions accessConditions,
-                                             boolean rangeGetContentMD5, Context context) {
-        Boolean getMD5 = rangeGetContentMD5 ? rangeGetContentMD5 : null;
+                                             boolean rangeGetContentMD5) {
```
Comment (rickle-msft) [inline storage/client/src/main/java/com/azure/storage/blob/BlobAsyncRawClient.java]: Shouldn't downloadToFile also be on the raw client?

File: storage/client/src/main/java/com/azure/storage/blob/BlobClient.java [hunk 26]
```diff
@@ -91,7 +95,81 @@ public AppendBlobClient asAppendBlobClient() {
...
+    /**
+     * Opens a blob input stream to download the blob.
+     * <p>
+     *
+     * @return An <code>InputStream</code> object that represents the stream to use for reading from the blob.
+     *
+     * @throws StorageException
+     *             If a storage service error occurred.
+     */
+    public final BlobInputStream openInputStream() {
```
Comment (rickle-msft) [inline storage/client/src/main/java/com/azure/storage/blob/BlobClient.java]: Where is openOutputStream?

File: storage/client/src/main/java/com/azure/storage/blob/BlobClient.java [hunk 27]
```diff
@@ -244,17 +314,25 @@ public void download(OutputStream stream) throws IOException {
...
      */
-    public void download(OutputStream stream, ReliableDownloadOptions options, BlobRange range,
-            BlobAccessConditions accessConditions, boolean rangeGetContentMD5, Duration timeout) throws IOException {
-        Flux<ByteBuffer> data = blobAsyncClient
-            .download(range, accessConditions, rangeGetContentMD5, options, null /*context*/);
-
-        data = timeout == null
-            ? data
-            : data.timeout(timeout); //TODO this isn't doing what we want
+    public VoidResponse download(OutputStream stream, ReliableDownloadOptions options, BlobRange range,
```
Comment (rickle-msft) [inline storage/client/src/main/java/com/azure/storage/blob/BlobClient.java]: IIRC we also want a download overload that returns an InputStream

File: storage/client/src/main/java/com/azure/storage/blob/BlockBlobAsyncClient.java [hunk 28]
```diff
@@ -47,6 +63,7 @@
  * object through {@link Mono#toFuture()}.
  */
 public final class BlockBlobAsyncClient extends BlobAsyncClient {
+    static final long BLOB_DEFAULT_UPLOAD_BLOCK_SIZE = 4 * Constants.MB;
```
Comment (rickle-msft) [inline storage/client/src/main/java/com/azure/storage/blob/BlockBlobAsyncClient.java]: This should be public. We should also have a constant BLOB_MAX_UPLOAD_BLOCK_SIZE = 100*Constants.MB

File: storage/client/src/main/java/com/azure/storage/blob/BlockBlobAsyncClient.java [hunk 29]
```diff
@@ -144,23 +161,61 @@ public static BlockBlobClientBuilder builder() {
...
     public Mono<Void> uploadFromFile(String filePath, BlobHTTPHeaders headers, Metadata metadata,
-            BlobAccessConditions accessConditions, Context context) {
-        //TODO make this method smart
-        return this.blockBlobAsyncRawClient
-            .upload(ByteBufFlux.fromPath(Paths.get(filePath)), new File(filePath).length())
-            .then();
+                                     BlobAccessConditions accessConditions, Context context) {
+        AsynchronousFileChannel channel;
+        try {
+            channel = AsynchronousFileChannel.open(Paths.get(filePath), StandardOpenOption.READ);
```
Comment (rickle-msft) [inline storage/client/src/main/java/com/azure/storage/blob/BlockBlobAsyncClient.java]: Similar to the download to file method, we should:

- Use Mono.using()
- support progres reporting
- support the possibility of doing a single putBlob

File: storage/client/src/main/java/com/azure/storage/blob/BlockBlobAsyncClient.java [hunk 30]
```diff
@@ -134,33 +150,63 @@ public static BlockBlobClientBuilder builder() {
...
+        } catch (IOException e) {
+            return Mono.error(e);
+        }
+        final SortedMap<Long, String> blockIds = new TreeMap<>();
+        return Flux.fromIterable(sliceFile(filePath))
+            .doOnNext(chunk -> blockIds.put(chunk.offset(), getBlockID()))
+            .flatMap(chunk -> {
```
Comment (rickle-msft) [inline storage/client/src/main/java/com/azure/storage/blob/BlockBlobAsyncClient.java]: I know you mentioned that concatMapEager in Rx had some weird performance behavior. Is the same true of flatMapSequential in Reactor? I think it might be preferable to not have state external to the reactive pipeline, but that's kind of moot.

File: storage/client/src/main/java/com/azure/storage/blob/BlockBlobAsyncClient.java [hunk 31]
```diff
@@ -184,9 +230,9 @@ public static BlockBlobClientBuilder builder() {
      * @return
      *      A reactive response signalling completion.
      */
-    public Mono<Void> stageBlock(String base64BlockID, Flux<ByteBuf> data,
+    public Mono<Response<BlockBlobItem>> stageBlock(String base64BlockID, Flux<ByteBuf> data,
```
Comment (rickle-msft) [inline storage/client/src/main/java/com/azure/storage/blob/BlockBlobAsyncClient.java]: I was under the impression that only the Raw clients (or the Raw methods) accept Flux<ByteBuf> and the ones on the "simple" clients would accept/return Flux<ByteBuffer>

File: storage/client/src/main/java/com/azure/storage/blob/StorageAsyncClient.java [hunk 32]
```diff
@@ -82,10 +78,52 @@ public static StorageClientBuilder storageClientBuilder() {
...
+
+    /**
+     * Creates a new container within a storage account. If a container with the same name already exists, the operation
+     * fails. For more information, see the
+     * <a href="https://docs.microsoft.com/rest/api/storageservices/create-container">Azure Docs</a>.
+     *
+     * @param containerName Name of the container to create
+     * @return A response containing a {@link ContainerAsyncClient} used to interact with the container created.
+     */
+    public Mono<Response<ContainerAsyncClient>> createContainer(String containerName) {
```
Comment (jaschrep-msft) [inline storage/client/src/main/java/com/azure/storage/blob/StorageAsyncClient.java]: If we're going to be able to create containers from the parent client, we need to discuss how to provide a similar experience for blobs. Since we're prioritizing block blob work right now, that's a bit tricky, as block blobs are the only blob type that don't need to be explicitly created upfront, but can just be uploaded to. Additionally, put blob rest calls will update (overwrite) an existing blob, while create container will fail if the container already exists, so that may influence our design.

File: storage/client/src/main/java/com/azure/storage/blob/models/BlockBlobItem.java [hunk 33]
```diff
@@ -0,0 +1,69 @@
+package com.azure.storage.blob.models;
+
+import com.azure.core.implementation.util.ImplUtils;
+
+import java.time.OffsetDateTime;
+
+public class BlockBlobItem {
```
Comment (jaschrep-msft) [inline storage/client/src/main/java/com/azure/storage/blob/models/BlockBlobItem.java]: This appears to be just the class AppendBlobItem. It contains fields specific to append blobs.

File: storage/client/src/main/java/com/azure/storage/blob/AppendBlobClientBuilder.java [hunk 34]
```diff
@@ -106,47 +128,88 @@ public AppendBlobAsyncClient buildAsyncClient() {
...
+        URL url;
         try {
-            this.endpoint = new URL(endpoint);
-        } catch (MalformedURLException ex) {
-            throw new IllegalArgumentException("The Azure Storage Queue endpoint url is malformed.");
+            url = new URL(endpoint);
+            BlobURLParts parts = URLParser.parse(url);
+            this.endpoint = new URL(parts.scheme() + "://" + parts.host());
+            this.containerName = parts.containerName();
+            this.blobName = parts.blobName();
```
[the remark this answers is not in the document]
Comment (jianghaolu) [reply storage/client/src/main/java/com/azure/storage/blob/AppendBlobClientBuilder.java]: N/A for append blob

File: storage/client/src/main/java/com/azure/storage/blob/AppendBlobClientBuilder.java [hunk 35]
```diff
@@ -106,47 +128,88 @@ public AppendBlobAsyncClient buildAsyncClient() {
...
+    /**
+     * Sets the name of the blob this client is connecting to.
+     * @param blobName the name of the blob
+     * @return the updated AppendBlobClientBuilder object
+     */
+    public AppendBlobClientBuilder blobName(String blobName) {
+        this.blobName = blobName;
+        return this;
+    }
+
```
[the remark this answers is not in the document]
Comment (jianghaolu) [reply storage/client/src/main/java/com/azure/storage/blob/AppendBlobClientBuilder.java]: N/A for append blob

File: storage/client/src/main/java/com/azure/storage/blob/ContainerAsyncClient.java [hunk 36]
```diff
@@ -140,13 +146,50 @@ public AppendBlobAsyncClient getAppendBlobAsyncClient(String blobName) {
...
         }
     }
 
+    /**
+     * Gets if the container this client represents exists in the cloud.
+     *
+     * @return
+     *         true if the container exists, false if it doesn't
+     */
+    public Mono<Response<Boolean>> exists() {
```
[the remark this answers is not in the document]
Comment (jianghaolu) [reply storage/client/src/main/java/com/azure/storage/blob/ContainerAsyncClient.java]: Talked to Jonathan - he liked neither returning Mono<Boolean> nor calling it `checkExistence()`. We should probably discuss this more after this preview.

File: storage/client/src/main/java/com/azure/storage/blob/ContainerClientBuilder.java [hunk 37]
```diff
@@ -127,45 +135,82 @@ public ContainerAsyncClient buildAsyncClient() {
...
     public ContainerClientBuilder endpoint(String endpoint) {
         Objects.requireNonNull(endpoint);
+        URL url;
         try {
-            this.endpoint = new URL(endpoint);
+            url = new URL(endpoint);
+            this.endpoint = new URL(url.getProtocol() + "://" + url.getAuthority());
+            String path = url.getPath();
+            if (path != null && !path.isEmpty() && !path.equals("/")) {
+                path = path.replaceAll("^/", "").replaceAll("/$", "");
```
[the remark this answers is not in the document]
Comment (jianghaolu) [reply storage/client/src/main/java/com/azure/storage/blob/ContainerClientBuilder.java]: Talked in person.

File: storage/client/src/main/java/com/azure/storage/blob/DownloadResponse.java [hunk 38]
```diff
@@ -1,5 +1,6 @@
 package com.azure.storage.blob;
 
+import com.azure.storage.blob.models.ReliableDownloadOptions;
```
[the remark this answers is not in the document]
Comment (jianghaolu) [reply storage/client/src/main/java/com/azure/storage/blob/DownloadResponse.java]: Talked in person.

File: storage/client/src/main/java/com/azure/storage/blob/models/BlockBlobItem.java (hunk 33 above)
Comment (jianghaolu) [reply storage/client/src/main/java/com/azure/storage/blob/models/BlockBlobItem.java]: Unrelated items removed.

File: storage/client/src/main/java/com/azure/storage/blob/AppendBlobAsyncClient.java (hunk 15 above)
Comment (jianghaolu) [reply storage/client/src/main/java/com/azure/storage/blob/AppendBlobAsyncClient.java]: This is written based on https://gist.github.com/jaschrep-msft/59f5d4312d0ef555f5ed454c9a504a13. All the important headers returned in the raw create method are included in AppendBlobItem class.

File: storage/client/src/main/java/com/azure/storage/blob/AppendBlobAsyncRawClient.java (hunk 16 above)
Comment (jianghaolu) [reply storage/client/src/main/java/com/azure/storage/blob/AppendBlobAsyncRawClient.java]: This is the raw client hidden from users and to be removed after preview 1.

File: storage/client/src/main/java/com/azure/storage/blob/AppendBlobClientBuilder.java (hunk 19 above)
Comment (jianghaolu) [reply storage/client/src/main/java/com/azure/storage/blob/AppendBlobClientBuilder.java]: Unfortunately they all need different credentials policy to work.

File: storage/client/src/main/java/com/azure/storage/blob/BlobAsyncRawClient.java (hunk 25 above)
Comment (jianghaolu) [reply storage/client/src/main/java/com/azure/storage/blob/BlobAsyncRawClient.java]: The raw client isn't exposed to users.

File: storage/client/src/main/java/com/azure/storage/blob/BlobClient.java (hunk 26 above)
Comment (jianghaolu) [reply storage/client/src/main/java/com/azure/storage/blob/BlobClient.java]: output streams depend on the blob type so they are on block/append/page blob clients

File: storage/client/src/main/java/com/azure/storage/blob/BlobClient.java (hunk 27 above)
Comment (jianghaolu) [reply storage/client/src/main/java/com/azure/storage/blob/BlobClient.java]: I thought we talked about this and agreed not to do it for this preview? But right now it should as simple as returning the BlobInputStream. Either way I'll leave this item for now due to time constraints and you guys can add if needed.

File: storage/client/src/main/java/com/azure/storage/blob/BlockBlobAsyncClient.java (hunk 31 above)
Comment (jianghaolu) [reply storage/client/src/main/java/com/azure/storage/blob/BlockBlobAsyncClient.java]: Fixed.

File: storage/client/src/main/java/com/azure/storage/blob/StorageAsyncClient.java (hunk 32 above)
Comment (jianghaolu) [reply storage/client/src/main/java/com/azure/storage/blob/StorageAsyncClient.java]: As James pointed out, `createBlob()` method on a container client doesn't make sense for a block blob. Not sure what to do, leaving it for discussions after I'm OOF.

File: storage/client/src/main/java/com/azure/storage/blob/BlobAsyncClient.java (hunk 22 above)
Comment (jianghaolu) [reply storage/client/src/main/java/com/azure/storage/blob/BlobAsyncClient.java]: This is called only once for each large file download, how is it doubling the number of IOs? If the files are really small, then yes - but without the full length the client is not able to parallelize the download work. The best way to avoid it is to provide the `BlobRange` parameter and I'll document it here.

Comment (jianghaolu) [reply storage/client/src/main/java/com/azure/storage/blob/BlobAsyncClient.java]: I don't understand what is etag locking so feel free to contribute. What kind of progress reporting are you looking for?

File: storage/client/src/main/java/com/azure/storage/blob/BlobAsyncClient.java (hunk 23 above)
Comment (jianghaolu) [reply storage/client/src/main/java/com/azure/storage/blob/BlobAsyncClient.java]: Changed to Mono.using.

File: storage/client/src/main/java/com/azure/storage/blob/BlockBlobAsyncClient.java (hunk 30 above)
Comment (jianghaolu) [reply storage/client/src/main/java/com/azure/storage/blob/BlockBlobAsyncClient.java]: Theoretically it will work - but I was worried about its buffering so decided to go the dumb but works-for-sure way. We can test it more and see if flatMapSequential helps simply this after preview 1.

File: storage/client/src/main/java/com/azure/storage/blob/BlockBlobAsyncClient.java (hunk 28 above)
Comment (jianghaolu) [reply storage/client/src/main/java/com/azure/storage/blob/BlockBlobAsyncClient.java]: Added and checked in uploadFromFile.

File: storage/client/src/main/java/com/azure/storage/blob/BlockBlobAsyncClient.java (hunk 29 above)
Comment (jianghaolu) [reply storage/client/src/main/java/com/azure/storage/blob/BlockBlobAsyncClient.java]: Same question for progress reporting. For a single putBlob, I believe it's the upload() method. Otherwise addressed.

File: storage/client/src/main/java/com/azure/storage/blob/AppendBlobClientBuilder.java (hunk 21 above)
Comment (jianghaolu) [reply storage/client/src/main/java/com/azure/storage/blob/AppendBlobClientBuilder.java]: The retry policy and options are being migrated.

File: storage/client/src/main/java/com/azure/storage/blob/BlockBlobClient.java [hunk 39]
```diff
@@ -154,7 +188,7 @@ public void uploadFromFile(String filePath) throws IOException {
 
     public void uploadFromFile(String filePath, BlobHTTPHeaders headers, Metadata metadata,
             BlobAccessConditions accessConditions, Duration timeout) throws IOException {
-        Mono<Void> upload = this.blockBlobAsyncClient.uploadFromFile(filePath, headers, metadata, accessConditions, null);
+        Mono<Void> upload = this.blockBlobAsyncClient.uploadFromFile(filePath, headers, metadata, accessConditions);
```
Comment (jaschrep-msft) [inline storage/client/src/main/java/com/azure/storage/blob/BlockBlobClient.java]: So you removed the Context parameter from the async method, and so removed it from this call. But then you added a blockSize integer parameter to the method, and didn't add it to this call. This doesn't compile.

File: storage/client/src/main/java/com/azure/storage/blob/AppendBlobClientBuilder.java (hunk 35 above)
[the remark this answers is not in the document]
Comment (jaschrep-msft) [reply storage/client/src/main/java/com/azure/storage/blob/AppendBlobClientBuilder.java]: Append blobs can have snapshots, we need to support an AppendBlobClient being able to read from one.

File: storage/client/src/main/java/com/azure/storage/blob/BlockBlobAsyncClient.java [hunk 40]
```diff
@@ -134,33 +152,77 @@ public static BlockBlobClientBuilder builder() {
...
+        return this.uploadFromFile(filePath, BLOB_DEFAULT_UPLOAD_BLOCK_SIZE, null, null, null);
     }
 
-    public Mono<Void> uploadFromFile(String filePath, BlobHTTPHeaders headers, Metadata metadata,
-            BlobAccessConditions accessConditions, Context context) {
-        //TODO make this method smart
-        return this.blockBlobAsyncRawClient
-            .upload(ByteBufFlux.fromPath(Paths.get(filePath)), new File(filePath).length())
-            .then();
+    public Mono<Void> uploadFromFile(String filePath, Integer blockSize, BlobHTTPHeaders headers, Metadata metadata,
```
Comment (rickle-msft) [inline storage/client/src/main/java/com/azure/storage/blob/BlockBlobAsyncClient.java]: I thought I left a comment (though I can't find it now) that we should have these on the Raw client as well. in addition, I noticed CommonRestResponse was deleted. What do you guys think should be the return type for this on the raw client so that customers can access all the headers (because it could either be a putBlob or putBlockList)? Or is the argument that the raw client only has methods that mirror the rest api so we don't have convenience things like uploadFromFile

Comment (jaschrep-msft) [reply storage/client/src/main/java/com/azure/storage/blob/BlockBlobAsyncClient.java]: The raw clients are hidden, I thought. The customer can't interact with them and (I believe) they will be removed before GA for the logic to be re-integrated into the async client. There doesn't seem to be a reason to put these methods on there and it feels like more to maintain.

File: storage/client/src/main/java/com/azure/storage/blob/AppendBlobClientBuilder.java (hunk 35 above)
[the remark this answers is not in the document]
Comment (jianghaolu) [reply storage/client/src/main/java/com/azure/storage/blob/AppendBlobClientBuilder.java]: Supported.

File: storage/client/src/main/java/com/azure/storage/blob/BlockBlobClient.java (hunk 39 above)
Comment (jianghaolu) [reply storage/client/src/main/java/com/azure/storage/blob/BlockBlobClient.java]: Latest commit has this fixed.

File: storage/client/src/main/java/com/azure/storage/blob/BlobAsyncRawClient.java [hunk 41]
```diff
@@ -255,32 +228,31 @@
...
-            .withCount(range.count())
-            .withETag(accessConditions.modifiedAccessConditions().ifMatch());
+            .offset(range.offset())
+            .count(range.count())
+            .eTag(accessConditions.modifiedAccessConditions().ifMatch());
 
         // TODO: range is BlobRange but expected as String
         // TODO: figure out correct response
         return postProcessResponse(this.azureBlobStorage.blobs().downloadWithRestResponseAsync(
             null, null, null, null, null, range.toHeaderValue(), getMD5,
```
[the remark this answers is not in the document]
Comment (jianghaolu) [reply storage/client/src/main/java/com/azure/storage/blob/BlobAsyncRawClient.java]: I believe you've fixed this.

File: storage/client/src/main/java/com/azure/storage/blob/BlockBlobAsyncClient.java (hunk 40 above)
Comment (jianghaolu) [reply storage/client/src/main/java/com/azure/storage/blob/BlockBlobAsyncClient.java]: Agree with James.

File: storage/client/src/main/java/com/azure/storage/blob/BlobAsyncClient.java [hunk 42]
```diff
@@ -51,15 +66,19 @@
...
     /**
      * Package-private constructor for use by {@link BlobClientBuilder}.
-     * @param azureBlobStorage the API client for blob storage API
+     * @param azureBlobStorageBuilder the API client builder for blob storage API
      */
-    BlobAsyncClient(AzureBlobStorageImpl azureBlobStorage) {
-        blobAsyncRawClient = new BlobAsyncRawClient(azureBlobStorage);
+    BlobAsyncClient(AzureBlobStorageBuilder azureBlobStorageBuilder, String snapshot) {
+        this.blobAsyncRawClient = new BlobAsyncRawClient(azureBlobStorageBuilder.build());
+        this.snapshot = snapshot;
```
[the remark this answers is not in the document]
Comment (jianghaolu) [reply storage/client/src/main/java/com/azure/storage/blob/BlobAsyncClient.java]: Talked to James in person - this behavior is having the equivalent effect of appending the snapshot on the URL. And since we are already parsing the URL to get the container name and blob name, this does not introduce a performance overhead.
Also, this is also actually preferred, compare to the previous way to doing it, in the way that having a query parameter decoupled from the base URL often help prevent potential URL parsing issues, when another query parameter needs to be appended.

File: storage/client/src/test/java/com/azure/storage/blob/AppendBlobAPITest.groovy [hunk 43]
```diff
@@ -0,0 +1,519 @@
...
+
+        then:
+        def e = thrown(Exception)
+        exceptionType.isInstance(e)
+
+        where:
+        data                        | dataSize            | exceptionType
+        null                        | defaultDataSize     | NullPointerException
+        defaultInputStream.get()    | defaultDataSize + 1 | IndexOutOfBoundsException
+        //defaultInputStream.get()    | defaultDataSize - 1 | StorageException
```
[the remark this answers is not in the document]
Comment (alzimmermsft) [reply storage/client/src/test/java/com/azure/storage/blob/AppendBlobAPITest.groovy]: That last test runs successfully as it will read all but the last byte of data from the input stream and send that off to the service.

Thoughts on allow this?

[the remark this answers is not in the document]
Comment (jaschrep-msft) [reply storage/client/src/test/java/com/azure/storage/blob/AppendBlobAPITest.groovy]: I'm not sure what the original test was trying to trip. @rickle-msft would know best.

My guess is that the entire stream was flushed to the network, but we sent more than we said we would, and so the service rejected the call. It seems that is no longer the behavior, if this test is passing.

File: storage/client/src/test/java/com/azure/storage/blob/BlobAPITest.groovy [hunk 44]
```diff
@@ -166,39 +173,43 @@ class BlobAPITest extends APISpec {
...
+            .leaseAccessConditions(new LeaseAccessConditions().leaseId(leaseID))
+            .modifiedAccessConditions(new ModifiedAccessConditions()
                 .ifModifiedSince(modified)
                 .ifUnmodifiedSince(unmodified)
                 .ifMatch(match)
-                .ifNoneMatch(noneMatch))
+                .ifNoneMatch(setupBlobMatchCondition(bu, noneMatch)))
+
+        when:
+        bu.download(new ByteArrayOutputStream(), null, null, bac, false, null).statusCode() == 206
```
[the remark this answers is not in the document]
Comment (alzimmermsft) [reply storage/client/src/test/java/com/azure/storage/blob/BlobAPITest.groovy]: Removed check for status code, if we got back a valid response the test would have failed due to the expected StorageException

**Comment by jaschrep-msft** [comment]
Will open an issue to turn linting back on.

File: storage/client/src/test/java/com/azure/storage/blob/AppendBlobAPITest.groovy (hunk 43 above)
[the remark this answers is not in the document]
Comment (anuchandy) [reply storage/client/src/test/java/com/azure/storage/blob/AppendBlobAPITest.groovy]: Created an issue to track/discuss this https://github.com/Azure/azure-sdk-for-java/issues/4193. 

Context:

UnexpectedLengthException was an exception from v2 runtime, we don't have this exception in new preview runtime. In v2 this exception was thrown from our own implementation of netty-rx-adapter. For new runtime we use third party netty-reactor-layer, we should be able to apply an operator to the content flux before passing it to netty-reactor-layer.
