### PR TITLE
Encoding URL for rename source file

### LINKED ISSUE #37777: [BUG] Permission error on renaming file in Azure File Storage
**Describe the bug**
The code was working fine from last 1-2 years and started getting exception today when trying to move file using rename() method.

***Exception or Stack Trace***
```
If you are using a StorageSharedKeyCredential, and the server returned an error message that says 'Signature did not match', you can compare the string to sign with the one generated by the SDK. To log the string to sign, pass in the context key value pair 'Azure-Storage-Log-String-To-Sign': true to the appropriate method call.
If you are using a SAS token, and the server returned an error message that says 'Signature did not match', you can compare the string to sign with the one generated by the SDK. To log the string to sign, pass in the context key value pair 'Azure-Storage-Log-String-To-Sign': true to the appropriate generateSas method call.
Please remember to disable 'Azure-Storage-Log-String-To-Sign' before going to production as this string can potentially contain PII.
Status code 403, "﻿<?xml version="1.0" encoding="utf-8"?><Error><Code>AuthenticationFailed</Code><Message>Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
RequestId:cac6a78f-301a-0063-7e26-1d18ed000000
Time:2023-11-22T09:31:34.2594142Z</Message><AuthenticationErrorDetail>The MAC signature found in the HTTP request 'NQpY6dIwGMXpgOp+3wkBoLFxzDr/u0TNA/dvkbDJ2a4=' is not the same as any computed signature. Server used following string to sign: 'PUT
```
 
 
 
Wed, 22 Nov 2023 09:31:34 GMT

**To Reproduce**

Using following version :
`azure-storage-file-share/12.16.1/azure-storage-file-share-12.16.1-sources.jar!/com/azure/storage/file/share/ShareFileClient.java`

Just run this :
StorageSharedKeyCredential storageCredentials = new StorageSharedKeyCredential(accountName,accessKey);
        }
        this.cloudStorageAccount = new ShareServiceClientBuilder()
                .endpoint("https://" + accountName + ".file.core.windows.net")
                .credential(storageCredentials)
                .buildClient();
`
//// Get any cloud file and invoke rename
cloudFile.rename(destinationPath);`

other opertaions like, copy, delete etc. works fine

***Code Snippet***
Add the code snippet that causes the issue.

**Expected behavior**
Should move successfully wihtout any error.

**Screenshots**

**Setup (please complete the following information):**
 - IDE: [e.g. IntelliJ]
 - Library/Libraries: [e.g. com.azure:azure-core:1.16.0 (groupId:artifactId:version)]
 - Java version: [e.g. 8] 
 - App Server/Environment: [e.g. Tomcat, WildFly, Azure Function, Apache Spark, Databricks, IDE plugin or anything special]
 - Frameworks: [e.g. Spring Boot, Micronaut, Quarkus, etc] 

If you suspect a dependency version mismatch (e.g. you see `NoClassDefFoundError`, `NoSuchMethodError` or similar), please check out [Troubleshoot dependency version conflict article](https://aka.ms/azsdk/java/dependency/troubleshoot) first. If it doesn't provide solution for the problem, please provide:
- verbose dependency tree (`mvn dependency:tree -Dverbose`)
- exception message, full stack trace, and any available logs

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

### PR DESCRIPTION
**Pull request by ibrahimrabab**
# Description

resolves #37777

SDK could not handle when source file contained unicode escape character "\u200B", adding same logic as beginCopy to encode the source file url before calling rename().

### CODE REVIEW

File: sdk/storage/azure-storage-file-share/src/test/java/com/azure/storage/file/share/FileApiTests.java [hunk 1]
```diff
@@ -2416,6 +2416,16 @@ public void renameMin() {
...
     }
 
+    @RequiredServiceVersion(clazz = ShareServiceVersion.class, min = "2021-04-10")
+    @ParameterizedTest
+    @ValueSource(strings = {"\u200B", "\u200C", "\u200D", "\uFEFF"})
+    public void renameWithUnicodeChars(String specialChar) {
+        ShareFileClient fileClient = shareClient.getFileClient("test-file-source" + specialChar + " pdf.txt");
+        fileClient.create(512);
+        ShareFileClient destClient = fileClient.rename("test-file-destination" + specialChar + " pdf.txt");
+        assertNotNull(destClient);
```
Comment (alzimmermsft) [inline sdk/storage/azure-storage-file-share/src/test/java/com/azure/storage/file/share/FileApiTests.java:2426]: Is there any validation we want to do on the destination client name?

**Review by alzimmermsft — APPROVED** [review]

File: sdk/storage/azure-storage-file-share/src/test/java/com/azure/storage/file/share/FileApiTests.java (hunk 1 above)
Comment (ibrahimrabab) [reply sdk/storage/azure-storage-file-share/src/test/java/com/azure/storage/file/share/FileApiTests.java:2427]: Adding an assertion to make sure the special characters are included in the destination client.
