### PR TITLE
Move cache miss errors to info level

### LINKED ISSUE #38300: MsalClientException exception thrown when token not found in cache
**Describe the bug**
When a token is not found in the in-memory cache then Azure identity log it as an MSAL exception.
The log level is a bit misleading if there is a cache miss. A warning level log might be better suited than an error log.

Or is it that I am missing something to configure it properly to avoid `ERROR` level log on cache miss?

***Exception or Stack Trace***
12:40:39.710 [ForkJoinPool.commonPool-worker-1] DEBUG c.m.a.m.ConfidentialClientApplication - [Correlation ID: f1f20e6d-42d7-4b54-baa8-7f74934320e0] Execution of class com.microsoft.aad.msal4j.AcquireTokenSilentSupplier failed.
```
com.microsoft.aad.msal4j.MsalClientException: Token not found in the cache
	at com.microsoft.aad.msal4j.AcquireTokenSilentSupplier.execute(AcquireTokenSilentSupplier.java:75)
	at com.microsoft.aad.msal4j.AuthenticationResultSupplier.get(AuthenticationResultSupplier.java:69)
	at com.microsoft.aad.msal4j.AuthenticationResultSupplier.get(AuthenticationResultSupplier.java:18)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
        ...
```

**To Reproduce**
 - Added code snippet to reproduce

***Code Snippet***
Add the code snippet that causes the issue.
```
                // create a clientCertificateCredential
                ClientCertificateCredential clientCertificateCredential = new ClientCertificateCredentialBuilder()
                        .tenantId(<Tenant_Id>)
                        .clientId(<Client_Id>)
                        .pemCertificate(<Certificate_Path>)
                        .sendCertificateChain(true)
                        .additionallyAllowedTenants("*")
                        .build();

                // create SecretClient using above credentials
                SecretClient client = new SecretClientBuilder()
                        .vaultUrl(<Vault_Url>)
                        .credential(clientCertificateCredential)
                        .buildClient();

                // get KV secret
                KeyVaultSecret spClientIdKvSecret;
                try {
                    spClientIdKvSecret = client.getSecret(<SECRET_NAME>);
                } catch (Exception ex) {
                    log.error("Unable to fetch service principal client ID secret from customer {} KV. Exception: {}",
                            destConfig.getAkvUrl(), getStackTrace(httpEx));
                    throw new ConfigurationException(format("Unable to fetch service principal client ID secret from customer %s KV.", destConfig.getAkvUrl()), httpEx);
                }
```

**Expected behavior**
Logging cache miss at a warning level might be better than logging it at error level.

**Screenshots**
NA

**Setup (please complete the following information):**
- OS: Windows 11
- IDE: IntelliJ
- Library/Libraries: com.azure:azure-identity:1.8.2
- Java version: 8
- App Server/Environment: JVM
- Frameworks: NA

**Additional context**
NA

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

### PR DESCRIPTION
**Pull request by billwert**
Customer reports spurious error messages for simple cache misses from MSAL. We'll catch those errors and log them at the INFO level instead of ERROR.

This only applies to sync cases. In async cases we already suppress the error entirely.

Fixes #38300

### CODE REVIEW

File: sdk/identity/azure-identity/src/main/java/com/azure/identity/ClientAssertionCredential.java [hunk 1]
```diff
@@ -119,8 +119,10 @@ public Mono<AccessToken> getToken(TokenRequestContext request) {
     public AccessToken getTokenSync(TokenRequestContext request) {
         try {
             AccessToken token = identitySyncClient.authenticateWithConfidentialClientCache(request);
-            LoggingUtil.logTokenSuccess(LOGGER, request);
-            return token;
+            if (token != null) {
+                LoggingUtil.logTokenSuccess(LOGGER, request);
+                return token;
+            }
```
Comment (alzimmermsft) [inline sdk/identity/azure-identity/src/main/java/com/azure/identity/ClientAssertionCredential.java:125]: Aside from the logging change, was this a bug before if a null token was returned here that we didn't continue to the next possible token retrieval call?

File: sdk/identity/azure-identity/src/main/java/com/azure/identity/implementation/IdentitySyncClient.java [hunk 2]
```diff
@@ -226,7 +238,13 @@ public MsalToken authenticateWithPublicClientCache(TokenRequestContext request,
         } catch (MalformedURLException e) {
             throw LOGGER.logExceptionAsError(new RuntimeException(e.getMessage(), e));
         } catch (ExecutionException | InterruptedException e) {
-            throw LOGGER.logExceptionAsError(new ClientAuthenticationException(e.getMessage(), null, e));
+            // Cache misses should not throw an exception, but should log.
+            if (e.getMessage().contains("Token not found in the cache")) {
+                LOGGER.info("Token not found in the MSAL cache.");
```
Comment (alzimmermsft) [inline sdk/identity/azure-identity/src/main/java/com/azure/identity/implementation/IdentitySyncClient.java:243]: INFO or VERBOSE? I'm thinking VERBOSE as this is really nitty-gritty information that is super low level.

File: sdk/identity/azure-identity/src/main/java/com/azure/identity/ClientCertificateCredential.java [hunk 3]
```diff
@@ -148,8 +148,10 @@ public Mono<AccessToken> getToken(TokenRequestContext request) {
     public AccessToken getTokenSync(TokenRequestContext request) {
         try {
             AccessToken token = identitySyncClient.authenticateWithConfidentialClientCache(request);
-            LoggingUtil.logTokenSuccess(LOGGER, request);
-            return token;
+            if (token != null) {
+                LoggingUtil.logTokenSuccess(LOGGER, request);
+                return token;
```
Comment (g2vinay) [inline sdk/identity/azure-identity/src/main/java/com/azure/identity/ClientCertificateCredential.java:153]: Can msal return null here ? I don't think they do, but if they do, its a bug.
If we got a token response, it is expected to be a non null and a success scenario.
So, the null check seems redundant.

File: sdk/identity/azure-identity/src/main/java/com/azure/identity/implementation/IdentitySyncClient.java (hunk 2 above)
Comment (g2vinay) [reply sdk/identity/azure-identity/src/main/java/com/azure/identity/implementation/IdentitySyncClient.java:243]: Yeah, Debug scenario probably sounds better for this.
This will also align with the goal of making our logs less noisy.

Comment (billwert) [reply sdk/identity/azure-identity/src/main/java/com/azure/identity/implementation/IdentitySyncClient.java:243]: I can go either way. It seemed like something a customer might be curious about so I went with INFO. I think of VERBOSE as for SDK devs basically.

File: sdk/identity/azure-identity/src/main/java/com/azure/identity/ClientAssertionCredential.java (hunk 1 above)
Comment (billwert) [reply sdk/identity/azure-identity/src/main/java/com/azure/identity/ClientAssertionCredential.java:125]: No. It either returned a token or threw an exception. I'm adding the null state to represent the cache miss.

File: sdk/identity/azure-identity/src/main/java/com/azure/identity/ClientCertificateCredential.java (hunk 3 above)
Comment (billwert) [reply sdk/identity/azure-identity/src/main/java/com/azure/identity/ClientCertificateCredential.java:153]: I added returning null in the case where we do not get a token from the cache.

File: sdk/identity/azure-identity/src/main/java/com/azure/identity/implementation/IdentitySyncClient.java (hunk 2 above)
Comment (billwert) [reply sdk/identity/azure-identity/src/main/java/com/azure/identity/implementation/IdentitySyncClient.java]: made it verbose.

File: sdk/identity/azure-identity/src/main/java/com/azure/identity/ClientCertificateCredential.java (hunk 3 above)
Comment (g2vinay) [reply sdk/identity/azure-identity/src/main/java/com/azure/identity/ClientCertificateCredential.java:153]: if there's no token to return, then an exception will get thrown I believe from Msal.
So, in what scenario do we get null back for token ?

**Review by g2vinay — APPROVED** [review]
