### PR TITLE
Retry overhaul

### LINKED ISSUE #3894: [Event Hubs] Rename `Retry` to `RetryPolicy`
Rename "Retry" to "RetryPolicy"

### LINKED ISSUE #4042: [Event Hubs] Investigate Retry surface area
* The Retry policy has an interesting API surface area. From feedback: https://github.com/Azure/azure-sdk-for-java/pull/3655#discussion_r296132801
  ```java
  class Retry {
     public Duration getNextRetryInterval(Exception lastException, Duration remainingTime);
  }
  ```

### LINKED ISSUE #4136: [Event Hubs] Clone retry policy and other builder parameters
* If any of the parameters are mutable, we should create a clone of them before creating the client/options/etc.

### LINKED ISSUE #4262: [Event Hubs] Add support for individual send message Retry
* For each send operation, there is a time we wait between sending a message and waiting for an acknowledgement. Currently, it is set to operationTimeout. We want to add this to a retry policy.
* Related #4042

### LINKED ISSUE #4308: [Event Hubs] Add fixed retry
Add implementation for fixed retry

### PR DESCRIPTION
**Pull request by conniey**
This PR is an overhaul of the existing Retry for azure-core-amqp. In addition, we add support for retrying not just send, but for any operation (ie. when an AMQP connection, link, session fails for creation).

Features:
* Renames Retry -> RetryPolicy to align with other language teams.
  * A lot of the changed files come from this file rename.
* Adds RetryOptions
* Removes .timeout() with RetryOptions.tryTimeout()
* Moves BatchOptions into model package class (unrelated to retry).

Fixes #4262
Fixes #4308

### CODE REVIEW

File: sdk/core/azure-core-amqp/src/main/java/com/azure/core/amqp/RetryOptions.java [hunk 1]
```diff
@@ -0,0 +1,184 @@
...
+     */
+    public RetryOptions delay(Duration delay) {
+        this.delay = delay;
+        return this;
+    }
+
+    /**
+     * Sets the maximum permissible delay between retry attempts.
+     *
+     * @param maximumDelay the maximum permissible delay between retry attempts.
```
Comment (joshfree) [inline sdk/core/azure-core-amqp/src/main/java/com/azure/core/amqp/RetryOptions.java]: nit: The

File: sdk/core/azure-core-amqp/src/main/java/com/azure/core/amqp/RetryOptions.java [hunk 2]
```diff
@@ -0,0 +1,184 @@
...
+    private Duration delay;
+    private Duration maxDelay;
+    private Duration tryTimeout;
+    private RetryMode retryMode;
+
+    /**
+     * Creates an instance with the default retry options set.
+     */
+    public RetryOptions() {
+        maxRetries = 3;
```
Comment (joshfree) [inline sdk/core/azure-core-amqp/src/main/java/com/azure/core/amqp/RetryOptions.java]: how did we decide on the defaults?

File: sdk/core/azure-core-amqp/src/main/java/com/azure/core/amqp/RetryPolicy.java [hunk 3]
```diff
@@ -0,0 +1,147 @@
...
+import java.util.Objects;
+import java.util.concurrent.ThreadLocalRandom;
+import java.util.concurrent.TimeoutException;
+
+import static com.azure.core.amqp.exception.ErrorCondition.SERVER_BUSY_ERROR;
+
+/**
+ * An abstract representation of a policy to govern retrying of messaging operations.
+ */
+public abstract class RetryPolicy implements Cloneable {
```
Comment (srnagar) [inline sdk/core/azure-core-amqp/src/main/java/com/azure/core/amqp/RetryPolicy.java]: These retry policies are fairly generic and not specific to amqp (except the exception thrown). Can this be moved to azure-core instead of azure-core-amqp?

File: sdk/eventhubs/azure-eventhubs/src/main/java/com/azure/messaging/eventhubs/implementation/CBSChannel.java [hunk 4]
```diff
@@ -35,29 +35,29 @@
     private final TokenCredential credential;
     private final Mono<RequestResponseChannel> cbsChannelMono;
     private final ReactorProvider provider;
-    private final Duration operationTimeout;
     private final CBSAuthorizationType authorizationType;
+    private final RetryOptions retry;
```
Comment (srnagar) [inline sdk/eventhubs/azure-eventhubs/src/main/java/com/azure/messaging/eventhubs/implementation/CBSChannel.java]: nit: `retryOptions`

File: sdk/eventhubs/azure-eventhubs/src/main/java/com/azure/messaging/eventhubs/implementation/RetryUtil.java [hunk 5]
```diff
@@ -0,0 +1,80 @@
...
+     * @return A new retry policy configured with the given {@code options}.
+     */
+    public static RetryPolicy getRetryPolicy(RetryOptions options) {
+        switch (options.retryMode()) {
+            case FIXED:
+                return new FixedRetryPolicy(options);
+            case EXPONENTIAL:
+                return new ExponentialRetryPolicy(options);
+            default:
+                throw new IllegalArgumentException(
```
Comment (srnagar) [inline sdk/eventhubs/azure-eventhubs/src/main/java/com/azure/messaging/eventhubs/implementation/RetryUtil.java]: Use `logger.logAndThrow()`

File: sdk/eventhubs/azure-eventhubs/src/main/java/com/azure/messaging/eventhubs/implementation/RetryUtil.java [hunk 6]
```diff
@@ -0,0 +1,80 @@
...
+public class RetryUtil {
+    // So this class can't be instantiated.
+    private RetryUtil() {
+    }
+
+    /**
+     * Given a set of {@link RetryOptions options}, creates the appropriate retry policy.
+     *
+     * @param options A set of options used to configure the retry policy.
+     * @return A new retry policy configured with the given {@code options}.
```
Comment (srnagar) [inline sdk/eventhubs/azure-eventhubs/src/main/java/com/azure/messaging/eventhubs/implementation/RetryUtil.java]: Add `throws` to the javadoc

File: sdk/core/azure-core-amqp/src/main/java/com/azure/core/amqp/RetryOptions.java [hunk 7]
```diff
@@ -0,0 +1,184 @@
...
+            && this.retryMode() == other.retryMode()
+            && Objects.equals(this.maxDelay(), other.maxDelay())
+            && Objects.equals(this.delay(), other.delay())
+            && Objects.equals(this.tryTimeout(), other.tryTimeout());
+    }
+
+    /**
+     * {@inheritDoc}
+     */
+    @Override
```
Comment (srnagar) [inline sdk/core/azure-core-amqp/src/main/java/com/azure/core/amqp/RetryOptions.java]: It would be useful to also override `toString` method to simplify logging retry options.

File: sdk/core/azure-core-amqp/src/main/java/com/azure/core/amqp/ExponentialRetryPolicy.java [hunk 8]
```diff
@@ -0,0 +1,94 @@
...
+    }
+
+    /**
+     * Creates a clone of this instance.
+     *
+     * @return A clone of the {@link ExponentialRetryPolicy} instance.
+     */
+    @SuppressWarnings("CloneDoesntCallSuperClone")
+    @Override
+    public Object clone() {
```
[the remark this answers is not in the document]
Comment (conniey) [reply sdk/core/azure-core-amqp/src/main/java/com/azure/core/amqp/ExponentialRetryPolicy.java]: When looking at how people had overridden clone(), it appeared they always used

```
@Override
public Object clone()
```

In this case, would I remove override and use `public ExponentialRetryPolicy clone()`? How does it know I implemented the interface. Hm.

File: sdk/core/azure-core-amqp/src/main/java/com/azure/core/amqp/ExponentialRetryPolicy.java [hunk 9]
```diff
@@ -0,0 +1,94 @@
...
+     *
+     * @param retryCount The number of attempts that have been made, including the initial attempt before any
+     *         retries.
+     * @param baseDelay The delay to use for the basis of the exponential backoff.
+     * @param baseJitter The duration to use for the basis of the random jitter value.
+     * @param random The random number generator used to calculate the jitter.
+     * @return The duration to delay before retrying a request.
+     */
+    @Override
+    protected Duration calculateRetryDelay(int retryCount, Duration baseDelay, Duration baseJitter,
```
[the remark this answers is not in the document]
Comment (conniey) [reply sdk/core/azure-core-amqp/src/main/java/com/azure/core/amqp/ExponentialRetryPolicy.java]: The calling method in the base class RetryPolicy will not call this code if the retry attempt is larger than max attempt.

File: sdk/core/azure-core-amqp/src/main/java/com/azure/core/amqp/ExponentialRetryPolicy.java [hunk 10]
```diff
@@ -0,0 +1,94 @@
...
+                                           ThreadLocalRandom random) {
+        final double jitterSeconds = random.nextDouble() * baseJitter.getSeconds();
+        final double nextRetrySeconds = Math.pow(retryFactor, (double) retryCount);
+        final Double nextRetryNanos = (jitterSeconds + nextRetrySeconds) * NANOS_PER_SECOND;
+
+        return baseDelay.plus(Duration.ofNanos(nextRetryNanos.longValue()));
```
[the remark this answers is not in the document]
Comment (conniey) [reply sdk/core/azure-core-amqp/src/main/java/com/azure/core/amqp/ExponentialRetryPolicy.java]: Good catch, I'll add this to the parent Retry class to encapsulate this logic for other retry implementations.

File: sdk/core/azure-core-amqp/src/main/java/com/azure/core/amqp/FixedRetryPolicy.java [hunk 11]
```diff
@@ -0,0 +1,72 @@
...
+    }
+
+    /**
+     * Creates a clone of this instance.
+     *
+     * @return A clone of the {@link FixedRetryPolicy} instance.
+     */
+    @SuppressWarnings("CloneDoesntCallSuperClone")
+    @Override
+    public Object clone() {
```
[the remark this answers is not in the document]
Comment (conniey) [reply sdk/core/azure-core-amqp/src/main/java/com/azure/core/amqp/FixedRetryPolicy.java]: Should I not bother to implement the Cloneable interface then?

File: sdk/core/azure-core-amqp/src/main/java/com/azure/core/amqp/RetryPolicy.java (hunk 3 above)
Comment (conniey) [reply sdk/core/azure-core-amqp/src/main/java/com/azure/core/amqp/RetryPolicy.java]: Unfortunately, our retry is different the Retry in azure-core in that the one in azure core reads from the retry after header, or reads the appropriate HTTP status code then then attempts to retry.

File: sdk/eventhubs/azure-eventhubs/src/main/java/com/azure/messaging/eventhubs/implementation/RetryUtil.java (hunk 5 above)
Comment (conniey) [reply sdk/eventhubs/azure-eventhubs/src/main/java/com/azure/messaging/eventhubs/implementation/RetryUtil.java]: @JonathanGiles 
Since this is a static class and method, I was reading that we shouldn't have static loggers, so I wasn't sure if I should create a static logger for this.
https://azuresdkspecs.z5.web.core.windows.net/JavaSpec.html#general-logging

File: sdk/core/azure-core-amqp/src/main/java/com/azure/core/amqp/RetryOptions.java (hunk 2 above)
Comment (conniey) [reply sdk/core/azure-core-amqp/src/main/java/com/azure/core/amqp/RetryOptions.java]: They were the existing ones from the Track 1 library. And then I copied the ones @jsquire had in his implementation. :)

File: sdk/core/azure-core-amqp/src/main/java/com/azure/core/amqp/ExponentialRetryPolicy.java (hunk 8 above)
[the remark this answers is not in the document]
Comment (conniey) [reply sdk/core/azure-core-amqp/src/main/java/com/azure/core/amqp/ExponentialRetryPolicy.java]: After reading that blog post, having a copy constructor is better.

File: sdk/core/azure-core-amqp/src/main/java/com/azure/core/amqp/RetryOptions.java (hunk 7 above)
Comment (conniey) [reply sdk/core/azure-core-amqp/src/main/java/com/azure/core/amqp/RetryOptions.java]: If we had a common way of implementing toString, I would, but it becomes a mash of random formats.

File: sdk/eventhubs/azure-eventhubs/src/main/java/com/azure/messaging/eventhubs/implementation/RetryUtil.java (hunk 6 above)
Comment (conniey) [reply sdk/eventhubs/azure-eventhubs/src/main/java/com/azure/messaging/eventhubs/implementation/RetryUtil.java]: Is it necessary even though this is an implementation class?

Comment (srnagar) [reply sdk/eventhubs/azure-eventhubs/src/main/java/com/azure/messaging/eventhubs/implementation/RetryUtil.java]: I guess it's not necessary since it's part of the implementation package and won't show up in apidocs anyway.

File: sdk/eventhubs/azure-eventhubs/src/main/java/com/azure/messaging/eventhubs/implementation/RetryUtil.java (hunk 5 above)
Comment (JonathanGiles) [reply sdk/eventhubs/azure-eventhubs/src/main/java/com/azure/messaging/eventhubs/implementation/RetryUtil.java]: No, just leave as-is for now.
