### PR TITLE
Sb track2 schedule multiple message validate batch size

### LINKED ISSUE #16714: Bug: Add validation scheduleMessage(Iterator<SBM>) :  If all the messages can not be added into batch
scheduleMessage (Iterator<SBReceivedMessage) API: 
Throw Exception when all the messages in Iterator can not be added into batch.

### PR DESCRIPTION
**Pull request by hemanttanwar**
API : receiver.scheduleMessage (Iterator<SBReceivedMessage)

Throw Exception when all the messages in Iterator can not be added into batch.

fixes #16714

### CODE REVIEW

File: sdk/servicebus/azure-messaging-servicebus/src/main/java/com/azure/messaging/servicebus/ServiceBusSenderAsyncClient.java [hunk 1]
```diff
@@ -371,13 +372,36 @@ public String getEntityPath() {
...
         }
 
-        return createBatch().flatMapMany(messageBatch -> {
-            messages.forEach(message -> messageBatch.tryAdd(message));
-            return getSendLink().flatMapMany(link -> connectionProcessor
-                .flatMap(connection -> connection.getManagementNode(entityName, entityType))
-                .flatMapMany(managementNode -> managementNode.schedule(messageBatch.getMessages(), scheduledEnqueueTime,
-                    messageBatch.getMaxSizeInBytes(), link.getLinkName(), transactionContext)));
-        });
+        return getSendLink().flatMapMany(link -> link.getLinkSize()
```
Comment (conniey) [inline sdk/servicebus/azure-messaging-servicebus/src/main/java/com/azure/messaging/servicebus/ServiceBusSenderAsyncClient.java:375]: Why did we duplicate createBatch() logic? By default it uses the default batch size.

File: sdk/servicebus/azure-messaging-servicebus/src/main/java/com/azure/messaging/servicebus/ServiceBusSenderAsyncClient.java [hunk 2]
```diff
@@ -371,13 +372,36 @@ public String getEntityPath() {
...
+            .flatMapMany(size -> {
+                int maxSize =  size > 0
+                    ? size
+                    : MAX_MESSAGE_LENGTH_BYTES;
+                final CreateBatchOptions batchOptions =  new CreateBatchOptions();
+                batchOptions.setMaximumSizeInBytes(maxSize);
+
+                return createBatch(batchOptions).flatMapMany(messageBatch ->  {
+                    AtomicInteger index = new AtomicInteger();
```
Comment (conniey) [inline sdk/servicebus/azure-messaging-servicebus/src/main/java/com/azure/messaging/servicebus/ServiceBusSenderAsyncClient.java:384]: Why are you keeping an atomic integer? We can just use a for loop

File: sdk/servicebus/azure-messaging-servicebus/src/main/java/com/azure/messaging/servicebus/ServiceBusSenderAsyncClient.java (hunk 1 above)
Comment (hemanttanwar) [reply sdk/servicebus/azure-messaging-servicebus/src/main/java/com/azure/messaging/servicebus/ServiceBusSenderAsyncClient.java]: I was checking size on the link but changed it to use default size.

File: sdk/servicebus/azure-messaging-servicebus/src/main/java/com/azure/messaging/servicebus/ServiceBusSenderAsyncClient.java [hunk 3]
```diff
@@ -371,13 +371,27 @@ public String getEntityPath() {
...
-                .flatMapMany(managementNode -> managementNode.schedule(messageBatch.getMessages(), scheduledEnqueueTime,
-                    messageBatch.getMaxSizeInBytes(), link.getLinkName(), transactionContext)));
-        });
+        return getSendLink().flatMapMany(link -> createMessageBatch()
+            .flatMapMany(messageBatch -> {
+                int index = 0;
+                for (ServiceBusMessage message : messages) {
+                    ++index;
+                    boolean added = messageBatch.tryAddMessage(message);
+                    if (!added) {
```
Comment (YijunXieMS) [inline sdk/servicebus/azure-messaging-servicebus/src/main/java/com/azure/messaging/servicebus/ServiceBusSenderAsyncClient.java:380]: nitpick only:
1. if(messageBatch.tryAddMessage(message)) is pretty readable. No need to have an additional variable if no other use.
2. Suggest index=0 instead of 1 for the first message because Java uses 0-based index.

**Review by YijunXieMS — APPROVED** [review]
LGTM
