### PR TITLE
Renew currently owned partitions stored in checkpointstore

### LINKED ISSUE #13597: [BUG] PartitionBasedLoadBalancer.java does sometimes PING-PONG between 2 EventProcessorClients.
Load balancing does not run always as expected. EventProcessorClients steal with PING-PONG the partitions. This PING-PONG is not fortunatelly endless.

Steps to reproduce the behavior (it is reproducible with 50%):
- Create event hub at least with 4 partitions. 
- Start the first EventProcessorClient and wait until it has all partitions as owner. 
- Start the second EventProcessorClient and wait until the load balancing is complete.
- See the logs. 

Example of Logs:
EventProcessorClient 1:
20/07/29 13:18:13 INFO eventhubs.PartitionBasedLoadBalancer: Attempting to claim ownership of partition 2 20/07/29 13:22:23 INFO eventhubs.PartitionBasedLoadBalancer: Attempting to claim ownership of partition 2
20/07/29 13:25:24 INFO eventhubs.PartitionBasedLoadBalancer: Attempting to claim ownership of partition 2
20/07/29 13:25:34 INFO eventhubs.PartitionBasedLoadBalancer: Attempting to claim ownership of partition 2
EventProcessorClient 2:
20/07/29 13:19:35 INFO eventhubs.PartitionBasedLoadBalancer: Attempting to claim ownership of partition 2
20/07/29 13:24:36 INFO eventhubs.PartitionBasedLoadBalancer: Attempting to claim ownership of partition 2
20/07/29 13:27:06 INFO eventhubs.PartitionBasedLoadBalancer: Attempting to claim ownership of partition 2

Possible problem (updating from checkpoint store could be the solution):
image-2020-07-13-16-41-53-762

The new second EventProcessorClient steals partitions from the first EventProcessorClient. There is some delay until the first EventProcessorClient gets an error for stolen partitions in its event pumps. During this delay, it sometimes reclaims its (already lost) ownerships for the stolen partitions, because it reclaims ownership for all (still) existing event pumps instead of the ownerships according to the checkpoint store.

Setup :
 - OS: Windows 10, Java 11
 - IDE : IntelliJ
 - Maven code:
       <dependency>
            <groupId>com.azure</groupId>
            <artifactId>azure-messaging-eventhubs</artifactId>
            <version>5.1.1</version>
        </dependency>

### PR DESCRIPTION
**Pull request by srnagar**
This PR updates the renew ownership logic to renew only partitions that are currently owned by the processor instance as stored in the checkpointstore instead of using the partitions stored in the partition processor map. This will resolve the issue of partitions switching between instances due to delays caused by service closing the link to a partition that was stolen by another instance.

Fixes #13597

### CODE REVIEW

File: sdk/eventhubs/azure-messaging-eventhubs/src/main/java/com/azure/messaging/eventhubs/PartitionBasedLoadBalancer.java [hunk 1]
```diff
@@ -278,6 +258,24 @@ void loadBalance() {
...
 
+    private void renewOwnership(Map<String, PartitionOwnership> partitionOwnershipMap) {
+        // renew ownership of already owned partitions
+        checkpointStore.claimOwnership(partitionPumpManager.getPartitionPumps().keySet()
+            .stream()
+            .filter(
+                partitionId -> partitionOwnershipMap.containsKey(partitionId) && partitionOwnershipMap.get(partitionId)
+                    .equals(this.ownerId))
+            .map(partitionId -> createPartitionOwnershipRequest(partitionOwnershipMap, partitionId))
+            .collect(Collectors.toList()))
```
Comment (conniey) [inline sdk/eventhubs/azure-messaging-eventhubs/src/main/java/com/azure/messaging/eventhubs/PartitionBasedLoadBalancer.java:269]: Do we need to collect this into a list if we're doing anything on the output?

File: sdk/eventhubs/azure-messaging-eventhubs/src/main/java/com/azure/messaging/eventhubs/PartitionBasedLoadBalancer.java [hunk 2]
```diff
@@ -218,35 +218,15 @@ void loadBalance() {
...
-                    .stream()
-                    .map(partitionId -> createPartitionOwnershipRequest(partitionOwnershipMap, partitionId))
-                    .collect(Collectors.toList()))
-                    .subscribe(ignored -> { },
-                        ex -> {
-                            logger.error("Error renewing partition ownership", ex);
-                            isLoadBalancerRunning.set(false);
-                        },
-                        () -> isLoadBalancerRunning.set(false));
+                renewOwnership(partitionOwnershipMap);
```
Comment (conniey) [inline sdk/eventhubs/azure-messaging-eventhubs/src/main/java/com/azure/messaging/eventhubs/PartitionBasedLoadBalancer.java:221]: Is it possible to have a test for this? 🤔
