### PR TITLE
Cosmos Spark: Adding support for ShortType and ByteType

### LINKED ISSUE #26135: [BUG] ShortType spark schema not supported in azure cosmos spark
**Describe the bug**
If a column in the input dataframe is spark ShortType, the process of writing into cosmos fails with:

```
 java.lang.Exception: Cannot cast 50 into a Json value. ShortType
```

***Exception or Stack Trace***
TaskSetManager: Lost task 1.0 in stage 135.0 (TID 195, 10.0.19.70, executor 4): java.lang.Exception: Cannot cast 50 into a Json value. ShortType has no matching Json value.
at com.azure.cosmos.spark.CosmosRowConverter.convertSparkDataTypeToJsonNodeNonNull(CosmosRowConverter.scala:343)
at com.azure.cosmos.spark.CosmosRowConverter.convertSparkDataTypeToJsonNode(CosmosRowConverter.scala:183)
at com.azure.cosmos.spark.CosmosRowConverter.$anonfun$fromInternalRowToObjectNode$1(CosmosRowConverter.scala:143)
at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)

**To Reproduce**
Simply create a dataframe with a column shortType

***Code Snippet***
In convertSparkDataTypeToJsonNodeNonNull , https://github.com/Azure/azure-sdk-for-java/blob/391fe8e3f008d4785e8191dce4efd59fdccd6ced/sdk/cosmos/azure-cosmos-spark_3-1_2-12/src/main/scala/com/azure/cosmos/spark/CosmosRowConverter.scala#L304

the match clause should include spark shortType on the left, and simply translate into number.

**Expected behavior**
The library should handle short values

**Setup (please complete the following information):**
 - OS: Spark
 - IDE: Intellij
 - Library/Libraries: com.azure.cosmos.spark / azure-cosmos-spark_3-1_2-12 / 4.4.2
 - Java version: 8-11
 - App Server/Environment: Apache Spark, Databricks
 - Frameworks: [e.g. Spring Boot, Micronaut, Quarkus, etc] 

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Bug Description Added
- [X] Repro Steps Added
- [X] Setup information Added

### PR DESCRIPTION
**Pull request by FabianMeiswinkel**
Fixes #26135

# Problem description
If a column in the input dataframe is spark ShortType, the process of writing into cosmos fails with:

`java.lang.Exception: Cannot cast 50 into a Json value. ShortType`

**Exception or Stack Trace**
TaskSetManager: Lost task 1.0 in stage 135.0 (TID 195, 10.0.19.70, executor 4): java.lang.Exception: Cannot cast 50 into a Json value. ShortType has no matching Json value.
at com.azure.cosmos.spark.CosmosRowConverter.convertSparkDataTypeToJsonNodeNonNull(CosmosRowConverter.scala:343)
at com.azure.cosmos.spark.CosmosRowConverter.convertSparkDataTypeToJsonNode(CosmosRowConverter.scala:183)
at com.azure.cosmos.spark.CosmosRowConverter.$anonfun$fromInternalRowToObjectNode$1(CosmosRowConverter.scala:143)
at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)

**To Reproduce**
Simply create a dataframe with a column shortType

# Fix
Add missing numeric Spark data types (all but ByteType and SHortType were supported already). This PR is adding ShortType and ByteType as well.

# [Testing Guidelines](../../CONTRIBUTING.md#building-and-unit-testing)
- [X] Pull request includes test coverage for the included changes.

### CODE REVIEW

**Review by kirankumarkolli — APPROVED** [review]

**Review by moderakh — APPROVED** [review]

File: sdk/cosmos/azure-cosmos-spark_3-1_2-12/src/test/scala/com/azure/cosmos/spark/CosmosRowConverterSpec.scala [hunk 1]
```diff
@@ -50,6 +50,50 @@ class CosmosRowConverterSpec extends UnitSpec with BasicLoggingTrait {
     objectNode.get(colName2).asText() shouldEqual colVal2
   }
 
+  "basic spark row with various numeric types" should "translate to ObjectNode" in {
```
Comment (ealsur) [inline sdk/cosmos/azure-cosmos-spark_3-1_2-12/src/test/scala/com/azure/cosmos/spark/CosmosRowConverterSpec.scala:53]: nit: THere is another test already doing this, might as well just add the new types to it https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/cosmos/azure-cosmos-spark_3-1_2-12/src/test/scala/com/azure/cosmos/spark/CosmosRowConverterSpec.scala#L390-L408

**Review by ealsur — APPROVED** [review]
LGTM, just one nit regarding test duplication

File: sdk/cosmos/azure-cosmos-spark_3-1_2-12/src/test/scala/com/azure/cosmos/spark/CosmosRowConverterSpec.scala (hunk 1 above)
Comment (FabianMeiswinkel) [reply sdk/cosmos/azure-cosmos-spark_3-1_2-12/src/test/scala/com/azure/cosmos/spark/CosmosRowConverterSpec.scala:53]: Good catch! Thanks

File: sdk/cosmos/azure-cosmos-spark_3-1_2-12/src/test/scala/com/azure/cosmos/spark/CosmosRowConverterSpec.scala [hunk 2]
```diff
@@ -396,57 +430,109 @@ class CosmosRowConverterSpec extends UnitSpec with BasicLoggingTrait {
...
     val colVal4: Decimal = Decimal(4.6)
-    val colVal5: Double = 0
-    val colVal6: Float = 0
-    val colVal7: Long = 0
-    val colVal8: Decimal = Decimal(0)
+    val colVal5: java.math.BigDecimal = new java.math.BigDecimal(4.6)
+    val colVal6: Int = 1234
+    val colVal7: Short = 123
+    val colVal8: Byte = 12
+    val colVal9: Double = 0
```
Comment (ealsur) [inline sdk/cosmos/azure-cosmos-spark_3-1_2-12/src/test/scala/com/azure/cosmos/spark/CosmosRowConverterSpec.scala:450]: nit: Repeated, the test already has Double, Float, Long, Decimal

**Review by ealsur — APPROVED** [review]
