### PR TITLE
Code Sample Fixes for DataLake and Blobs

### LINKED ISSUE #36969: Storage - Files Data Lake Samples Issue
1.

**Section** [link1](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/storage/azure-storage-file-datalake/src/samples/java/com/azure/storage/file/datalake/PathClientJavaDocCodeSamples.java#L252), [link2](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/storage/azure-storage-file-datalake/src/samples/java/com/azure/storage/file/datalake/PathClientJavaDocCodeSamples.java#L271), [link3](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/storage/azure-storage-file-datalake/src/samples/java/com/azure/storage/file/datalake/PathClientJavaDocCodeSamples.java#L304), [link4](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/storage/azure-storage-file-datalake/src/samples/java/com/azure/storage/file/datalake/PathClientJavaDocCodeSamples.java#L323):
image

**Reason**:
java.lang.NullPointerException: Cannot invoke "String.toLowerCase(java.util.Locale)" because the return value of "com.azure.storage.file.datalake.models.AccessControlType.toString()" is null.

**Suggestion**:
Update code to
```
PathAccessControlEntry ownerEntry = new PathAccessControlEntry()
	              .setAccessControlType(AccessControlType.USER)
	              .setPermissions(new RolePermissions().setReadPermission(true).setWritePermission(true).setExecutePermission(true));

PathAccessControlEntry groupEntry = new PathAccessControlEntry()
	      .setAccessControlType(AccessControlType.GROUP)
	      .setPermissions(new RolePermissions().setReadPermission(true).setWritePermission(true));

PathAccessControlEntry otherEntry = new PathAccessControlEntry()
	      .setAccessControlType(AccessControlType.OTHER)
	      .setPermissions(new RolePermissions());

List<PathAccessControlEntry> pathAccessControlEntries = new ArrayList<>();
pathAccessControlEntries.add(ownerEntry);
pathAccessControlEntries.add(groupEntry);
pathAccessControlEntries.add(otherEntry);
```

2.

**Section** [link1](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/storage/azure-storage-file-datalake/src/samples/java/com/azure/storage/file/datalake/PathClientJavaDocCodeSamples.java#L356), [link2](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/storage/azure-storage-file-datalake/src/samples/java/com/azure/storage/file/datalake/PathClientJavaDocCodeSamples.java#L374):
image

**Reason**:
java.lang.NullPointerException: Cannot invoke "String.toLowerCase(java.util.Locale)" because the return value of "com.azure.storage.file.datalake.models.AccessControlType.toString()" is null.

**Suggestion**:
Update code to
```
PathRemoveAccessControlEntry ownerEntry = new PathRemoveAccessControlEntry()
	                .setAccessControlType(AccessControlType.USER)
	                .setDefaultScope(true);
	
PathRemoveAccessControlEntry groupEntry = new PathRemoveAccessControlEntry()
	      .setAccessControlType(AccessControlType.GROUP)
	      .setDefaultScope(true);

PathRemoveAccessControlEntry otherEntry = new PathRemoveAccessControlEntry()
	      .setAccessControlType(AccessControlType.OTHER)
	      .setDefaultScope(true);
List<PathRemoveAccessControlEntry> pathAccessControlEntries = new ArrayList<>();
pathAccessControlEntries.add(ownerEntry);
pathAccessControlEntries.add(groupEntry);
pathAccessControlEntries.add(otherEntry);
```
@sandeep-sen , @joshfree , @rohit-ganguly , @kasobol-msft and @alzimmermsft to notification.

### LINKED ISSUE #36971: Storage - Blobs Samples Issue
1.

**Section** [link1](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/storage/azure-storage-blob/src/samples/java/com/azure/storage/blob/specialized/BlockBlobClientJavaDocCodeSnippets.java#L118), [link2](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/storage/azure-storage-blob/src/samples/java/com/azure/storage/blob/specialized/BlockBlobClientJavaDocCodeSnippets.java#L147), [link3](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/storage/azure-storage-blob/src/samples/java/com/azure/storage/blob/specialized/BlockBlobClientJavaDocCodeSnippets.java#L199), [link4](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/storage/azure-storage-blob/src/samples/java/com/azure/storage/blob/specialized/BlockBlobClientJavaDocCodeSnippets.java#L387):
image
**Reason**:
The MD5 value specified in the request is invalid. MD5 value must be 128 bits and base64 encoded.

**Suggestion**:
Update code to
```
.setContentMd5(MessageDigest.getInstance("MD5").digest("data".getBytes(StandardCharsets.UTF_8))
```

2.

**Section** [link](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/storage/azure-storage-blob/src/samples/java/com/azure/storage/blob/specialized/BlobAsyncClientBaseJavaDocCodeSnippets.java#L59):
image

**Reason**:
`BlobAsyncClientBase(com.azure.core.http.HttpPipeline, java.lang.String, com.azure.storage.blob.BlobServiceVersion, java.lang.String, java.lang.String, java.lang.String, java.lang.String, ...)` has protected access in `com.azure.storage.blob.specialized.BlobAsyncClientBase`.

**Suggestion**:
Change `BlobAsyncClientBase(com.azure.core.http.HttpPipeline, java.lang.String, com.azure.storage.blob.BlobServiceVersion, java.lang. String, java.lang.String, java.lang.String, java.lang.String, ...)` method access permission changed to public, or delete this test code.

3.

**Section** [link](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/storage/azure-storage-blob/src/samples/java/com/azure/storage/blob/specialized/BlobClientBaseJavaDocCodeSnippets.java#L66):
image

**Reason**:
`BlobClientBase(com.azure.storage.blob.specialized.BlobAsyncClientBase)` has protected access in `com.azure.storage.blob.specialized.BlobClientBase`.

**Suggestion**:
Change the access permission of the `BlobClientBase(com.azure.storage.blob.specialized.BlobAsyncClientBase)` method in the `com.azure.storage.blob.specialized.BlobClientBase` class to public, or delete this test code.

4.

**Section** [link](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/storage/azure-storage-blob/src/samples/java/com/azure/storage/blob/JavaDocCodeSnippetsHelpers.java#L22):
image

**Reason**:
`BlobClient(com.azure.storage.blob.BlobAsyncClient)` has protected access in `com.azure.storage.blob.BlobClient`.

**Suggestion**:
Change the access permission of the `BlobClient(com.azure.storage.blob.BlobAsyncClient)` method in the `com.azure.storage.blob.BlobClient` class to public, or delete this test code.

5.

**Section** [link](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/storage/azure-storage-blob/src/samples/java/com/azure/storage/blob/BlobAsyncClientJavaDocCodeSnippets.java#L615):
image

**Reason**:
`BLOB_MAX_UPLOAD_BLOCK_SIZE` is not public in `com.azure.storage.blob.BlobAsyncClient`. Cannot be accessed from outside package.

**Suggestion**:
Change the access permission of the `BlobAsyncClient.BLOB_MAX_UPLOAD_BLOCK_SIZE` method in the `com.azure.storage.blob.BlobClient` class to public, or delete this test code.

@sandeep-sen , @joshfree , @rohit-ganguly , @kasobol-msft and @alzimmermsft to notification.

### PR DESCRIPTION
**Pull request by ibrahimrabab**
# Description

resolves #36969
resolves #36971

### CODE REVIEW

File: sdk/storage/azure-storage-blob/src/samples/java/com/azure/storage/blob/BlobClientJavaDocCodeSnippets.java [hunk 1]
```diff
@@ -36,7 +36,7 @@
  */
 @SuppressWarnings("unused")
 public class BlobClientJavaDocCodeSnippets {
-    private BlobClient client = JavaDocCodeSnippetsHelpers.getBlobClient("blobName");
+    private BlobClient client = new BlobClientBuilder().blobName("blobName").buildClient();
```
Comment (alzimmermsft) [inline sdk/storage/azure-storage-blob/src/samples/java/com/azure/storage/blob/BlobClientJavaDocCodeSnippets.java:39]: Should configure what is actually needed in the builders for them to function properly.
