### PR TITLE
Making databaseAccount read dynamic after V4 master merge

### LINKED ISSUE #7668: Use DatabaseAccount for configurations read dynamically
**Describe the bug**
Currently DatabaseAccount used to read several configurations example maxReplicacount on read calls is the one time snapshot during app initialization.

**Expected behavior**
DatabaseAccount  uses to read configurations  should refresh dynamically with periodic cache refresh in GlobalEndpointManager

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

### PR DESCRIPTION
**Pull request by simplynaveen20**
This is same as PR on V4 branch - https://github.com/Azure/azure-sdk-for-java/pull/7831
Created the new PR altogether as it was easier after V4 merge.

Below is the context
Currently GatewayServiceConfigurationReader initialize during client start up with one time snapshot of databaseAccount read via GlobalEndPointManager. Its value remain same throughout the lifespan of application.
This PR will read all the databaseAccount configurations via GatewayServiceConfigurationReader dynamically from cache which updates with its scheduling mechanism or any read/write account error.
This will also fix an issue in which application hits DatabaseAccount read call twice during startup.

fixes #7668

### CODE REVIEW

File: sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/GlobalEndpointManager.java [hunk 1]
```diff
@@ -159,6 +166,20 @@ public void close() {
         });
     }
 
+    public Mono<DatabaseAccount> getDatabaseAccountFromCache(URI defaultEndpoint) {
+        return this.databaseAccountAsyncCache.getAsync(StringUtils.EMPTY, null, () -> this.owner.getDatabaseAccountFromEndpoint(defaultEndpoint).single().doOnSuccess(databaseAccount -> {
+            if(databaseAccount != null) {
+                this.latestDatabaseAccount = databaseAccount;
+            }
+
+            this.refreshLocationAsync(databaseAccount, false);
```
Comment (moderakh) [inline sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/GlobalEndpointManager.java]: there is a bug here in `refreshLocationAsync(.)` invocation

File: sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/RxDocumentClientImpl.java [hunk 2]
```diff
@@ -250,29 +250,12 @@ private RxDocumentClientImpl(URI serviceEndpoint,
...
-        this.gatewayConfigurationReader = new GatewayServiceConfigurationReader(this.serviceEndpoint,
-                this.hasAuthKeyResourceToken,
-                resourceToken,
-                this.connectionPolicy,
-                this.authorizationTokenProvider,
-                this.reactorHttpClient);
-
-        DatabaseAccount databaseAccount = this.gatewayConfigurationReader.initializeReaderAsync().block();
+        this.gatewayConfigurationReader = new GatewayServiceConfigurationReader(this.serviceEndpoint, this.globalEndpointManager);
+        DatabaseAccount databaseAccount = this.globalEndpointManager.getLatestDatabaseAccount();
```
Comment (moderakh) [inline sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/RxDocumentClientImpl.java]: where are we doing the initialization blocking call now?

If the global endpoint manager is not fully initialized with first databaseAccount fetch could this return null?

File: sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/GlobalEndpointManager.java [hunk 3]
```diff
@@ -159,6 +166,20 @@ public void close() {
...
+        }));
+    }
+
+    public DatabaseAccount getLatestDatabaseAccount() {
+        return this.latestDatabaseAccount;
```
Comment (moderakh) [inline sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/GlobalEndpointManager.java]: there is a time window where GlobalEndpointManager is instantiated but hasn't fetched DatabaseAccount, within that period how do we ensure this never returns null?

File: sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/RxDocumentClientImpl.java (hunk 2 above)
Comment (simplynaveen20) [reply sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/RxDocumentClientImpl.java]: GatewayServiceConfigurationReader constructor is doing blocking call on async cache , so for first time if cache in null it will hit the BE

File: sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/GlobalEndpointManager.java (hunk 3 above)
Comment (simplynaveen20) [reply sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/GlobalEndpointManager.java]: We are calling init on GlobalEndpointManager  from RxDocumentClientImpl which will update this value , any future call if return null due to any exception or error we will not update latestDatabaseAccount and async cahce , they will hold the previous not null value

File: sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/GlobalEndpointManager.java (hunk 1 above)
Comment (simplynaveen20) [reply sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/GlobalEndpointManager.java]: What bug , please explain . this is same as the code initially doing in RxDocumentClientImpl, via this.globalEndpointManager.refreshLocationAsync(databaseAccount, false).block();

Comment (simplynaveen20) [reply sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/GlobalEndpointManager.java]: I think i see the bug will fix in next iteration

Comment (simplynaveen20) [reply sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/GlobalEndpointManager.java]: Made refreshLocationAsync in async pipeline , added test cases to make sure this method is getting called

File: sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/GlobalEndpointManager.java (hunk 3 above)
Comment (moderakh) [reply sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/GlobalEndpointManager.java]: Please document the new API saying what you said above.

File: sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/RxDocumentClientImpl.java (hunk 2 above)
Comment (moderakh) [reply sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/RxDocumentClientImpl.java]: could you please add an `assert(databaseAccount != null)` here. for sanity check and readibility.

File: sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/directconnectivity/GatewayServiceConfigurationReader.java [hunk 4]
```diff
@@ -42,118 +24,28 @@
...
-        httpHeaders.set(HttpConstants.HttpHeaders.VERSION, HttpConstants.Versions.CURRENT_VERSION);
-
-        UserAgentContainer userAgentContainer = new UserAgentContainer();
-        String userAgentSuffix = this.connectionPolicy.getUserAgentSuffix();
-        if (userAgentSuffix != null && userAgentSuffix.length() > 0) {
-            userAgentContainer.setSuffix(userAgentSuffix);
-        }
-
-        httpHeaders.set(HttpConstants.HttpHeaders.USER_AGENT, userAgentContainer.getUserAgent());
-        httpHeaders.set(HttpConstants.HttpHeaders.API_TYPE, Constants.Properties.SQL_API_TYPE);
```
Comment (moderakh) [inline sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/directconnectivity/GatewayServiceConfigurationReader.java]: as this `httpHeaders.set(HttpConstants.HttpHeaders.API_TYPE, Constants.Properties.SQL_API_TYPE);` is removed, we are not passing this header to the service in the initialization time. 

* what does .Net do?
* Is that ok not to set SQL_API_TYPE? what happens on non sql type account?

File: sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/GlobalEndpointManager.java [hunk 5]
```diff
@@ -253,8 +274,27 @@ private void startRefreshLocationTimerAsync() {
...
+        };
+
+        Mono<DatabaseAccount> obsoleteValueMono = databaseAccountAsyncCache.getAsync(StringUtils.EMPTY, null, fetchDatabaseAccount);
+        return obsoleteValueMono.flatMap(obsoleteValue -> {
+            if (firstTimeDatabaseAccountInitialization.compareAndSet(true, false)) {
+                return Mono.just(obsoleteValue);
+            }
+            return databaseAccountAsyncCache.getAsync(StringUtils.EMPTY, obsoleteValue, fetchDatabaseAccount).doOnError(t -> {
+                //Putting back the old value in cache, this will avoid cache corruption
+                databaseAccountAsyncCache.set(StringUtils.EMPTY, obsoleteValue);
```
Comment (moderakh) [inline sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/GlobalEndpointManager.java]: does this mean there is a window of time where there is an invalid result in the cache?

Comment (simplynaveen20) [reply sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/GlobalEndpointManager.java]: Yes

Comment (simplynaveen20) [reply sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/GlobalEndpointManager.java]: Removed cache as per offline discussion

File: sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/directconnectivity/GatewayServiceConfigurationReader.java (hunk 4 above)
Comment (simplynaveen20) [reply sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/directconnectivity/GatewayServiceConfigurationReader.java]: Checked with Jake , for .NET code is there to send apiType on all gateway calls , but currently it is taking ApiType.None, which is is filtered out when call goes to gateway.
Now for java we have one place for all gateway calls ,we should include that in common place . We can track this item separately

File: sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/GlobalEndpointManager.java (hunk 3 above)
Comment (simplynaveen20) [reply sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/GlobalEndpointManager.java]: done

File: sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/directconnectivity/GatewayServiceConfigurationReader.java (hunk 4 above)
Comment (moderakh) [reply sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/directconnectivity/GatewayServiceConfigurationReader.java]: thanks

File: sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/RxDocumentClientImpl.java (hunk 2 above)
Comment (simplynaveen20) [reply sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/RxDocumentClientImpl.java]: done
