### PR TITLE
Fixes error when there are no messages to be peeked.

### LINKED ISSUE #15034: [BUG] - ServiceBus - Exception throw when calling peek on empty queue
Calling `peekMessages` on an empty queue results in an exception. Expected behaviour was to return an empty iterable.

[31m  com.azure.core.amqp.exception.AmqpException: errorCondition[com.microsoft:message-not-found]. description[null], errorContext[NAMESPACE: l.servicebus.windows.net, PATH: /$management, REFERENCE_ID: -mgmt:receiver, LINK_CREDIT: 0][0m
[31m  at com.azure.core.amqp.implementation.ExceptionUtil.toException(ExceptionUtil.java:42)[0m
[31m  at com.azure.messaging.servicebus.implementation.MessageUtils.toException(MessageUtils.java:225)[0m
[31m  at com.azure.messaging.servicebus.implementation.ManagementChannel.lambda$sendWithVerify$16(ManagementChannel.java:454)[0m
[31m  at reactor.core.publisher.FluxHandleFuseable$HandleFuseableSubscriber.onNext(FluxHandleFuseable.java:163)[0m
[31m  at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1782)[0m
[31m  at reactor.core.publisher.MonoIgnoreThen$ThenAcceptInner.onNext(MonoIgnoreThen.java:296)[0m
[31m  at reactor.core.publisher.MonoCreate$DefaultMonoSink.success(MonoCreate.java:156)[0m
[31m  at com.azure.core.amqp.implementation.RequestResponseChannel.settleMessage(RequestResponseChannel.java:300)[0m
[31m  at com.azure.core.amqp.implementation.RequestResponseChannel.lambda$new$0(RequestResponseChannel.java:135)[0m
[31m  at reactor.core.publisher.LambdaSubscriber.onNext(LambdaSubscriber.java:160)[0m

**Version:**
com.azure:azure-messaging-servicebus:7.0.0-beta.5

### PR DESCRIPTION
**Pull request by conniey**
* Checks for "No content" status code and "Message not found" error condition when making a management request.
* Deletes ServiceBusErrorCondition and moves constants AmqpErrorCondition.
    * azure-core-amqp is specific to Azure services, so the constants are moved there to consolidate them.
* Delete unused internal constant, MAX_USER_AGENT_LENGTH.
* Replaces .last() with .next() because .last() will throw an exception if there are no elements whereas .next() will return an empty Mono.

Fixes #15034.

### CODE REVIEW

File: sdk/servicebus/azure-messaging-servicebus/src/test/java/com/azure/messaging/servicebus/ServiceBusReceiverAsyncClientIntegrationTest.java [hunk 1]
```diff
@@ -532,6 +549,23 @@ void peekBatchMessagesFromSequence(MessagingEntityType entityType) {
...
+    @ParameterizedTest
+    void peekMessagesFromSequenceEmptyEntity(MessagingEntityType entityType, boolean isSessionEnabled) {
+        // Arrange
+        setSenderAndReceiver(entityType, TestUtils.USE_CASE_EMPTY_ENTITY, isSessionEnabled);
+
+        final int maxMessages = 10;
+        final int fromSequenceNumber = 1;
+
+        // Assert & Act
+        StepVerifier.create(receiver.peekMessagesAt(maxMessages, fromSequenceNumber))
```
Comment (hemanttanwar) [inline sdk/servicebus/azure-messaging-servicebus/src/test/java/com/azure/messaging/servicebus/ServiceBusReceiverAsyncClientIntegrationTest.java:565]: What is difference in this and test at line 382 above, it looks duplicate test or you wanted to test a different scenario ?
line 382 ` StepVerifier.create(receiver.peekMessagesAt(maxMessages, fromSequenceNumber))
            .verifyComplete();`

**Review by hemanttanwar — APPROVED** [review]

File: sdk/servicebus/azure-messaging-servicebus/src/test/java/com/azure/messaging/servicebus/ServiceBusReceiverAsyncClientIntegrationTest.java (hunk 1 above)
Comment (conniey) [reply sdk/servicebus/azure-messaging-servicebus/src/test/java/com/azure/messaging/servicebus/ServiceBusReceiverAsyncClientIntegrationTest.java:565]: The first one should be not plural (message). I'll fix it.
