### PR TITLE
Fix Cognitive Search Samples Issue

### LINKED ISSUE #36575: Cognitive Search Samples Issue
1.
**Section** [link1](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/search/azure-search-documents/src/samples/java/com/azure/search/documents/ReadmeSamples.java#L147)：
image
**Reason:**
image
	Running the method pictured above gives an error:  Cannot construct instance of com.xsh.search.documents.ReadmeSamples$Hotel: non-static inner classes like this can only by instantiated using default, no-argument constructor.

**Suggestion：**
Update code to  `public static class Hotel `

2.
**Section** [link](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/search/azure-search-documents/src/samples/java/com/azure/search/documents/ReadmeSamples.java#L273):
image

**Reason**:
com.azure.core.exception.HttpResponseException: Status code 400, "{"error":{"code":"OperationNotAllowed","message":"The request is invalid. Details: index : Found 0 key fields in index 'index'. Each index must have exactly one key field.","details":[{"code":"MissingKeyField","message":"Found 0 key fields in index 'index'. Each index must have exactly one key field. Parameters: index"}]}}"

**Suggestion**:
Update code to
```
List<SearchField> searchFieldList = new ArrayList<>();
searchFieldList.add(new SearchField("hotelId", SearchFieldDataType.STRING)
	                .setKey(true)
	                .setFilterable(true)
	                .setSortable(true));
SEARCH_INDEX_CLIENT.createIndex(new SearchIndex("index1", searchFields).setFields(searchFieldList));

```
3.
**Section** [link](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/search/azure-search-documents/src/samples/java/com/azure/search/documents/indexes/CreateIndexWithFieldBuilderExample.java#L33):
image
**Reason**:
com.azure.core.exception.HttpResponseException: Status code 400, "{"error":{"code":"OperationNotAllowed","message":"The request is invalid. Details: index : Found 0 key fields in index 'index'. Each index must have exactly one key field.","details":[{"code":"MissingKeyField","message":"Found 0 key fields in index 'index'. Each index must have exactly one key field. Parameters: index"}]}}"

**Suggestion**:
Update code to
```
List<SearchField> searchFieldList = new ArrayList<>();
searchFieldList.add(new SearchField("hotelId", SearchFieldDataType.STRING)
	                .setKey(true)
	                .setFilterable(true)
	                .setSortable(true));
SearchIndex newIndex = new SearchIndex(indexName, indexFields)
	                .setFields(searchFieldList);
```
  @sandeep-sen, @joshfree, @achandmsft, @mayurid and @jairmyree to notification.

### PR DESCRIPTION
**Pull request by faynef**
Fixes #36575

@sandeep-sen, @joshfree, @achandmsft, @mayurid and @jairmyree to notification.

### CODE REVIEW

File: sdk/search/azure-search-documents/src/samples/java/com/azure/search/documents/ReadmeSamples.java [hunk 1]
```diff
@@ -271,7 +271,12 @@ public void createIndex() {
     public void createIndexUseFieldBuilder() {
         // BEGIN: readme-sample-createIndexUseFieldBuilder
         List<SearchField> searchFields = SearchIndexClient.buildSearchFields(Hotel.class, null);
-        SEARCH_INDEX_CLIENT.createIndex(new SearchIndex("index", searchFields));
+        List<SearchField> searchFieldList = new ArrayList<>();
+        searchFieldList.add(new SearchField("hotelId", SearchFieldDataType.STRING)
```
Comment (alzimmermsft) [inline sdk/search/azure-search-documents/src/samples/java/com/azure/search/documents/ReadmeSamples.java:275]: This can be simplified to just add the additional SearchField to `searchFields`. Another option would be adding `SimpleField` or `SearchableField` annotations to the Hotel class.

```java
@SimpleField(isKey = true, isFilterable = true, isSortable = true)
private String id;

@SearchableField(isFilterable = true, isSortable = true)
private String name;
```

**Comment by v-xuto** [comment]
@alzimmermsft We have updated by your comments, please re-review this PR. Thanks a lot.

**Review by alzimmermsft — APPROVED** [review]
