### PR TITLE
Fix List.Add Exception and Performance Improvements

### LINKED ISSUE #23237: java.lang.UnsupportedOperationException in com.azure.identity.implementation.IdentityClient#authenticateWithAzurePowerShell
This line fails since Array does not support List#add method.

https://github.com/Azure/azure-sdk-for-java/blob/6eb6c81fd197da4d180c613adee6748cc4d117f0/sdk/identity/azure-identity/src/main/java/com/azure/identity/implementation/IdentityClient.java#L499

### LINKED ISSUE #23382: [BUG] FailureException: NoClassDefFoundError: Could not initialize class reactor.netty.http.client.HttpClientConfig
**Describe the bug**
I'm following this tutorial to access a Key Vault from an Azure Function written in Java. From my PC I can successfully read a secret from the Key Vault, but not when the code is deployed to a Function App.

***Exception or Stack Trace***
2021-08-05T22:47:50.015 [Error] Executed 'Functions.UpdateAha' (Failed, Id=cd0f171d-8ef0-4cbc-8ebb-1a78375d7c70, Duration=8ms)Result: FailureException: NoClassDefFoundError: Could not initialize class reactor.netty.http.client.HttpClientConfigStack: java.lang.reflect.InvocationTargetExceptionat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.lang.reflect.Method.invoke(Method.java:498)at com.microsoft.azure.functions.worker.broker.JavaMethodInvokeInfo.invoke(JavaMethodInvokeInfo.java:22)at com.microsoft.azure.functions.worker.broker.JavaMethodExecutorImpl.execute(JavaMethodExecutorImpl.java:54)at com.microsoft.azure.functions.worker.broker.JavaFunctionBroker.invokeMethod(JavaFunctionBroker.java:57)at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:33)at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:10)at com.microsoft.azure.functions.worker.handler.MessageHandler.handle(MessageHandler.java:45)at com.microsoft.azure.functions.worker.JavaWorkerClient$StreamingMessagePeer.lambda$onNext$0(JavaWorkerClient.java:92)at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)at java.util.concurrent.FutureTask.run(FutureTask.java:266)at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)at java.lang.Thread.run(Thread.java:748)Caused by: java.lang.NoClassDefFoundError: Could not initialize class reactor.netty.http.client.HttpClientConfigat reactor.netty.http.client.HttpClientConnect.<init>(HttpClientConnect.java:84)at reactor.netty.http.client.HttpClient.create(HttpClient.java:393)at com.azure.core.http.netty.NettyAsyncHttpClientBuilder.build(NettyAsyncHttpClientBuilder.java:97)at com.azure.core.http.netty.NettyAsyncHttpClientProvider.createInstance(NettyAsyncHttpClientProvider.java:18)at com.azure.core.implementation.http.HttpClientProviders.createInstance(HttpClientProviders.java:58)at com.azure.core.http.HttpClient.createDefault(HttpClient.java:50)at com.azure.core.http.HttpClient.createDefault(HttpClient.java:40)at com.azure.core.http.HttpPipelineBuilder.build(HttpPipelineBuilder.java:62)at com.azure.security.keyvault.secrets.SecretClientBuilder.buildAsyncClient(SecretClientBuilder.java:190)at com.azure.security.keyvault.secrets.SecretClientBuilder.buildClient(SecretClientBuilder.java:112)at 

**To Reproduce**

***Code Snippet***
public class Function {
	@FunctionName("Function")
	public void run(
					@TimerTrigger(name = "timerInfo", schedule = "0 0 * * * *") String timerInfo,
					final ExecutionContext context
	) {
SecretClient secretClient = new SecretClientBuilder()
						.vaultUrl("https://<myVault>.vault.azure.net")
						.credential(new DefaultAzureCredentialBuilder().build())
						.buildClient();
           }
}

**Setup (please complete the following information):**
 - OS: Azure
 - IDE: VS
 - Library/Libraries: 
		<dependency>
			<groupId>com.microsoft.azure.functions</groupId>
			<artifactId>azure-functions-java-library</artifactId>
			<version>${azure.functions.java.library.version}</version>
		</dependency>

		<dependency>
			<groupId>com.azure</groupId>
			<artifactId>azure-identity</artifactId>
			<version>1.3.4</version>
		</dependency>
		
		<dependency>
			<groupId>com.azure</groupId>
			<artifactId>azure-security-keyvault-secrets</artifactId>
			<version>4.3.1</version>
		</dependency>

	

 - Java version: [e.g. 8] 
 - App Server/Environment:   Azure Function 
 - Frameworks: None

image

### PR DESCRIPTION
**Pull request by alzimmermsft**
Fixes #23237
Fixes #23382

This PR resolves an issue where the `List` returned from `Arrays.asList` was attempted to be mutated. Unfortunately, the implementation of the `List` returned is read-only, leading to an exception being thrown. Now, this code path uses an `ArrayList` which can be added to after the initial add, preventing the error from being thrown.

Additionally, a few performance fixes were done:

- Use `Pattern.compile` instead of `String` methods that compile a pattern internally.
- Use singleton `ObjectMapper`s instead of creating one per call.

### CODE REVIEW

File: sdk/identity/azure-identity/src/main/java/com/azure/identity/implementation/IdentityClient.java [hunk 1]
```diff
@@ -494,7 +494,8 @@
         PowershellManager legacyPowerShellManager = Platform.isWindows()
             ? new PowershellManager(LEGACY_WINDOWS_PS_EXECUTABLE) : null;
 
-        List<PowershellManager> powershellManagers = Arrays.asList(defaultPowerShellManager);
+        List<PowershellManager> powershellManagers = new ArrayList<>();
```
Comment (g2vinay) [inline sdk/identity/azure-identity/src/main/java/com/azure/identity/implementation/IdentityClient.java:497]: we can set the initial size to 2.

**Review by g2vinay — APPROVED** [review]
