### PR TITLE
[Service Bus] Client validation improvements for cross-language consistency

### LINKED ISSUE #17364: SB T2 Match Error messages with other languages
The error messages and validation is  documented in this onenote link .
We need to match how other languages are doing.

https://microsoft.sharepoint.com/teams/AzureDeveloperExperience/_layouts/OneNote.aspx?id=%2Fteams%2FAzureDeveloperExperience%2FShared%20Documents%2FService%20-%20Service%20Bus%2FAzure%20SDK%20-%20Service%20-%20Service%20Bus&wd=target%28Design.one%7C14D18AA9-3941-CF4D-B2FA-4B211AC30733%2FException%5C%2FError%20handling%7CE696ADB4-72C6-4A64-85FB-1D187557099B%2F%29
onenote:https://microsoft.sharepoint.com/teams/AzureDeveloperExperience/Shared%20Documents/Service%20-%20Service%20Bus/Azure%20SDK%20-%20Service%20-%20Service%20Bus/Design.one#Exception/Error%20handling&section-id={14D18AA9-3941-CF4D-B2FA-4B211AC30733}&page-id={E696ADB4-72C6-4A64-85FB-1D187557099B}&end

(using row numbers from our internal onenote):
- [ ] 1. Partition key != session ID 
- [x] 2. settle a message twice: "The message has either been deleted or already settled "
- [x] 3. Settle a message that has been peeked:
  - Check receiver mode first: "The operation not supported in 'ReceiveAndDelete' receive mode."
  - Check lock token next: "This operation is not supported for peeked messages. Only messages received using (methods) in PeekLock mode can be settled."
- [x] 4. Settle a message that was received in receiveAndDelete mode: "The operation not supported in 'ReceiveAndDelete' receive mode." (should get this for free once (3) is done)
- [x] 13. peekMessages where count < 0: "maxMessageCount must be 1 or greater"
   Java: maxMessages' cannot be less than or equal to 0. maxMessages: 0
- [ ] 14. receiveDeferredMessages with an empty list: return an empty list.
- [ ] 16. empty batch send: "A ServiceBusMessageBatch or list of Message must have at least one Message"
   **NOTE**: this might revert to simply no-oping on empty batches (in which case there is no work to do here).
- [ ] 18. Renew message lock on message received from session: "Renewing message lock is an invalid operation when working with sessions."
- [ ] 19, 20, 21: SessionId/ReplyToSessionId/MessageId/PartitionKey > 128 characters: "<field name> cannot be longer than 128 characters."

### PR DESCRIPTION
**Pull request by richardpark-msft**
Adding in additional client-side validation and unit tests.

Fixes #17364

### CODE REVIEW

File: sdk/servicebus/azure-messaging-servicebus/src/main/java/com/azure/messaging/servicebus/ServiceBusMessage.java [hunk 1]
```diff
@@ -267,6 +271,7 @@ public String getMessageId() {
      * @return The updated {@link ServiceBusMessage}.
      */
```
Comment (conniey) [inline sdk/servicebus/azure-messaging-servicebus/src/main/java/com/azure/messaging/servicebus/ServiceBusMessage.java:272]: Since you are adding validation, I would add a `@throws` to say what runtime exceptions are thrown.

File: sdk/servicebus/azure-messaging-servicebus/src/main/java/com/azure/messaging/servicebus/ServiceBusReceiverAsyncClient.java [hunk 2]
```diff
@@ -987,6 +986,11 @@ private boolean isManagementToken(String lockToken) {
         } else if (message.isSettled()) {
             return Mono.error(logger.logExceptionAsError(
                 new IllegalArgumentException("The message has either been deleted or already settled.")));
+        } else if (message.getLockToken() == null) {
+            // message must be a peeked message (or somehow they created a message w/o a lock token)
+            return Mono.error(
+                logger.logExceptionAsError(new UnsupportedOperationException("This operation is not supported for peeked messages. Only messages received using receiveMessages() or receiveMessagesWithContext() in PEEK_LOCK mode can be settled."))
```
Comment (hemanttanwar) [inline sdk/servicebus/azure-messaging-servicebus/src/main/java/com/azure/messaging/servicebus/ServiceBusReceiverAsyncClient.java:992]: We can add this in java doc for all the settlement operation (for ex complete, abandon.. etc ) in the client  
 `@throws UnsupportedOperationException` section.

File: sdk/servicebus/azure-messaging-servicebus/src/main/java/com/azure/messaging/servicebus/implementation/ManagementChannel.java [hunk 3]
```diff
@@ -189,7 +189,17 @@
...
+                                                                   String associatedLinkName, Iterable<Long> sequenceNumbers) {
+        if (sequenceNumbers == null) {
+            return fluxError(logger, new NullPointerException("'sequenceNumbers' cannot be null"));
+        }
+
+        final List<Long> numbers = new ArrayList<>();
+        sequenceNumbers.forEach(s -> numbers.add(s));
+
+        if (numbers.isEmpty()) {
+            return Flux.empty();
```
Comment (hemanttanwar) [inline sdk/servicebus/azure-messaging-servicebus/src/main/java/com/azure/messaging/servicebus/implementation/ManagementChannel.java:201]: We might want to put in `receiveDeferredMessages` API  (which take in `Iterable<Long> sequenceNumbers`  ) in sync and async client that empty list will complete the flux without sending to service bus .

File: sdk/servicebus/azure-messaging-servicebus/src/main/java/com/azure/messaging/servicebus/implementation/ManagementChannel.java [hunk 4]
```diff
@@ -291,7 +298,7 @@
      */
     @Override
     public Flux<Long> schedule(List<ServiceBusMessage> messages, OffsetDateTime scheduledEnqueueTime,
-        int maxLinkSize, String associatedLinkName, ServiceBusTransactionContext transactionContext) {
+                               int maxLinkSize, String associatedLinkName, ServiceBusTransactionContext transactionContext) {
```
Comment (hemanttanwar) [inline sdk/servicebus/azure-messaging-servicebus/src/main/java/com/azure/messaging/servicebus/implementation/ManagementChannel.java:301]: This is done by intellij for you, without you knowing . This should have 4 spaces before  `int` .  I see few more places like this.

Comment (richardpark-msft) [reply sdk/servicebus/azure-messaging-servicebus/src/main/java/com/azure/messaging/servicebus/implementation/ManagementChannel.java:301]: Gah, will fix :|

File: sdk/servicebus/azure-messaging-servicebus/src/main/java/com/azure/messaging/servicebus/implementation/ManagementChannel.java (hunk 3 above)
Comment (richardpark-msft) [reply sdk/servicebus/azure-messaging-servicebus/src/main/java/com/azure/messaging/servicebus/implementation/ManagementChannel.java:201]: Thinking about this a bit more - are we sure that's something that needs documenting? We're no longer treating it as an error condition so this just seems to fall under normal operating conditions.

File: sdk/servicebus/azure-messaging-servicebus/src/main/java/com/azure/messaging/servicebus/implementation/ManagementChannel.java (hunk 4 above)
Comment (richardpark-msft) [reply sdk/servicebus/azure-messaging-servicebus/src/main/java/com/azure/messaging/servicebus/implementation/ManagementChannel.java]: Fixed.

File: sdk/servicebus/azure-messaging-servicebus/src/main/java/com/azure/messaging/servicebus/ServiceBusReceiverAsyncClient.java (hunk 2 above)
Comment (richardpark-msft) [reply sdk/servicebus/azure-messaging-servicebus/src/main/java/com/azure/messaging/servicebus/ServiceBusReceiverAsyncClient.java]: Added.

File: sdk/servicebus/azure-messaging-servicebus/src/main/java/com/azure/messaging/servicebus/ServiceBusMessage.java (hunk 1 above)
Comment (richardpark-msft) [reply sdk/servicebus/azure-messaging-servicebus/src/main/java/com/azure/messaging/servicebus/ServiceBusMessage.java:273]: Added.

**Review by hemanttanwar — APPROVED** [review]

**Comment by richardpark-msft** [comment]
After talking with @hemanttanwar  I was able to run a sampling of the live tests on my machine so I'm calling this okay and I'm going to merge.
