### PR TITLE
Workaround for Cosmos endpoint PATCH operations

### LINKED ISSUE #20025: Cosmos Table endpoints diverge from Storage endpoint http behavior on merge operations
The Merge operation (which is implemented as Patch) always fails with a `405 MethodNotAllowed` response against Cosmos table endpoints. Inspecting the traffic sent by the track 1 client reveals that they send Merge as `Post` with an additional header: `X-HTTP-Method: MERGE`. Adding this header and changing the method to Post results in a successful merge in my testing.

Ideally the Cosmos Table endpoint would accept the same http request shape as Storage.

#cosmosKnownIssue

### PR DESCRIPTION
**Pull request by vcolin7**
Fixes #20025.

### CODE REVIEW

File: sdk/tables/azure-data-tables/src/main/java/com/azure/data/tables/implementation/TablesJacksonSerializer.java [hunk 1]
```diff
@@ -104,7 +104,11 @@ public String serialize(Object object, SerializerEncoding encoding) throws IOExc
 
     @Override
     public <U> U deserialize(byte[] bytes, Type type, SerializerEncoding encoding) throws IOException {
-        return deserialize(new ByteArrayInputStream(bytes), type, encoding);
+        if (bytes == null || bytes.length == 0) {
```
Comment (alzimmermsft) [inline sdk/tables/azure-data-tables/src/main/java/com/azure/data/tables/implementation/TablesJacksonSerializer.java:107]: This change looks good to me to resolve the issue you mentioned. Longer term I'm wondering if this class should move away from sub-typing JacksonAdapter to a composition style pattern. Another solution would be implementing custom JsonSerializer, JsonDeserializer classes which handle the few edge cases this class appears to have been created to handle.

**Review by alzimmermsft — APPROVED** [review]

File: sdk/tables/azure-data-tables/src/main/java/com/azure/data/tables/implementation/CosmosPatchTransformPolicy.java [hunk 2]
```diff
@@ -0,0 +1,41 @@
...
+        });
+    }
+
+    /**
+     * Transform a PATCH request into POST request with the "X-HTTP-Method":"MERGE" header set.
+     *
+     * @param request The pipeline's {@link HttpRequest}.
+     */
+    private void transformPatchToCosmosPost(HttpRequest request) {
+        request.setHttpMethod(HttpMethod.PATCH);
```
Comment (anuchandy) [inline sdk/tables/azure-data-tables/src/main/java/com/azure/data/tables/implementation/CosmosPatchTransformPolicy.java:38]: you mean `request.setHttpMethod(HttpMethod.POST);`, right?

Comment (vcolin7) [reply sdk/tables/azure-data-tables/src/main/java/com/azure/data/tables/implementation/CosmosPatchTransformPolicy.java:38]: You are correct, thanks for catching that!
