### PR TITLE
Use the builder to create table clients from service clients

### LINKED ISSUE #16292: [BUG] Exception "'Timestamp' must be an OffsetDateTime" when listing Table entities
When listing entities of an Azure Storage Table, I receive the exception:

```
12:15:39.877 [vert.x-eventloop-thread-0] ERROR fr.rexel.platform.core.server.toolkit.http.OpenApiOperationsHandler - Request failure with exception
java.lang.IllegalArgumentException: 'Timestamp' must be an OffsetDateTime.
	at com.azure.data.tables.models.TableEntity.validateProperty(TableEntity.java:137) ~[azure-data-tables-12.0.0-beta.2.jar:?]
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Assembly trace from producer [reactor.core.publisher.MonoFlatMap] :
	reactor.core.publisher.Mono.flatMap(Mono.java:2748)
	com.azure.data.tables.TableAsyncClient.listEntities(TableAsyncClient.java:616)
Error has been observed at the following site(s):
	|_       Mono.flatMap ⇢ at com.azure.data.tables.TableAsyncClient.listEntities(TableAsyncClient.java:616)
	|_       Mono.flatMap ⇢ at com.azure.core.util.FluxUtil.withContext(FluxUtil.java:203)
	|_          Mono.flux ⇢ at com.azure.core.http.rest.PagedFlux.lambda$new$1(PagedFlux.java:66)
	|_ Flux.switchIfEmpty ⇢ at com.azure.core.util.paging.ContinuablePagedFluxCore.concatFluxOfPage(ContinuablePagedFluxCore.java:170)
	|_      Flux.doOnNext ⇢ at com.azure.core.util.paging.ContinuablePagedFluxCore.concatFluxOfPage(ContinuablePagedFluxCore.java:174)
	|_    Flux.concatWith ⇢ at com.azure.core.util.paging.ContinuablePagedFluxCore.concatFluxOfPage(ContinuablePagedFluxCore.java:175)
	|_         Flux.defer ⇢ at com.azure.core.util.paging.ContinuablePagedFluxCore.byPage(ContinuablePagedFluxCore.java:145)
	|_       Flux.flatMap ⇢ at com.azure.core.util.paging.ContinuablePagedFluxCore.subscribe(ContinuablePagedFluxCore.java:122)
Stack trace:
		at com.azure.data.tables.models.TableEntity.validateProperty(TableEntity.java:137) ~[azure-data-tables-12.0.0-beta.2.jar:?]
		at com.azure.data.tables.models.TableEntity.addProperties(TableEntity.java:121) ~[azure-data-tables-12.0.0-beta.2.jar:?]
		at com.azure.data.tables.implementation.ModelHelper.createEntity(ModelHelper.java:78) ~[azure-data-tables-12.0.0-beta.2.jar:?]
		at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) ~[?:?]
		at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655) ~[?:?]
		at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
		at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
		at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[?:?]
		at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
		at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) ~[?:?]
		at com.azure.data.tables.TableAsyncClient.lambda$listEntities$33(TableAsyncClient.java:630) ~[azure-data-tables-12.0.0-beta.2.jar:?]
		at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:118) ~[reactor-core-3.3.9.RELEASE.jar:3.3.9.RELEASE]
...
```

And indeed the Timestamp property is of type String in the deserialzed response: https://ibb.co/JcShrdb

- OS: Windows
- IDE : IntelliJ IDEA
- kotlin 1.4.10
- azure-data-tables-12.0.0-beta.2

### PR DESCRIPTION
**Pull request by bsiegel**
Previously we thought we could be most optimal by just reusing the `AzureTableImpl` object, but we can't do that because the table client needs to use a specific serializer that knows how to handle the EDM data types, whereas the service client uses the default serializer or lets the customer customize it.

Fixes #16292

### CODE REVIEW

File: sdk/tables/azure-data-tables/src/main/java/com/azure/data/tables/BuilderHelper.java [hunk 1]
```diff
@@ -130,6 +135,7 @@ private static String getPrimaryEndpointForTokenAuth(String endpoint) {
      */
     private static HttpLogOptions getDefaultHttpLogOptions() {
         HttpLogOptions defaultOptions = new HttpLogOptions();
+        // TODO
```
Comment (conniey) [inline sdk/tables/azure-data-tables/src/main/java/com/azure/data/tables/BuilderHelper.java:138]: TODO?

**Review by conniey — APPROVED** [review]

File: sdk/tables/azure-data-tables/src/main/java/com/azure/data/tables/BuilderHelper.java (hunk 1 above)
Comment (bsiegel) [reply sdk/tables/azure-data-tables/src/main/java/com/azure/data/tables/BuilderHelper.java:138]: Yes, this code was commented already but there was no TODO, so I had missed it previously. I don't want to fix it in this PR, it's not critical - all this does is set up the allowlist of header and query string names that are permitted to be logged. Without it, they show up as `REDACTED`. I need to take the time to mine the docs / swagger / etc to determine the list of service headers / query string params that should be permitted.

Comment (bsiegel) [reply sdk/tables/azure-data-tables/src/main/java/com/azure/data/tables/BuilderHelper.java:138]: Filed #16408 to track this
