### PR TITLE
Stop logging HttpResponseExceptions in RestProxy classes

### LINKED ISSUE #36673: Adjusting the logging for Sync Rest Proxy
Sync rest proxy should not utilize the RestProxyBase logger, it adds difficultly towards understanding the logs.

Also, we should look to adjust rest proxy base to not log status codes for completed HTTP requests. If the service rejects the request, we should allow that to be logged by the SDKs, allowing them to maintain their own logging logic.

### PR DESCRIPTION
**Pull request by alzimmermsft**
# Description

Fixes #36673

This changes how `RestProxyBase` implementations propagate `HttpResponseException`s to have them not be logged. `HttpResponseException`s aren't exceptions that happen due to runtime problems but represent the service call made wasn't proper and shouldn't be logged as a runtime error in the SDKs.

This also makes a change to `HttpResponseException` instantiation to return an `HttpResponseException` if the type fails to be created instead of the previous `IOException`. This aligns better with how `UnexpectedExceptionInformation` works in the default behavior being `HttpResponseException` as the default exception type.

# All SDK Contribution checklist:
- [x] **The pull request does not introduce [breaking changes]**
- [x] **CHANGELOG is updated for new features, bug fixes or other significant changes.**
- [x] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md).**

## [General Guidelines and Best Practices](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md#developer-guide)
- [x] Title of the pull request is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md#building-and-unit-testing)
- [x] Pull request includes test coverage for the included changes.

### CODE REVIEW

File: sdk/core/azure-core/src/main/java/com/azure/core/implementation/http/rest/SyncRestProxy.java [hunk 1]
```diff
@@ -80,22 +80,17 @@ public Object invoke(Object proxy, Method method, RequestOptions options, EnumSe
...
+        } catch (Exception e) {
             tracer.end(null, e, context);
-            throw LOGGER.logExceptionAsError(e);
-        } finally {
-            try {
-                scope.close();
-            } catch (Exception e) {
-                LOGGER.verbose("Failed to close scope");
-            }
+            sneakyThrows(e);
```
Comment (lmolkova) [inline sdk/core/azure-core/src/main/java/com/azure/core/implementation/http/rest/SyncRestProxy.java:85]: :ok_hand:

**Review by lmolkova — APPROVED** [review]

File: sdk/core/azure-core/src/main/java/com/azure/core/implementation/http/rest/SyncRestProxy.java (hunk 1 above)
Comment (alzimmermsft) [reply sdk/core/azure-core/src/main/java/com/azure/core/implementation/http/rest/SyncRestProxy.java:85]: Reading through some of OpenTelemetry's code in Tracers I'm not even sure this will be reached. 😄

**Comment by serafimpinto** [comment]
Hi @alzimmermsft and @lmolkova I tested the version https://mvnrepository.com/artifact/com.azure/azure-data-tables/12.3.18 and I'am still getting the error Status code 409

**Comment by serafimpinto** [comment]
Sorry @alzimmermsft I didn't copy all the logs. So I am receiving these logs every time I call `createTableIfNotExists`:

```
c.a.c.i.http.rest.RestProxyBase          : Status code 409, "{"odata.error":{"code":"TableAlreadyExists","message":{"lang":"en-US","value":"The table specified already exists.\nRequestId:bf6206e5-8002-0049-027d-4909ec000000\nTime:2024-01-17T19:43:38.5963411Z"}}}"
c.a.c.i.http.rest.RestProxyBase          : Status code 409, "{"odata.error":{"code":"TableAlreadyExists","message":{"lang":"en-US","value":"The table specified already exists.\nRequestId:bf6206e5-8002-0049-027d-4909ec000000\nTime:2024-01-17T19:43:38.5963411Z"}}}"
c.azure.data.tables.TableServiceClient   : Status code 409, "{"odata.error":{"code":"TableAlreadyExists","message":{"lang":"en-US","value":"The table specified already exists.\nRequestId:bf6206e5-8002-0049-027d-4909ec000000\nTime:2024-01-17T19:43:38.5963411Z"}}}"
```

So I think it might be related to the issue in this PR. I already tried some workarounds but without success

**Comment by alzimmermsft** [comment]
@serafimpinto when calling this API, does it also throw an exception as well? Or, does it just have these errant logs?

I'll need to do some investigation on why this is happening as `TableServiceClient` shouldn't be logging an exception when calling `createTableIfNotExists` and the error code is 409 TableAlreadyExists, which can be seen here:

https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/tables/azure-data-tables/src/main/java/com/azure/data/tables/TableServiceClient.java#L484

And the only time `RestProxyBase`, `SyncRestProxy`, and `AsyncRestProxy` should log a message is when there is an `IOException` when handling the request, which is doesn't seem is the case here.

https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/core/azure-core/src/main/java/com/azure/core/implementation/http/rest/RestProxyBase.java#L131

Could you include a `mvn dependency:tree` of your project to make sure `azure-data-tables` `12.3.18` is being resolved? And that `azure-core` `1.45.1` is being resolved.

**Comment by serafimpinto** [comment]
Hello @alzimmermsft,

After inspecting the dependencies, I noticed that `azure-core` version `1.45.1` was not present. This change effectively resolved the issue with the logs from the `RestProxyBase` class. Thank you for addressing that.

However, I've observed that the `TableServiceClient` still logs `409` errors. I understand this might not be directly related to this particular issue, but I wanted to bring it up for visibility. As a temporary workaround, I've added `logging.level.com.azure.data.tables.TableServiceClient=off` to my `application.properties` to prevent flooding my logs with these errors. While this might not be the optimal solution, it provides a stopgap measure.

Thanks for your attention to this matter.

**Comment by alzimmermsft** [comment]
> Hello @alzimmermsft,
> 
> After inspecting the dependencies, I noticed that `azure-core` version `1.45.1` was not present. This change effectively resolved the issue with the logs from the `RestProxyBase` class. Thank you for addressing that.
> 
> However, I've observed that the `TableServiceClient` still logs `409` errors. I understand this might not be directly related to this particular issue, but I wanted to bring it up for visibility. As a temporary workaround, I've added `logging.level.com.azure.data.tables.TableServiceClient=off` to my `application.properties` to prevent flooding my logs with these errors. While this might not be the optimal solution, it provides a stopgap measure.
> 
> Thanks for your attention to this matter.

@serafimpinto, glad to hear the `RestProxyBase` logging was resolved. For the logging in `TableServiceClient` could you file an issue for that?
