### PR TITLE
Filter out the closed receiving links before passing them downstream.

### LINKED ISSUE #32919: [BUG]When the receive link is recovering due to a transient error, the `ServiceBusReceiveLinkProcessor` repeatedly request the closed link until the new link is active.
**Describe the bug**

When link is detached by remote or encounter some other transient error, the link subscription in `ServiceBusReceiveLinkProcessor` will complete and request a new link. For some reason (currently I suspect because the new link is created on the reactor thread and is not synchronized), `ServiceBusReceiveLinkProcessor` will get the same closed link until a new link is created and become active. 

Thus, during this period of time, `ServiceBusReceiveLinkProcessor` repeatedly request a new link -> receive the closed link -> link subscription onComplete and request a new link. This is a waste of CPU resources and generates a lot of noisy logs:

```
11:35:22.435 [reactor-executor-1] DEBUG c.a.c.a.i.ReactorReceiver - {"az.sdk.message":"State ACTIVE","connectionId":"MF_2a9abe_1673494518595","entityPath":"testqueue","linkName":"testqueue_0ad7d0_1673494518565"}
11:35:22.435 [reactor-executor-1] INFO  c.a.c.a.i.handler.ReceiveLinkHandler - {"az.sdk.message":"onLinkRemoteOpen","connectionId":"MF_2a9abe_1673494518595","entityPath":"testqueue","linkName":"testqueue_0ad7d0_1673494518565","remoteSource":"Source{address='testqueue', durable=NONE, expiryPolicy=SESSION_END, timeout=0, dynamic=false, dynamicNodeProperties=null, distributionMode=null, filter=null, defaultOutcome=null, outcomes=null, capabilities=null}"}
11:37:11.090 [reactor-executor-1] INFO  c.a.c.a.i.handler.ReceiveLinkHandler - {"az.sdk.message":"onLinkRemoteClose","connectionId":"MF_2a9abe_1673494518595","errorCondition":"amqp:link:detach-forced","errorDescription":"The link 'G48:4410112:testqueue_0ad7d0_1673494518565' is force detached. Code: consumer(link514975). Details: InnerMessageReceiver was closed. TrackingId:db7bf3c8000000400007db9f63bf7ff9_G48_B15, SystemTracker:servicebusliuku:Queue:testqueue, Timestamp:2023-01-12T03:37:10","linkName":"testqueue_0ad7d0_1673494518565","entityPath":"testqueue"}
11:37:11.090 [reactor-executor-1] INFO  c.a.c.a.i.handler.ReceiveLinkHandler - {"az.sdk.message":"Local link state is not closed.","connectionId":"MF_2a9abe_1673494518595","linkName":"testqueue_0ad7d0_1673494518565","entityPath":"testqueue","state":"ACTIVE"}
11:37:11.094 [reactor-executor-1] INFO  c.a.c.a.i.ReactorReceiver - {"az.sdk.message":"Freeing resources due to error.","connectionId":"MF_2a9abe_1673494518595","entityPath":"testqueue","linkName":"testqueue_0ad7d0_1673494518565"}
11:37:11.096 [reactor-executor-1] DEBUG c.a.c.a.i.handler.ReceiveLinkHandler - {"az.sdk.message":"Could not emit deliveries.close when closing handler.","connectionId":"MF_2a9abe_1673494518595","entityPath":"testqueue","linkName":"testqueue_0ad7d0_1673494518565"}
11:37:11.104 [reactor-executor-1] WARN  c.a.m.s.i.ServiceBusReceiveLinkProcessor - {"az.sdk.message":"Transient error occurred.","exception":"The link 'G48:4410112:testqueue_0ad7d0_1673494518565' is force detached. Code: consumer(link514975). Details: InnerMessageReceiver was closed. TrackingId:db7bf3c8000000400007db9f63bf7ff9_G48_B15, SystemTracker:servicebusliuku:Queue:testqueue, Timestamp:2023-01-12T03:37:10, errorContext[NAMESPACE: servicebusliuku.servicebus.windows.net. ERROR CONTEXT: N/A, PATH: testqueue, REFERENCE_ID: testqueue_0ad7d0_1673494518565, LINK_CREDIT: 1]","linkName":"n/a","entityPath":"n/a","attempt":1,"retryAfter":4511}
com.azure.core.amqp.exception.AmqpException: The link 'G48:4410112:testqueue_0ad7d0_1673494518565' is force detached. Code: consumer(link514975). Details: InnerMessageReceiver was closed. TrackingId:db7bf3c8000000400007db9f63bf7ff9_G48_B15, SystemTracker:servicebusliuku:Queue:testqueue, Timestamp:2023-01-12T03:37:10, errorContext[NAMESPACE: servicebusliuku.servicebus.windows.net. ERROR CONTEXT: N/A, PATH: testqueue, REFERENCE_ID: testqueue_0ad7d0_1673494518565, LINK_CREDIT: 1]
	at com.azure.core.amqp.implementation.ExceptionUtil.toException(ExceptionUtil.java:85)
	at com.azure.core.amqp.implementation.handler.LinkHandler.handleRemoteLinkClosed(LinkHandler.java:120)
	at com.azure.core.amqp.implementation.handler.LinkHandler.onLinkRemoteClose(LinkHandler.java:64)
	at com.azure.core.amqp.implementation.handler.ReceiveLinkHandler.onLinkRemoteClose(ReceiveLinkHandler.java:228)
	at org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:176)
	at org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:324)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:291)
	at com.azure.core.amqp.implementation.ReactorExecutor.run(ReactorExecutor.java:91)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
11:37:11.105 [reactor-executor-1] DEBUG c.a.c.a.i.handler.ReceiveLinkHandler - {"az.sdk.message":"onLinkLocalClose","connectionId":"MF_2a9abe_1673494518595","errorCondition":"amqp:link:detach-forced","errorDescription":"The link 'G48:4410112:testqueue_0ad7d0_1673494518565' is force detached. Code: consumer(link514975). Details: InnerMessageReceiver was closed. TrackingId:db7bf3c8000000400007db9f63bf7ff9_G48_B15, SystemTracker:servicebusliuku:Queue:testqueue, Timestamp:2023-01-12T03:37:10","linkName":"testqueue_0ad7d0_1673494518565","entityPath":"testqueue"}
11:37:11.107 [reactor-executor-1] INFO  c.a.c.a.i.handler.ReceiveLinkHandler - {"az.sdk.message":"onLinkFinal","connectionId":"MF_2a9abe_1673494518595","linkName":"testqueue_0ad7d0_1673494518565","entityPath":"testqueue"}
11:37:15.632 [parallel-2] INFO  c.a.m.s.i.ServiceBusReceiveLinkProcessor - Requesting a new AmqpReceiveLink from upstream.
11:37:15.632 [parallel-2] DEBUG c.a.m.s.ServiceBusReceiverAsyncClient - {"az.sdk.message":"Created consumer for Service Bus resource.","linkName":"testqueue_0ad7d0_1673494518565","entityPath":"testqueue","mode":"PEEK_LOCK","isSessionEnabled":false,"entityType":"QUEUE"}
11:37:15.632 [parallel-2] INFO  c.a.m.s.i.ServiceBusReceiveLinkProcessor - {"az.sdk.message":"Setting next AMQP receive link.","linkName":"testqueue_0ad7d0_1673494518565","entityPath":"testqueue"}
11:37:15.632 [parallel-2] DEBUG c.a.m.s.i.ServiceBusReceiveLinkProcessor - {"az.sdk.message":"Adding credits.","prefetch":0,"requested":1,"linkCredits":1,"expectedTotalCredit":1,"queuedMessages":0,"creditsToAdd":0,"messageQueueSize":0}
11:37:15.632 [parallel-2] DEBUG c.a.m.s.i.ServiceBusReactorAmqpConnection - {"az.sdk.message":"Get or create consumer.","entityPath":"testqueue"}
11:37:15.632 [parallel-2] DEBUG c.a.c.a.i.AzureTokenManagerProvider - {"az.sdk.message":"Creating new token manager.","audience":"amqp://servicebusliuku.servicebus.windows.net/testqueue","resource":"testqueue"}
11:37:15.632 [boundedElastic-3] WARN  c.a.m.s.i.ServiceBusReceiveLinkProcessor - {"az.sdk.message":"Transient error occurred.","exception":"The link 'G48:4410112:testqueue_0ad7d0_1673494518565' is force detached. Code: consumer(link514975). Details: InnerMessageReceiver was closed. TrackingId:db7bf3c8000000400007db9f63bf7ff9_G48_B15, SystemTracker:servicebusliuku:Queue:testqueue, Timestamp:2023-01-12T03:37:10, errorContext[NAMESPACE: servicebusliuku.servicebus.windows.net. ERROR CONTEXT: N/A, PATH: testqueue, REFERENCE_ID: testqueue_0ad7d0_1673494518565, LINK_CREDIT: 1]","linkName":"n/a","entityPath":"n/a","attempt":1,"retryAfter":4511}
com.azure.core.amqp.exception.AmqpException: The link 'G48:4410112:testqueue_0ad7d0_1673494518565' is force detached. Code: consumer(link514975). Details: InnerMessageReceiver was closed. TrackingId:db7bf3c8000000400007db9f63bf7ff9_G48_B15, SystemTracker:servicebusliuku:Queue:testqueue, Timestamp:2023-01-12T03:37:10, errorContext[NAMESPACE: servicebusliuku.servicebus.windows.net. ERROR CONTEXT: N/A, PATH: testqueue, REFERENCE_ID: testqueue_0ad7d0_1673494518565, LINK_CREDIT: 1]
	at com.azure.core.amqp.implementation.ExceptionUtil.toException(ExceptionUtil.java:85)
	at com.azure.core.amqp.implementation.handler.LinkHandler.handleRemoteLinkClosed(LinkHandler.java:120)
	at com.azure.core.amqp.implementation.handler.LinkHandler.onLinkRemoteClose(LinkHandler.java:64)
	at com.azure.core.amqp.implementation.handler.ReceiveLinkHandler.onLinkRemoteClose(ReceiveLinkHandler.java:228)
	at org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:176)
	at org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:324)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:291)
	at com.azure.core.amqp.implementation.ReactorExecutor.run(ReactorExecutor.java:91)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
11:37:15.635 [parallel-2] DEBUG c.a.c.a.i.RequestResponseChannel - {"az.sdk.message":"Scheduling on dispatcher.","connectionId":"MF_2a9abe_1673494518595","linkName":"cbs","messageId":null}
11:37:15.635 [reactor-executor-1] DEBUG c.a.c.a.i.handler.SendLinkHandler - {"az.sdk.message":"onLinkFlow.","connectionId":"MF_2a9abe_1673494518595","linkName":"cbs","unsettled":0,"credits":98}
11:37:15.934 [reactor-executor-1] DEBUG c.a.c.a.i.RequestResponseChannel - {"az.sdk.message":"Settling message.","connectionId":"MF_2a9abe_1673494518595","linkName":"cbs","messageId":"2"}
11:37:15.934 [reactor-executor-1] INFO  c.a.c.a.i.ActiveClientTokenManager - {"az.sdk.message":"Scheduling refresh token task.","scopes":"amqp://servicebusliuku.servicebus.windows.net/testqueue"}
11:37:15.934 [reactor-executor-1] DEBUG c.a.c.a.i.handler.ReceiveLinkHandler - {"az.sdk.message":"onDelivery.","connectionId":"MF_2a9abe_1673494518595","errorCondition":null,"errorDescription":null,"entityPath":"$cbs","linkName":"cbs","updatedLinkCredit":0,"remoteCredit":0,"delivery.isPartial":false,"delivery.isSettled":false}
11:37:15.934 [reactor-executor-1] INFO  c.a.c.a.i.ReactorSession - {"az.sdk.message":"Creating a new receiver link.","connectionId":"MF_2a9abe_1673494518595","sessionName":"testqueue","linkName":"testqueue_0ad7d0_1673494518565"}
11:37:15.934 [reactor-executor-1] DEBUG c.a.c.a.i.ReactorReceiver - {"az.sdk.message":"State UNINITIALIZED","connectionId":"MF_2a9abe_1673494518595","entityPath":"testqueue","linkName":"testqueue_0ad7d0_1673494518565"}
11:37:15.934 [reactor-executor-1] DEBUG c.a.c.a.i.ReactorReceiver - {"az.sdk.message":"Token refreshed.","connectionId":"MF_2a9abe_1673494518595","entityPath":"testqueue","linkName":"testqueue_0ad7d0_1673494518565","response":"ACCEPTED"}
11:37:15.934 [reactor-executor-1] DEBUG c.a.c.a.i.handler.ReceiveLinkHandler - {"az.sdk.message":"onLinkLocalOpen","connectionId":"MF_2a9abe_1673494518595","entityPath":"testqueue","linkName":"testqueue_0ad7d0_1673494518565","localSource":"Source{address='testqueue', durable=NONE, expiryPolicy=SESSION_END, timeout=0, dynamic=false, dynamicNodeProperties=null, distributionMode=null, filter=null, defaultOutcome=null, outcomes=null, capabilities=null}"}
11:37:16.242 [reactor-executor-1] DEBUG c.a.c.a.i.ReactorReceiver - {"az.sdk.message":"State ACTIVE","connectionId":"MF_2a9abe_1673494518595","entityPath":"testqueue","linkName":"testqueue_0ad7d0_1673494518565"}
11:37:16.242 [reactor-executor-1] INFO  c.a.c.a.i.handler.ReceiveLinkHandler - {"az.sdk.message":"onLinkRemoteOpen","connectionId":"MF_2a9abe_1673494518595","entityPath":"testqueue","linkName":"testqueue_0ad7d0_1673494518565","remoteSource":"Source{address='testqueue', durable=NONE, expiryPolicy=SESSION_END, timeout=0, dynamic=false, dynamicNodeProperties=null, distributionMode=null, filter=null, defaultOutcome=null, outcomes=null, capabilities=null}"}
11:37:20.153 [parallel-3] INFO  c.a.m.s.i.ServiceBusReceiveLinkProcessor - Requesting a new AmqpReceiveLink from upstream.
11:37:20.153 [parallel-3] DEBUG c.a.m.s.ServiceBusReceiverAsyncClient - {"az.sdk.message":"Created consumer for Service Bus resource.","linkName":"testqueue_0ad7d0_1673494518565","entityPath":"testqueue","mode":"PEEK_LOCK","isSessionEnabled":false,"entityType":"QUEUE"}
11:37:20.153 [parallel-3] INFO  c.a.m.s.i.ServiceBusReceiveLinkProcessor - {"az.sdk.message":"Setting next AMQP receive link.","linkName":"testqueue_0ad7d0_1673494518565","entityPath":"testqueue"}
11:37:20.153 [parallel-3] DEBUG c.a.m.s.i.ServiceBusReceiveLinkProcessor - {"az.sdk.message":"Adding credits.","prefetch":0,"requested":1,"linkCredits":0,"expectedTotalCredit":1,"queuedMessages":0,"creditsToAdd":1,"messageQueueSize":0}
11:37:20.155 [parallel-3] DEBUG c.a.m.s.i.ServiceBusReactorAmqpConnection - {"az.sdk.message":"Get or create consumer.","entityPath":"testqueue"}
11:37:20.155 [parallel-3] INFO  c.a.c.a.i.ReactorSession - {"az.sdk.message":"Returning existing receive link.","connectionId":"MF_2a9abe_1673494518595","linkName":"testqueue_0ad7d0_1673494518565","entityPath":"testqueue"}
```

The `AmqpReceiveLinkProcessor` in EH could also have the same issue.

**To Reproduce**
Create a transient error while receiver isreceiving the messages (update SB lock time/ wait link idle)

***Code Snippet***
```
    private static CountDownLatch latch = new CountDownLatch(1);

    public static void main(String[] args) throws InterruptedException {
        Consumer<ServiceBusReceivedMessageContext> processMessage = messageContext -> {
            try {
                System.out.println(messageContext.getMessage().getMessageId());
                // other message processing code
                messageContext.complete();
            } catch (Exception ex) {
                messageContext.abandon();
            }
        };

        Consumer<ServiceBusErrorContext> processError = errorContext -> {
            System.err.println("Error occurred while receiving message: " + errorContext.getException());
        };

        ServiceBusProcessorClient processorClient = new ServiceBusClientBuilder()
                .connectionString(Credentials.serviceBusConnectionString)
                .processor()
                .maxAutoLockRenewDuration(Duration.ZERO)
                .disableAutoComplete()
                .queueName(Credentials.serviceBusQueue)
                .processMessage(processMessage)
                .processError(processError)
                .buildProcessorClient();

        processorClient.start();

        latch.await();
    }
```

### PR DESCRIPTION
**Pull request by liukun-msft**
# Description

- Fixes #32919

Add a filter to filter out the closed links is the quick fix for this issue.

The long-term plan will be refactoring the `ServiceBusReceiveLinkProcessor` and `AmqpReceiveLinkProcessor` with the new design for `ConnectionProcessor`.

# The reason for "Cannot add credits to closed link:"

Analyzing the logs and the internal of the Reactor indicate that the logged error is due to an undesired prefetching/caching by the MonoFlatMap Reactor operator (in the async-chain associated with ServiceBusReceiveLinkProcessor).

### The async-chain

The async-chain associated with ServiceBusReceiveLinkProcessor in order to obtain a Link looks like below -

```
ServiceBusLinkProcessor
     |          ↑ 
    [1]        [8]
     ↓          |
Repeat [Flux<Link>]
     |          ↑ 
    [2]        [7]
     ↓          |
|---------------|------------------------------------------|
| MonoFlatMap   |                                          |
|    |      |  [6]                                         |
|    |     [5]  |                                          |
|   [3]     ↓   |                                          |
|    |      ObtainLink connection.createLink [Mono<Link>]  |
|    |                                                     |
|----|-----------------------------------------------------|
     |   ↑
     |   |
     |  [4] 
     ↓   |
ObtainConnection [ConnectionProcessor : Mono<Connection>]

```

### The async-chain flow

The flow in the async-chain that leads to the error message "Cannot add credits to closed link:" is described below -

1. ServiceBusReceiveLinkProcessor (SRLP) _**Subscribe**_ and _**Request**_ the first Link from it upstream 'repeat()'.
2. The 'repeat()' _**Subscribe**_ and _**Request**_ its upstream 'MonoFlatmap.'
3. The 'MonoFlatmap' _**Subscribe**_ and _**Request**_ it upstream 'ConnectionProcessor', it's a Mono&lt;Connection&gt;.
4. The Mono&lt;Connection&gt; emits a Connection to 'MonoFlatmap'.
5. The 'MonoFlatmap' _**Subscribe**_ to Connection.createLink and _**Request**_ a link.
6. The Connection.createLink creates Link1, caches it in Link-HashMap-Cache in Connection's session, and emits Link1 to 'MonoFlatmap'.
7. The 'MonoFlatmap' emits the Link1 to 'repeat()'.
8. The 'repeat()' emits the Link1 to SRLP.
9. The SRLP schedules credit on Link1, and then the call stack unwinds, and the control returns to the call site, i.e., to the line after emission (Step-8) in the 'repeat()' operator.
10. At this point,  the 'repeat()' internally Re-_**Subscribe**_ to 'MonoFlatmap'. Note that it's only _**Subscribe**_; it won't make a _**Request**_.

The 'MonoFlatmap' by design will perform the work it represents when downstream (repeat() in this case) _**Subscribe**_, i.e., it does not require downstream to _**Request**_, but a Subscription is enough to trigger the work.

The triggering of work results  'MonoFlatmap' to both _**Subscribe**_ and _**Request**_ Connection to Mono&lt;Connection&gt;; once Connection is received, the 'MonoFlatmap' _**Subscribe**_ to createLink and _**Request**_ a Link. This time, the Link will be served from the cache (Link-HashMap-Cache in Connection's session), i.e., the 'MonoFlatmap' receives the same Link1.

11. In Step-10, the 'repeat()' is only _**Subscribe**_-d 'MonoFlatmap' but didn't _**Request**_. Because of that, the 'MonoFlatmap' operator won't emit the Link1, but hold to (i.e., cache) it.

12. Eventually, when Link1 receives detach frame (say after 10 min idle timeout),

- Link1 Pojo gets closed (disposed).
- Link1 gets removed from the Link-HashMap-Cache in Connection's session.
- The SRLP is notified of Link1 closure, and it does some cleanup.
- The SRLP requests a new Link from the upstream 'repeat()'.

13. The repeat() _**Request**_ a link from its upstream, i.e., 'MonoFlatmap'
14. The 'MonoFlatmap' emits the Link cached in step11, which is nothing but the closed Link1.
13. SRLP gets the closed Link1 and schedule credit on it, which reports the error "Cannot add credits to closed link:".
14. At this point, the call stack unwinds (the same sequence we saw from step 8), 'repeat()' Re-_**Subscribe**_ where the resulting flow experience cache miss from Link-HashMap-Cache and obtains a new Link2, and the 'MonoFlatmap' holds on to it. It won't be emitted as there is no _**Request**_ yet.

Here is a standalone runnable async-chain code similar to what we have in the library. The code has the necessary hooks to print the flow described above.

<details>
  <summary>Runnable async-chain code</summary>
  
```java
package com.anuchan.console;

import org.reactivestreams.Subscription;
import reactor.core.CoreSubscriber;
import reactor.core.publisher.Mono;
import reactor.core.scheduler.Schedulers;

import java.time.Instant;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.atomic.AtomicBoolean;
import java.util.concurrent.atomic.AtomicInteger;
import java.util.concurrent.atomic.AtomicReference;

public class ObtainLinkControlFlow {

    public static void main( String[] args ) throws InterruptedException {

        final Mono<Connection> obtainConnection = Mono.<Connection>create(connectionSink -> {
            System.out.println("  ObtainConnection.body {con=Connection}");
            connectionSink.success(Connection.CON);
        }).doOnSubscribe(__ -> {
            System.out.println("↑ ObtainConnection.subscribe()");
        }).doOnRequest(r -> {
            String rStr = (r == Long.MAX_VALUE) ? "LONG.MAX" : String.valueOf(r);
            System.out.println("↑ ObtainConnection.onRequest(" + rStr + ")");
        }).doOnNext(__ -> {
            System.out.println("  ObtainConnection.emitted(con)                                 ↓");
        });

       final Mono<Link> monoFlatmap = obtainConnection.flatMap(c -> {
           System.out.println("  MonoFlatmap.body {Got con, now obtain link}");
           return c.createLink();
       }).doOnSubscribe(__ -> {
           System.out.println("↑ MonoFlatmap.subscribe()");
       }).doOnRequest(r -> {
           System.out.println("↑ MonoFlatmap.onRequest(" + r + ")");
       }).doOnNext(l -> {
           System.out.println("  MonoFlatmap.emitted(" + l.toString() + ")    ↓");
       });

        monoFlatmap.repeat()
        .doOnSubscribe(__ -> {
            System.out.println("↑ repeat.subscribe()");
        }).doOnRequest(r -> {
            System.out.println("↑ repeat.onRequest(" + r + ")");
        }).doOnNext(l -> {
            System.out.println("  repeat.emitted(" + l.toString() + ")         ↓");
        })
        .subscribe(new CoreSubscriber<Link>() {
            private Subscription s;
            private AtomicInteger invocations = new AtomicInteger();

            @Override
            public void onSubscribe(Subscription s) {
                this.s = s;
                System.out.println("  \n  ServiceBusReceiveLinkProcessor requesting first link \n");
                s.request(1);
            }

            @Override
            public void onNext(final Link l) {
                final int c = invocations.getAndIncrement();
                if (c == 0) {
                    System.out.println("  \n  ServiceBusReceiveLinkProcessor got first link - " + l.toString() + "\n");
                    Schedulers.boundedElastic().schedule(() -> {
                        System.out.println("\n  ServiceBusReceiveLinkProcessor closing first link & requesting second \n");
                        l.close();
                        s.request(1);
                    }, 2, TimeUnit.SECONDS);
                } else {
                    System.out.println("  \n  ServiceBusReceiveLinkProcessor got second link - " + l.toString() + "\n");
                }
            }

            @Override
            public void onError(Throwable t) {

            }

            @Override
            public void onComplete() {

            }
        });

        TimeUnit.SECONDS.sleep(10);
    }

    final static class Link extends AtomicBoolean {
        private final Instant createdAt;

        Link() {
            this.createdAt = Instant.now();
        }

        public boolean isClosed() {
            return this.get();
        }

        public void close() {
            this.getAndSet(true);
        }

        @Override
        public String toString() {
            return "{LinkId:" + this.createdAt.toEpochMilli() + " isClosed:" + this.get() + "}";
        }
    }

    final static class Connection {
        final static Connection CON = new Connection();
        private final AtomicReference<Link> linkCache = new AtomicReference<>();

        public Mono<Link> createLink() {
            final Mono<Link> obtainLink = Mono.fromSupplier(() -> {
                if (linkCache.get() == null || linkCache.get().isClosed()) {
                    System.out.println("  Con.ObtainLink.body { link=new_Link }");
                    linkCache.set(new Link());
                } else {
                    System.out.println("  Con.ObtainLink.body { link=from_cache }");
                }
                return linkCache.get();
            }).doOnSubscribe(__ -> {
                System.out.println("↑ Con.ObtainLink.subscribe()");
            }).doOnRequest(r -> {
                String rStr = (r == Long.MAX_VALUE) ? "LONG.MAX" : String.valueOf(r);
                System.out.println("↑ Con.ObtainLink.onRequest(" + rStr + ")");
            }).doOnNext(l -> {
                System.out.println("  Con.ObtainLink.emitted(" + l.toString() + ") ↓");
            });
            return obtainLink;
        }
    }
}
```

</details>

### Conclusions

1. Is this a reliability issue? _**NO**_ , While SRLP logs the error, given that Link1 is disposed, its endpoint replays the termination so that the SRLP will make another _**Request**_ to it's upstream 'repeat()'; this time, the _**Request**_ obtains the healthy Link, Link2, that 'MonoFlatmap' cached in step 16.

2. Should we clean this up? _**YES**_, because, as we can see, the SRLP has to do unnecessary work when the cached closed link is received; there are subscriptions made to the cached closed link on the BoundedElastic pool only to listen to error replay from the closed link endpoint. (allocations, CPU cycles, unnecessary loggings that's not useful)

3. How to do the cleanup? The easiest way is to apply a filter after 'repeat()' to filter out cached closed links. 

4. The same async-chain pattern is used for AmqpReceiveLinkProcessor; hence the described flow is also applicable for Event Hubs.

### CODE REVIEW

File: sdk/servicebus/azure-messaging-servicebus/src/main/java/com/azure/messaging/servicebus/ServiceBusReceiverAsyncClient.java [hunk 1]
```diff
@@ -1542,7 +1542,13 @@ private ServiceBusAsyncConsumer getOrCreateConsumer() {
         // It also requests a new link (i.e. retry) when the current link it holds gets terminated
         // (e.g., when the service decides to close that link).
         //
-        final Flux<ServiceBusReceiveLink> receiveLinkFlux = retryableReceiveLinkMono.repeat();
+        final Flux<ServiceBusReceiveLink> receiveLinkFlux = retryableReceiveLinkMono
+            .repeat()
+            // The repeat() operator will prefetch and cache the existing link as it subscribes to the flatmap().
+            // When the link is doing recover, the repeat() operator may emit the closed link to its downstream
+            // 'ServiceBusReceiveLinkProcessor', resulting in unnecessary work and logging. Thus, we filter out
+            // the closed links before passing them to downstream.
```
Comment (anuchandy) [inline sdk/servicebus/azure-messaging-servicebus/src/main/java/com/azure/messaging/servicebus/ServiceBusReceiverAsyncClient.java:1550]: It should be Ok to use the actual operator type name when documenting their internal behavior, as these are for dev references. Something like -

_The re-subscribe nature of 'MonoRepeat' following the emission of a link will cause the 'MonoFlatmap' (the upstream of repeat operator) to cache the same link. When AmqpReceiveLinkProcessor later requests a new link, the corresponding request from the 'MonoRepeat' will be answered with the cached (and closed) link by the 'MonoFlatmap'. We'll filter out these cached (closed) links to avoid AmqpReceiveLinkProcessor from doing unusable work (creating subscriptions and attempting to place the credit) on those links and associated logging. See the PR description "https://github.com/Azure/azure-sdk-for-java/pull/33204" for more details_.

Comment (anuchandy) [reply sdk/servicebus/azure-messaging-servicebus/src/main/java/com/azure/messaging/servicebus/ServiceBusReceiverAsyncClient.java:1550]: My understanding is - Per reactive spec, flowing _null_ values in a reactor chain is prohibited, so we don't have to check for null values.

Comment (liukun-msft) [reply sdk/servicebus/azure-messaging-servicebus/src/main/java/com/azure/messaging/servicebus/ServiceBusReceiverAsyncClient.java]: I added it because I saw AmqpReceiveLinkProcessor have that null check. But you are right, I'll remove the null check and update the documentation.

**Review by anuchandy — APPROVED** [review]
Thanks Kun!

**Review by ZejiaJiang — APPROVED** [review]
Thanks Kun! Thank you for your doc and code. I run the code that really helps me to understand how repeat works.
