### PR TITLE
Tracing docs fixes

### LINKED ISSUE #39294: Incorrect return type for getTracingOptions() documented
### Type of issue

Typo

### Description

[Enter feedback here]
The return type of `com.azure.core.util.ClientOptions.getTracingOptions()` documents that the return type is `com.azure.core.util.MetricOptions` whilst it should be `com.azure.core.util.TracingOptions`. 

This typo is present all over the document like in the `Method Summary` section also.

### Page URL

https://learn.microsoft.com/en-us/java/api/com.azure.core.util.clientoptions?view=azure-java-stable

### Content source URL

https://github.com/Azure/azure-docs-sdk-java/blob/master/docs-ref-autogen/com.azure.core.util.ClientOptions.yml

### Document Version Independent Id

ff4c8bde-1f8b-5adf-e3a5-8920caeed34e

### Article author

@rloutlaw

### Metadata

* ID: e83a12a1-549a-a64f-58dd-83459d4df0cf 
* Service: **azure**

### PR DESCRIPTION
**Pull request by lmolkova**
Fixes #39294 and #38905

### CODE REVIEW

**Review by alzimmermsft — APPROVED** [review]

File: sdk/core/azure-core/src/main/java/com/azure/core/util/MetricsOptions.java [hunk 1]
```diff
@@ -59,9 +59,8 @@ private MetricsOptions(Configuration configuration) {
     /**
      * Attempts to load metrics options from the configuration.
      * <p>
```
Comment (alzimmermsft) [inline sdk/core/azure-core/src/main/java/com/azure/core/util/MetricsOptions.java:61]: Empty <p> tag
