### PR TITLE
Fix spotbugs in identity tests and samples.

### LINKED ISSUE #13689: Enable Spotbugs check on Azure-Identity SDK Samples and test code files
Tracking issue for just the Azure.Identity portion of https://github.com/Azure/azure-sdk-for-java/issues/9360

> Spotbugs check does not run on Track 2 Samples and Test code files currently.
> Enable it in sdk/parents/azure-client-sdk-parent/pom.xml,  set this flag to true. : [ClickHere](https://github.com/Azure/azure-sdk-for-java/blob/bb07d3cdf421bfb821b974c16ffaa797b4473770/sdk/parents/azure-client-sdk-parent/pom.xml#L197) 
> Fix the spotgubs issues in all the track 2 SDKs samples and test code files.
>

### PR DESCRIPTION
**Pull request by g2vinay**
Fixes #13689

### CODE REVIEW

File: sdk/identity/azure-identity/src/test/java/com/azure/identity/implementation/IdentityClientTests.java [hunk 1]
```diff
@@ -454,7 +455,7 @@ private void mockForMSICodeFlow(String tokenJson) throws Exception {
         PowerMockito.doNothing().when(huc).setRequestMethod(anyString());
         PowerMockito.doNothing().when(huc).setRequestMethod(anyString());
         PowerMockito.doNothing().when(huc).setRequestMethod(anyString());
-        InputStream inputStream = new ByteArrayInputStream(tokenJson.getBytes());
+        InputStream inputStream = new ByteArrayInputStream(tokenJson.getBytes(Charset.defaultCharset()));
```
Comment (alzimmermsft) [inline sdk/identity/azure-identity/src/test/java/com/azure/identity/implementation/IdentityClientTests.java:458]: Are tokens guaranteed to be ASCII only? If not it may be better to use `StandardCharset.UTF_8` here as the `defaultCharset` is specific to the machine. Linux and Mac will default `UTF-8` while Windows defaults `CP1252`.

Comment (g2vinay) [reply sdk/identity/azure-identity/src/test/java/com/azure/identity/implementation/IdentityClientTests.java:458]: yeah, ASCII covers tokens char range.
This is test code. So, if any failures are ever encountered, it'd interesting to look at and we can fix it.
