### PR TITLE
fix: [SparkConnector] Skip readContainerThroughput when targetThroughput is configured

### LINKED ISSUE #48799: [BUG][SparkConnector]Avoid unnecessary readContainerThroughput if targetThroughput is being used
In spark connector, when customer using AAD + targetThroughput for throughout control, within spark connector we always create a. throughputQueryMono:

```
    private def getThroughputQueryMono(
                                          userConfig: Map[String, String],
                                          cacheItem: CosmosClientCacheItem,
                                          cosmosContainerConfig: CosmosContainerConfig): Option[SMono[Integer]] = {
        val cosmosAuthConfig = CosmosAccountConfig.parseCosmosAccountConfig(userConfig).authConfig
        cosmosAuthConfig match {
            case _: CosmosMasterKeyAuthConfig => None
            case _: CosmosServicePrincipalAuthConfig =>
                Some(cacheItem.sparkCatalogClient.readContainerThroughput(cosmosContainerConfig.database, cosmosContainerConfig.container))
            case _: CosmosManagedIdentityAuthConfig =>
              Some(cacheItem.sparkCatalogClient.readContainerThroughput(cosmosContainerConfig.database, cosmosContainerConfig.container))
            case _: CosmosAccessTokenAuthConfig =>
              Some(cacheItem.sparkCatalogClient.readContainerThroughput(cosmosContainerConfig.database, cosmosContainerConfig.container))
        }
    }
```
which will require customer to always add Microsoft.DocumentDB/databaseAccounts/sqlDatabases/containers/throughputSettings/read permission. Else the application may hang. 

Change to return None if targetThroughput is used.

### PR DESCRIPTION
**Pull request by xinlian12**
## Fix

When using AAD auth with `targetThroughput` (absolute value, not `targetThroughputThreshold`) for throughput control, the SDK's `SDKThroughputContainerController.resolveContainerMaxThroughput()` was always subscribing to the `throughputQueryMono`. This triggers a `readContainerThroughput` call requiring the `Microsoft.DocumentDB/databaseAccounts/sqlDatabases/containers/throughputSettings/read` permission — which AAD principals may not have, causing the application to hang.

### Root Cause

The container's max throughput is only needed when `targetThroughputThreshold` is configured (to compute `maxThroughput × threshold`). When only `targetThroughput` is used, `getThroughputResolveLevel()` correctly returns `NONE`. However, `resolveContainerMaxThroughput()` was missing the scope check and always subscribing to the query mono.

The `refreshContainerMaxThroughputTask()` already had this guard — the init path was the gap.

### Fix

Added a `throughputProvisioningScope == NONE` guard in `resolveContainerMaxThroughput()` to skip the query when it's not needed. This is at the SDK layer (`SDKThroughputContainerController`) so all consumers benefit, not just the Spark connector.

### Changes
- `SDKThroughputContainerController.java`: Added scope check in `resolveContainerMaxThroughput()`
- `azure-cosmos/CHANGELOG.md`: Added bug fix entry

Fixes #48799

### Tests:
Run notebook in Databricks to verify that with main, using target throughput + AAD application will fail, after the fix, application be able to start and complete

### CODE REVIEW

**Review by FabianMeiswinkel — APPROVED** [review]
LGTM

File: sdk/cosmos/azure-cosmos-spark_3/src/main/scala/com/azure/cosmos/spark/ThroughputControlHelper.scala [hunk 1]
```diff
@@ -268,7 +268,15 @@ private object ThroughputControlHelper extends BasicLoggingTrait {
...
                                           userConfig: Map[String, String],
                                           cacheItem: CosmosClientCacheItem,
-                                          cosmosContainerConfig: CosmosContainerConfig): Option[SMono[Integer]] = {
+                                          cosmosContainerConfig: CosmosContainerConfig,
+                                          throughputControlConfig: CosmosSDKThroughputControlConfig): Option[SMono[Integer]] = {
+        // When targetThroughput is explicitly configured, skip the container throughput query.
+        // The query requires Microsoft.DocumentDB/databaseAccounts/sqlDatabases/containers/throughputSettings/read
+        // permission which AAD principals may not have, and it is unnecessary when the target is already known.
+        if (throughputControlConfig.targetThroughput.isDefined) {
+            return None
```
[the remark this answers is not in the document]
Comment (xinlian12) [reply sdk/cosmos/azure-cosmos-spark_3/src/main/scala/com/azure/cosmos/spark/ThroughputControlHelper.scala]: will done through e2e tests

File: sdk/cosmos/azure-cosmos-tests/src/test/java/com/azure/cosmos/implementation/throughputControl/sdk/controller/SDKThroughputContainerControllerTests.java [hunk 2]
```diff
@@ -0,0 +1,126 @@
...
+import java.util.UUID;
+import java.util.concurrent.atomic.AtomicBoolean;
+
+import static org.assertj.core.api.AssertionsForClassTypes.assertThat;
+
+public class SDKThroughputContainerControllerTests {
+
+    /**
+     * Validates that when only targetThroughput is configured (no targetThroughputThreshold),
+     * the throughputQueryMono is NOT subscribed during resolveContainerMaxThroughput.
```
Comment (xinlian12) [inline sdk/cosmos/azure-cosmos-tests/src/test/java/com/azure/cosmos/implementation/throughputControl/sdk/controller/SDKThroughputContainerControllerTests.java]: remove this comment

**Comment by xinlian12** [comment]
@sdkReviewAgent-2

File: sdk/cosmos/azure-cosmos-tests/src/test/java/com/azure/cosmos/implementation/throughputControl/sdk/controller/SDKThroughputContainerControllerTests.java [hunk 3]
```diff
@@ -0,0 +1,126 @@
...
+        SDKThroughputContainerController controller = new SDKThroughputContainerController(
+            collectionCacheMock,
+            ConnectionMode.DIRECT,
+            groups,
+            pkRangeCacheMock,
+            null,
+            trackingThroughputQueryMono);
+
+        // The constructor should NOT have subscribed to the throughput query mono
+        assertThat(throughputQuerySubscribed.get())
```
Comment (xinlian12) [inline sdk/cosmos/azure-cosmos-tests/src/test/java/com/azure/cosmos/implementation/throughputControl/sdk/controller/SDKThroughputContainerControllerTests.java:84]: 🟡 **Recommendation — Test Coverage: Test does not exercise the fix**

This test asserts the constructor doesn't subscribe to `throughputQueryMono`, but the constructor **never subscribed** — even before this PR. Line 109 of `SDKThroughputContainerController.java` is a lazy Mono assignment:

```java
this.throughputQueryMono = throughputQueryMono == null ? this.resolveContainerMaxThroughputCore() : throughputQueryMono;

```

The actual fix is the new guard in `resolveContainerMaxThroughput()`, which is called from `init()` (line 126). Since this test never calls `init()`, it would pass identically on the **pre-fix** codebase. You can verify by reverting the production guard and re-running — the test still passes.

**To properly regression-guard the fix**, the test should call `controller.init()` and verify `throughputQuerySubscribed` remains `false`. This requires additional mocking:
- `containerMock.read()` → return a mock `CosmosContainerResponse` (for `resolveContainerResourceId()`)
- Or use `Mockito.spy()` on the controller and stub `resolveContainerResourceId()` to return `Mono.just(controller)`

Without this, the fix has no unit-level regression protection — if someone removes the guard, no test fails.

Similarly, the second test (`throughputQueryMonoWiredWhenThresholdConfigured`, line 124) only asserts `controller != null`, which is trivially true after any constructor call. Consider strengthening it to verify that `init()` **does** subscribe when threshold is configured, creating a proper positive/negative test pair.

⚠️ AI-generated review — may be incorrect. Agree? → resolve the conversation. Disagree? → reply with your reasoning.

**Comment by xinlian12** [comment]
✅ **Review complete** (25:58)

Posted **1** inline comment(s).

<sub>Steps: ✓ context, correctness, cross-sdk, design, history, past-prs, synthesis, test-coverage</sub>

File: sdk/cosmos/azure-cosmos-tests/src/test/java/com/azure/cosmos/implementation/throughputControl/sdk/controller/SDKThroughputContainerControllerTests.java (hunk 3 above)
Comment (xinlian12) [reply sdk/cosmos/azure-cosmos-tests/src/test/java/com/azure/cosmos/implementation/throughputControl/sdk/controller/SDKThroughputContainerControllerTests.java:84]: updated the test to do proper tests

**Comment by xinlian12** [comment]
@sdkReviewAgent

**Comment by xinlian12** [comment]
✅ **Review complete** (34:11)

No new comments — existing review coverage is sufficient.

<sub>Steps: ✓ context, correctness, cross-sdk, design, history, past-prs, synthesis, test-coverage</sub>

**Review by FabianMeiswinkel — APPROVED** [review]
LGTM
