### PR TITLE
Fix numeric handling bug in JsonReader.readUntyped

### LINKED ISSUE #44391: [BUG] SearchClient fails to deserialize facet values in scientific notation format
**Describe the bug**
The Azure Search SDK fails to deserialize search results when facet values contain numbers in scientific notation format (e.g., "1E-05"). During deserialization, the JsonReader attempts to parse these scientific notation values as Long instead of Double, resulting in a NumberFormatException.

***Exception or Stack Trace***
Caused by: java.lang.NumberFormatException: For input string: "1E-05"
    at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
    at java.base/java.lang.Long.parseLong(Long.java:709)
    at java.base/java.lang.Long.parseLong(Long.java:832)
    at com.azure.json.JsonReader.readUntypedHelper(JsonReader.java:623)
    at com.azure.json.JsonReader.readUntyped(JsonReader.java:591)
    at com.azure.search.documents.implementation.models.SearchResult.lambda$fromJson$3(SearchResult.java:190)
    at com.azure.json.JsonReader.readMapOrObject(JsonReader.java:551)
    at com.azure.json.JsonReader.readObject(JsonReader.java:455)
    at com.azure.search.documents.implementation.models.SearchResult.fromJson(SearchResult.java:162)
    at com.azure.search.documents.implementation.models.SearchDocumentsResult.lambda$fromJson$0(SearchDocumentsResult.java:250)
    at com.azure.json.JsonReader.readArray(JsonReader.java:494)
    at com.azure.search.documents.implementation.models.SearchDocumentsResult.lambda$fromJson$4(SearchDocumentsResult.java:250)
    at com.azure.json.JsonReader.readMapOrObject(JsonReader.java:551)
    at com.azure.json.JsonReader.readObject(JsonReader.java:455)
    at com.azure.search.documents.implementation.models.SearchDocumentsResult.fromJson(SearchDocumentsResult.java:232)
    at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:733)
    at com.azure.core.implementation.MethodHandleReflectiveInvoker.invokeStatic(MethodHandleReflectiveInvoker.java:26)
    at com.azure.core.implementation.ReflectionSerializable.deserializeAsJsonSerializable(ReflectionSerializable.java:159)

**To Reproduce**
- Create an Azure Cognitive Search index with a field containing very small double value (e.g., 0.00001)
- Make the field facetable
- Perform a search that includes facets for this field
- Attempt to access the facet results

***Code Snippet***
```java
SearchClient searchClient = new SearchClientBuilder()
    .endpoint(endpoint)
    .credential(new AzureKeyCredential(apiKey))
    .indexName(index)
    .serviceVersion(SearchServiceVersion.V2024_07_01)
    .buildClient();

// Building search options with facets
SearchOptions options = new SearchOptions();
options.setFacets("fieldWithSmallValues");

// Performing the search
SearchPagedIterable results = searchClient.search("*", options, Context.NONE);

// This line triggers the exception when a facet contains scientific notation values
Map<String, List<FacetResult>> facets = results.getFacets();
```

**Expected behavior**
The SDK should properly handle numeric values in scientific notation during deserialization by either:

Parsing them as Double/BigDecimal instead of Long when scientific notation is detected
Preserving the original string representation to allow client-side parsing
Providing a configuration option to specify how numeric facet values should be deserialized

**Screenshots**

**Setup (please complete the following information):**
OS: Windows 10
IDE: IntelliJ IDEA
Library/Libraries: com.azure:azure-search-documents:11.6.0 also tried the new betas
Java version: 21
App Server/Environment: Spring Boot application
Frameworks: Spring Boot 3.4.2 

If you suspect a dependency version mismatch (e.g. you see `NoClassDefFoundError`, `NoSuchMethodError` or similar), please check out [Troubleshoot dependency version conflict article](https://aka.ms/azsdk/java/dependency/troubleshoot) first. If it doesn't provide solution for the problem, please provide:
- verbose dependency tree (`mvn dependency:tree -Dverbose`)
- exception message, full stack trace, and any available logs

**Additional context**
The issue specifically occurs when dealing with facet values containing very small decimal values that Azure Cognitive Search returns in scientific notation format (e.g., 1E-05 instead of 0.00001). These values are correctly handled in normal document results but fail during facet deserialization.
The root cause appears to be in the JsonReader.readUntypedHelper method that tries to parse these values as Long instead of detecting and handling scientific notation patterns properly.

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

### PR DESCRIPTION
**Pull request by alzimmermsft**
# Description

Fixes #44391

This PR fixes a bug in `JsonReader.readUntyped()` where incomplete numeric handling was being performed. Exponent numbers weren't being handled correctly.

In addition to the numeric handling, there are a few other changes:

- `JsonReader.readUntyped()` and `JsonNumber` are unifying their behavior to match what `JsonNumber` was doing. In all parsing cases the smallest numeric type will be used (int before long before BigInteger, float before double before BigDecimal), except in the case of special numerics (`NaN`, `Infinity`, `+Infinity`, and `-Infinity`) where double is always used.
- Support for `INF`, `-INF`, and `+INF` was removed as this wasn't consistent with what Java supported in `Float` and `Double` (only `Infinity` variants are supported).
- `azure-json-gson` and `azure-json-reflect` were removed as they never shipped GA nor will ever be shipped GA.

# All SDK Contribution checklist:
- [x] **The pull request does not introduce [breaking changes]**
- [x] **CHANGELOG is updated for new features, bug fixes or other significant changes.**
- [x] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md).**

## [General Guidelines and Best Practices](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md#developer-guide)
- [x] Title of the pull request is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md#building-and-unit-testing)
- [x] Pull request includes test coverage for the included changes.

### CODE REVIEW

**Review by anuchandy — APPROVED** [review]

File: sdk/clientcore/core/src/main/java/io/clientcore/core/serialization/json/implementation/JsonUtils.java [hunk 1]
```diff
@@ -0,0 +1,92 @@
...
+        return floatingPoint ? handleFloatingPoint(numberString) : handleInteger(numberString);
+    }
+
+    private static Number handleFloatingPoint(String value) {
+        // Floating point parsing will return Infinity if the String value is larger than what can be contained by
+        // the numeric type. Check if the String contains the Infinity representation to know when to scale up the
+        // numeric type.
+        // Additionally, due to the handling of values that can't fit into the numeric type, the only time floating
+        // point parsing will throw is when the string value is invalid.
+        double d = Double.parseDouble(value);
```
Comment (srnagar) [inline sdk/clientcore/core/src/main/java/io/clientcore/core/serialization/json/implementation/JsonUtils.java:67]: Do we have to first check if it can be `float` before going to `double`?

**Review by jairmyree — APPROVED** [review]

**Review by srnagar — APPROVED** [review]

File: sdk/clientcore/core/src/main/java/io/clientcore/core/serialization/json/implementation/JsonUtils.java (hunk 1 above)
Comment (alzimmermsft) [reply sdk/clientcore/core/src/main/java/io/clientcore/core/serialization/json/implementation/JsonUtils.java:67]: Per our offline discussion we had a slight miscommunication here.

This utility method is only used when we're performing unknown numeric parsing (`JsonReader.readUntyped`, `JsonNumber.fromJson`). This change is aligning with default behaviors in all of Gson, Jackson, and Java where unknown decimal point processing is `double` by default.

`float` operations are still supported with `JsonReader.getFloat()` or using `float` as a value for `JsonNumber` or in general JSON serializable objects.

**Comment by joshfree** [comment]
Thahks for the quick turnaround here, @alzimmermsft
