### PR TITLE
Fix session token capturing behavior when Account default is Session

### LINKED ISSUE #33797: [BUG] CosmosClient does not pass Session Token from Writes to Reads
**Describe the bug**
Creating a CosmosClient/CosmosAsyncClient instance has the **optional** Consistency parameter. By default, according to documentation, the account consistency would be used.

When an Account that is Session Consistency creates a client **without defining the Consistency** configuration, the `SessionContainer` is being initialized disabled:

https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/RxDocumentClientImpl.java#L421-L423

```
boolean disableSessionCapturing = (ConsistencyLevel.SESSION != consistencyLevel && !sessionCapturingOverrideEnabled);

this.sessionContainer = new SessionContainer(this.serviceEndpoint.getHost(), disableSessionCapturing);
```

`consistencyLevel` is `null` because none is specified on the configuration, which makes `disableSessionCapturing` to `true`, and inside `SessionContainer` we don't save any tokens:

https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/SessionContainer.java#L183-L186

The `SessionContainer` is being initialized before the account information is read.

**To Reproduce**

1. Create a Session account
2. Create a CosmosAsyncClient without setting Consistency configuration
3. Perform a Write operation, capture the Diagnostics
4. Perform a Read operation, capture the Diagnostics

The `requestSessionToken` on step 4 is `null`.

***Code Snippet***

```
CosmosAsyncClient client = new CosmosClientBuilder()
	.endpoint(""endpoint")
	.key("key")
	.directMode()
	.buildAsyncClient();

CosmosAsyncContainer container = client.getDatabase("items").getContainer("items");

String theId = "7";
MyPoco poco = new MyPoco();
poco.setId(theId);

container.upsertItem(conflictObject).doOnSuccess(itemResponse -> {
	logger.info(itemResponse.getDiagnostics().toString());

	container.readItem(theId, new PartitionKey(theId), MyPoco.class).doOnSuccess(
			readResponse -> {
				logger.info(readResponse.getDiagnostics().toString());
			}).block();
}).block();
```

**Expected behavior**
The Session Token from the Write operation should be sent on the Read operation.

**Setup (please complete the following information):**
 - OS: Windows
 - IDE: IntelliJ
 - Library/Libraries: com.azure:azure-cosmos:4.42.0
 - Java version: 11
 - App Server/Environment: Any
 - Frameworks: None
 
**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

### PR DESCRIPTION
**Pull request by FabianMeiswinkel**
This fixes #33797

# Description
Fixes #33797 - when `CosmosClinetBuilder.consistencyLevel` is not specified, currently for accounts with default consistency level `SESSION` no session tokens are captured (effectively use eventual consistency). The expected behavior would be to honor the account default consistency (SESSION) and capture session tokens.

# All SDK Contribution checklist:
- [] **The pull request does not introduce [breaking changes]**
- [x] **CHANGELOG is updated for new features, bug fixes or other significant changes.**
- [x] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md).**

## [General Guidelines and Best Practices](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md#developer-guide)
- [x] Title of the pull request is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md#building-and-unit-testing)
- [x] Pull request includes test coverage for the included changes.

### CODE REVIEW

File: sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/RxDocumentClientImpl.java [hunk 1]
```diff
@@ -611,6 +613,12 @@ public void init(CosmosClientMetadataCachesSnapshot metadataCachesSnapshot, Func
                 this.initializeDirectConnectivity();
             }
             this.retryPolicy.setRxCollectionCache(this.collectionCache);
+            ConsistencyLevel effectiveConsistencyLevel = consistencyLevel != null
```
Comment (jeet1995) [inline sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/RxDocumentClientImpl.java:616]: So, session token capturing in `SessionContainer` is falling back to client-side settings. Wouldn't this lead to session token being captured in case of account-level consistencies weaker than Session consistency? I assume customers doing account-level changes (changing consistency from Eventual to Session) is less prevalent than client-level changes.

**Review by jeet1995 — APPROVED** [review]
LGTM - thanks!

File: sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/RxDocumentClientImpl.java (hunk 1 above)
Comment (FabianMeiswinkel) [reply sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/RxDocumentClientImpl.java:616]: Capturing session tokens in that case is fine. Whether Session consistency is used depends on two things - effective consistency level for a request and whether session token is present (customer provided or in the session token container). Setting client level consistency to Session and account level consistency being eventual was possible before a swell.

Comment (FabianMeiswinkel) [reply sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/RxDocumentClientImpl.java:616]: In general Cient-setting overrides account default
RequestOptions override client-setting

Comment (FabianMeiswinkel) [reply sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/RxDocumentClientImpl.java:616]: Downgrades (requested consistency less than account default is only applicable for reads/queries)

Comment (FabianMeiswinkel) [reply sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/RxDocumentClientImpl.java:616]: Upgrades should always be ignored

**Review by kushagraThapar — APPROVED** [review]

File: sdk/cosmos/azure-cosmos/CHANGELOG.md [hunk 2]
```diff
@@ -9,9 +9,11 @@
...
+* Fixed an issue where Session consistency was not honored when the consistency level on the `CosmosClientBuilder.consistencyLevel` was not explicitly set to `ConsistencyLevel.SESSION` but the default account consistency level is session. If not enforcing session consistency is the intended behavior, you can set the `CosmsoClientBuilder.consistencyLevel` to `ConsistencyLevel.EVENTUAL`. - See [PR 37377](https://github.com/Azure/azure-sdk-for-java/pull/37377)
 
 #### Other Changes
+* Modified the event payload when diagnostic details are traced (vis Open telemetry traces). The diagnostics can exceed the max. attribute size of 8KB. This PR will split the diagnostics and trace them in multiple events (ordered by `SequenceNumber` attribute) to ensure the full diagnostics message is available in logged events. - See [PR 37376](https://github.com/Azure/azure-sdk-for-java/pull/37376)
+* Fixed an issue where client level `EndToEndOperationLatencyPolicyConfig` is not being applied for `query` - See [PR 37511](https://github.com/Azure/azure-sdk-for-java/pull/37511)
```
Comment (xinlian12) [inline sdk/cosmos/azure-cosmos/CHANGELOG.md:16]: why this moves to other changes section
