### PR TITLE
Cosmos Spark: Fixes inference for nested empty arrays

### LINKED ISSUE #26503: Spark 3.* Cosmos DB connector schema inference issue for nested arrays
For the past few days I've been trying to use the _azure-cosmos-spark_3-1_2-12_ connector (version 4.5.3), using different schema inference configuration options but it's not working as expected.

Tested on Databricks Runtime Version 8.4 and 9.1 LTS.

**Full Collection**
Code used to bring over the entire collection (~820 documents):
``` python
readConfig = {
  "spark.cosmos.accountEndpoint": CosmosDBEndpoint,
  "spark.cosmos.accountKey": CosmosDBMasterKey,
  "spark.cosmos.database": CosmosDBDatabase,
  "spark.cosmos.container": CosmosDBCollection,
  "spark.cosmos.read.inferSchema.includeSystemProperties": "true"
}

# Connect via azure-cosmosdb-spark to create Spark DataFrame
dfCosmosDB = (spark.read
		   .format("cosmos.oltp")
		   .options(**readConfig)
		   .load())

dfCosmosDB.printSchema()
```

The following is part of the resulting schema that matters to this discussion. For ~100 of those documents, the `Actions.Condition` is filled in with data, but the connector infers it as `NullType` and forces every result to null:
FullCollection_Schema

**Infer Schema Query**
Used the `inferSchema.query` option to force the connector to only use documents that have the `Actions.Condition` filled in (including filtering by a specific id), but it didn't change the result:
``` python
"spark.cosmos.read.inferSchema.query": f"SELECT f FROM f JOIN a IN f.Actions JOIN c IN a.Condition"
```
InferSchemaQuery_Schema

**Custom Query**
Tried as well to use the `customQuery` to fetch only documents that have the `Actions.Condition` populated, but no change in the resulting schema:
``` python
"spark.cosmos.read.customQuery": f"SELECT f FROM f JOIN a IN f.Actions JOIN c IN a.Condition"
```
CustomQuery_f_Schema

If you look at the query used above, it's fetching data from the root `f`, but if it's changed to one of the nested arrays, e.g. `a`, the schema will be inferred correctly:
``` python
"spark.cosmos.read.customQuery": f"SELECT a FROM f JOIN a IN f.Actions JOIN c IN a.Condition"
```
CustomQuery_a_Schema

This change in behavior occurs both on `customQuery` and `inferSchema.query` options.
Important to note that for all documents that have `Actions.Condition` populated, also have empty/null `Actions.Filter`, which is why it's showing as `NullType` (correctly) in the last schema. This also makes me wonder why in the previous query it was showing a structure, as if it was using documents outside of the scope of the query to infer the schema.

### PR DESCRIPTION
**Pull request by ealsur**
When using inference, for attributes that were arrays, we were only looking at the first element of the array to infer the type.

We are now checking all elements and making sure we aggregate the properties of each element in case we have elements with different schema.

In scenarios like:

```json
{ "Actions": 
      [{ "Condition": [] },
      { "Condition": [{ "BodyPath": "{{ step1.StatusCode }}",
						"Value": "400" }] },
      { "Condition": [{ "BodyPath": "{{ step1.StatusCode }}",
						"Operation": 2,
						"Value": "400" }] }]}
```

The schema will contain a `Condition` field which is an `ArrayType[StructType]` where the detected `StructType` contains 3 fields: `BodyPath` as a string, `Operation` as an interger (because at least 1 array item has it), and `Value` as a string.

Closes #26503

### CODE REVIEW

File: sdk/cosmos/azure-cosmos-spark_3_2-12/src/main/scala/com/azure/cosmos/spark/CosmosTableSchemaInferrer.scala [hunk 1]
```diff
@@ -211,7 +211,16 @@ private object CosmosTableSchemaInferrer
 
   // scalastyle:on
   private def inferDataTypeFromArrayNode(node: ArrayNode, allowNullForInferredProperties: Boolean): Option[DataType] = {
-    Option(node.get(0)).map(firstElement => inferDataTypeFromJsonNode(firstElement, allowNullForInferredProperties))
+    val notNullElements = node.elements.asScala
+      .filter(element  => !element.isNull)
```
Comment (FabianMeiswinkel) [inline sdk/cosmos/azure-cosmos-spark_3_2-12/src/main/scala/com/azure/cosmos/spark/CosmosTableSchemaInferrer.scala:215]: NIT: my preference would be to have LF before each .
like 
node
  .elements
  .asScala
  .filter(xxx)

**Review by FabianMeiswinkel — APPROVED** [review]
Thanks!
