### PR TITLE
Identity Managed Identity & VsCode Credential + Docs Updates

### LINKED ISSUE #14720: Add IDENTITY ENDPOINT and HEADER environment variables to Configuration in Core.
Add the "IDENTITY_ENDPOINT" and "IDENTITY_HEADER" environment variables to the Configuration class in Core.

### LINKED ISSUE #15373: [BUG] Update DAC docs to include new types
These:
https://docs.microsoft.com/en-us/java/api/com.azure.identity.defaultazurecredential?view=azure-java-stable
https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/identity/azure-identity/src/main/java/com/azure/identity/DefaultAzureCredential.java

Do not have all cred types that DAC will try.

@g2vinay

### LINKED ISSUE #16195: [BUG] VsCode Credential not reading correct values from the access token cache.
**Describe the bug**
VsCode credential is reading in the token value of 'Azure' account from the VSCode iDE cache. This value is never purged, so cannot be relied upon. This results in following issues:
1. VSCode credential reads token even if no user logged in the IDE.
2. VSCode credential reads in expired tokens, if the user hasn't logged in the VSCode IDE in weeks/months.
3. Azure CLI can never be reached in DAC flow.

Screen Shot 2020-10-08 at 10 27 55 AM

**To Reproduce**
1. Login to VS Code IDE against public cloud.
2. Logout of VSCode IDE.
3. VsCode credential will continue to work.
4. Let the token expire.
5. VsCode credential will read expired token and break the DAC flow.
6. Azure CLI is never reached in DAC credential.

**Expected behavior**
VSCode credential should throw Credential Unavailable Exception when no user logged into VS code IDE.

**How to Fix**
1. Update Identity SDK  VSCode Cred public cloud env mapping to AzureCloud from Azure.
2. Use AzureCloud as default env instead of Azure in the Identity SDK code for VSCode credential.

### PR DESCRIPTION
**Pull request by g2vinay**
Fixes #14720
Adds MI credential new Env Vars to Configuration class in azure-core

Fixes #15373
Fixes DAC docs to include new credentials in the internal chain of creds.

Fixes #16195
Fixes the Bug to read from AzureCloud VSCode cache account instead of Azure.

### CODE REVIEW

**Review by jianghaolu — APPROVED** [review]

File: sdk/core/azure-core/src/main/java/com/azure/core/util/Configuration.java [hunk 1]
```diff
@@ -23,6 +23,16 @@
      */
     public static final String PROPERTY_HTTPS_PROXY = "HTTPS_PROXY";
 
+    /**
+     * Endpoint to connect to when using Azure Active Directory managed service identity (MSI).
+     */
+    public static final String PROPERTY_IDENTITY_ENDPOINT = "IDENTITY_ENDPOINT";
```
Comment (srnagar) [inline sdk/core/azure-core/src/main/java/com/azure/core/util/Configuration.java:29]: If this is specific to AAD, can this constant be declared in azure-identity where we have everything related to AAD?

File: sdk/identity/azure-identity/src/main/java/com/azure/identity/ManagedIdentityCredential.java [hunk 2]
```diff
@@ -24,9 +24,6 @@
     private final VirtualMachineMsiCredential virtualMachineMSICredential;
     private final ClientLogger logger = new ClientLogger(ManagedIdentityCredential.class);
 
-    // TODO: Migrate to Configuration class in Core (https://github.com/Azure/azure-sdk-for-java/issues/14720)
-    static final String PROPERTY_IDENTITY_ENDPOINT = "IDENTITY_ENDPOINT";
-    static final String PROPERTY_IDENTITY_HEADER = "IDENTITY_HEADER";
```
Comment (srnagar) [inline sdk/identity/azure-identity/src/main/java/com/azure/identity/ManagedIdentityCredential.java:29]: Interesting, so this was in azure-identity earlier. What's the reason for moving this to azure-core? I guess these two are needed only when we use the azure-identity library.

**Review by srnagar — APPROVED** [review]
Looks good! Just curious about why we want the identity constants in core.

**Review by schaabs — APPROVED** [review]
