### PR TITLE
ACR minor fixes

### LINKED ISSUE #32571: Enable ACR tests disabled due to service regression
Enable ACR tests disabled due to service regression and remove skipping jacoco testing coverage

### PR DESCRIPTION
**Pull request by lmolkova**
Fixes #32571, #32451, #28210

### CODE REVIEW

File: sdk/containerregistry/azure-containers-containerregistry/src/main/java/com/azure/containers/containerregistry/models/ContainerRegistryAudience.java [hunk 1]
```diff
@@ -13,7 +13,11 @@ public final class ContainerRegistryAudience extends ExpandableStringEnum<Contai
     /** Static value AZURE_RESOURCE_MANAGER_CHINA for ContainerRegistryAudience. */
     public static final ContainerRegistryAudience AZURE_RESOURCE_MANAGER_CHINA = fromString("https://management.chinacloudapi.cn");
 
-    /** Static value AZURE_RESOURCE_MANAGER_GERMANY for ContainerRegistryAudience. */
+    /**
+     * Static value AZURE_RESOURCE_MANAGER_GERMANY for ContainerRegistryAudience.
+     * @deprecated Germany government cloud is no longer supported.
+     */
+    @Deprecated
```
Comment (samvaity) [inline sdk/containerregistry/azure-containers-containerregistry/src/main/java/com/azure/containers/containerregistry/models/ContainerRegistryAudience.java:20]: Should we add this to breaking changes changelog?

**Review by samvaity — APPROVED** [review]
Lgtm!
