### PR TITLE
Fixes issues in auto-* operations

### LINKED ISSUE #9785: [SB Track2] Fix implementation of maxAutoRenewDuration
maxAutoRenewDuration is implemented incorrectly.

### LINKED ISSUE #9795: Service Bus Track 2  API Change - ReceiveAsyncOptions for AsyncReceiverClient
remove these from ServiceBusReceiverClientBuilder

Add as part of AsyncReceiverClient
ReceiveAsyncOptions
maxAutoLockRenewalDuration(Duration renewDuration) 
enableAutoComplete(boolean autoComplete)

### PR DESCRIPTION
**Pull request by conniey**
* Removes `isAutoComplete`, `isAutoLockRenew`, and maxAutoLockRenewDuration into ReceiveAsyncOptions
* Adds overload for receive(ReceiveAsyncOptions)
* Fixes logic in maxAutoLockRenewDuration.
* Changes all UUID to Strings except for ManagementChannel to save multiple conversion operations.

Fixes #9795 
Fixes #9785

### CODE REVIEW

File: sdk/servicebus/azure-messaging-servicebus/src/main/java/com/azure/messaging/servicebus/ReceiverOptions.java [hunk 1]
```diff
@@ -0,0 +1,37 @@
+// Copyright (c) Microsoft Corporation. All rights reserved.
```
Comment (conniey) [inline sdk/servicebus/azure-messaging-servicebus/src/main/java/com/azure/messaging/servicebus/ReceiverOptions.java:1]: Package-private class renamed from ReceiveMessageOptions.

File: sdk/servicebus/azure-messaging-servicebus/src/main/java/com/azure/messaging/servicebus/ServiceBusReceiverAsyncClient.java [hunk 2]
```diff
@@ -346,25 +353,44 @@ public String getEntityPath() {
...
      * @return A stream of messages from the Service Bus entity.
      */
     public Flux<ServiceBusReceivedMessage> receive() {
+        return receive(defaultReceiveOptions);
+    }
+
+    /**
+     * Receives a stream of {@link ServiceBusReceivedMessage messages} from the Service Bus entity.
+     *
+     * @return A stream of messages from the Service Bus entity.
```
Comment (hemanttanwar) [inline sdk/servicebus/azure-messaging-servicebus/src/main/java/com/azure/messaging/servicebus/ServiceBusReceiverAsyncClient.java:368]: May be explaining here that  `To disable auto-renew, user have to set MaxAutoRenewDuration to zero.` And default is true

File: sdk/servicebus/azure-messaging-servicebus/src/main/java/com/azure/messaging/servicebus/implementation/ServiceBusMessageProcessor.java [hunk 3]
```diff
@@ -34,24 +42,26 @@
...
+    private final AmqpErrorContext errorContext;
+    private final Function<MessageLockToken, Mono<Void>> completeFunction;
+    private final Function<MessageLockToken, Mono<Void>> onAbandon;
+    private final Function<MessageLockToken, Mono<Instant>> onRenewLock;
     private final Deque<ServiceBusReceivedMessage> messageQueue = new ConcurrentLinkedDeque<>();
     private final boolean isAutoRenewLock;
     private final Duration maxAutoLockRenewal;
     private final MessageLockContainer messageLockContainer;
 
     ServiceBusMessageProcessor(boolean isAutoComplete, boolean isAutoRenewLock, Duration maxAutoLockRenewal,
```
Comment (hemanttanwar) [inline sdk/servicebus/azure-messaging-servicebus/src/main/java/com/azure/messaging/servicebus/implementation/ServiceBusMessageProcessor.java:54]: One option could be calculate `isAutoRenewLock` here using `maxAutoLockRenewal` value and  remove this argument `isAutoRenewLock` being passed in. But  it is not must.

Comment (conniey) [reply sdk/servicebus/azure-messaging-servicebus/src/main/java/com/azure/messaging/servicebus/implementation/ServiceBusMessageProcessor.java:54]: I thought about that. But decoupling it seemed like a better approach to separate responsibility.

File: sdk/servicebus/azure-messaging-servicebus/src/main/java/com/azure/messaging/servicebus/implementation/MessageLockContainer.java [hunk 4]
```diff
@@ -23,7 +23,7 @@
      * @return The updated value in the container. If the expiration time in the container is larger than
      *     {@code lockTokenExpiration}, then the current container value is used.
      */
-    public Instant addOrUpdate(UUID lockToken, Instant lockTokenExpiration) {
+    public Instant addOrUpdate(String lockToken, Instant lockTokenExpiration) {
```
Comment (hemanttanwar) [inline sdk/servicebus/azure-messaging-servicebus/src/main/java/com/azure/messaging/servicebus/implementation/MessageLockContainer.java:26]: While  you are changing this to String, you can look at `receiveDeferredMessage` , there is a problem where we are not calling `addOrUpdate`  in `receiveDeferredMessage`  in PEEK LOCK mode. Thus once we receive DeferredMessage, it can not be Completed or deadLetter because MessageLockContainer does not have an entry for this message lock.
