### PR TITLE
Fixed servicebus default proxy configuration bug

### LINKED ISSUE #24230: [BUG] - Proxy authentication not set correctly in ServiceBusClientBuilder
**Describe the bug**
When service bus client is created from the apps behind corporate proxy, the proxy authentication fails because the authentication type always defaults to NONE.

This results in the client connection failure

***Exception or Stack Trace***
2021-09-21 21:04:17.499 ERROR 4464 --- [ctor-executor-1] c.m.a.p.transport.proxy.impl.ProxyImpl   : Proxy authentication required. User configured: 'NONE', but supported proxy authentication methods are: BASIC

**To Reproduce**
Configure HTTP_PROXY, HTTPS_PROXY, PROXY_USERNAME, PROXY_PASSWORD variables as environment variables.

Create service bus configuration using below sample config

spring:
  cloud:
    function:
      definition: Sampleprocessor
    stream:
      bindings:
        SampleProcessor-in-0:
          destination: input.2
          group: corp-proxy-group
        SampleProcessor-out-0:
          destination: topic-1
    azure:
      servicebus:
        connection-string: Endpoint= <<Azure service bus connection string>>
        transport-type: amqp_web_sockets

Run the application

***Code Snippet*** from ServiceBusClientBuilder.java
    private ProxyOptions getDefaultProxyConfiguration(Configuration configuration) {
        ProxyAuthenticationType authentication = ProxyAuthenticationType.NONE;
The above code sets default authentication to NONE, however, in the downstream, this is never reset if proxy credentials are configured as below.

  private ProxyOptions getProxyOptions(ProxyAuthenticationType authentication, String proxyAddress) {
        String host;
        int port;
        if (HOST_PORT_PATTERN.matcher(proxyAddress.trim()).find()) {
            final String[] hostPort = proxyAddress.split(":");
            host = hostPort[0];
            port = Integer.parseInt(hostPort[1]);
            final Proxy proxy = new Proxy(Proxy.Type.HTTP, new InetSocketAddress(host, port));
            final String username = configuration.get(ProxyOptions.PROXY_USERNAME);
            final String password = configuration.get(ProxyOptions.PROXY_PASSWORD);
            return new ProxyOptions(authentication, proxy, username, password);
        } else {
            com.azure.core.http.ProxyOptions coreProxyOptions = com.azure.core.http.ProxyOptions
                .fromConfiguration(configuration);
            return new ProxyOptions(authentication, new Proxy(coreProxyOptions.getType().toProxyType(),
                coreProxyOptions.getAddress()), coreProxyOptions.getUsername(), coreProxyOptions.getPassword());
        }
    }

**Expected behavior**
The authentication type is chosen based on the environment varaibles. and not defaulted to NONE.

**Screenshots**

**Setup (please complete the following information):**
 - OS: Windows 10
 - IDE: IntelliJ
 - Library/Libraries: azure-messaging-servicebus 7.4.1
 - Java version: openjdk11
 - App Server/Environment: tomcat
 - Frameworks: Spring Boot

If you suspect a dependency version mismatch (e.g. you see `NoClassDefFoundError`, `NoSuchMethodError` or similar), please provide
- verbose dependency tree (`mvn dependency:tree -Dverbose`)
  
**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

### PR DESCRIPTION
**Pull request by ki1729**
# Description

Fixed #24230

# All SDK Contribution checklist:
- [x] **The pull request does not introduce [breaking changes]**
- [x] **CHANGELOG is updated for new features, bug fixes or other significant changes.**
- [x] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md).**

## [General Guidelines and Best Practices](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md#developer-guide)
- [x] Title of the pull request is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).

### CODE REVIEW

**Review by liukun-msft — APPROVED** [review]
LGTM. Add the CHANGELOG for the fix?

File: sdk/servicebus/azure-messaging-servicebus/src/main/java/com/azure/messaging/servicebus/ServiceBusClientBuilder.java [hunk 1]
```diff
@@ -770,48 +767,6 @@ private ConnectionOptions getConnectionOptions() {
         }
     }
 
-    private ProxyOptions getDefaultProxyConfiguration(Configuration configuration) {
-        ProxyAuthenticationType authentication = ProxyAuthenticationType.NONE;
-        if (proxyOptions != null) {
-            authentication = proxyOptions.getAuthentication();
```
Comment (liukun-msft) [inline sdk/servicebus/azure-messaging-servicebus/src/main/java/com/azure/messaging/servicebus/ServiceBusClientBuilder.java:776]: Information for other reviewers: here the authentication is never read correctly from the configuration. The correctly logic is moved to the `ProxyOptions.fromConfiguration()`.

**Review by ZejiaJiang — APPROVED** [review]
LGTM
