### PR TITLE
Queues Samples Issue Fix

### LINKED ISSUE #40920: Storage - Queues Samples Issue
**Section** [link1](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/storage/azure-storage-queue/src/samples/java/com/azure/storage/queue/MessageSamples.java#L22), [link2](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/storage/azure-storage-queue/src/samples/java/com/azure/storage/queue/AsyncSamples.java#L23), [link3](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/storage/azure-storage-queue/src/samples/java/com/azure/storage/queue/QueueServiceSamples.java#L18), [link4](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/storage/azure-storage-queue/src/samples/java/com/azure/storage/queue/QueueExceptionSamples.java#L29):

image

**Reason:**
Server failed to authenticate the request. Please refer to the information in the www-authenticate header.

**Suggestion:**
Update `%s` to `?%s`.

@sandeep-sen, @josefree, @rohit-ganguly, @Kurtzeborn and @alzimmermsft for notification.

### PR DESCRIPTION
**Pull request by ibrahimrabab**
# Description

resolves #40920

### CODE REVIEW

File: sdk/storage/azure-storage-queue/src/samples/java/com/azure/storage/queue/AsyncSamples.java [hunk 1]
```diff
@@ -20,7 +20,7 @@ public class AsyncSamples {
      */
     public static void main(String[] args) {
         // Create an async queue client.
-        String queueURL = String.format("https://%s.queue.core.windows.net/%s%s", ACCOUNT_NAME, QUEUE_NAME, SAS_TOKEN);
+        String queueURL = String.format("https://%s.queue.core.windows.net/?%s%s", ACCOUNT_NAME, QUEUE_NAME, SAS_TOKEN);
```
Comment (alzimmermsft) [inline sdk/storage/azure-storage-queue/src/samples/java/com/azure/storage/queue/AsyncSamples.java:23]: I think the query parameter start is in the wrong spot, shouldn't it be after the queue name as that is part of the URL path?

```suggestion
        String queueURL = String.format("https://%s.queue.core.windows.net/%s?%s", ACCOUNT_NAME, QUEUE_NAME, SAS_TOKEN);
```

**Review by alzimmermsft — APPROVED** [review]
