### PR TITLE
Messaging (Event Hubs, Service Bus) logging improvements

### LINKED ISSUE #39575: [BUG] Service bus sender client: connection errors in logs
**Describe the bug**
The sender client works, and messages are sent successfully to a service bus. But from time to time, there are several types of errors appear in the logs:

- com.azure.core.amqp.exception.AmqpException: Connection reset, errorContext[NAMESPACE: *****.servicebus.windows.net. ERROR CONTEXT: N/A]
- com.azure.core.amqp.exception.AmqpException: Connection timed out: getsockopt, errorContext[NAMESPACE: *****.servicebus.windows.net. ERROR CONTEXT: N/A]
- com.azure.core.amqp.exception.AmqpException: connection aborted, errorContext[NAMESPACE: *****.servicebus.windows.net. ERROR CONTEXT: N/A]

These errors have no influence on the messages sending process, all messages are sent successfully.

***Exception or Stack Trace***
```
reactor.core.Exceptions$ErrorCallbackNotImplemented: com.azure.core.amqp.exception.AmqpException: connection aborted, errorContext[NAMESPACE: ***********.servicebus.windows.net. ERROR CONTEXT: N/A]
Caused by: com.azure.core.amqp.exception.AmqpException: connection aborted, errorContext[NAMESPACE *********.servicebus.windows.net. ERROR CONTEXT: N/A]
at com.azure.core.amqp.implementation.ExceptionUtil.toException(ExceptionUtil.java:85)
at com.azure.core.amqp.implementation.handler.ConnectionHandler.notifyErrorContext(ConnectionHandler.java:362)
at com.azure.core.amqp.implementation.handler.ConnectionHandler.onTransportError(ConnectionHandler.java:259)
at org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:191)
at org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108)
at org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:324)
at org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:291)
at com.azure.core.amqp.implementation.ReactorExecutor.run(ReactorExecutor.java:91)
at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68)
at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
```

**To Reproduce**

***Code Snippet***
```
spring:
  cloud:
    azure:
      servicebus:
        namespace: ${service-bus-namespace}
        producer:
          entity-name: ${service-bus-queue-name}
          entity-type: QUEUE

ServiceBusSenderClient client; - injected client
client.sendMessage(message);
```

**Setup (please complete the following information):**
 - OS: Windows
 - Library: com.azure.spring:spring-cloud-azure-starter-servicebus:5.10.0
 - Java version: 21
 - App Server/Environment: Azure Function, standalone app running
 - Frameworks: Spring Boot

### PR DESCRIPTION
**Pull request by lmolkova**
Fixes #39575
- logs transient issues as warnings (instead of errors)
- logs issues when something is already closed or disposed as warnings  (instead of errors)
- logs terminal issues as errors (if they aren't)

Removes some deprecated (a long time ago) internal, unused constructors.

### CODE REVIEW

File: sdk/core/azure-core-amqp/src/main/java/com/azure/core/amqp/implementation/ReactorDispatcher.java [hunk 1]
```diff
@@ -257,7 +257,7 @@ public void run(Selectable selectable) {
                     ioSignal.source().close();
                 }
             } catch (IOException ioException) {
-                logger.error("CloseHandler.source().close() failed with an error.", ioException);
+                logger.warning("CloseHandler.source().close() failed with an error.", ioException);
```
Comment (anuchandy) [inline sdk/core/azure-core-amqp/src/main/java/com/azure/core/amqp/implementation/ReactorDispatcher.java:260]: My understanding is, it’s less likely to hit this code path (so the log line) and line 250, but when it does, this error likely to be useful for us, to back track any memory-leak due to io-pipes not being cleaned up?

File: sdk/core/azure-core-amqp/src/main/java/com/azure/core/amqp/implementation/handler/WebSocketsProxyConnectionHandler.java [hunk 2]
```diff
@@ -190,8 +190,10 @@ public void onTransportError(Event event) {
         final URI url = createURI(fullyQualifiedNamespace, port);
         final InetSocketAddress address = new InetSocketAddress(hostNameParts[0], port);
 
-        logger.atError()
-            .log("Failed to connect to url: '{}', proxy host: '{}'", url, address.getHostString(), ioException);
+        logger.atWarning()
+            .addKeyValue("url", url)
+            .addKeyValue("proxyHost", address.getHostString())
+            .log("Failed to connect.", ioException);
```
Comment (anuchandy) [inline sdk/core/azure-core-amqp/src/main/java/com/azure/core/amqp/implementation/handler/WebSocketsProxyConnectionHandler.java:196]: Our current proxy implementation (extended to proton-extensions) does not signal a useful error, but a general transport-error gets reported in common transport level, so I was wondering this external proxy specific Connect error should be in error-level to detect problem easier. WDYT?

File: sdk/core/azure-core-amqp/src/main/java/com/azure/core/amqp/implementation/AmqpChannelProcessor.java [hunk 3]
```diff
@@ -63,28 +63,6 @@ public class AmqpChannelProcessor<T> extends Mono<T> implements Processor<T, T>,
...
-    public AmqpChannelProcessor(String fullyQualifiedNamespace, String entityPath,
-        Function<T, Flux<AmqpEndpointState>> endpointStatesFunction, AmqpRetryPolicy retryPolicy, ClientLogger logger) {
-        this.endpointStatesFunction
-            = Objects.requireNonNull(endpointStatesFunction, "'endpointStates' cannot be null.");
-        this.retryPolicy = Objects.requireNonNull(retryPolicy, "'retryPolicy' cannot be null.");
-        Map<String, Object> loggingContext = new HashMap<>(1);
-        loggingContext.put(ENTITY_PATH_KEY, Objects.requireNonNull(entityPath, "'entityPath' cannot be null."));
-        this.logger = new ClientLogger(getClass(), loggingContext);
-        this.errorContext = new AmqpErrorContext(fullyQualifiedNamespace);
-    }
```
Comment (anuchandy) [inline sdk/core/azure-core-amqp/src/main/java/com/azure/core/amqp/implementation/AmqpChannelProcessor.java:86]: thanks for getting rid of all these unused Ctrs :)

**Review by anuchandy — COMMENTED** [review]
Thank you Liudmila, I don’t think with the changes so far we miss any logs that is crucial for incident investigations. Just some minor comments to hear your thoughts

File: sdk/core/azure-core-amqp/src/main/java/com/azure/core/amqp/implementation/ReactorDispatcher.java (hunk 1 above)
Comment (anuchandy) [reply sdk/core/azure-core-amqp/src/main/java/com/azure/core/amqp/implementation/ReactorDispatcher.java:260]: TBH; I've yet to see this in any incident logs.

Comment (lmolkova) [reply sdk/core/azure-core-amqp/src/main/java/com/azure/core/amqp/implementation/ReactorDispatcher.java:260]: Good point! 

Do you think people would disable warnings coming from our loggers? 

the main reason I change closing errors to warnings is that when things are being closed, we create a ton of logs which look scary but are probably benign. 

But based on you explanation, I realized this is an error from close() and not some race-condition because something is already closed. So I'm happy to revert changes here.

File: sdk/core/azure-core-amqp/src/main/java/com/azure/core/amqp/implementation/handler/WebSocketsProxyConnectionHandler.java (hunk 2 above)
Comment (lmolkova) [reply sdk/core/azure-core-amqp/src/main/java/com/azure/core/amqp/implementation/handler/WebSocketsProxyConnectionHandler.java:196]: I don't have a strong opinion here. 

The motivation to make it a warning:
- We'd still report the error and I'd expect users to set level to warning for 3rd party libs by default.
- It seems to be transient

If based on your experience, users don't enable warnings, I'm happy to change the severity back to error.

Comment (anuchandy) [reply sdk/core/azure-core-amqp/src/main/java/com/azure/core/amqp/implementation/handler/WebSocketsProxyConnectionHandler.java:196]: Thanks for sharing the thoughts. What I observed (when exploring custom proxy auth) was, the proxy connect error from proton-extensions layer gets signaled as generic framing-error in core-amqp, those generic error are retried for ever since wrong proxy config won’t get resolved automatically. Thinking a bit more, **I agree with you on using warn**, since this is not a situation (race/one-off) where missing this data would affect diagnosis, as the unable-to-connect behavior would be persistent.

Our messaging log sample configs (in troubleshooting section) do not have entries to enable proton-extension logs, but if incidents happen for web-socket mode, we can instruct users to enable it.

File: sdk/core/azure-core-amqp/src/main/java/com/azure/core/amqp/implementation/ReactorDispatcher.java (hunk 1 above)
Comment (anuchandy) [reply sdk/core/azure-core-amqp/src/main/java/com/azure/core/amqp/implementation/ReactorDispatcher.java]: Typically, users want to use the lowest logging level. Upon request, _warn_ is someone less hesitant to set compared to _verbose_, upon request. Yes, given we never observed this error, I was thinking keeping it as it is

File: sdk/core/azure-core-amqp/src/main/java/com/azure/core/amqp/implementation/AmqpChannelProcessor.java (hunk 3 above)
Comment (lmolkova) [reply sdk/core/azure-core-amqp/src/main/java/com/azure/core/amqp/implementation/AmqpChannelProcessor.java:86]: apparently not all of them are unused 🤐

File: sdk/servicebus/azure-messaging-servicebus-stress/pom.xml [hunk 4]
```diff
@@ -42,6 +42,12 @@
       <version>2.7.18</version> <!-- {x-version-update;org.springframework.boot:spring-boot-starter;external_dependency} -->
     </dependency>
 
+    <dependency>
+      <groupId>com.azure</groupId>
+      <artifactId>azure-core-amqp</artifactId>
+      <version>2.10.0-beta.1</version>  <!-- {x-version-update;com.azure:azure-core-amqp;current} -->
```
Comment (anuchandy) [inline sdk/servicebus/azure-messaging-servicebus-stress/pom.xml:48]: nit; should this be `<!-- {x-version-update;unreleased_com.azure:azure-core-amqp;dependency} -->` ?

**Review by anuchandy — APPROVED** [review]
thank you, LGTM!

File: sdk/servicebus/azure-messaging-servicebus-stress/pom.xml (hunk 4 above)
Comment (lmolkova) [reply sdk/servicebus/azure-messaging-servicebus-stress/pom.xml]: not sure, I'm going to remove it from stress tests since we'd get dependency on newest core-amqp via SB now and we have FromSource pipelines to validate compatibility
