### PR TITLE
Throwing exception if blob name is passed as null

### LINKED ISSUE #40926: [BUG] The response `The requested URI does not represent any resource on the server.` is not helpful when the blob name is `null`
**Describe the bug**
The response `The requested URI does not represent any resource on the server.` is not helpful when the blob name is `null`

***Exception or Stack Trace***
Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed: com.azure.storage.blob.models.BlobStorageException: Status code 400, "﻿<?xml version="1.0" encoding="utf-8"?><Error><Code>InvalidUri</Code><Message>The requested URI does not represent any resource on the server.

**To Reproduce**
Pass the blob name as null
 BlobClient blobClient = blobContainerClient.getBlobClient(null);

***Code Snippet***
 BlobClient blobClient = blobContainerClient.getBlobClient(null);

**Expected behavior**
The blob name is null

**Screenshots**

**Setup (please complete the following information):**
 - IDE: [e.g. IntelliJ]
 - Library/Libraries: [e.g. com.azure:azure-core:1.16.0 (groupId:artifactId:version)]
 - Java version: [e.g. 8] 
 - App Server/Environment: [e.g. Tomcat, WildFly, Azure Function, Apache Spark, Databricks, IDE plugin or anything special]
 - Frameworks: [e.g. Spring Boot, Micronaut, Quarkus, etc] 

If you suspect a dependency version mismatch (e.g. you see `NoClassDefFoundError`, `NoSuchMethodError` or similar), please check out [Troubleshoot dependency version conflict article](https://aka.ms/azsdk/java/dependency/troubleshoot) first. If it doesn't provide solution for the problem, please provide:
- verbose dependency tree (`mvn dependency:tree -Dverbose`)
- exception message, full stack trace, and any available logs

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

### PR DESCRIPTION
**Pull request by ibrahimrabab**
# Description

resolves #40926

Throwing NullPointerException if blob name is passed as null.

### CODE REVIEW

**Review by ibrandes — APPROVED** [review]

File: sdk/storage/azure-storage-blob/src/main/java/com/azure/storage/blob/specialized/BlobAsyncClientBase.java [hunk 1]
```diff
@@ -230,6 +230,9 @@ protected BlobAsyncClientBase(HttpPipeline pipeline, String url, BlobServiceVers
             throw LOGGER.logExceptionAsError(
                 new IllegalArgumentException("'snapshot' and 'versionId' cannot be used at the same time."));
         }
+        if (blobName == null) {
```
Comment (alzimmermsft) [inline sdk/storage/azure-storage-blob/src/main/java/com/azure/storage/blob/specialized/BlobAsyncClientBase.java:233]: Is an empty string blobName allowed? If not, we should check for that as well.

And were all other Storage SDKs checked for this possible issue as well?

**Review by alzimmermsft — APPROVED** [review]

File: sdk/storage/azure-storage-blob/src/main/java/com/azure/storage/blob/specialized/BlobAsyncClientBase.java [hunk 2]
```diff
@@ -230,6 +230,9 @@ protected BlobAsyncClientBase(HttpPipeline pipeline, String url, BlobServiceVers
...
+            throw LOGGER.logExceptionAsError(new IllegalArgumentException("'blobName' can not be set to null."));
```
Comment (srnagar) [inline sdk/storage/azure-storage-blob/src/main/java/com/azure/storage/blob/specialized/BlobAsyncClientBase.java:234]: For null values, [SDK guidelines](https://azure.github.io/azure-sdk/java_introduction.html#java-errors-system-errors) suggest that we throw NullPointerException.

File: sdk/storage/azure-storage-blob/src/main/java/com/azure/storage/blob/specialized/BlobAsyncClientBase.java (hunk 1 above)
Comment (srnagar) [reply sdk/storage/azure-storage-blob/src/main/java/com/azure/storage/blob/specialized/BlobAsyncClientBase.java:233]: Yes, we should check for empty strings too as that will also result in an invalid path.

Comment (ibrahimrabab) [reply sdk/storage/azure-storage-blob/src/main/java/com/azure/storage/blob/specialized/BlobAsyncClientBase.java:233]: Since empty strings are used when setting the root directory in datalake, empty strings are considered valid:
https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/storage/azure-storage-file-datalake/src/main/java/com/azure/storage/file/datalake/DataLakeFileSystemClient.java#L215
