### PR TITLE
Fixed JsonFlatten Recursion on Fields

### LINKED ISSUE #22473: [BUG] Recursively Apply JsonFlatten when Annotating a Property
When a property is annotated with `@JsonFlatten` `FlatteningSerializer` and `FlatteningDeserializer` should be recursively applied to properties of the type annotated. So, given the following example:

```java
public class A {
  @JsonFlatten
  @JsonProperty("wrapper.B")
  private B b;
}

public class B {
  @JsonProperty("C")
  private C c;
}

public class C {
  @JsonFlatten
  @JsonProperty("innerWrapper.name")
  private String name;

  @JsonFlatten
  @JsonProperty("innerWrapper.details")
  private String details
}
```

Currently, when class `A` is serialized the resulting JSON ends up being the following:

```json
{
  "wrapper": {
    "B": {
      "C": {
        "innerWrapper.name": "name",
        "innerWrapper.details": "details"
      }
    }
  }
}
```

But with the given properties and annotations the resulting JSON should be the following:

```json
{
  "wrapper": {
    "B": {
      "C": {
        "innerWrapper": {
          "name": "name",
          "details": "details"
        }
      }
    }
  }
}
```

### PR DESCRIPTION
**Pull request by alzimmermsft**
Fixes #22473

This PR resolves an issue when `JsonFlatten` is annotated on a `FIELD` where the flattening serializer wasn't called recursively. 

Before, `FlatteningSerializer` was leveraging an external `ObjectMapper` to translate the object being serialized into a JSON tree. Then the flattening serializer, if the class wasn't annotated with `JsonFlatten`, would inspect each field to determine if the JSON sub-tree would need to be flattened. This worked if the object being serialized has no properties types which had `JsonFlatten` either as a class or field annotation. But, if a property type did has the `JsonFlatten` annotation it wouldn't be flattened properly.

Now, `FlatteningSerializer` constructs the JSON tree manually if the class only has `JsonFlatten` on fields. It then leverages the contextual `ObjectMapper` to handle serializing the generated tree. This resolves the issue of having the flattening serializer being called recursively on sub-properties if they were annotated with `JsonFlatten`.

### CODE REVIEW

File: sdk/core/azure-core/src/main/java/com/azure/core/util/serializer/FlatteningSerializer.java [hunk 1]
```diff
@@ -291,9 +309,25 @@ public void resolve(SerializerProvider provider) throws JsonMappingException {
...
     }
 
-    @Override
-    public void serializeWithType(Object value, JsonGenerator gen, SerializerProvider provider,
-        TypeSerializer typeSerializer) throws IOException {
-        serialize(value, gen, provider);
+    private void propertyOnlyFlattenSerialize(Object value, JsonGenerator jgen, ObjectNode objNode) throws IOException {
+        for (BeanPropertyDefinition beanPropertyDefinition : beanDescription.findProperties()) {
+            if (jsonPropertiesWithJsonFlatten.contains(beanPropertyDefinition.getName())) {
+                String[] splitNames = SPLIT_FLATTEN_PROPERTY_PATTERN.split(beanPropertyDefinition.getName());
```
Comment (lmolkova) [inline sdk/core/azure-core/src/main/java/com/azure/core/util/serializer/FlatteningSerializer.java:315]: It seems none of the above 3 lines are not specific, but done on each call, could something be pre-cached/pre-calculated for optimization reasons?

**Review by lmolkova — DISMISSED** [review]
LGTM, left some comment regarding possible perf optimization

File: sdk/core/azure-core/src/main/java/com/azure/core/util/serializer/FlatteningSerializer.java (hunk 1 above)
Comment (alzimmermsft) [reply sdk/core/azure-core/src/main/java/com/azure/core/util/serializer/FlatteningSerializer.java:315]: I believe it would be possible to cache the properties and their split names if needed

**Review by lmolkova — APPROVED** [review]
LGTM. 

One vague idea for the future (if you haven't already explored it): it seems we have to mix flattening and additional properties (JsonAnyGetter/Setter) support in the flattening serializer. Can we separate those somehow? 

Can we handle anygetter/setter somewhere else (we have `AdditionalPropertiesSerializer` or maybe can offload it to jackson), so by the time it reaches `FlatteningSerializer`, we don't have to think about it? (order is arbitrary, can be opposite).

File: sdk/core/azure-core/src/test/java/com/azure/core/implementation/models/jsonflatten/FlattenedPropertiesAndJsonAnyGetter.java [hunk 2]
```diff
@@ -0,0 +1,51 @@
...
+        this.string = string;
+        return this;
+    }
+
+    public String getString() {
+        return string;
+    }
+
+    @JsonAnyGetter
+    public Map<String, Object> additionalProperties() {
```
Comment (lmolkova) [inline sdk/core/azure-core/src/test/java/com/azure/core/implementation/models/jsonflatten/FlattenedPropertiesAndJsonAnyGetter.java:38]: could there be a case with both `@JsonAnyGetter` and `@JsonFlatten` annotations?

File: sdk/core/azure-core/src/test/java/com/azure/core/implementation/models/jsonflatten/JsonFlattenOnJsonIgnoredProperty.java [hunk 3]
```diff
@@ -0,0 +1,41 @@
...
+ */
+@Fluent
+public final class JsonFlattenOnJsonIgnoredProperty {
+    @JsonProperty("name")
+    private String name;
+
+    @JsonIgnore
+    @JsonFlatten
+    @JsonProperty("jsonflatten.ignored")
+    private String ignored;
```
Comment (srnagar) [inline sdk/core/azure-core/src/test/java/com/azure/core/implementation/models/jsonflatten/JsonFlattenOnJsonIgnoredProperty.java:22]: Is this even valid to have `@JsonIgnore` and `@JsonProperty`?

**Review by srnagar — APPROVED** [review]

File: sdk/core/azure-core/src/test/java/com/azure/core/implementation/models/jsonflatten/FlattenedPropertiesAndJsonAnyGetter.java (hunk 2 above)
Comment (alzimmermsft) [reply sdk/core/azure-core/src/test/java/com/azure/core/implementation/models/jsonflatten/FlattenedPropertiesAndJsonAnyGetter.java:38]: From a code perspective it should be possible but we wouldn't generated code in that way. I can take this as a follow-up to see what would happen.

File: sdk/core/azure-core/src/test/java/com/azure/core/implementation/models/jsonflatten/JsonFlattenOnJsonIgnoredProperty.java (hunk 3 above)
Comment (alzimmermsft) [reply sdk/core/azure-core/src/test/java/com/azure/core/implementation/models/jsonflatten/JsonFlattenOnJsonIgnoredProperty.java:22]: Yes, but it doesn't really make much sense, I just wanted to ensure that `JsonFlatten` wouldn't result in an inappropriate serialization in this instance

File: sdk/core/azure-core/src/main/java/com/azure/core/util/serializer/FlatteningDeserializer.java [hunk 4]
```diff
@@ -179,56 +182,66 @@ private void handleFlatteningForField(AnnotatedField annotatedField, JsonNode js
...
-                // This should replace the JsonNode it is compacting.
-                ((ObjectNode) jsonNode).set(jsonPropValue, childJsonNode);
-            }
-        }
-    }
+                // Keep track of the JsonNodes which lead to the flattened property being deserialized.
+                //
+                // This will be used later to clean up the parent JsonNode so that there aren't additional dangling
+                // JSON once the flattened value is uplifted. If this isn't done it can result in models with
+                // @JsonAnySetter containing errant values.
```
[the remark this answers is not in the document]
Comment (alzimmermsft) [reply sdk/core/azure-core/src/main/java/com/azure/core/util/serializer/FlatteningDeserializer.java:196]: I'll add a more detailed comment. The following is a class and JSON string I'll use as an example:

```java
public class AClass {
  @JsonFlatten
  @JsonProperty("flattened.string")
  private String flattenedString;

  @JsonIgnore
  private Map<String, Object> additionalProperties;

  @JsonAnySetter
  void addAdditionalProperty(String key, Object value) {
    if (additionalProperties == null) {
      additionalProperties = new HashMap<>();
    }
    additionalProperties.put(key, value);
  }
}
```

```json
{
  "flattened": {
    "string": "string"
  },
  "additionalProperty1": "value1",
  "additionalProperty2": "value2"
}
```

Before this change, after applying the un-flattening of `flattened.string` the JSON tree structure would have been equivalent to the following JSON:

```json
{
  "flattened": {
    "string": "string"
  },
  "additionalProperty1": "value1",
  "additionalProperty2": "value2",
  "flattened.string": "string"
}
```

With the `JsonAnySetter` existing this would have then resulted in an errant entry existing in `additionalProperties` of:

```
additionalProperties.get("flattened") => map of "string":"string"
```

After this change, after applying the un-flattening of `flattened.string` the JSON tree structure leading to the flattened value will be cleaned up for every sub-tree which is now empty, resulting the following JSON:

```json
{
  "additionalProperty1": "value1",
  "additionalProperty2": "value2",
  "flattened.string": "string"
}
```

So, there will no longer be any errant properties existing in `additionalProperties`.
