### PR TITLE
Shorten tracing span names

### LINKED ISSUE #6791: [BUG] Distributed tracing: short span names for public api surface
**Describe the bug**
Java SDKs set span names (for public api surface spans) to fully qualified name: 'namespace.class/method'.  Namespace presence makes span names too long and is not very informative. 'Class.method' provides enough granularity and context for users.
 
Python and JS SDKs use class.method (or method only).

***Exception or Stack Trace***
N/A

**To Reproduce**

***Code Snippet***

**Expected behavior**
Span names should look like "Appconfig.setKey'. It should affect the convenience layer spans only.

**Screenshots**

This is how it looks now:

image

how it looks with short names (screenshot is taken from the different .NET app with different scenario):

image

**Setup (please complete the following information):**
 - OS:  N/A
 - IDE : N/A
 - Version of the Library used: -

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

### PR DESCRIPTION
**Pull request by samvaity**
Remove `Azure` prefix from span names.
Fixes #6791

Now,

image

image

### CODE REVIEW

File: sdk/core/azure-core/src/main/java/com/azure/core/http/rest/RestProxy.java [hunk 1]
```diff
@@ -196,7 +196,7 @@ private Method determineResumeMethod(Method method, String resumeMethodName) {
      * @return The updated context containing the span context.
      */
     private Context startTracingSpan(Method method, Context context) {
-        String spanName = String.format("Azure.%s/%s", interfaceParser.getServiceName(), method.getName());
+        String spanName = String.format("%s/%s", interfaceParser.getServiceName(), method.getName());
```
Comment (lmolkova) [inline sdk/core/azure-core/src/main/java/com/azure/core/http/rest/RestProxy.java]: for the sake of having the same naming format as other azure SDKs. can we use '.' as a separator everywhere?

E.g. 'Appconfig.getKey' rather than 'Appconfig/getKey'

File: sdk/core/azure-core-amqp/src/main/java/com/azure/core/amqp/implementation/TracerProvider.java [hunk 2]
```diff
@@ -115,7 +115,7 @@ private void end(String statusMessage, Throwable throwable, Context context) {
     }
 
     private String getSpanName(ProcessKind processKind) {
-        String spanName = "Azure.eventhubs.";
+        String spanName = "Eventhubs.";
```
Comment (conniey) [inline sdk/core/azure-core-amqp/src/main/java/com/azure/core/amqp/implementation/TracerProvider.java]: `EventHubs.`

Comment (conniey) [reply sdk/core/azure-core-amqp/src/main/java/com/azure/core/amqp/implementation/TracerProvider.java]: Same with all the other ones.
