### PR TITLE
Check for java.net.useSystemProxies Before Consuming HTTP_PROXY

### LINKED ISSUE #25186: [BUG] azure-messaging-eventhubs 5.10.1 & 5.10.2 throws NPE when PROXY configuration is set
**Describe the bug**
Using `azure-messaging-eventhubs 5.10.1 or 5.10.2`, when a proxy configuration is set through environment variables:
```
HTTPS_PROXY=http://10.xx.xx.xx:3128
HTTP_PROXY=http://10.xx.xx.xx:3128
NO_PROXY=localblobstore,localhost
```

EventHubClientBuilder will throw a NullPointerException when calling  buildProducerClient: 
```
Caused by: java.lang.NullPointerException: null
    at com.azure.messaging.eventhubs.EventHubClientBuilder.getProxyOptions(EventHubClientBuilder.java:823) 
```

A Docker container running an earlier versions of the package work fine, like 5.10.0.
Is this bug related to a proxy bug in azure-core that got fixed in 1.19.0 (which 5.10.0 uses)? Maybe a regression in 1.20.0 (which 5.10.1 uses, the version we see this problem occur).

Problem also occurs in 5.10.2 which uses a newer azure-core version.

***Exception or Stack Trace***
```
Caused by: java.lang.NullPointerException: null
	at com.azure.messaging.eventhubs.EventHubClientBuilder.getProxyOptions(EventHubClientBuilder.java:823) ~[app.jar:1.0.0-SNAPSHOT]
	at com.azure.messaging.eventhubs.EventHubClientBuilder.getDefaultProxyConfiguration(EventHubClientBuilder.java:805) ~[app.jar:1.0.0-SNAPSHOT]
	at com.azure.messaging.eventhubs.EventHubClientBuilder.getConnectionOptions(EventHubClientBuilder.java:757) ~[app.jar:1.0.0-SNAPSHOT]
	at com.azure.messaging.eventhubs.EventHubClientBuilder.buildConnectionProcessor(EventHubClientBuilder.java:705) ~[app.jar:1.0.0-SNAPSHOT]
	at com.azure.messaging.eventhubs.EventHubClientBuilder.buildAsyncClient(EventHubClientBuilder.java:638) ~[app.jar:1.0.0-SNAPSHOT]
	at com.azure.messaging.eventhubs.EventHubClientBuilder.buildClient(EventHubClientBuilder.java:676) ~[app.jar:1.0.0-SNAPSHOT]
	at com.azure.messaging.eventhubs.EventHubClientBuilder.buildProducerClient(EventHubClientBuilder.java:584) ~[app.jar:1.0.0-SNAPSHOT]
```

The code line 823 in version 5.10.1 and 5.10.2 is azure-core proxy related: 
```
821            com.azure.core.http.ProxyOptions coreProxyOptions = com.azure.core.http.ProxyOptions
822                .fromConfiguration(configuration);
823            Proxy.Type proxyType = coreProxyOptions.getType().toProxyType();
```

**To Reproduce**
1) Use azure-messaging-eventhubs 5.10.1 or 5.10.2 
2) Set environment variables:
```
HTTPS_PROXY=http://10.xx.xx.xx:3128
HTTP_PROXY=http://10.xx.xx.xx:3128
NO_PROXY=localblobstore,localhost
```
3) Build a producer client:
```java
this.eventHubProducerClient = new EventHubClientBuilder()
	.transportType(AmqpTransportType.AMQP_WEB_SOCKETS)
        .connectionString(eventHubConfig.getConnectionString())
	.buildProducerClient();
```

**Expected behavior**
Earlier versions of the SDK worked perfectly (i.e. azure-messaging-eventhubs 5.10.0).  Expecting the same.

**Setup (please complete the following information):**
 - OS: Ubuntu 18.04 in a Docker Container via IoT Edge on an Edge device
 - Library/Libraries: azure-messaging-eventhubs 5.10.1
 - Java version: 11
 - Frameworks: Spring Boot

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

### PR DESCRIPTION
**Pull request by alzimmermsft**
Fixes #25186

This PR resolves a potential `NullPointerException` when `HTTP_PROXY` is configured in the environment but `java.net.useSystemProxies` is false. In this scenario `ProxyOptions.fromConfiguration(Configuration)` will return a null `ProxyOptions` if only `HTTPS_PROXY` or `HTTP_PROXY` is set, conforming with how the JDK handles environment proxies.

### CODE REVIEW

File: sdk/servicebus/azure-messaging-servicebus/src/main/java/com/azure/messaging/servicebus/ServiceBusClientBuilder.java [hunk 1]
```diff
@@ -552,10 +552,12 @@ private ProxyOptions getDefaultProxyConfiguration(Configuration configuration) {
             return ProxyOptions.SYSTEM_DEFAULTS;
         }
 
-        return getProxyOptions(authentication, proxyAddress);
+        return getProxyOptions(authentication, proxyAddress, configuration,
+            Boolean.parseBoolean(configuration.get("java.net.useSystemProxies")));
     }
 
-    private ProxyOptions getProxyOptions(ProxyAuthenticationType authentication, String proxyAddress) {
+    private ProxyOptions getProxyOptions(ProxyAuthenticationType authentication, String proxyAddress,
```
Comment (srnagar) [inline sdk/servicebus/azure-messaging-servicebus/src/main/java/com/azure/messaging/servicebus/ServiceBusClientBuilder.java:559]: Maybe this is out of scope for this PR but we could consolidate how messaging services support proxies by having this method as a helper in core-amqp (similar to CoreUtils, we can have AmqpUtils). Both EventHubClientBuilder and ServiceBusClientBuilder can just call into this method.

**Review by srnagar — APPROVED** [review]
