### PR TITLE
Remove Void Responses from being Eagerly Read

### LINKED ISSUE #28033: Use enum instead of boolean for eagerlyReadResponse
Today, RestProxy takes care of disposing response if there's no need to process body, i.e. there's `Response<Foo, Void>`. 

Related code:
https://github.com/Azure/azure-sdk-for-java/blob/627f10710712d00eea89dfd892587f18da2a456a/sdk/core/azure-core/src/main/java/com/azure/core/http/rest/RestProxy.java#L475
and
https://github.com/Azure/azure-sdk-for-java/blob/627f10710712d00eea89dfd892587f18da2a456a/sdk/core/azure-core/src/main/java/com/azure/core/implementation/serializer/HttpResponseBodyDecoder.java#L393

We can (probably) simplify this logic a bit by introducing enum to cover the requested response type and also release a connection a little bit faster.
We can consider an `enum ResponseBodyReadStrategy { EAGER, STREAMED, NO_RESPONSE_BODY  }` and take care of that handling at http client layer instead in rest proxy.
Something like:
image

### LINKED ISSUE #31555: [BUG] BlobClient.exists() is greedy for heap space
**Describe the bug**
Calling BlobClient.exists() seems to require a significant amount of heap space, proportional to the size of the blob.

**To Reproduce**
Manually upload object to blob storage. Update the code snippet below with the URL to the blob and the managed resource ID. Run setting the -Xmx flag. For a 250MB blob the max heap size has to be set to ~450MB, for a 1.3GB blob we seem to require almost 2GB heap size otherwise the exists call hangs forever. In the snippet below I've used existsWithResponse in order to set a 30s timeout to avoid getting stuck on the exists call. If the max heap size is set too low then we'll hit the IllegalStateException after the timeout duration.

Calling .exists() for a blob that does not exist always returns quickly and requires a very small max heap size - 150MB is fine.

***Code Snippet***

    import java.time.Duration;
    import com.azure.core.http.rest.Response;
    import com.azure.identity.ManagedIdentityCredential;
    import com.azure.identity.ManagedIdentityCredentialBuilder;
    import com.azure.storage.blob.BlobClient;
    import com.azure.storage.blob.BlobClientBuilder;

    public class AzureExistsTest {

        public static void main(String[] args) throws Exception
        {
            String blobURI = "https://container.blob.core.windows.net/<path to blob>";
            String resourceId = "<RESOURCE ID>";
            ManagedIdentityCredential managedIdentityCredential =
                  new ManagedIdentityCredentialBuilder().resourceId(resourceId).build();

            BlobClient blobClient = new BlobClientBuilder().credential(managedIdentityCredential)
                                                           .endpoint(blobURI)
                                                           .buildClient();
            Boolean blobExists = false;

            try
            {
                Response<Boolean> lresponse = blobClient.existsWithResponse(Duration.ofSeconds(30), null);
                blobExists = lresponse.getValue();
                System.out.println("Blob exists returned: " + blobExists);
            }
            catch (IllegalStateException ex)
            {
                System.out.println("Illegal state exception: " + ex.getMessage());
            }
            catch (Exception ex)
            {
                System.out.println("Caught exception: " + ex.getMessage());
            }
        }
    }

**Expected behavior**
Expect BlobClient.exists() to return within a few seconds for blobs of any size with a true/false response whilst still being able to restrict the maximum heap size of the overall Java process to less than 1 GB.

**Setup (please complete the following information):**
 - OS: CentOS
 - IDE: None
 - Library/Libraries: com.azure:azure-core:1.32.0 
                               com.azure:azure-storage-blob:12.19.1
                               com.azure:azure-identity:1.5.5
                               com.azure:azure-storage-common:12.18.1
                               com.azure:azure-storage-internal-avro:12.4.2
                               com.azure:azure-core-http-netty:1.12.5  
 - Java version: 8
 - App Server/Environment: None
 - Frameworks: None

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

### LINKED ISSUE #31849: [BUG] OutOfMemoryError when calling ShareFileAsyncClient.getProperties() after `azure-storage-file-share` lib upgrade
**Describe the bug**
When using `azure-storage-file-share` version `12.15.1` and `12.16.0` I got an `OutOfMemoryError` when downloading large file (325M) with `ShareFileAsyncClient.downloadWithResponse()`
No such error with version `12.14.0`

***Exception or Stack Trace***
```
java.lang.OutOfMemoryError: Java heap space
	at com.azure.core.implementation.ByteBufferCollector.<init>(ByteBufferCollector.java:52) ~[azure-core-1.33.0.jar:1.33.0]
	at com.azure.core.util.FluxUtil.lambda$collectBytesInByteBufferStream$2(FluxUtil.java:139) ~[azure-core-1.33.0.jar:1.33.0]
	at com.azure.core.util.FluxUtil$$Lambda$1447/0x00000008014b4fc0.get(Unknown Source) ~[?:?]
	at reactor.core.publisher.MonoCollect.subscribeOrReturn(MonoCollect.java:58) ~[reactor-core-3.4.24.jar:3.4.24]
	at reactor.core.publisher.Flux.subscribe(Flux.java:8512) ~[reactor-core-3.4.24.jar:3.4.24]
	at reactor.core.publisher.MonoFlatMapMany$FlatMapManyMain.onNext(MonoFlatMapMany.java:195) ~[reactor-core-3.4.24.jar:3.4.24]
	at reactor.core.publisher.SerializedSubscriber.onNext(SerializedSubscriber.java:99) ~[reactor-core-3.4.24.jar:3.4.24]
	at reactor.core.publisher.FluxRetryWhen$RetryWhenMainSubscriber.onNext(FluxRetryWhen.java:174) ~[reactor-core-3.4.24.jar:3.4.24]
	at reactor.core.publisher.MonoCreate$DefaultMonoSink.success(MonoCreate.java:172) ~[reactor-core-3.4.24.jar:3.4.24]
	at reactor.netty.http.client.HttpClientConnect$HttpIOHandlerObserver.onStateChange(HttpClientConnect.java:431) ~[reactor-netty-http-1.0.24.jar:1.0.24]
	at reactor.netty.ReactorNetty$CompositeConnectionObserver.onStateChange(ReactorNetty.java:677) ~[reactor-netty-core-1.0.24.jar:1.0.24]
	at reactor.netty.resources.DefaultPooledConnectionProvider$DisposableAcquire.onStateChange(DefaultPooledConnectionProvider.java:187) ~[reactor-netty-core-1.0.24.jar:1.0.24]
	at reactor.netty.resources.DefaultPooledConnectionProvider$PooledConnection.onStateChange(DefaultPooledConnectionProvider.java:444) ~[reactor-netty-core-1.0.24.jar:1.0.24]
	at reactor.netty.http.client.HttpClientOperations.onInboundNext(HttpClientOperations.java:637) ~[reactor-netty-http-1.0.24.jar:1.0.24]
	at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:113) ~[reactor-netty-core-1.0.24.jar:1.0.24]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[netty-transport-4.1.84.Final.jar:4.1.84.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.84.Final.jar:4.1.84.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.84.Final.jar:4.1.84.Final]
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436) ~[netty-transport-4.1.84.Final.jar:4.1.84.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:336) ~[netty-codec-4.1.84.Final.jar:4.1.84.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:308) ~[netty-codec-4.1.84.Final.jar:4.1.84.Final]
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251) ~[netty-transport-4.1.84.Final.jar:4.1.84.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[netty-transport-4.1.84.Final.jar:4.1.84.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.84.Final.jar:4.1.84.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.84.Final.jar:4.1.84.Final]
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1373) ~[netty-handler-4.1.84.Final.jar:4.1.84.Final]
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1236) ~[netty-handler-4.1.84.Final.jar:4.1.84.Final]
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1285) ~[netty-handler-4.1.84.Final.jar:4.1.84.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:519) ~[netty-codec-4.1.84.Final.jar:4.1.84.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:458) ~[netty-codec-4.1.84.Final.jar:4.1.84.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:280) ~[netty-codec-4.1.84.Final.jar:4.1.84.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[netty-transport-4.1.84.Final.jar:4.1.84.Final]
```
**To Reproduce**
Limit your heap size, and download a large file with code below.
Jvm options used: `-Xms64M -Xmx256M -Xss256k -XX:+UseStringDeduplication -XX:MaxHeapFreeRatio=30 -XX:MinHeapFreeRatio=10`

***Code Snippet***
```java
        final ShareFileAsyncClient shareFileClient = ...
        final StreamingResponseBody streamingResponseBody = outputStream ->
                shareFileClient.downloadWithResponse(fileRange, null)
                        .flatMap(response -> FluxUtil.writeToOutputStream(response.getValue(), outputStream)).block();
        return responseEntity
                .cacheControl(CacheControl.maxAge(Duration.ofDays(10L)))
                .contentType(VIDEO_MP4)
                .contentLength(contentLength)
                .eTag(etag)
                .lastModified(lastModifiedInstant)
                .body(streamingResponseBody);
```

**Expected behavior**
No `OutOfMemoryError`.

**Setup (please complete the following information):**
 - OS: Windows 10
 - IDE: IntelliJ
 - Library/Libraries: `com.azure:azure-storage-file-share:12.16.0`
 - Java version: `OpenJDK Runtime Environment Temurin-17.0.5+8 (build 17.0.5+8)`
 - App Server/Environment: Tomcat
 - Frameworks: Spring-boot v2.7.5

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

### PR DESCRIPTION
**Pull request by alzimmermsft**
# Description

Fixes #28033
Fixes #31555 
Fixes #31849 

Adds a new concept to `SwaggerMethodParser` which determines if the network response body will be consumed. This helps resolve an issue where before `void`-based responses would eagerly be read and could result in error cases. The Storage `getProperties` APIs are an example of this where the size of the blob or file is returned by the `Content-Length` header, then a buffer of that size would be created in preparation to read the response into memory eagerly. This would result in either excessive memory usage or `OutOfMemoryError`s, depending on the size of the blob or file. Now `void`-based responses have special handling where the network response will be ignored and drained instead of attempting to read them.

This issue only began happening recently due to multiple, unrelated changes exposing this edge case.

# All SDK Contribution checklist:
- [x] **The pull request does not introduce [breaking changes]**
- [x] **CHANGELOG is updated for new features, bug fixes or other significant changes.**
- [x] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md).**

## [General Guidelines and Best Practices](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md#developer-guide)
- [x] Title of the pull request is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md#building-and-unit-testing)
- [x] Pull request includes test coverage for the included changes.

### CODE REVIEW

**Review by mssfang — APPROVED** [review]

File: sdk/core/azure-core-http-okhttp/src/main/java/com/azure/core/http/okhttp/OkHttpAsyncHttpClient.java [hunk 1]
```diff
@@ -198,20 +203,26 @@ private static long getRequestContentLength(BinaryDataContent content, HttpHeade
...
     private static HttpResponse toHttpResponse(HttpRequest request, okhttp3.Response response,
-        boolean eagerlyReadResponse, boolean eagerlyConvertHeaders) throws IOException {
+        boolean eagerlyReadResponse, boolean ignoreResponseBody, boolean eagerlyConvertHeaders) throws IOException {
+        // Ignoring the response body takes precedent over eagerly reading the response body.
+        // Both should never be true at the same time but this is acts as a safeguard.
+        if (ignoreResponseBody) {
+            ResponseBody body = response.body();
+            if (body != null) {
+                body.close();
+            }
```
Comment (srnagar) [inline sdk/core/azure-core-http-okhttp/src/main/java/com/azure/core/http/okhttp/OkHttpAsyncHttpClient.java:213]: When would `body` be non-null? If this check evaluates to true, then we should throw as we are ignoring response body when there's actually some content.

**Review by srnagar — APPROVED** [review]

**Review by ibrahimrabab — APPROVED** [review]

File: sdk/core/azure-core-http-okhttp/src/main/java/com/azure/core/http/okhttp/OkHttpAsyncHttpClient.java (hunk 1 above)
Comment (alzimmermsft) [reply sdk/core/azure-core-http-okhttp/src/main/java/com/azure/core/http/okhttp/OkHttpAsyncHttpClient.java:213]: Thoughts on making this a warning or info log message for now? This would be a possible issue where either the Swagger was wrong or the server unexpectantly returned a response. FWIW, we already ignore the response body when the return body type is void, this just pushes the logic down into the HTTP client layer.

Comment (alzimmermsft) [reply sdk/core/azure-core-http-okhttp/src/main/java/com/azure/core/http/okhttp/OkHttpAsyncHttpClient.java]: Done
