### PR TITLE
Suppress False-Positive Warnings

### LINKED ISSUE #20801: Remove/redact credentials in Storage SDK playback files
The [CredScan tool](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/413/Credential-Scan-Step-in-Pipeline) reports these errors related to java storage sdk (all from azure-storage-blob-cryptography). 
[StorageSDKCredScan.txt](https://github.com/Azure/azure-sdk-for-java/files/6339389/StorageSDKCredScan.txt)
 
Using file "EncyptedBlockBlobAPITestencryption[0].json" as an example, I tried to change the credential to something else then the test failed with error 
“reactor.core.Exceptions$ReactiveException: javax.crypto.BadPaddingException: Given final block not properly padded. Such issues can arise if a bad key is used during decryption.” 
So I can’t simply redact it.

What we need to do is:
1.	Update the test code to not have explicit credentials. If the playback files are re-generated someday, no new credentials are generated to cause the cred scan to report errors.
2.	If we do want to use credentials with the correct format in the playback test, we may use fake credentials. We can add fake credentials to the [suppression file](https://github.com/Azure/azure-sdk-for-java/blob/master/eng/CredScanSuppression.json) so they don’t cause errors/warnings. But we don’t want this suppression file to grow too large. So it’s better the fake credentials can be shared by multiple tests and we don’t create new fake credentials from time to time.

### PR DESCRIPTION
**Pull request by alzimmermsft**
Fixes #20801

This PR suppresses false-positive CredScan warnings by making the following changes:

- Suppress the dotnet-devcert.pfx as this is a well-known and public certificate.
- Updated in-code connection strings in azure-storage-common tests to use the well-known and public Azurite connection string.
- Updated in-code SAS tokens in azure-storage-blob tests to use a fake `sig` based on the value `password`.
- Updated AES key generation in azure-storage-blob-cryptography tests to use a consistent key when running tests in `PLAYBACK` or `RECORD` modes and continue using true randomness when running tests in `LIVE` mode.

### CODE REVIEW

File: sdk/storage/azure-storage-blob-cryptography/src/main/java/com/azure/storage/blob/specialized/cryptography/EncryptedBlobAsyncClient.java [hunk 1]
```diff
@@ -475,116 +469,110 @@ public EncryptedBlobAsyncClient getCustomerProvidedKeyAsyncClient(CustomerProvid
...
+    }
+
+    Cipher generateCipher(SecretKey aesKey) throws GeneralSecurityException {
+        Cipher cipher = Cipher.getInstance(CryptographyConstants.AES_CBC_PKCS5PADDING);
+
+        // Generate content encryption key
+        cipher.init(Cipher.ENCRYPT_MODE, aesKey);
+
+        return cipher;
+    }
```
Comment (kasobol-msft) [inline sdk/storage/azure-storage-blob-cryptography/src/main/java/com/azure/storage/blob/specialized/cryptography/EncryptedBlobAsyncClient.java:549]: I'm guessing this is to make these overridable and have "spy" in tests. Should we take KeyGenerator and Cipher references in ctor instead?
