### PR TITLE
Multiple fixes

### LINKED ISSUE #9136: CosmosAsyncItemResponse::getRequestCharge() fails on international systems
**Describe the bug**
getRequestCharge() will fail on systems where a "," is used as a decimal separator.

***Exception or Stack Trace***
java.lang.NumberFormatException: For input string: "3,64"

**To Reproduce**
Set your locale to German and run this example code: [SampleCRUDQuickstartAsync.java](https://github.com/Azure-Samples/azure-cosmos-java-sql-api-samples/blob/master/src/main/java/com/azure/cosmos/examples/crudquickstart/async/SampleCRUDQuickstartAsync.java)
The method createFamilies() will fail.

**Setup (please complete the following information):**
 - OS: Windows
 - Java SDK v4 preview.2

**Additional context**
The machine used in this test has German locale defined and uses a "," as a decimal separator.

The source of this issue seems to be in the implementation of populatePartitionedQueryMetrics in DocumentProducer.java
[in this line here](https://github.com/Azure/azure-sdk-for-java/blob/2c32ea66cefeec207d9c88d5bff79961fc6e5cef/sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/query/DocumentProducer.java#L68)

The current locale will be used to produce the string and on some systems a "," will be used as a decimal separator. The locale won't be used by Double.parseDouble() (actually, why is the locale ignored by Double..?) when parsing the string which in the end leads to the NumberFormatException mentioned above.

Possible fix
1. set the locale and enforce a "." as a decimal separator:
String.format(Locale.US, "%f", floatValue)
or
2. don't use Double.parseDouble() and use NumberFormat etc. instead (?)

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

### LINKED ISSUE #15833: readMany / readManyAsync APIs don't work in GATEWAY mode on azure-cosmos V4 Java SDK
* readMany / readManyAsync APIs don't work in GATEWAY mode on azure-cosmos V4 Java SDK
* If used in GATEWAY mode, we get this error:

```
CosmosException{userAgent=Windows10/10.0 JRE/1.8.0_202 cosmosdb-java-sdk/4.3.0, error={"code":"MethodNotAllowed","message":"RequestHandler.Post, StatusCode: MethodNotAllowed"
```

### LINKED ISSUE #16065: Single partition queries routing to gateway in direct mode.
Single partition queries could go to gateway even in direct mode and this needs to be fixed.

### PR DESCRIPTION
**Pull request by mbhaskar**
This PR fixes the following issues
- Singlepartition queries going to gateway instead of direct path in directMode. Fixes #16065
- readMany not working in gateway Mode. Fixes #15833
- QueryMetrics failing to parse request charge in a non US locale. Fixes #9136

### CODE REVIEW

File: sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/RxDocumentClientImpl.java [hunk 1]
```diff
@@ -3566,7 +3567,8 @@ private RxStoreModel getStoreProxy(RxDocumentServiceRequest request) {
         } else {
             if ((request.getOperationType() == OperationType.Query || request.getOperationType() == OperationType.SqlQuery) &&
                     Utils.isCollectionChild(request.getResourceType())) {
-                if (request.getPartitionKeyRangeIdentity() == null) {
+                // Go to gateway only if there is no partition key range or partition key set. This should be very rare
+                if (request.getPartitionKeyRangeIdentity() == null && request.getHeaders().get(HttpConstants.HttpHeaders.PARTITION_KEY) == null) {
```
Comment (FabianMeiswinkel) [inline sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/RxDocumentClientImpl.java:3571]: NIT line break after &&

File: sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/query/DocumentProducer.java [hunk 2]
```diff
@@ -65,7 +66,10 @@
         void populatePartitionedQueryMetrics() {
             String queryMetricsDelimitedString = pageResult.getResponseHeaders().get(HttpConstants.HttpHeaders.QUERY_METRICS);
             if (!StringUtils.isEmpty(queryMetricsDelimitedString)) {
-                queryMetricsDelimitedString += String.format(";%s=%.2f", QueryMetricsConstants.RequestCharge, pageResult.getRequestCharge());
+                queryMetricsDelimitedString += String.format(Locale.ROOT,
+                                                             ";%s=%.2f",
+                                                             QueryMetricsConstants.RequestCharge,
```
Comment (FabianMeiswinkel) [inline sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/query/DocumentProducer.java:71]: Just to double-check my understanding is correct - instead of changing the place where we were Parsing the Double you decided to normalize the locale here because for all other content where we parse floating point numbers the content is created by our backend and we own the locale/formatting, correct?

**Review by FabianMeiswinkel — APPROVED** [review]
LGTM - thank you!

File: sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/query/DocumentProducer.java (hunk 2 above)
Comment (mbhaskar) [reply sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/query/DocumentProducer.java:71]: Thats correct Fabian

**Review by milismsft — APPROVED** [review]

**Review by moderakh — APPROVED** [review]
great and clean work thanks for the fix.

LGTM.

**Review by kushagraThapar — APPROVED** [review]
LGTM

File: sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/RxDocumentClientImpl.java (hunk 1 above)
Comment (mbhaskar) [reply sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/RxDocumentClientImpl.java]: done
