### PR TITLE
Maintain Before and After Retry Polices Separately in HttpPolicyProviders

### LINKED ISSUE #8163: Blob SDK class HttpPolicyProviders throws an exception with multiple concurrent uploads.
Blob SDK class throws an exception with multiple concurrent uploads.  hashmap used by SDK concurrently modified by different threads

Exception stack trace

Caused by: java.util.ConcurrentModificationException
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1134)
	at com.azure.core.http.policy.HttpPolicyProviders.getPolicyProviders(HttpPolicyProviders.java:59)
	at com.azure.core.http.policy.HttpPolicyProviders.lambda$addAfterRetryPolicies$1(HttpPolicyProviders.java:39)
	at com.azure.core.http.policy.HttpPolicyProviders.addRetryPolicies(HttpPolicyProviders.java:44)
	at com.azure.core.http.policy.HttpPolicyProviders.addAfterRetryPolicies(HttpPolicyProviders.java:39)
	at com.azure.storage.blob.implementation.util.BuilderHelper.buildPipeline(BuilderHelper.java:95)
	at com.azure.storage.blob.BlobClientBuilder.buildAsyncClient(BlobClientBuilder.java:123)
	at com.azure.storage.blob.BlobClientBuilder.buildClient(BlobClientBuilder.java:93)
	at com.sonymusic.delivery.azure.client.AzureStorageClient.getBlobClient(AzureStorageClient.java:110)
	at com.sonymusic.delivery.azure.client.AzureStorageClient.uploadFile(AzureStorageClient.java:42

SDK V12.3.1

//My code to create a blob client
        return new BlobClientBuilder()
                .credential(credential)
                .endpoint(endPoint)
                .blobName(blobName)
                .buildClient();
                
                
//HttpPolicyProviders.java file. HashMap
private static final Map<Class<? extends HttpPolicyProvider>, ServiceLoader<? extends HttpPolicyProvider>>
        SERVICE_LOADERS = new HashMap<>();

ServiceLoader<? extends HttpPolicyProvider> serviceLoader = SERVICE_LOADERS
            .computeIfAbsent(cls, ServiceLoader::load);

### PR DESCRIPTION
**Pull request by alzimmermsft**
Fixes #8163 

Re-writes `HttpPolicyProviders` to maintain the `BeforeRetryPolicyProvider`s and `AfterRetryPolicyProvider`s as separate entities instead of combining them into a single `Map`.

### CODE REVIEW

File: sdk/core/azure-core/src/main/java/com/azure/core/http/policy/HttpPolicyProviders.java [hunk 1]
```diff
@@ -36,32 +39,18 @@ public static void addBeforeRetryPolicies(List<HttpPipelinePolicy> policies) {
...
-            HttpPolicyProvider policyProvider = it.next();
-            HttpPipelinePolicy policy = policyProvider.create();
+    private static void addPolices(List<HttpPipelinePolicy> policies,
+        Iterable<? extends HttpPolicyProvider> providers) {
+        for (HttpPolicyProvider provider : providers) {
+            HttpPipelinePolicy policy = provider.create();
             if (policy == null) {
-                throw new NullPointerException("HttpPipelinePolicy created with " + policyProvider.getClass()
-                    + " resulted in a null policy");
+                throw new NullPointerException(String.format(INVALID_POLICY, provider.getClass()));
```
Comment (srnagar) [inline sdk/core/azure-core/src/main/java/com/azure/core/http/policy/HttpPolicyProviders.java]: Log and throw the exception. Also, this should have been caught in checkstyle.

Comment (alzimmermsft) [reply sdk/core/azure-core/src/main/java/com/azure/core/http/policy/HttpPolicyProviders.java]: Being used from a static method which conflicts with the logging guidelines, we may want to amend those to allow them in a static only class.

**Comment by ahmedbaberkhan** [comment]
I saw the above fix is a part of 1.3.0-beta.2
Can you please update when this version will be released?
